// BonziSolitaire.exe :: frmMain
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 38

// ---- Public_0 @ 0070efa0

/* WARNING: Type propagation algorithm not settling */

undefined4 frmMain::Public_0(int *param_1)

{
  int iVar1;
  float10 fVar2;
  float local_28;
  float local_24 [3];
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffb8;
  local_c = &DAT_004011b8;
  local_8 = 0;
  ExceptionList = &local_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_24[2] = 0.0;
  local_24[1] = 0.0;
  local_24[0] = 0.0;
  local_28 = 0.0;
  fVar2 = (float10)__vbaFpCSngR4();
  local_28 = (float)fVar2;
  fVar2 = (float10)__vbaFpCSngR4();
  local_24[0] = (float)fVar2;
  local_24[1] = 0.0;
  local_24[2] = 1.4013e-45;
  iVar1 = (**(code **)(*param_1 + 0x708))(param_1,local_24 + 2,local_24 + 1,local_24,&local_28);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1,&LAB_00403954,0x708);
  }
  (**(code **)(*param_1 + 8))(param_1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Form_ev10 @ 0070f070

void frmMain::Form_ev10(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004011c0;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  uVar1 = __vbaCastObj(piVar2,&DAT_00404680);
  __vbaObjSet(&local_1c,uVar1);
  modMain::Proc_724200(&local_1c);
  __vbaFreeObj();
  return;
}


// ---- Form_ev13 @ 0070f120

undefined4 frmMain::Form_ev13(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004011d0;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  if (DAT_007273ca == '\x01') {
    modMain::Proc_720c50(&DAT_0072737c,&DAT_00727380);
  }
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Form_ev15 @ 0070f1a0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void frmMain::Form_ev15(uint param_1,short *param_2)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 uVar3;
  int *piVar4;
  int *piVar5;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc0;
  local_c = &DAT_004011d8;
  local_8 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar5 + 4))(piVar5);
  DAT_007273d0 = 0xffff;
  local_1c = 0;
  local_20 = 0;
  local_24 = 0;
  uVar3 = *(undefined4 *)piVar5[0x42];
  rtcBstrFromAnsi((int)*param_2);
  uVar1 = __vbaStrMove(uVar3);
  __vbaStrCat(uVar1,uVar3);
  __vbaStrMove();
  __vbaStrCopy();
  __vbaFreeStrList(2,&local_1c,&local_20);
  iVar2 = __vbaInStr(1,u_enter_debug_mode_00404694,*(undefined4 *)piVar5[0x42],1);
  if (0 < iVar2) {
    __vbaStrCopy();
    uVar3 = (**(code **)(*piVar5 + 0x398))(piVar5);
    piVar4 = (int *)__vbaObjSet(&local_24,uVar3);
    iVar2 = (**(code **)(*piVar4 + 0x5c))(piVar4,0xffffffff);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,piVar4,&DAT_004040a8,0x5c);
    }
    __vbaFreeObj();
    _DAT_007273d4 = 0xffff;
  }
  iVar2 = __vbaInStr(1,u_exit_debug_mode_004046c0,*(undefined4 *)piVar5[0x42],1);
  if (0 < iVar2) {
    __vbaStrCopy();
    uVar3 = (**(code **)(*piVar5 + 0x398))(piVar5);
    piVar5 = (int *)__vbaObjSet(&local_24,uVar3);
    iVar2 = (**(code **)(*piVar5 + 0x5c))(piVar5,0);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,piVar5,&DAT_004040a8,0x5c);
    }
    __vbaFreeObj();
    _DAT_007273d4 = 0;
  }
  return;
}


// ---- Form_ev19 @ 0070f370

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
frmMain::Form_ev19(uint param_1,short *param_2,undefined4 param_3,undefined4 param_4,
                  undefined4 param_5)

{
  short sVar1;
  int *piVar2;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004011e8;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  if (*param_2 == 1) {
    DAT_007273a0 = __vbaUI1I2();
    DAT_0072703a = 0;
    DAT_007273ca = __vbaUI1I2();
    if ((*param_2 == 2) && (DAT_007273ce == 0)) {
      _DAT_0072738c = __vbaFpI4();
      _DAT_00727390 = __vbaFpI4();
    }
    if ((*param_2 == 1) && (DAT_007273ce == 0)) {
      if (DAT_007273d0 == 0) {
        DAT_007273d0 = -1;
      }
      else {
        DAT_0072737c = __vbaFpI4();
        DAT_00727380 = __vbaFpI4();
        sVar1 = modMain::Proc_7200b0(param_4,param_5);
        if ((sVar1 == 0) && (sVar1 = modMain::Proc_71e030(param_4,param_5), sVar1 == 0)) {
          modMain::Proc_71e900(param_4,param_5);
        }
      }
    }
  }
  local_8 = 0;
  (**(code **)(*piVar2 + 8))(piVar2);
  ExceptionList = local_18;
  return local_8;
}


// ---- Form_ev20 @ 0070f4a0

undefined4
frmMain::Form_ev20(uint param_1,short *param_2,undefined4 param_3,undefined4 param_4,
                  undefined4 param_5)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004011f0;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  if ((*param_2 == 1) && (DAT_007273ce != 0)) {
    modMain::Proc_7141b0(param_4,param_5);
  }
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Form_ev21 @ 0070f530

undefined4
frmMain::Form_ev21(uint param_1,short *param_2,undefined4 param_3,undefined4 param_4,
                  undefined4 param_5)

{
  short sVar1;
  int *piVar2;
  short sVar3;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004011f8;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  if (*param_2 == 1) {
    sVar3 = 0;
    sVar1 = modMain::Proc_712da0(param_4,param_5);
    if (sVar1 != 0) {
      sVar3 = -1;
    }
    sVar1 = modMain::Proc_71ecd0(param_4,param_5);
    if ((sVar1 != 0) || (sVar1 = 0, sVar3 != 0)) {
      sVar1 = -1;
    }
    DAT_0072703a = 0;
    if (sVar1 == 0) {
      if (DAT_007273ce != 0) {
        modMain::Proc_713a90();
      }
    }
    else if ((DAT_007273af == '\x03') && (DAT_007273cc == '\x03')) {
      DAT_007273cc = __vbaUI1I2();
    }
  }
  local_8 = 0;
  (**(code **)(*piVar2 + 8))(piVar2);
  ExceptionList = local_18;
  return local_8;
}


// ---- Form_ev22 @ 0070f610

undefined4 frmMain::Form_ev22(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00401200;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  modMain::Proc_71c9c0();
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Form_ev8 @ 0070f680

undefined4 frmMain::Form_ev8(uint param_1,undefined2 *param_2)

{
  int *piVar1;
  int *piVar2;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00401208;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  piVar2 = piVar1;
  (**(code **)(*piVar1 + 4))(piVar1);
  *param_2 = 1;
  modMain::Proc_7194c0();
  __vbaEnd(piVar2);
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuDebugDisabledebug_ev0 @ 0070f700

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void frmMain::mnuDebugDisabledebug_ev0(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00401210;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  _DAT_007273d4 = 0;
  local_1c = 0;
  uVar1 = (**(code **)(*piVar3 + 0x398))(piVar3);
  piVar3 = (int *)__vbaObjSet(&local_1c,uVar1);
  iVar2 = (**(code **)(*piVar3 + 0x5c))(piVar3,0);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar3,&DAT_004040a8,0x5c);
  }
  __vbaFreeObj();
  if (DAT_00727010 == (int *)0x0) {
    __vbaNew2(&DAT_00402418,&DAT_00727010);
  }
  piVar3 = DAT_00727010;
  iVar2 = (**(code **)(*DAT_00727010 + 0x54))(DAT_00727010,DAT_007273e8);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar3,&DAT_00403924,0x54);
  }
  modMain::Proc_721e30();
  return;
}


// ---- mnuDebugNoshuffle_ev0 @ 0070f810

undefined4 frmMain::mnuDebugNoshuffle_ev0(uint param_1)

{
  int *piVar1;
  undefined1 local_1c [4];
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00401220;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  local_1c[0] = 0;
  modMain::Proc_714ce0();
  modMain::Proc_71a9e0();
  local_1c[0] = __vbaUI1I2();
  modMain::Proc_71c380(local_1c);
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Public_12 @ 0070f8a0

undefined4 frmMain::Public_12(void)

{
  int *piVar1;
  undefined4 uVar2;
  int iVar3;
  undefined4 local_98 [2];
  wchar_t *local_90;
  undefined4 local_78 [4];
  undefined4 local_68 [4];
  undefined4 local_58 [2];
  undefined4 local_50;
  undefined4 local_48 [4];
  undefined4 local_38 [4];
  undefined4 local_28 [2];
  short local_20;
  undefined4 local_18;
  void *pvStack_14;
  undefined1 *puStack_10;
  undefined1 *local_c;
  undefined *local_8;
  
  puStack_10 = &LAB_004016b6;
  pvStack_14 = ExceptionList;
  local_c = &stack0xffffff50;
  local_8 = &DAT_00401228;
  local_18 = 0;
  local_28[0] = 0;
  local_38[0] = 0;
  local_48[0] = 0;
  local_58[0] = 0;
  local_68[0] = 0;
  local_78[0] = 0;
  local_98[0] = 0;
  ExceptionList = &pvStack_14;
  modMain::Proc_721ff0();
  local_50 = __vbaStrCat(u_BG_BG_004046fc,DAT_0072739c);
  local_20 = DAT_007273c0 + 1;
  if (!SCARRY2(DAT_007273c0,1)) {
    local_58[0] = 8;
    local_28[0] = 2;
    rtcVarStrFromVar(local_38,local_28);
    rtcTrimVar(local_48,local_38);
    local_98[0] = 8;
    local_90 = u__BMP_0040470c;
    uVar2 = __vbaVarCat(local_68,local_48,local_58);
    uVar2 = __vbaVarCat(local_78,local_98,uVar2);
    __vbaStrVarMove(uVar2);
    __vbaStrMove();
    __vbaStrCopy();
    __vbaFreeStr();
    __vbaFreeVarList(6,local_28,local_38,local_58,local_48,local_68,local_78);
    modMain::Proc_719470(&DAT_0072730c);
    modMain::Proc_718810(&DAT_0072730c);
    modMain::Proc_722870();
    if (DAT_00727010 == (int *)0x0) {
      __vbaNew2(&DAT_00402418,&DAT_00727010);
    }
    piVar1 = DAT_00727010;
    iVar3 = (**(code **)(*DAT_00727010 + 0x54))(DAT_00727010,DAT_007273e8);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar1,&DAT_00403924,0x54);
    }
    uVar2 = modMain::Proc_71ddd0();
    return uVar2;
  }
  __vbaErrorOverflow(local_38);
  modMain::Proc_71ddd0();
  return 0;
}


// ---- mnuDebugResetsettings_ev0 @ 0070fa80

void frmMain::mnuDebugResetsettings_ev0(uint param_1)

{
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00401238;
  local_8 = param_1 & 1;
  ExceptionList = &pvStack_18;
  (**(code **)(*(int *)(param_1 & 0xfffffffe) + 4))((int *)(param_1 & 0xfffffffe));
  DAT_007273b8 = 0;
  DAT_007273bc = 0;
  DAT_007273c0 = 0;
  __vbaStrCat(u_BG_BG1_BMP_0040471c,DAT_0072739c);
  __vbaStrMove();
  __vbaStrCopy();
  __vbaFreeStr();
  modMain::Proc_719470(&DAT_0072730c);
  modMain::Proc_718810(&DAT_0072730c);
  modMain::Proc_722870();
  modMain::Proc_71ddd0();
  return;
}


// ---- mnuDebugWin_ev0 @ 0070fb70

undefined4 frmMain::mnuDebugWin_ev0(uint param_1)

{
  code *pcVar1;
  byte bVar2;
  byte bVar3;
  undefined1 uVar4;
  int *piVar5;
  int *piVar6;
  undefined4 unaff_EBX;
  uint unaff_ESI;
  bool bVar7;
  code *pcStack_68;
  int iStack_64;
  byte bStack_60;
  undefined3 uStack_5f;
  void *pvStack_54;
  undefined1 *puStack_50;
  undefined1 *puStack_4c;
  undefined *puStack_48;
  int *piStack_44;
  int *piStack_40;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffc4;
  local_c = &DAT_00401248;
  local_8 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  piStack_44 = (int *)0x70fbaf;
  ExceptionList = &local_18;
  piStack_40 = piVar5;
  (**(code **)(*piVar5 + 4))();
  pcVar1 = __vbaUI1I2_exref;
  piStack_44 = (int *)0x70fbbc;
  bVar2 = __vbaUI1I2();
  piStack_44 = (int *)0x70fbc6;
  bVar3 = __vbaUI1I2();
  do {
    if (bVar2 < bVar3) {
      piStack_44 = (int *)0x70fc0b;
      modMain::Proc_71f6e0();
      local_8 = 0;
      puStack_48 = (undefined *)0x70fc1b;
      piStack_44 = piVar5;
      (**(code **)(*piVar5 + 8))();
      ExceptionList = local_18;
      return local_8;
    }
    if (3 < bVar3 - 1) {
      puStack_48 = (undefined *)0x70fbe7;
      __vbaGenerateBoundsError();
    }
    piStack_44 = (int *)0x70fbee;
    uVar4 = __vbaUI1I2();
    iStack_64 = (bVar3 - 1) * 0x10;
    bVar7 = bVar3 != 0xff;
    bStack_60 = bVar3 + 1;
    (&DAT_00727218)[iStack_64] = uVar4;
    bVar3 = bStack_60;
  } while (bVar7);
  piStack_44 = (int *)0x70fc37;
  __vbaErrorOverflow();
  puStack_50 = &LAB_004016b6;
  pvStack_54 = ExceptionList;
  puStack_4c = (undefined1 *)&pcStack_68;
  pcStack_68 = pcVar1;
  puStack_48 = &DAT_00401250;
  piStack_44 = (int *)(unaff_ESI & 1);
  piVar6 = (int *)(unaff_ESI & 0xfffffffe);
  ExceptionList = &pvStack_54;
  piVar5 = piVar6;
  piStack_40 = (int *)&stack0xfffffffc;
  uStack_5f = (int3)((uint)unaff_EBX >> 8);
  (**(code **)(*piVar6 + 4))(piVar6);
  modMain::Proc_7194c0();
  __vbaEnd(piVar5);
  piStack_44 = (int *)0x0;
  (**(code **)(*piVar6 + 8))(piVar6);
  ExceptionList = pvStack_54;
  return piStack_44;
}


// ---- mnuFileExit_ev0 @ 0070fc40

undefined4 frmMain::mnuFileExit_ev0(uint param_1)

{
  int *piVar1;
  int *piVar2;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00401250;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  piVar2 = piVar1;
  (**(code **)(*piVar1 + 4))(piVar1);
  modMain::Proc_7194c0();
  __vbaEnd(piVar2);
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuFileNewgame_ev0 @ 0070fcb0

void frmMain::mnuFileNewgame_ev0(uint param_1)

{
  int iVar1;
  undefined1 local_7c [36];
  undefined4 local_58 [2];
  undefined *local_50;
  undefined4 local_48 [2];
  undefined *local_40;
  undefined4 local_38 [2];
  undefined4 local_30;
  undefined4 local_28 [2];
  undefined4 local_20;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff6c;
  local_c = &DAT_00401258;
  local_8 = param_1 & 1;
  ExceptionList = &pvStack_18;
  (**(code **)(*(int *)(param_1 & 0xfffffffe) + 4))((int *)(param_1 & 0xfffffffe));
  local_38[0] = 10;
  local_28[0] = 10;
  local_58[0] = 0x4008;
  local_48[0] = 0x4008;
  local_30 = 0x80020004;
  local_20 = 0x80020004;
  local_7c[0] = 0;
  local_50 = &DAT_00727464;
  local_40 = &DAT_00727468;
  iVar1 = rtcMsgBox(local_48,0x24,local_58,local_28,local_38);
  __vbaFreeVarList(2,local_28,local_38);
  if (iVar1 == 6) {
    local_7c[0] = __vbaUI1I2();
    modMain::Proc_71c380(local_7c);
  }
  return;
}


// ---- mnuFileUndo_ev0 @ 0070fdc0

undefined4 frmMain::mnuFileUndo_ev0(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00401268;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  modMain::Proc_722bc0();
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuHelpAbout_ev0 @ 0070fe30

/* WARNING: Type propagation algorithm not settling */

void frmMain::mnuHelpAbout_ev0(uint param_1)

{
  byte bVar1;
  undefined1 uVar2;
  byte bVar3;
  byte bVar4;
  uint uVar5;
  undefined4 uVar6;
  int *piVar7;
  short sVar8;
  short sVar9;
  undefined4 *puVar10;
  code *pcVar11;
  int iVar12;
  code *pcVar13;
  code *pcVar14;
  uint uVar15;
  int *piVar16;
  uint unaff_EDI;
  bool bVar17;
  ushort in_FPUStatusWord;
  uint uStack_13c;
  code *pcStack_138;
  code *pcStack_134;
  undefined4 uStack_130;
  undefined4 uStack_12c;
  short **ppsStack_128;
  undefined4 uStack_124;
  undefined4 uStack_120;
  undefined4 uStack_11c;
  uint auStack_118 [3];
  short **ppsStack_10c;
  undefined1 *puStack_108;
  undefined *puStack_104;
  short **ppsStack_100;
  undefined **ppuStack_fc;
  undefined4 *puStack_f8;
  int *piStack_f4;
  int local_d0;
  int local_b8;
  undefined4 local_80 [2];
  undefined4 local_78;
  undefined4 local_70;
  undefined4 local_6c;
  undefined4 local_68;
  undefined4 local_64;
  undefined4 local_60;
  undefined4 local_5c;
  short *local_44 [2];
  int local_3c;
  code *local_30;
  uint local_28;
  short *local_24 [2];
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff10;
  local_c = &DAT_00401278;
  local_8 = param_1 & 1;
  piStack_f4 = (int *)(param_1 & 0xfffffffe);
  puStack_f8 = (undefined4 *)0x70fe72;
  ExceptionList = &pvStack_18;
  (**(code **)(*piStack_f4 + 4))();
  local_6c = 0;
  pcVar14 = (code *)0x0;
  local_68 = 0;
  puStack_f8 = (undefined4 *)DAT_0072739c;
  local_64 = 0;
  ppuStack_fc = &PTR_DAT_00404750;
  local_60 = 0;
  local_24[0] = (short *)0x0;
  local_44[0] = (short *)0x0;
  local_5c = 0;
  local_70 = 0;
  local_80[0] = 0;
  DAT_007273d0 = 0;
  ppsStack_100 = (short **)0x70feaa;
  __vbaStrCat();
  puStack_f8 = (undefined4 *)0x70feb5;
  __vbaStrMove();
  puStack_f8 = (undefined4 *)0x70fec0;
  __vbaStrCopy();
  puStack_f8 = (undefined4 *)0x70fec9;
  __vbaFreeStr();
  puStack_f8 = &local_6c;
  ppuStack_fc = (undefined **)0x70fed2;
  modMain::Proc_718810();
  pcVar13 = __vbaI2I4_exref;
  uVar5 = unaff_EDI;
  puVar10 = puStack_f8;
  if (!SCARRY4(DAT_0072735c / (int)(short)local_5c,1)) {
    ppuStack_fc = (undefined **)0x70fef1;
    uVar5 = __vbaI2I4();
    puVar10 = puStack_f8;
    local_28 = uVar5;
    if (!SCARRY4(DAT_00727360 / (int)local_5c._2_2_,1)) {
      ppuStack_fc = (undefined **)0x70ff0f;
      local_1c = __vbaI2I4();
      sVar9 = (short)uVar5;
      puVar10 = puStack_f8;
      if (!SBORROW2(sVar9,1)) {
        iVar12 = (int)(short)(sVar9 + -1) * (int)(short)local_5c;
        sVar8 = (short)iVar12;
        if ((sVar8 == iVar12) &&
           ((uVar15 = local_28, DAT_0072735c <= sVar8 ||
            (uVar5 = CONCAT22((short)(uVar5 >> 0x10),sVar9 + 1), uVar15 = uVar5, !SCARRY2(sVar9,1)))
           )) {
          local_28 = uVar15;
          sVar9 = (short)local_1c;
          if (!SBORROW2(sVar9,1)) {
            iVar12 = (int)(short)(sVar9 + -1) * (int)local_5c._2_2_;
            sVar8 = (short)iVar12;
            if ((sVar8 == iVar12) &&
               ((uVar6 = local_1c, DAT_00727360 <= sVar8 ||
                (uVar6 = CONCAT22((short)((uint)local_1c >> 0x10),sVar9 + 1), !SCARRY2(sVar9,1)))))
            {
              local_1c = uVar6;
              ppuStack_fc = (undefined **)0x1;
              ppsStack_100 = (short **)0xc8;
              puStack_104 = (undefined *)0x1;
              ppsStack_10c = local_44;
              puStack_108 = (undefined1 *)0x0;
              auStack_118[2] = 8;
              auStack_118[1] = 0;
              uVar5 = 0;
              local_3c = 0;
              auStack_118[0] = 0x70ff90;
              __vbaRedim();
              auStack_118[0] = 1;
              uStack_11c = 200;
              uStack_120 = 1;
              ppsStack_128 = local_24;
              uStack_124 = 3;
              uStack_12c = 4;
              uStack_130 = 0x80;
              pcStack_134 = (code *)0x70ffa8;
              __vbaRedim();
              ppuStack_fc = (undefined **)local_44[0];
              ppsStack_100 = (short **)0x1;
              puStack_104 = (undefined *)0x70ffb7;
              __vbaUbound();
              ppuStack_fc = (undefined **)0x70ffbf;
              bVar1 = __vbaUI1I4();
              pcVar13 = __vbaUI1I2_exref;
              ppuStack_fc = (undefined **)0x70ffd2;
              uVar2 = __vbaUI1I2();
              local_30 = (code *)CONCAT31(local_30._1_3_,uVar2);
              while (pcVar11 = local_30, pcVar14 = __vbaSetSystemError_exref,
                    (byte)local_30 <= bVar1) {
                local_78 = 0x80020004;
                local_80[0] = 10;
                if ((local_44[0] == (short *)0x0) || (*local_44[0] != 1)) {
                  ppuStack_fc = (undefined **)0x710033;
                  local_b8 = __vbaGenerateBoundsError();
                  pcVar11 = local_30;
                }
                else {
                  uVar15 = ((uint)local_30 & 0xff) - *(int *)(local_44[0] + 10);
                  if (*(uint *)(local_44[0] + 8) <= uVar15) {
                    ppuStack_fc = (undefined **)0x71001e;
                    __vbaGenerateBoundsError();
                  }
                  local_b8 = uVar15 * 8;
                }
                puStack_f8 = local_80;
                ppuStack_fc = (undefined **)0x710046;
                rtcRandomNext();
                pcVar14 = __vbaFpI4_exref;
                pcVar13 = pcVar11;
                puVar10 = puStack_f8;
                if ((longlong)(int)-(longlong)DAT_0072735c != -(longlong)DAT_0072735c)
                goto LAB_007103c8;
                if ((in_FPUStatusWord & 0xd) != 0) {
LAB_007103c3:
                  __vbaFPException();
                  return;
                }
                ppsStack_100 = (short **)0x710095;
                uVar6 = __vbaFpI4();
                *(undefined4 *)(*(int *)(local_44[0] + 6) + local_b8) = uVar6;
                ppsStack_100 = (short **)0x7100ad;
                __vbaFreeVar();
                local_78 = 0x80020004;
                local_80[0] = 10;
                if ((local_44[0] == (short *)0x0) || (*local_44[0] != 1)) {
                  ppsStack_100 = (short **)0x7100fd;
                  local_d0 = __vbaGenerateBoundsError();
                }
                else {
                  uVar15 = ((uint)pcVar11 & 0xff) - *(int *)(local_44[0] + 10);
                  if (*(uint *)(local_44[0] + 8) <= uVar15) {
                    ppsStack_100 = (short **)0x7100e2;
                    __vbaGenerateBoundsError();
                  }
                  local_d0 = uVar15 * 8;
                  pcVar14 = __vbaFpI4_exref;
                }
                ppuStack_fc = (undefined **)local_80;
                ppsStack_100 = (short **)0x71010d;
                rtcRandomNext();
                if ((in_FPUStatusWord & 0xd) != 0) goto LAB_007103c3;
                ppuStack_fc = (undefined **)0x710158;
                uVar6 = (*pcVar14)();
                *(undefined4 *)(*(int *)(local_44[0] + 6) + 4 + local_d0) = uVar6;
                ppsStack_100 = (short **)0x710171;
                __vbaFreeVar();
                local_78 = 0x80020004;
                local_80[0] = 10;
                if ((local_24[0] == (short *)0x0) || (*local_24[0] != 1)) {
                  ppsStack_100 = (short **)0x7101af;
                  iVar12 = __vbaGenerateBoundsError();
                }
                else {
                  uVar15 = ((uint)pcVar11 & 0xff) - *(int *)(local_24[0] + 10);
                  if (*(uint *)(local_24[0] + 8) <= uVar15) {
                    ppsStack_100 = (short **)0x7101a4;
                    __vbaGenerateBoundsError();
                  }
                  iVar12 = uVar15 * 4;
                }
                ppuStack_fc = (undefined **)local_80;
                ppsStack_100 = (short **)0x7101bb;
                rtcRandomNext();
                if ((in_FPUStatusWord & 0xd) != 0) goto LAB_007103c3;
                ppuStack_fc = (undefined **)0x7101cd;
                uVar6 = (*pcVar14)();
                *(undefined4 *)(*(int *)(local_24[0] + 6) + iVar12) = uVar6;
                ppuStack_fc = (undefined **)0x7101df;
                __vbaFreeVar();
                pcVar13 = __vbaUI1I2_exref;
                puVar10 = puStack_f8;
                if (0xfe < (byte)local_30) goto LAB_007103c8;
                local_30 = (code *)CONCAT31(local_30._1_3_,(byte)local_30 + 1);
              }
              while( true ) {
                if (DAT_007273d0 != 0) {
                  ppuStack_fc = (undefined **)&local_6c;
                  ppsStack_100 = (short **)0x710357;
                  modMain::Proc_719470();
                  ppuStack_fc = (undefined **)0x71035c;
                  modMain::Proc_71ddd0();
                  local_8 = 0;
                  ppuStack_fc = (undefined **)&LAB_007103a4;
                  ppsStack_100 = local_24;
                  puStack_104 = (undefined *)0x0;
                  puStack_108 = (undefined1 *)0x71038c;
                  __vbaAryDestruct();
                  ppsStack_100 = local_44;
                  puStack_104 = (undefined *)0x0;
                  puStack_108 = (undefined1 *)0x710394;
                  __vbaAryDestruct();
                  ppsStack_100 = (short **)&local_6c;
                  puStack_104 = &DAT_00403f6c;
                  puStack_108 = (undefined1 *)0x7103a3;
                  __vbaRecDestruct();
                  return;
                }
                ppuStack_fc = (undefined **)0x710215;
                bVar1 = (*pcVar13)();
                ppuStack_fc = (undefined **)0x71021f;
                uVar2 = (*pcVar13)();
                local_30 = (code *)CONCAT31(local_30._1_3_,uVar2);
                while ((byte)local_30 <= bVar1) {
                  ppuStack_fc = (undefined **)0x710238;
                  bVar3 = (*pcVar13)();
                  ppuStack_fc = (undefined **)0x710242;
                  bVar4 = (*pcVar13)();
                  while( true ) {
                    pcVar13 = (code *)CONCAT31((int3)((uint)pcVar13 >> 8),bVar4);
                    if (bVar3 < bVar4) break;
                    ppuStack_fc = (undefined **)0xcc0020;
                    ppsStack_100 = (short **)0x0;
                    ppsStack_10c = (short **)(int)local_5c._2_2_;
                    puStack_104 = (undefined *)0x0;
                    puStack_108 = (undefined1 *)local_60;
                    puVar10 = (undefined4 *)(int)(short)local_5c;
                    if (((((SBORROW2((ushort)bVar4,1)) ||
                          (iVar12 = (int)(short)(bVar4 - 1) * (int)local_5c._2_2_,
                          sVar9 = (short)iVar12, sVar9 != iVar12)) ||
                         (puStack_f8 = (undefined4 *)(sVar9 + local_3c),
                         SCARRY4((int)sVar9,local_3c))) ||
                        ((puVar10 = puStack_f8, SBORROW2((ushort)(byte)local_30,1) ||
                         (iVar12 = (int)(short)((byte)local_30 - 1) * (int)(short)local_5c,
                         sVar9 = (short)iVar12, sVar9 != iVar12)))) || (SCARRY4((int)sVar9,uVar5)))
                    goto LAB_007103c8;
                    uStack_11c = DAT_007272f0;
                    uStack_120 = 0x7102c5;
                    auStack_118[0] = (int)sVar9 + uVar5;
                    FUN_0040432c();
                    ppuStack_fc = (undefined **)0x7102c7;
                    __vbaSetSystemError();
                    bVar17 = 0xfe < bVar4;
                    bVar4 = bVar4 + 1;
                    puVar10 = puStack_f8;
                    if (bVar17) goto LAB_007103c8;
                  }
                  pcVar13 = __vbaUI1I2_exref;
                  puVar10 = puStack_f8;
                  if (0xfe < (byte)local_30) goto LAB_007103c8;
                  local_30 = (code *)CONCAT31(local_30._1_3_,(byte)local_30 + 1);
                }
                ppuStack_fc = (undefined **)0x7102f6;
                modMain::Proc_71c9c0();
                bVar17 = SCARRY4(uVar5,2);
                uVar5 = uVar5 + 2;
                puVar10 = puStack_f8;
                if ((bVar17) || (iVar12 = local_3c + -1, SBORROW4(local_3c,1))) break;
                if ((int)(short)local_5c < (int)uVar5) {
                  uVar5 = 1;
                }
                if ((int)uVar5 < -(int)(short)local_5c) {
                  uVar5 = 0xffffffff;
                }
                local_3c = iVar12;
                if (local_5c._2_2_ < iVar12) {
                  local_3c = 1;
                }
                if (local_3c < -(int)local_5c._2_2_) {
                  local_3c = -1;
                }
                ppuStack_fc = (undefined **)0x710349;
                rtcDoEvents();
              }
            }
          }
        }
      }
    }
  }
LAB_007103c8:
  puStack_f8 = puVar10;
  ppuStack_fc = (undefined **)0x7103ce;
  __vbaErrorOverflow();
  puStack_108 = &LAB_004016b6;
  ppsStack_10c = ExceptionList;
  puStack_104 = (undefined *)&uStack_13c;
  ppsStack_100 = (short **)&DAT_00401288;
  ppuStack_fc = (undefined **)(unaff_EDI & 1);
  piVar16 = (int *)(unaff_EDI & 0xfffffffe);
  ExceptionList = &ppsStack_10c;
  uStack_13c = uVar5;
  pcStack_138 = pcVar14;
  pcStack_134 = pcVar13;
  puStack_f8 = (undefined4 *)&stack0xfffffffc;
  (**(code **)(*piVar16 + 4))(piVar16);
  auStack_118[2] = 0;
  auStack_118[1] = 0;
  auStack_118[0] = 0;
  uVar6 = (**(code **)(*piVar16 + 0x330))(piVar16);
  piVar7 = (int *)__vbaObjSet(auStack_118 + 1,uVar6);
  uVar6 = (**(code **)(*piVar16 + 0x330))(piVar16);
  piVar16 = (int *)__vbaObjSet(auStack_118 + 2,uVar6);
  iVar12 = (**(code **)(*piVar16 + 0x68))(piVar16,auStack_118);
  if (iVar12 < 0) {
    __vbaHresultCheckObj(iVar12,piVar16,&DAT_004040a8,0x68);
  }
  iVar12 = (**(code **)(*piVar7 + 0x6c))(piVar7,~auStack_118[0]);
  if (iVar12 < 0) {
    __vbaHresultCheckObj(iVar12,piVar7,&DAT_004040a8,0x6c);
  }
  __vbaFreeObjList(2,auStack_118 + 2,auStack_118 + 1);
  return;
}


// ---- mnuOptionsBonziHelp_ev0 @ 007103d0

/* WARNING: Type propagation algorithm not settling */

void frmMain::mnuOptionsBonziHelp_ev0(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  int *piVar4;
  uint local_24 [3];
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffb8;
  local_c = &DAT_00401288;
  local_8 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar4 + 4))(piVar4);
  local_24[2] = 0;
  local_24[1] = 0;
  local_24[0] = 0;
  uVar1 = (**(code **)(*piVar4 + 0x330))(piVar4);
  piVar2 = (int *)__vbaObjSet(local_24 + 1,uVar1);
  uVar1 = (**(code **)(*piVar4 + 0x330))(piVar4);
  piVar4 = (int *)__vbaObjSet(local_24 + 2,uVar1);
  iVar3 = (**(code **)(*piVar4 + 0x68))(piVar4,local_24);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_004040a8,0x68);
  }
  iVar3 = (**(code **)(*piVar2 + 0x6c))(piVar2,~local_24[0]);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_004040a8,0x6c);
  }
  __vbaFreeObjList(2,local_24 + 2,local_24 + 1);
  return;
}


// ---- mnuOptionsLanguageEnglish_ev0 @ 007104e0

undefined4 frmMain::mnuOptionsLanguageEnglish_ev0(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00401298;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  __vbaStrCopy();
  modMain::Proc_712890();
  modMain::Proc_711b50();
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuOptionsLanguageGerman_ev0 @ 00710560

undefined4 frmMain::mnuOptionsLanguageGerman_ev0(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004012a0;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  __vbaStrCopy();
  modMain::Proc_712890();
  modMain::Proc_711b50();
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuOptionsLanguageNorwegian_ev0 @ 007105e0

undefined4 frmMain::mnuOptionsLanguageNorwegian_ev0(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004012a8;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  __vbaStrCopy();
  modMain::Proc_712890();
  modMain::Proc_711b50();
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuOptionsLayoutBackBack_ev0 @ 00710660

undefined4 frmMain::mnuOptionsLayoutBackBack_ev0(uint param_1,undefined2 *param_2)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004012b0;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  DAT_007273bc = *param_2;
  modMain::Proc_71ddd0();
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuOptionsLayoutBgBg_ev0 @ 007106e0

undefined4 frmMain::mnuOptionsLayoutBgBg_ev0(uint param_1,short *param_2)

{
  undefined4 uVar1;
  undefined2 *unaff_EDI;
  short *psStack_e8;
  undefined4 uStack_e4;
  undefined4 uStack_e0;
  undefined4 uStack_d8;
  void *pvStack_d4;
  undefined4 *puStack_d0;
  undefined4 *puStack_cc;
  undefined4 *puStack_c8;
  undefined4 *puStack_c4;
  wchar_t *pwStack_c0;
  undefined4 *puStack_bc;
  int *piStack_b8;
  undefined4 local_a0;
  undefined4 local_9c [2];
  wchar_t *local_94;
  undefined4 local_7c [4];
  undefined4 local_6c [4];
  undefined4 local_5c [2];
  undefined4 local_54;
  undefined4 local_4c [4];
  undefined4 local_3c [4];
  undefined4 local_2c [2];
  short local_24;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff4c;
  local_c = &DAT_004012b8;
  local_8 = param_1 & 1;
  piStack_b8 = (int *)(param_1 & 0xfffffffe);
  puStack_bc = (undefined4 *)0x710722;
  ExceptionList = &pvStack_18;
  (**(code **)(*piStack_b8 + 4))();
  puStack_bc = (undefined4 *)DAT_0072739c;
  DAT_007273c0 = *param_2;
  pwStack_c0 = u_BG_BG_004046fc;
  local_1c = 0;
  local_2c[0] = 0;
  local_3c[0] = 0;
  local_4c[0] = 0;
  local_5c[0] = 0;
  local_6c[0] = 0;
  local_7c[0] = 0;
  local_9c[0] = 0;
  local_a0 = 0;
  puStack_c4 = (undefined4 *)0x710763;
  local_54 = __vbaStrCat();
  puStack_bc = local_2c;
  local_24 = *param_2 + 1;
  pwStack_c0 = (wchar_t *)local_3c;
  if (!SCARRY2(*param_2,1)) {
    local_5c[0] = 8;
    local_2c[0] = 2;
    puStack_c4 = (undefined4 *)0x710794;
    rtcVarStrFromVar();
    puStack_bc = local_3c;
    pwStack_c0 = (wchar_t *)local_4c;
    puStack_c4 = (undefined4 *)0x7107a2;
    rtcTrimVar();
    puStack_bc = local_5c;
    pwStack_c0 = (wchar_t *)local_4c;
    puStack_c4 = local_6c;
    local_94 = u__BMP_0040470c;
    local_9c[0] = 8;
    puStack_c8 = (undefined4 *)0x7107c6;
    puStack_bc = (undefined4 *)__vbaVarCat();
    pwStack_c0 = (wchar_t *)local_9c;
    puStack_c4 = local_7c;
    puStack_c8 = (undefined4 *)0x7107d4;
    puStack_bc = (undefined4 *)__vbaVarCat();
    pwStack_c0 = (wchar_t *)0x7107db;
    __vbaStrVarMove();
    puStack_bc = (undefined4 *)0x7107e6;
    __vbaStrMove();
    puStack_bc = (undefined4 *)0x7107f3;
    __vbaStrCopy();
    puStack_bc = (undefined4 *)0x7107fc;
    __vbaFreeStr();
    puStack_bc = local_7c;
    pwStack_c0 = (wchar_t *)local_6c;
    puStack_c4 = local_4c;
    puStack_c8 = local_5c;
    puStack_cc = local_3c;
    puStack_d0 = local_2c;
    pvStack_d4 = (void *)0x6;
    uStack_d8 = 0x71081c;
    __vbaFreeVarList();
    puStack_bc = &local_a0;
    local_a0 = 0;
    pwStack_c0 = (wchar_t *)&DAT_0072730c;
    puStack_c4 = (undefined4 *)0x710836;
    modMain::Proc_718ed0();
    puStack_c4 = (undefined4 *)0x71083b;
    modMain::Proc_722870();
    puStack_c4 = (undefined4 *)0x710840;
    uVar1 = modMain::Proc_71ddd0();
    return uVar1;
  }
  puStack_c4 = (undefined4 *)0x71089d;
  __vbaErrorOverflow();
  puStack_d0 = (undefined4 *)&LAB_004016b6;
  pvStack_d4 = ExceptionList;
  uStack_e0 = 8;
  uStack_e4 = 0;
  puStack_cc = &psStack_e8;
  psStack_e8 = param_2;
  puStack_c8 = (undefined4 *)&DAT_004012c8;
  puStack_c4 = (undefined4 *)((uint)piStack_b8 & 1);
  piStack_b8 = (int *)((uint)piStack_b8 & 0xfffffffe);
  ExceptionList = &pvStack_d4;
  pwStack_c0 = (wchar_t *)&stack0xfffffffc;
  (**(code **)(*piStack_b8 + 4))(piStack_b8);
  DAT_007273b8 = *unaff_EDI;
  modMain::Proc_71ddd0();
  puStack_c4 = (undefined4 *)0x0;
  (**(code **)(*piStack_b8 + 8))(piStack_b8);
  ExceptionList = pvStack_d4;
  return puStack_c4;
}


// ---- mnuOptionsLayoutFrontFront_ev0 @ 007108a0

undefined4 frmMain::mnuOptionsLayoutFrontFront_ev0(uint param_1,undefined2 *param_2)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004012c8;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  DAT_007273b8 = *param_2;
  modMain::Proc_71ddd0();
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuOptionsRulesDrawOne_ev0 @ 00710920

undefined4 frmMain::mnuOptionsRulesDrawOne_ev0(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004012d0;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  DAT_007273cb = __vbaUI1I2();
  modMain::Proc_71ddd0();
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuOptionsRulesDrawThree_ev0 @ 007109a0

undefined4 frmMain::mnuOptionsRulesDrawThree_ev0(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004012d8;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  DAT_007273cb = __vbaUI1I2();
  modMain::Proc_71ddd0();
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuOptionsSoundsDefsndSnd_ev0 @ 00710a20

void frmMain::mnuOptionsSoundsDefsndSnd_ev0(uint param_1,short *param_2)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  short *unaff_EDI;
  undefined4 *puStack_18c;
  undefined4 *puStack_188;
  undefined4 *puStack_184;
  undefined4 *puStack_180;
  undefined4 *puStack_17c;
  undefined4 *puStack_178;
  undefined4 **ppuStack_174;
  undefined4 *puStack_170;
  int *piStack_16c;
  undefined4 auStack_154 [2];
  wchar_t *pwStack_14c;
  undefined4 auStack_134 [4];
  undefined4 auStack_124 [4];
  undefined4 auStack_114 [2];
  undefined4 uStack_10c;
  undefined4 auStack_104 [4];
  undefined4 auStack_f4 [4];
  undefined4 auStack_e4 [2];
  undefined4 uStack_dc;
  undefined4 uStack_d8;
  undefined4 *puStack_d4;
  undefined **ppuStack_d0;
  undefined4 *puStack_cc;
  undefined **ppuStack_c8;
  undefined4 *puStack_c4;
  undefined4 *puStack_c0;
  undefined **ppuStack_bc;
  undefined **ppuStack_b8;
  int *piStack_b4;
  undefined *local_9c [2];
  wchar_t *local_94;
  undefined4 local_7c [4];
  undefined4 local_6c [4];
  undefined4 local_5c [2];
  undefined4 local_54;
  undefined *local_4c [4];
  undefined *local_3c [4];
  undefined4 local_2c [2];
  short local_24;
  undefined *local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff50;
  local_c = &DAT_004012e0;
  local_8 = param_1 & 1;
  piStack_b4 = (int *)(param_1 & 0xfffffffe);
  ppuStack_b8 = (undefined **)0x710a62;
  ExceptionList = &pvStack_18;
  (**(code **)(*piStack_b4 + 4))();
  local_1c = (undefined *)0x0;
  local_2c[0] = 0;
  local_3c[0] = (undefined *)0x0;
  local_4c[0] = (undefined *)0x0;
  local_5c[0] = 0;
  local_6c[0] = 0;
  local_7c[0] = 0;
  local_9c[0] = (undefined *)0x0;
  ppuStack_b8 = (undefined **)0x710a85;
  rtcDoEvents();
  ppuStack_b8 = (undefined **)local_2c;
  ppuStack_bc = local_3c;
  DAT_007273c4 = *param_2;
  local_24 = DAT_007273c4 + 1;
  if (!SCARRY2(DAT_007273c4,1)) {
    local_2c[0] = 2;
    puStack_c0 = (undefined4 *)0x710ab4;
    rtcVarStrFromVar();
    ppuStack_b8 = local_3c;
    ppuStack_bc = local_4c;
    puStack_c0 = (undefined4 *)0x710ac2;
    rtcTrimVar();
    ppuStack_b8 = (undefined **)DAT_0072739c;
    ppuStack_bc = &PTR_LAB_0040478c;
    puStack_c0 = (undefined4 *)0x710ad4;
    local_54 = __vbaStrCat();
    ppuStack_bc = local_4c;
    local_5c[0] = 8;
    local_9c[0] = (undefined *)0x8;
    ppuStack_b8 = (undefined **)local_5c;
    puStack_c0 = local_6c;
    local_94 = u__wav_00404798;
    puStack_c4 = (undefined4 *)0x710b03;
    ppuStack_b8 = (undefined **)__vbaVarCat();
    ppuStack_bc = local_9c;
    puStack_c0 = local_7c;
    puStack_c4 = (undefined4 *)0x710b11;
    ppuStack_b8 = (undefined **)__vbaVarCat();
    ppuStack_bc = (undefined **)0x710b18;
    __vbaStrVarMove();
    ppuStack_b8 = (undefined **)0x710b23;
    __vbaStrMove();
    ppuStack_bc = &local_1c;
    ppuStack_b8 = (undefined **)&DAT_0072736c;
    puStack_c0 = (undefined4 *)0x710b31;
    modMain::Proc_722980();
    puStack_c0 = (undefined4 *)0x710b3a;
    __vbaFreeStr();
    puStack_c0 = local_7c;
    puStack_c4 = local_6c;
    ppuStack_c8 = local_4c;
    puStack_cc = local_5c;
    ppuStack_d0 = local_3c;
    puStack_d4 = local_2c;
    uStack_d8 = 6;
    uStack_dc = 0x710b5a;
    __vbaFreeVarList();
    return;
  }
  puStack_c0 = (undefined4 *)0x710bba;
  __vbaErrorOverflow();
  puStack_cc = (undefined4 *)&LAB_004016b6;
  ppuStack_d0 = ExceptionList;
  ppuStack_c8 = (undefined **)&stack0xfffffe98;
  puStack_c4 = (undefined4 *)&DAT_004012f0;
  puStack_c0 = (undefined4 *)((uint)piStack_b4 & 1);
  piStack_16c = (int *)((uint)piStack_b4 & 0xfffffffe);
  puStack_170 = (undefined4 *)0x710c02;
  ExceptionList = &ppuStack_d0;
  ppuStack_bc = (undefined **)&stack0xfffffffc;
  piStack_b4 = piStack_16c;
  (**(code **)(*piStack_16c + 4))();
  puStack_d4 = (undefined4 *)0x0;
  auStack_e4[0] = 0;
  auStack_f4[0] = 0;
  auStack_104[0] = 0;
  auStack_114[0] = 0;
  auStack_124[0] = 0;
  auStack_134[0] = 0;
  auStack_154[0] = 0;
  puStack_170 = (undefined4 *)0x710c25;
  rtcDoEvents();
  puStack_170 = auStack_e4;
  ppuStack_174 = (undefined4 **)auStack_f4;
  DAT_007273c6 = *unaff_EDI;
  if (!SCARRY2(DAT_007273c6,1)) {
    uStack_dc = CONCAT22(uStack_dc._2_2_,DAT_007273c6 + 1);
    auStack_e4[0] = 2;
    puStack_178 = (undefined4 *)0x710c54;
    rtcVarStrFromVar();
    puStack_170 = auStack_f4;
    ppuStack_174 = (undefined4 **)auStack_104;
    puStack_178 = (undefined4 *)0x710c62;
    rtcTrimVar();
    puStack_170 = (undefined4 *)DAT_0072739c;
    ppuStack_174 = (undefined4 **)&PTR_LAB_0040478c;
    puStack_178 = (undefined4 *)0x710c74;
    uStack_10c = __vbaStrCat();
    ppuStack_174 = (undefined4 **)auStack_104;
    auStack_114[0] = 8;
    auStack_154[0] = 8;
    puStack_170 = auStack_114;
    puStack_178 = auStack_124;
    pwStack_14c = u__wav_00404798;
    puStack_17c = (undefined4 *)0x710ca3;
    puStack_170 = (undefined4 *)__vbaVarCat();
    ppuStack_174 = (undefined4 **)auStack_154;
    puStack_178 = auStack_134;
    puStack_17c = (undefined4 *)0x710cb1;
    puStack_170 = (undefined4 *)__vbaVarCat();
    ppuStack_174 = (undefined4 **)0x710cb8;
    __vbaStrVarMove();
    puStack_170 = (undefined4 *)0x710cc3;
    __vbaStrMove();
    ppuStack_174 = &puStack_d4;
    puStack_170 = (undefined4 *)&DAT_00727370;
    puStack_178 = (undefined4 *)0x710cd1;
    modMain::Proc_722980();
    puStack_178 = (undefined4 *)0x710cda;
    __vbaFreeStr();
    puStack_178 = auStack_134;
    puStack_17c = auStack_124;
    puStack_180 = auStack_104;
    puStack_184 = auStack_114;
    puStack_188 = auStack_f4;
    puStack_18c = auStack_e4;
    __vbaFreeVarList();
    return;
  }
  puStack_178 = (undefined4 *)0x710d5a;
  __vbaErrorOverflow();
  puStack_184 = (undefined4 *)&LAB_004016b6;
  puStack_188 = ExceptionList;
  puStack_180 = (undefined4 *)&stack0xfffffe58;
  puStack_17c = (undefined4 *)&DAT_00401300;
  puStack_178 = (undefined4 *)((uint)piStack_16c & 1);
  piVar3 = (int *)((uint)piStack_16c & 0xfffffffe);
  ExceptionList = &puStack_188;
  ppuStack_174 = &ppuStack_bc;
  piStack_16c = piVar3;
  (**(code **)(*piVar3 + 4))(piVar3);
  DAT_007273d8 = ~DAT_007273d8;
  puStack_18c = (undefined4 *)0x0;
  uVar1 = (**(code **)(*piVar3 + 0x380))(piVar3);
  piVar3 = (int *)__vbaObjSet(&puStack_18c,uVar1);
  iVar2 = (**(code **)(*piVar3 + 0x6c))(piVar3,DAT_007273d8);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar3,&DAT_004040a8,0x6c);
  }
  __vbaFreeObj();
  return;
}


// ---- mnuOptionsSoundsGoalsndSnd_ev0 @ 00710bc0

void frmMain::mnuOptionsSoundsGoalsndSnd_ev0(uint param_1,short *param_2)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 *puStack_d4;
  undefined4 *puStack_d0;
  undefined4 *puStack_cc;
  undefined4 *puStack_c8;
  undefined4 *puStack_c4;
  undefined4 *puStack_c0;
  undefined **ppuStack_bc;
  undefined4 *puStack_b8;
  int *piStack_b4;
  undefined4 local_9c [2];
  wchar_t *local_94;
  undefined4 local_7c [4];
  undefined4 local_6c [4];
  undefined4 local_5c [2];
  undefined4 local_54;
  undefined4 local_4c [4];
  undefined4 local_3c [4];
  undefined4 local_2c [2];
  short local_24;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff50;
  local_c = &DAT_004012f0;
  local_8 = param_1 & 1;
  piStack_b4 = (int *)(param_1 & 0xfffffffe);
  puStack_b8 = (undefined4 *)0x710c02;
  ExceptionList = &pvStack_18;
  (**(code **)(*piStack_b4 + 4))();
  local_1c = 0;
  local_2c[0] = 0;
  local_3c[0] = 0;
  local_4c[0] = 0;
  local_5c[0] = 0;
  local_6c[0] = 0;
  local_7c[0] = 0;
  local_9c[0] = 0;
  puStack_b8 = (undefined4 *)0x710c25;
  rtcDoEvents();
  puStack_b8 = local_2c;
  ppuStack_bc = (undefined **)local_3c;
  DAT_007273c6 = *param_2;
  local_24 = DAT_007273c6 + 1;
  if (!SCARRY2(DAT_007273c6,1)) {
    local_2c[0] = 2;
    puStack_c0 = (undefined4 *)0x710c54;
    rtcVarStrFromVar();
    puStack_b8 = local_3c;
    ppuStack_bc = (undefined **)local_4c;
    puStack_c0 = (undefined4 *)0x710c62;
    rtcTrimVar();
    puStack_b8 = (undefined4 *)DAT_0072739c;
    ppuStack_bc = &PTR_LAB_0040478c;
    puStack_c0 = (undefined4 *)0x710c74;
    local_54 = __vbaStrCat();
    ppuStack_bc = (undefined **)local_4c;
    local_5c[0] = 8;
    local_9c[0] = 8;
    puStack_b8 = local_5c;
    puStack_c0 = local_6c;
    local_94 = u__wav_00404798;
    puStack_c4 = (undefined4 *)0x710ca3;
    puStack_b8 = (undefined4 *)__vbaVarCat();
    ppuStack_bc = (undefined **)local_9c;
    puStack_c0 = local_7c;
    puStack_c4 = (undefined4 *)0x710cb1;
    puStack_b8 = (undefined4 *)__vbaVarCat();
    ppuStack_bc = (undefined **)0x710cb8;
    __vbaStrVarMove();
    puStack_b8 = (undefined4 *)0x710cc3;
    __vbaStrMove();
    ppuStack_bc = (undefined **)&local_1c;
    puStack_b8 = (undefined4 *)&DAT_00727370;
    puStack_c0 = (undefined4 *)0x710cd1;
    modMain::Proc_722980();
    puStack_c0 = (undefined4 *)0x710cda;
    __vbaFreeStr();
    puStack_c0 = local_7c;
    puStack_c4 = local_6c;
    puStack_c8 = local_4c;
    puStack_cc = local_5c;
    puStack_d0 = local_3c;
    puStack_d4 = local_2c;
    __vbaFreeVarList();
    return;
  }
  puStack_c0 = (undefined4 *)0x710d5a;
  __vbaErrorOverflow();
  puStack_cc = (undefined4 *)&LAB_004016b6;
  puStack_d0 = ExceptionList;
  puStack_c8 = (undefined4 *)&stack0xffffff10;
  puStack_c4 = (undefined4 *)&DAT_00401300;
  puStack_c0 = (undefined4 *)((uint)piStack_b4 & 1);
  piVar3 = (int *)((uint)piStack_b4 & 0xfffffffe);
  ExceptionList = &puStack_d0;
  ppuStack_bc = (undefined **)&stack0xfffffffc;
  piStack_b4 = piVar3;
  (**(code **)(*piVar3 + 4))(piVar3);
  DAT_007273d8 = ~DAT_007273d8;
  puStack_d4 = (undefined4 *)0x0;
  uVar1 = (**(code **)(*piVar3 + 0x380))(piVar3);
  piVar3 = (int *)__vbaObjSet(&puStack_d4,uVar1);
  iVar2 = (**(code **)(*piVar3 + 0x6c))(piVar3,DAT_007273d8);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar3,&DAT_004040a8,0x6c);
  }
  __vbaFreeObj();
  return;
}


// ---- mnuOptionsSoundsPlaysounds_ev0 @ 00710d60

void frmMain::mnuOptionsSoundsPlaysounds_ev0(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00401300;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  DAT_007273d8 = ~DAT_007273d8;
  local_1c = 0;
  uVar1 = (**(code **)(*piVar3 + 0x380))(piVar3);
  piVar3 = (int *)__vbaObjSet(&local_1c,uVar1);
  iVar2 = (**(code **)(*piVar3 + 0x6c))(piVar3,DAT_007273d8);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar3,&DAT_004040a8,0x6c);
  }
  __vbaFreeObj();
  return;
}


// ---- mnuThemesBeach_ev0 @ 00710e30

undefined4 frmMain::mnuThemesBeach_ev0(uint param_1)

{
  int iVar1;
  int *piVar2;
  undefined4 local_1c;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffcc;
  local_c = &DAT_00401310;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  DAT_0072703c = 0;
  local_1c = __vbaI2I4();
  iVar1 = (**(code **)(*piVar2 + 0x760))(piVar2,&local_1c);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar2,&LAB_00403954,0x760);
  }
  local_1c = __vbaI2I4();
  iVar1 = (**(code **)(*piVar2 + 0x75c))(piVar2,&local_1c);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar2,&LAB_00403954,0x75c);
  }
  modMain::Proc_725520();
  local_8 = 0;
  (**(code **)(*piVar2 + 8))(piVar2);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuThemesJungle_ev0 @ 00710f00

undefined4 frmMain::mnuThemesJungle_ev0(uint param_1)

{
  int iVar1;
  int *piVar2;
  undefined4 local_1c;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffcc;
  local_c = &DAT_00401318;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  DAT_0072703c = 1;
  local_1c = __vbaI2I4();
  iVar1 = (**(code **)(*piVar2 + 0x760))(piVar2,&local_1c);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar2,&LAB_00403954,0x760);
  }
  local_1c = __vbaI2I4();
  iVar1 = (**(code **)(*piVar2 + 0x75c))(piVar2,&local_1c);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar2,&LAB_00403954,0x75c);
  }
  modMain::Proc_725520();
  local_8 = 0;
  (**(code **)(*piVar2 + 8))(piVar2);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuThemesRuins_ev0 @ 00710fe0

undefined4 frmMain::mnuThemesRuins_ev0(uint param_1)

{
  int iVar1;
  int *piVar2;
  undefined4 local_1c;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffcc;
  local_c = &DAT_00401320;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  DAT_0072703c = 2;
  local_1c = __vbaI2I4();
  iVar1 = (**(code **)(*piVar2 + 0x760))(piVar2,&local_1c);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar2,&LAB_00403954,0x760);
  }
  local_1c = __vbaI2I4();
  iVar1 = (**(code **)(*piVar2 + 0x75c))(piVar2,&local_1c);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar2,&LAB_00403954,0x75c);
  }
  modMain::Proc_725520();
  local_8 = 0;
  (**(code **)(*piVar2 + 8))(piVar2);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuTopFile_ev0 @ 007110c0

void frmMain::mnuTopFile_ev0(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00401328;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  DAT_007273d0 = 0xffff;
  local_1c = 0;
  if (DAT_00727398 == 0) {
    uVar1 = (**(code **)(*piVar3 + 0x310))(piVar3);
    piVar3 = (int *)__vbaObjSet(&local_1c,uVar1);
    iVar2 = (**(code **)(*piVar3 + 0x74))(piVar3,0);
  }
  else {
    uVar1 = (**(code **)(*piVar3 + 0x310))();
    piVar3 = (int *)__vbaObjSet(&local_1c,uVar1);
    iVar2 = (**(code **)(*piVar3 + 0x74))(piVar3,0xffffffff);
  }
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar3,&DAT_004040a8,0x74);
  }
  __vbaFreeObj();
  return;
}


// ---- mnuTopHelp_ev0 @ 007111b0

undefined4 frmMain::mnuTopHelp_ev0(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00401338;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  DAT_007273d0 = 0xffff;
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- mnuTopOptions_ev0 @ 00711220

void frmMain::mnuTopOptions_ev0(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  code *pcVar4;
  int *piVar5;
  code *pcVar6;
  undefined4 local_20 [2];
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc4;
  local_c = &DAT_00401340;
  local_8 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar5 + 4))(piVar5);
  DAT_007273d0 = 0xffff;
  local_20[0] = 0;
  if (DAT_007273cb == '\x01') {
    uVar1 = (**(code **)(*piVar5 + 0x390))();
    pcVar4 = __vbaObjSet_exref;
    piVar2 = (int *)__vbaObjSet(local_20,uVar1);
    iVar3 = (**(code **)(*piVar2 + 0x6c))(piVar2,0xffffffff);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar2,&DAT_004040a8,0x6c);
    }
    __vbaFreeObj();
    uVar1 = (**(code **)(*piVar5 + 0x394))(piVar5);
    piVar2 = (int *)__vbaObjSet(local_20,uVar1);
    iVar3 = (**(code **)(*piVar2 + 0x6c))(piVar2,0);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar2,&DAT_004040a8,0x6c);
    }
    pcVar6 = __vbaFreeObj_exref;
    __vbaFreeObj();
  }
  else {
    uVar1 = (**(code **)(*piVar5 + 0x390))(piVar5);
    pcVar4 = __vbaObjSet_exref;
    piVar2 = (int *)__vbaObjSet(local_20,uVar1);
    iVar3 = (**(code **)(*piVar2 + 0x6c))(piVar2,0);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar2,&DAT_004040a8,0x6c);
    }
    __vbaFreeObj();
    uVar1 = (**(code **)(*piVar5 + 0x394))(piVar5);
    piVar2 = (int *)__vbaObjSet(local_20,uVar1);
    iVar3 = (**(code **)(*piVar2 + 0x6c))(piVar2,0xffffffff);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar2,&DAT_004040a8,0x6c);
    }
    __vbaFreeObj();
    pcVar6 = __vbaFreeObj_exref;
  }
  if (DAT_007273d8 == 0) {
    uVar1 = (**(code **)(*piVar5 + 0x380))(piVar5);
    piVar5 = (int *)(*pcVar4)(local_20,uVar1);
    iVar3 = (**(code **)(*piVar5 + 0x6c))(piVar5,0);
  }
  else {
    uVar1 = (**(code **)(*piVar5 + 0x380))();
    piVar5 = (int *)(*pcVar4)(local_20,uVar1);
    iVar3 = (**(code **)(*piVar5 + 0x6c))(piVar5,0xffffffff);
  }
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar5,&DAT_004040a8,0x6c);
  }
  (*pcVar6)();
  return;
}


// ---- tmrShutDown_ev0 @ 00711410

/* WARNING: Restarted to delay deadcode elimination for space: ram */

void frmMain::tmrShutDown_ev0(uint param_1)

{
  short sVar1;
  int iVar2;
  int *piVar3;
  undefined4 uVar4;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_004016b6;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00401350;
  local_14 = param_1 & 1;
  local_10 = 0;
  (**(code **)(*(int *)(param_1 & 0xfffffffe) + 4))((int *)(param_1 & 0xfffffffe));
  local_8 = 2;
  __vbaOnError(0xffffffff);
  local_8 = 3;
  uVar4 = 8;
  __vbaChkstk(u_FALSE_004047d8);
  rtcGetSetting(u_BonziBUDDY_0040390c,&PTR_DAT_004047a8,u_ShutDown_004047c0,uVar4);
  __vbaStrMove();
  sVar1 = __vbaBoolStr();
  __vbaFreeStr();
  if (sVar1 != 0) {
    local_8 = 4;
    if (DAT_00727870 == (int *)0x0) {
      __vbaNew2();
    }
    piVar3 = DAT_00727870;
    if (DAT_00727010 == 0) {
      __vbaNew2();
    }
    __vbaObjSetAddref();
    iVar2 = (**(code **)(*piVar3 + 0x10))();
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,piVar3);
    }
    __vbaFreeObj();
    local_8 = 5;
    __vbaEnd();
  }
  return;
}


// ---- tmrUpdateTime_ev0 @ 00711600

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void frmMain::tmrUpdateTime_ev0(uint param_1)

{
  uint uVar1;
  code **ppcVar2;
  undefined1 uVar3;
  short sVar4;
  int iVar5;
  int **ppiVar6;
  undefined4 uVar7;
  int *piVar8;
  undefined2 extraout_var;
  undefined2 extraout_var_00;
  undefined2 extraout_var_01;
  undefined2 extraout_var_02;
  undefined2 extraout_var_03;
  code *pcVar9;
  code *pcVar10;
  code *unaff_EDI;
  bool bVar11;
  code *pcStack_194;
  code *pcStack_190;
  undefined4 uStack_18c;
  undefined4 uStack_184;
  undefined4 uStack_17c;
  undefined4 uStack_174;
  undefined4 uStack_16c;
  undefined4 uStack_164;
  int *apiStack_15c [4];
  int **ppiStack_14c;
  undefined4 auStack_148 [2];
  undefined4 uStack_140;
  undefined4 auStack_128 [4];
  undefined4 auStack_118 [4];
  undefined4 auStack_108 [2];
  undefined4 uStack_100;
  undefined4 uStack_fc;
  int *piStack_f8;
  undefined4 *puStack_f4;
  int iStack_f0;
  int *piStack_ec;
  code *pcStack_e8;
  int **ppiStack_e4;
  int *piStack_e0;
  uint uStack_dc;
  int **ppiStack_d8;
  int *piStack_d4;
  int **ppiStack_d0;
  undefined **ppuStack_cc;
  int *piStack_c8;
  undefined4 local_9c [2];
  undefined **local_94;
  undefined4 local_8c [2];
  int *local_84;
  undefined4 local_7c [4];
  undefined4 local_6c [2];
  undefined4 local_64;
  int local_5c [4];
  int *local_4c;
  undefined4 local_48;
  int local_44 [3];
  int local_38;
  undefined4 local_34;
  undefined4 local_30;
  int local_2c;
  uint local_28;
  undefined4 local_24;
  int local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff3c;
  local_c = &DAT_00401390;
  local_8 = param_1 & 1;
  piStack_c8 = (int *)(param_1 & 0xfffffffe);
  ppuStack_cc = (undefined **)0x711642;
  ExceptionList = &pvStack_18;
  (**(code **)(*piStack_c8 + 4))();
  local_1c = 0;
  local_20 = 0;
  local_24 = 0;
  local_2c = 0;
  local_30 = 0;
  local_34 = 0;
  local_38 = 0;
  local_44[1] = 0;
  local_44[0] = 0;
  local_48 = 0;
  local_4c = (int *)0x0;
  local_5c[0] = 0;
  local_6c[0] = 0;
  local_7c[0] = 0;
  local_8c[0] = 0;
  local_9c[0] = 0;
  ppuStack_cc = (undefined **)0x71167f;
  iVar5 = FUN_00404384();
  ppuStack_cc = (undefined **)0x711687;
  __vbaSetSystemError();
  pcVar10 = (code *)(iVar5 - DAT_007273b0);
  _DAT_007273b4 = iVar5;
  if (!SBORROW4(iVar5,DAT_007273b0)) {
    local_2c = (int)pcVar10 / 3600000;
    iVar5 = (int)((longlong)local_2c * 3600000);
    if (((longlong)iVar5 == (longlong)local_2c * 3600000) &&
       (bVar11 = SBORROW4((int)pcVar10,iVar5), pcVar10 = pcVar10 + -iVar5, !bVar11)) {
      local_20 = (int)pcVar10 / 60000;
      iVar5 = (int)((longlong)local_20 * 60000);
      if (((longlong)iVar5 == (longlong)local_20 * 60000) &&
         (bVar11 = SBORROW4((int)pcVar10,iVar5), pcVar10 = pcVar10 + -iVar5, !bVar11)) {
        local_38 = (int)pcVar10 / 1000;
        ppuStack_cc = (undefined **)0x71170f;
        __vbaStrCopy();
        ppuStack_cc = (undefined **)0x711719;
        __vbaStrCopy();
        pcVar10 = __vbaStrMove_exref;
        unaff_EDI = __vbaStrVarMove_exref;
        if (0 < local_2c) {
          ppuStack_cc = (undefined **)local_8c;
          ppiStack_d0 = (int **)local_5c;
          local_84 = &local_2c;
          local_8c[0] = 0x4003;
          piStack_d4 = (int *)0x711743;
          rtcVarStrFromVar();
          ppuStack_cc = (undefined **)local_5c;
          ppiStack_d0 = (int **)local_6c;
          piStack_d4 = (int *)0x711751;
          rtcTrimVar();
          ppuStack_cc = (undefined **)local_6c;
          ppiStack_d0 = (int **)local_9c;
          piStack_d4 = local_7c;
          local_94 = &PTR_LAB_00404820;
          local_9c[0] = 8;
          ppiStack_d8 = (int **)0x71177a;
          ppuStack_cc = (undefined **)__vbaVarCat();
          unaff_EDI = __vbaStrVarMove_exref;
          ppiStack_d0 = (int **)0x711783;
          __vbaStrVarMove();
          pcVar10 = __vbaStrMove_exref;
          ppuStack_cc = (undefined **)0x711790;
          __vbaStrMove();
          ppuStack_cc = (undefined **)local_7c;
          ppiStack_d0 = (int **)local_6c;
          piStack_d4 = local_5c;
          ppiStack_d8 = (int **)0x3;
          uStack_dc = 0x7117a4;
          __vbaFreeVarList();
        }
        if ((0 < local_20) || (0 < local_2c)) {
          ppuStack_cc = (undefined **)local_8c;
          ppiStack_d0 = (int **)local_5c;
          local_84 = &local_20;
          local_8c[0] = 0x4003;
          piStack_d4 = (int *)0x7117e0;
          rtcVarStrFromVar();
          ppuStack_cc = (undefined **)local_5c;
          ppiStack_d0 = (int **)local_6c;
          piStack_d4 = (int *)0x7117ee;
          rtcTrimVar();
          ppuStack_cc = (undefined **)local_6c;
          ppiStack_d0 = (int **)local_9c;
          piStack_d4 = local_7c;
          local_94 = &PTR_DAT_0040482c;
          local_9c[0] = 8;
          ppiStack_d8 = (int **)0x711817;
          ppuStack_cc = (undefined **)__vbaVarCat();
          ppiStack_d0 = (int **)0x71181a;
          (*unaff_EDI)();
          ppiStack_d0 = (int **)0x711821;
          (*pcVar10)();
          ppuStack_cc = (undefined **)local_7c;
          ppiStack_d0 = (int **)local_6c;
          piStack_d4 = local_5c;
          ppiStack_d8 = (int **)0x3;
          uStack_dc = 0x711835;
          __vbaFreeVarList();
        }
        ppuStack_cc = (undefined **)local_8c;
        ppiStack_d0 = (int **)local_5c;
        local_84 = &local_38;
        local_8c[0] = 0x4003;
        piStack_d4 = (int *)0x711859;
        rtcVarStrFromVar();
        ppuStack_cc = (undefined **)local_5c;
        ppiStack_d0 = (int **)local_6c;
        piStack_d4 = (int *)0x711867;
        rtcTrimVar();
        ppuStack_cc = (undefined **)local_6c;
        ppiStack_d0 = (int **)local_9c;
        piStack_d4 = local_7c;
        local_94 = (undefined **)&DAT_00404838;
        local_9c[0] = 8;
        ppiStack_d8 = (int **)0x711890;
        ppuStack_cc = (undefined **)__vbaVarCat();
        ppiStack_d0 = (int **)0x711893;
        (*unaff_EDI)();
        ppiStack_d0 = (int **)0x71189a;
        (*pcVar10)();
        ppuStack_cc = (undefined **)local_7c;
        ppiStack_d0 = (int **)local_6c;
        piStack_d4 = local_5c;
        ppiStack_d8 = (int **)0x3;
        uStack_dc = 0x7118ae;
        __vbaFreeVarList();
        ppuStack_cc = (undefined **)local_34;
        ppiStack_d0 = (int **)0x7118bb;
        iVar5 = __vbaLenBstr();
        ppuStack_cc = (undefined **)(6 - iVar5);
        if (!SBORROW4(6,iVar5)) {
          ppiStack_d0 = (int **)0x7118cf;
          rtcSpaceBstr();
          ppuStack_cc = (undefined **)0x7118d6;
          ppuStack_cc = (undefined **)(*pcVar10)();
          unaff_EDI = __vbaStrCat_exref;
          ppiStack_d0 = (int **)local_34;
          piStack_d4 = (int *)0x7118e3;
          __vbaStrCat();
          ppuStack_cc = (undefined **)0x7118ea;
          (*pcVar10)();
          ppuStack_cc = (undefined **)0x7118f3;
          __vbaFreeStr();
          ppuStack_cc = (undefined **)local_30;
          ppiStack_d0 = (int **)0x7118fd;
          iVar5 = __vbaLenBstr();
          ppuStack_cc = (undefined **)(5 - iVar5);
          if (!SBORROW4(5,iVar5)) {
            ppiStack_d0 = (int **)0x711911;
            rtcSpaceBstr();
            ppuStack_cc = (undefined **)0x711918;
            ppuStack_cc = (undefined **)(*pcVar10)();
            ppiStack_d0 = (int **)local_30;
            piStack_d4 = (int *)0x71191f;
            __vbaStrCat();
            ppuStack_cc = (undefined **)0x711926;
            (*pcVar10)();
            ppuStack_cc = (undefined **)0x71192f;
            __vbaFreeStr();
            ppuStack_cc = (undefined **)local_1c;
            ppiStack_d0 = (int **)0x711939;
            iVar5 = __vbaLenBstr();
            ppuStack_cc = (undefined **)(5 - iVar5);
            if (!SBORROW4(5,iVar5)) {
              ppiStack_d0 = (int **)0x71194d;
              rtcSpaceBstr();
              ppuStack_cc = (undefined **)0x711954;
              ppuStack_cc = (undefined **)(*pcVar10)();
              ppiStack_d0 = (int **)local_1c;
              piStack_d4 = (int *)0x71195b;
              __vbaStrCat();
              ppuStack_cc = (undefined **)0x711962;
              (*pcVar10)();
              ppuStack_cc = (undefined **)0x71196b;
              __vbaFreeStr();
              ppuStack_cc = (undefined **)local_34;
              ppiStack_d0 = (int **)local_30;
              piStack_d4 = (int *)0x711975;
              __vbaStrCat();
              ppuStack_cc = (undefined **)0x71197c;
              ppuStack_cc = (undefined **)(*pcVar10)();
              ppiStack_d0 = (int **)local_1c;
              piStack_d4 = (int *)0x711983;
              __vbaStrCat();
              ppuStack_cc = (undefined **)0x71198a;
              (*pcVar10)();
              ppuStack_cc = (undefined **)0x711993;
              __vbaFreeStr();
              ppuStack_cc = (undefined **)0x71199e;
              uVar3 = __vbaUI1I2();
              local_28 = CONCAT31(local_28._1_3_,uVar3);
              ppuStack_cc = (undefined **)local_24;
              ppiStack_d0 = (int **)0x7119ab;
              iVar5 = __vbaLenBstr();
              ppuStack_cc = (undefined **)((local_28 & 0xff) - iVar5);
              if (!SBORROW4(local_28 & 0xff,iVar5)) {
                ppiStack_d0 = (int **)0x7119c3;
                rtcSpaceBstr();
                ppuStack_cc = (undefined **)0x7119ca;
                ppuStack_cc = (undefined **)(*pcVar10)();
                ppiStack_d0 = (int **)local_24;
                piStack_d4 = (int *)0x7119d1;
                __vbaStrCat();
                ppuStack_cc = (undefined **)0x7119d8;
                (*pcVar10)();
                ppuStack_cc = (undefined **)0x7119e1;
                __vbaFreeStr();
                ppuStack_cc = &PTR_DAT_00404858;
                ppiStack_d0 = (int **)local_24;
                piStack_d4 = (int *)0x7119ec;
                __vbaStrCat();
                ppuStack_cc = (undefined **)0x7119f3;
                (*pcVar10)();
                if (DAT_00727010 == (int **)0x0) {
                  ppuStack_cc = (undefined **)&DAT_00727010;
                  ppiStack_d0 = (int **)&DAT_00402418;
                  piStack_d4 = (int *)0x711a0c;
                  __vbaNew2();
                }
                ppuStack_cc = (undefined **)&DAT_00404884;
                ppiStack_d0 = (int **)0x0;
                piStack_d4 = (int *)0x3;
                ppiStack_d8 = DAT_00727010;
                uStack_dc = 0x711a22;
                uStack_dc = (*(code *)(*DAT_00727010)[0xf6])();
                piStack_e0 = local_44;
                ppiStack_e4 = (int **)0x711a2f;
                uStack_dc = __vbaObjSet();
                piStack_e0 = local_5c;
                ppiStack_e4 = (int **)0x711a3a;
                piStack_d4 = (int *)__vbaLateIdCallLd();
                ppiStack_d8 = (int **)0x711a44;
                ppiStack_d0 = (int **)__vbaCastObjVar();
                piStack_d4 = &local_48;
                ppiStack_d8 = (int **)0x711a4b;
                ppiVar6 = (int **)__vbaObjSet();
                ppiStack_d0 = &local_4c;
                piStack_d4 = local_6c;
                local_64 = 1;
                local_6c[0] = 2;
                uStack_dc = 0x711a69;
                ppiStack_d8 = ppiVar6;
                pcVar10 = (code *)(*(code *)(*ppiVar6)[9])();
                if ((int)pcVar10 < 0) {
                  uStack_dc = 0x24;
                  piStack_e0 = (int *)&DAT_00404884;
                  piStack_ec = (int *)0x711a7e;
                  pcStack_e8 = pcVar10;
                  ppiStack_e4 = ppiVar6;
                  __vbaHresultCheckObj();
                }
                piVar8 = local_4c;
                uStack_dc = local_24;
                piStack_e0 = local_4c;
                ppiStack_e4 = (int **)0x711a90;
                iStack_f0 = (**(code **)(*local_4c + 0x80))();
                if (iStack_f0 < 0) {
                  ppiStack_e4 = (int **)0x80;
                  pcStack_e8 = (code *)&DAT_00404894;
                  piStack_ec = piVar8;
                  puStack_f4 = (undefined4 *)0x711aa8;
                  __vbaHresultCheckObj();
                }
                ppiStack_e4 = &local_4c;
                pcStack_e8 = (code *)&local_48;
                piStack_ec = local_44;
                iStack_f0 = 3;
                puStack_f4 = (undefined4 *)0x711abc;
                __vbaFreeObjList();
                puStack_f4 = local_6c;
                piStack_f8 = local_5c;
                uStack_fc = 2;
                uStack_100 = 0x711acc;
                __vbaFreeVarList();
                local_8 = 0;
                ppiStack_e4 = (int **)&LAB_00711b29;
                pcStack_e8 = (code *)0x711b19;
                __vbaFreeStr();
                pcStack_e8 = (code *)0x711b1e;
                __vbaFreeStr();
                pcStack_e8 = (code *)0x711b23;
                __vbaFreeStr();
                pcStack_e8 = (code *)0x711b28;
                __vbaFreeStr();
                return;
              }
            }
          }
        }
      }
    }
  }
  ppuStack_cc = (undefined **)0x711b4e;
  __vbaErrorOverflow();
  piStack_d4 = (int *)&LAB_004016b6;
  ppiStack_d8 = ExceptionList;
  uStack_18c = 0;
  ppiStack_d0 = (int **)&pcStack_194;
  ppuStack_cc = (undefined **)&DAT_004013a0;
  piStack_e0 = (int *)0x0;
  ppiStack_e4 = (int **)0x0;
  pcStack_e8 = (code *)0x0;
  piStack_f8 = (int *)0x0;
  auStack_108[0] = 0;
  auStack_118[0] = 0;
  auStack_128[0] = 0;
  auStack_148[0] = 0;
  apiStack_15c[0] = (int *)0x0;
  ExceptionList = &ppiStack_d8;
  pcStack_194 = unaff_EDI;
  pcStack_190 = pcVar10;
  ppcVar2 = &pcStack_194;
  piStack_c8 = (int *)&stack0xfffffffc;
  if (DAT_00727010 == (int **)0x0) {
    ExceptionList = &ppiStack_d8;
    piStack_c8 = (int *)&stack0xfffffffc;
    __vbaNew2(&DAT_00402418,&DAT_00727010);
    ppcVar2 = (code **)ppiStack_d0;
  }
  ppiStack_d0 = (int **)ppcVar2;
  __vbaObjSetAddref(apiStack_15c,DAT_00727010);
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x308))(apiStack_15c[0]);
  pcVar9 = __vbaObjSet_exref;
  piVar8 = (int *)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_007273ec);
  pcVar10 = __vbaHresultCheckObj_exref;
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,piVar8,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x31c))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_007273f0);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x3b4))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_007273f4);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x30c))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_007273f8);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x310))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_007273fc);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x318))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_00727400);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x358))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_00727404);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x35c))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_00727408);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x364))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_0072740c);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x360))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_00727410);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x334))(apiStack_15c[0]);
  ppiStack_14c = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  iVar5 = (**(code **)((int)*ppiStack_14c + 100))(ppiStack_14c,DAT_00727414);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  uVar7 = (**(code **)(*apiStack_15c[0] + 0x344))(apiStack_15c[0]);
  ppiVar6 = (int **)__vbaObjSet(&ppiStack_e4,uVar7);
  ppiStack_14c = ppiVar6;
  iVar5 = (*(code *)(*ppiVar6)[0x19])(ppiVar6,DAT_00727418);
  if (iVar5 < 0) {
    __vbaHresultCheckObj(iVar5,ppiStack_14c,&DAT_004040a8,100);
  }
  __vbaFreeObj();
  if (!SBORROW2(DAT_007273ba,1)) {
    uStack_dc = 0;
    uStack_164 = CONCAT22(extraout_var,DAT_007273ba + -1);
    uVar1 = uStack_dc;
    do {
      uStack_dc = uVar1;
      uVar1 = uStack_dc;
      sVar4 = (short)uStack_dc;
      if ((short)uStack_164 < sVar4) {
        uVar7 = (**(code **)(*apiStack_15c[0] + 0x34c))(apiStack_15c[0]);
        piVar8 = (int *)__vbaObjSet(&ppiStack_e4,uVar7);
        iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_00727420);
        if (iVar5 < 0) {
          (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
        }
        __vbaFreeObj();
        if (!SBORROW2(DAT_007273be,1)) {
          sVar4 = 0;
          uStack_16c = CONCAT22(extraout_var_00,DAT_007273be + -1);
          goto LAB_00712096;
        }
        break;
      }
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x348))(apiStack_15c[0]);
      piVar8 = (int *)__vbaObjSet(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 0x40))(piVar8,uVar1,&pcStack_e8);
      if (iVar5 < 0) {
        __vbaHresultCheckObj(iVar5,piVar8,&DAT_00404af0,0x40);
      }
      pcVar10 = pcStack_e8;
      ppiVar6 = &piStack_f8;
      if (SCARRY2(sVar4,1)) break;
      uStack_140 = DAT_0072741c;
      auStack_148[0] = 8;
      iStack_f0 = CONCAT22(iStack_f0._2_2_,sVar4 + 1);
      piStack_f8 = (int *)0x2;
      rtcVarStrFromVar(auStack_108,ppiVar6);
      rtcTrimVar(auStack_118,auStack_108);
      iVar5 = *(int *)pcVar10;
      uVar7 = __vbaVarCat(auStack_128,auStack_118,auStack_148);
      ppiVar6 = (int **)__vbaStrVarVal(&piStack_e0,uVar7);
      iVar5 = (**(code **)(iVar5 + 100))(pcVar10,ppiVar6);
      if (iVar5 < 0) {
        __vbaHresultCheckObj(iVar5,pcVar10,&DAT_004040a8,100);
      }
      __vbaFreeStr();
      __vbaFreeObjList(2,&ppiStack_e4,&pcStack_e8);
      __vbaFreeVarList(4,&piStack_f8,auStack_108,auStack_118,auStack_128);
      pcVar10 = __vbaHresultCheckObj_exref;
      uVar1 = (uint)(ushort)((short)uStack_dc + 1);
    } while (!SCARRY2((short)uStack_dc,1));
  }
  goto LAB_00712886;
  while( true ) {
    uVar7 = (**(code **)(*apiStack_15c[0] + 0x350))(apiStack_15c[0]);
    piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
    iVar5 = (**(code **)(*piVar8 + 0x40))(piVar8,sVar4,&pcStack_e8);
    if (iVar5 < 0) {
      __vbaHresultCheckObj(iVar5,piVar8,&DAT_00404af0,0x40);
    }
    pcVar10 = pcStack_e8;
    uStack_140 = DAT_00727424;
    ppiVar6 = &piStack_f8;
    if (SCARRY2(sVar4,1)) break;
    auStack_148[0] = 8;
    iStack_f0 = CONCAT22(iStack_f0._2_2_,sVar4 + 1);
    piStack_f8 = (int *)0x2;
    rtcVarStrFromVar(auStack_108,ppiVar6);
    rtcTrimVar(auStack_118,auStack_108);
    iVar5 = *(int *)pcVar10;
    uVar7 = __vbaVarCat(auStack_128,auStack_118,auStack_148);
    ppiVar6 = (int **)__vbaStrVarVal(&piStack_e0,uVar7);
    iVar5 = (**(code **)(iVar5 + 100))(pcVar10,ppiVar6);
    if (iVar5 < 0) {
      __vbaHresultCheckObj(iVar5,pcVar10,&DAT_004040a8,100);
    }
    __vbaFreeStr();
    __vbaFreeObjList(2,&ppiStack_e4,&pcStack_e8);
    __vbaFreeVarList(4,&piStack_f8,auStack_108,auStack_118,auStack_128);
    bVar11 = SCARRY2(sVar4,1);
    sVar4 = sVar4 + 1;
    pcVar9 = __vbaObjSet_exref;
    if (bVar11) break;
LAB_00712096:
    if ((short)uStack_16c < sVar4) {
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x338))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_00727428);
      pcVar10 = __vbaHresultCheckObj_exref;
      if (iVar5 < 0) {
        __vbaHresultCheckObj(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      if (!SBORROW2(DAT_007273c2,1)) {
        sVar4 = 0;
        uStack_174 = CONCAT22(extraout_var_01,DAT_007273c2 + -1);
        goto LAB_0071220a;
      }
      break;
    }
  }
  goto LAB_00712886;
  while( true ) {
    uVar7 = (**(code **)(*apiStack_15c[0] + 0x33c))(apiStack_15c[0]);
    piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
    iVar5 = (**(code **)(*piVar8 + 0x40))(piVar8,sVar4,&pcStack_e8);
    if (iVar5 < 0) {
      (*pcVar10)(iVar5,piVar8,&DAT_00404af0,0x40);
    }
    pcVar10 = pcStack_e8;
    uStack_140 = DAT_0072742c;
    ppiVar6 = &piStack_f8;
    if (SCARRY2(sVar4,1)) break;
    auStack_148[0] = 8;
    iStack_f0 = CONCAT22(iStack_f0._2_2_,sVar4 + 1);
    piStack_f8 = (int *)0x2;
    rtcVarStrFromVar(auStack_108,ppiVar6);
    rtcTrimVar(auStack_118,auStack_108);
    iVar5 = *(int *)pcVar10;
    uVar7 = __vbaVarCat(auStack_128,auStack_118,auStack_148);
    ppiVar6 = (int **)__vbaStrVarVal(&piStack_e0,uVar7);
    iVar5 = (**(code **)(iVar5 + 100))(pcVar10,ppiVar6);
    if (iVar5 < 0) {
      __vbaHresultCheckObj(iVar5,pcVar10,&DAT_004040a8,100);
    }
    __vbaFreeStr();
    __vbaFreeObjList(2,&ppiStack_e4,&pcStack_e8);
    __vbaFreeVarList(4,&piStack_f8,auStack_108,auStack_118,auStack_128);
    bVar11 = SCARRY2(sVar4,1);
    sVar4 = sVar4 + 1;
    pcVar9 = __vbaObjSet_exref;
    pcVar10 = __vbaHresultCheckObj_exref;
    if (bVar11) break;
LAB_0071220a:
    if ((short)uStack_174 < sVar4) {
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x368))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_00727430);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x36c))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_00727434);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      if (!SBORROW2(DAT_007273c8,1)) {
        sVar4 = 0;
        uStack_17c = CONCAT22(extraout_var_02,DAT_007273c8 + -1);
        goto LAB_007123b1;
      }
      break;
    }
  }
  goto LAB_00712886;
  while( true ) {
    uVar7 = (**(code **)(*apiStack_15c[0] + 0x370))();
    piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
    iVar5 = (**(code **)(*piVar8 + 0x40))(piVar8,sVar4,&pcStack_e8);
    if (iVar5 < 0) {
      (*pcVar10)(iVar5,piVar8,&DAT_00404af0,0x40);
    }
    pcVar10 = pcStack_e8;
    uStack_140 = DAT_00727438;
    ppiVar6 = &piStack_f8;
    if (SCARRY2(sVar4,1)) break;
    auStack_148[0] = 8;
    iStack_f0 = CONCAT22(iStack_f0._2_2_,sVar4 + 1);
    piStack_f8 = (int *)0x2;
    rtcVarStrFromVar(auStack_108,ppiVar6);
    rtcTrimVar(auStack_118,auStack_108);
    iVar5 = *(int *)pcVar10;
    uVar7 = __vbaVarCat(auStack_128,auStack_118,auStack_148);
    ppiVar6 = (int **)__vbaStrVarVal(&piStack_e0,uVar7);
    iVar5 = (**(code **)(iVar5 + 100))(pcVar10,ppiVar6);
    if (iVar5 < 0) {
      __vbaHresultCheckObj(iVar5,pcVar10,&DAT_004040a8,100);
    }
    __vbaFreeStr();
    __vbaFreeObjList(2,&ppiStack_e4,&pcStack_e8);
    __vbaFreeVarList(4,&piStack_f8,auStack_108,auStack_118,auStack_128);
    bVar11 = SCARRY2(sVar4,1);
    sVar4 = sVar4 + 1;
    pcVar9 = __vbaObjSet_exref;
    pcVar10 = __vbaHresultCheckObj_exref;
    if (bVar11) break;
LAB_007123b1:
    if ((short)uStack_17c < sVar4) {
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x374))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_0072743c);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      if (!SBORROW2(DAT_007273c8,1)) {
        sVar4 = 0;
        uStack_184 = CONCAT22(extraout_var_03,DAT_007273c8 + -1);
        goto LAB_00712517;
      }
      break;
    }
  }
  goto LAB_00712886;
  while( true ) {
    auStack_148[0] = 8;
    iStack_f0 = CONCAT22(iStack_f0._2_2_,sVar4 + 1);
    piStack_f8 = (int *)0x2;
    rtcVarStrFromVar(auStack_108,ppiVar6);
    rtcTrimVar(auStack_118,auStack_108);
    iVar5 = *(int *)pcVar10;
    uVar7 = __vbaVarCat(auStack_128,auStack_118,auStack_148);
    ppiVar6 = (int **)__vbaStrVarVal(&piStack_e0,uVar7);
    iVar5 = (**(code **)(iVar5 + 100))(pcVar10,ppiVar6);
    if (iVar5 < 0) {
      __vbaHresultCheckObj(iVar5,pcVar10,&DAT_004040a8,100);
    }
    __vbaFreeStr();
    __vbaFreeObjList(2,&ppiStack_e4,&pcStack_e8);
    __vbaFreeVarList(4,&piStack_f8,auStack_108,auStack_118,auStack_128);
    bVar11 = SCARRY2(sVar4,1);
    sVar4 = sVar4 + 1;
    pcVar9 = __vbaObjSet_exref;
    pcVar10 = __vbaHresultCheckObj_exref;
    if (bVar11) break;
LAB_00712517:
    if ((short)uStack_184 < sVar4) {
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x380))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_00727444);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x388))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_00727448);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x38c))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_0072744c);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x390))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_00727450);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x394))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_00727454);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x3c0))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_0072745c);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      uVar7 = (**(code **)(*apiStack_15c[0] + 0x3b8))(apiStack_15c[0]);
      piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
      iVar5 = (**(code **)(*piVar8 + 100))(piVar8,DAT_00727460);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,piVar8,&DAT_004040a8,100);
      }
      __vbaFreeObj();
      if (DAT_00727010 == (int **)0x0) {
        __vbaNew2(&DAT_00402418,&DAT_00727010);
      }
      ppiVar6 = DAT_00727010;
      iVar5 = (*(code *)(*DAT_00727010)[0x15])(DAT_00727010,DAT_007273e8);
      if (iVar5 < 0) {
        (*pcVar10)(iVar5,ppiVar6,&DAT_00403924,0x54);
      }
      __vbaObjSetAddref(apiStack_15c,0);
      __vbaFreeObj(&LAB_00712875);
      return;
    }
    uVar7 = (**(code **)(*apiStack_15c[0] + 0x378))(apiStack_15c[0]);
    piVar8 = (int *)(*pcVar9)(&ppiStack_e4,uVar7);
    iVar5 = (**(code **)(*piVar8 + 0x40))(piVar8,sVar4,&pcStack_e8);
    if (iVar5 < 0) {
      (*pcVar10)(iVar5,piVar8,&DAT_00404af0,0x40);
    }
    pcVar10 = pcStack_e8;
    uStack_140 = DAT_00727440;
    ppiVar6 = &piStack_f8;
    if (SCARRY2(sVar4,1)) break;
  }
LAB_00712886:
  __vbaErrorOverflow(ppiVar6);
  iVar5 = __vbaStrCmp(&PTR_DAT_00404780,DAT_007273e0);
  if (iVar5 == 0) {
    __vbaStrCopy(pcVar10);
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    __vbaStrCopy();
    return;
  }
  iVar5 = __vbaStrCmp(&PTR_DAT_00404768,DAT_007273e0);
  if (iVar5 != 0) {
    iVar5 = __vbaStrCmp(&PTR_LAB_00404774,DAT_007273e0);
    if (iVar5 == 0) {
      __vbaStrCopy(pcVar10);
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
      __vbaStrCopy();
    }
    return;
  }
  __vbaStrCopy(pcVar10);
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaStrCopy();
  return;
}


