// BonziSolitaire.exe :: frmSplash
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 2

// ---- Form_ev12 @ 00725a40

void frmSplash::Form_ev12(uint param_1)

{
  int *piVar1;
  int *piVar2;
  int iVar3;
  undefined4 uVar4;
  undefined1 local_40 [8];
  undefined4 local_38;
  undefined4 local_30;
  undefined4 local_2c;
  undefined4 local_28;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffa4;
  local_c = &DAT_00401688;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  local_40[0] = 0;
  local_40[0] = __vbaUI1I2();
  modMain::Proc_71c380(local_40);
  if (DAT_00727010 == (int *)0x0) {
    __vbaNew2(&DAT_00402418,&DAT_00727010);
  }
  piVar1 = DAT_00727010;
  local_2c = 10;
  iVar3 = (**(code **)(*DAT_00727010 + 0x2b0))
                    (DAT_00727010,10,local_28,0x80020004,local_20,10,local_38,0x80020004,local_30);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar1,&DAT_00403924,0x2b0);
  }
  if (DAT_00727870 == (int *)0x0) {
    __vbaNew2(&DAT_00404804,&DAT_00727870);
  }
  piVar1 = DAT_00727870;
  iVar3 = *DAT_00727870;
  uVar4 = __vbaObjSetAddref(&local_1c,piVar2);
  iVar3 = (**(code **)(iVar3 + 0x10))(piVar1,uVar4);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar1,&DAT_004047f4,0x10);
  }
  __vbaFreeObj();
  return;
}


// ---- tmrEffect_ev0 @ 00725bb0

/* WARNING: Control flow encountered bad instruction data */

void frmSplash::tmrEffect_ev0(uint param_1)

{
  int *piVar1;
  byte bVar2;
  undefined1 uVar3;
  int iVar4;
  uint uVar5;
  int iVar6;
  undefined4 uVar7;
  uint uVar8;
  code *pcVar9;
  int *piVar10;
  int *piVar11;
  int local_6c;
  undefined1 local_68 [4];
  undefined4 local_64;
  undefined4 local_60;
  undefined4 local_58;
  undefined4 local_54;
  undefined4 local_50;
  undefined4 local_4c;
  undefined4 local_48;
  undefined4 local_44;
  uint local_40;
  uint local_3c;
  int local_38;
  uint local_34;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_004016b6;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff54;
  local_c = &DAT_00401698;
  local_8 = param_1 & 1;
  piVar10 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  piVar11 = piVar10;
  (**(code **)(*piVar10 + 4))(piVar10);
  pcVar9 = __vbaUI1I2_exref;
  local_44 = 0;
  local_54 = 0;
  local_64 = 0;
  local_68[0] = 0;
  local_6c = 0;
  bVar2 = __vbaUI1I2();
  local_34 = CONCAT31(local_34._1_3_,bVar2);
  if (!SBORROW2((ushort)bVar2,1)) {
    bVar2 = __vbaUI1I2();
    uVar3 = __vbaUI1I2();
    local_40 = CONCAT31(local_40._1_3_,uVar3);
    while( true ) {
      if (bVar2 < (byte)local_40) {
        local_68[0] = (*pcVar9)();
        modMain::Proc_71c380(local_68);
        if (DAT_00727010 == (int *)0x0) {
          __vbaNew2(&DAT_00402418,&DAT_00727010);
        }
        piVar11 = DAT_00727010;
        local_54 = 10;
        local_4c = 0x80020004;
        iVar6 = (**(code **)(*DAT_00727010 + 0x2b0))
                          (DAT_00727010,10,local_50,0x80020004,local_48,10,local_60,0x80020004,
                           local_58);
        if (iVar6 < 0) {
          __vbaHresultCheckObj(iVar6,piVar11,&DAT_00403924,0x2b0);
        }
        if (DAT_00727870 == (int *)0x0) {
          __vbaNew2(&DAT_00404804,&DAT_00727870);
        }
        piVar11 = DAT_00727870;
        iVar6 = *DAT_00727870;
        uVar7 = __vbaObjSetAddref(&local_44,piVar10);
        iVar6 = (**(code **)(iVar6 + 0x10))(piVar11,uVar7);
        if (iVar6 < 0) {
          __vbaHresultCheckObj(iVar6,piVar11,&DAT_004047f4,0x10);
        }
        __vbaFreeObj();
        return;
      }
      local_6c = FUN_00404384();
      __vbaSetSystemError();
      iVar6 = local_6c;
      local_6c = FUN_00404384();
      __vbaSetSystemError();
      local_38 = local_6c;
      if (DAT_00727480 == (int *)0x0) {
        __vbaNew2(&DAT_00401bb0,&DAT_00727480);
      }
      piVar1 = DAT_00727480;
      iVar4 = (**(code **)(*DAT_00727480 + 0x100))(DAT_00727480,&local_6c);
      pcVar9 = __vbaHresultCheckObj_exref;
      if (iVar4 < 0) {
        __vbaHresultCheckObj(iVar4,piVar1,&LAB_004059b8,0x100);
      }
      iVar4 = __vbaFpI4();
      uVar5 = local_34 & 0xff;
      uVar8 = local_40 & 0xff;
      while (local_3c = uVar8, (int)uVar8 <= iVar4) {
        while( true ) {
          if (SBORROW4(local_38,iVar6)) goto LAB_00725fc0;
          if (-1 < local_38 - iVar6) break;
          local_6c = FUN_00404384();
          __vbaSetSystemError();
          local_38 = local_6c;
        }
        iVar6 = (**(code **)(*piVar10 + 0x100))(piVar10,&local_6c);
        if (iVar6 < 0) {
          (*pcVar9)(iVar6,piVar10,&LAB_004059b8,0x100);
        }
        __vbaFpI4();
        iVar6 = (**(code **)(*piVar10 + 0x108))(piVar10,&local_6c);
        if (iVar6 < 0) {
          (*pcVar9)(iVar6,piVar10,&LAB_004059b8,0x108);
        }
        if (DAT_00727480 == (int *)0x0) {
          __vbaNew2(&DAT_00401bb0,&DAT_00727480);
        }
        piVar1 = DAT_00727480;
        iVar6 = (**(code **)(*DAT_00727480 + 0x2c8))
                          (DAT_00727480,6,(float)(int)local_3c,0,(float)(int)local_3c,local_6c,0);
        if (iVar6 < 0) {
          __vbaHresultCheckObj(iVar6,piVar1,&LAB_004059b8,0x2c8);
        }
        iVar6 = (**(code **)(*piVar10 + 0x100))(piVar10,&local_6c);
        if (iVar6 < 0) {
          __vbaHresultCheckObj(iVar6,piVar10,&LAB_004059b8,0x100);
        }
        if (DAT_00727480 == (int *)0x0) {
          __vbaNew2(&DAT_00401bb0,&DAT_00727480);
        }
        piVar1 = DAT_00727480;
        iVar6 = (**(code **)(*DAT_00727480 + 0x2c8))
                          (DAT_00727480,6,0,(float)(int)local_3c,local_6c,(float)(int)local_3c,0);
        if (iVar6 < 0) {
          __vbaHresultCheckObj(iVar6,piVar1,&LAB_004059b8,0x2c8);
        }
        local_6c = FUN_00404384();
        __vbaSetSystemError();
        uVar8 = uVar5 + local_3c;
        iVar6 = local_6c;
        pcVar9 = __vbaHresultCheckObj_exref;
        if (SCARRY4(uVar5,local_3c)) goto LAB_00725fc0;
      }
      if (0xfe < (byte)local_40) break;
      local_40 = CONCAT31(local_40._1_3_,(byte)local_40 + 1);
      pcVar9 = __vbaUI1I2_exref;
    }
  }
LAB_00725fc0:
  __vbaErrorOverflow(piVar11);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}


