// BonziBDY_35.EXE :: BBIMContacts
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 7

// ---- Public_0 @ 005c95a0

/* WARNING: Restarted to delay deadcode elimination for space: stack */

void BBIMContacts::Public_0
               (int **param_1,undefined4 param_2,int ****param_3,short *param_4,undefined4 *param_5)

{
  short sVar1;
  int ***pppiVar2;
  int ***pppiVar3;
  undefined4 *puVar4;
  int iVar5;
  undefined4 uVar6;
  code *pcVar7;
  undefined4 *unaff_ESI;
  code *pcVar8;
  int **ppiVar9;
  int *piStack_12c;
  int ***pppiStack_11c;
  int **ppiStack_118;
  code *pcStack_114;
  undefined4 *puStack_110;
  int **ppiStack_10c;
  int ***pppiStack_108;
  int **ppiStack_104;
  int **ppiStack_100;
  int **ppiStack_fc;
  int **ppiStack_f8;
  int **ppiStack_f4;
  int ***pppiStack_f0;
  int ***pppiStack_ec;
  int **ppiStack_e8;
  int local_bc [9];
  int *local_98 [2];
  int ***local_90;
  undefined4 local_88 [2];
  int ***local_80;
  undefined4 local_78;
  int *local_68 [2];
  undefined4 local_60;
  int **local_58 [2];
  undefined4 local_50;
  int **local_48 [2];
  undefined4 local_40;
  int ***local_38;
  undefined4 local_34;
  int **local_30;
  int **local_2c;
  int **local_28;
  int **local_24;
  void *pvStack_20;
  undefined *puStack_1c;
  undefined1 *local_18;
  undefined *local_14;
  undefined4 local_10;
  undefined4 local_c;
  
  puStack_1c = &DAT_0040fb26;
  pvStack_20 = ExceptionList;
  local_18 = &stack0xffffff1c;
  local_14 = &DAT_004070e8;
  local_10 = 0;
  local_c = 0;
  ppiStack_e8 = param_1;
  pppiStack_ec = (int ***)0x5c95dd;
  ExceptionList = &pvStack_20;
  (*(code *)(*param_1)[1])();
  local_24 = (int **)0x0;
  local_28 = (int **)0x0;
  local_2c = (int **)0x0;
  local_30 = (int **)0x0;
  local_34 = 0;
  local_38 = (int ***)0x0;
  local_48[0] = (int **)0x0;
  local_58[0] = (int **)0x0;
  local_68[0] = (int *)0x0;
  local_78 = 0;
  local_88[0] = 0;
  local_98[0] = (int *)0x0;
  local_bc[0] = 0;
  pppiStack_ec = (int ***)param_2;
  pppiStack_f0 = &local_2c;
  ppiStack_f4 = (int **)0x5c961b;
  __vbaObjSetAddref();
  *param_5 = 0;
  pppiStack_ec = (int ***)0x1;
  pppiStack_f0 = (int ***)0x5c9628;
  __vbaOnError();
  pppiStack_ec = (int ***)0x0;
  pppiStack_f0 = (int ***)local_2c;
  ppiStack_f4 = (int **)0x5c9633;
  sVar1 = __vbaObjIs();
  if (sVar1 == 0) {
    local_80 = (int ***)param_3;
    local_88[0] = 0x4008;
    pppiStack_ec = (int ***)&local_38;
    pppiStack_f0 = (int ***)local_88;
    ppiStack_f4 = param_1;
    ppiStack_f8 = (int **)0x5c965d;
    pppiVar2 = (int ***)(*(code *)(*param_1)[8])();
    if ((int)pppiVar2 < 0) {
      pppiStack_ec = (int ***)0x20;
      pppiStack_f0 = (int ***)&LAB_00447be0;
      ppiStack_f4 = param_1;
      ppiStack_fc = (int **)0x5c9670;
      ppiStack_f8 = (int **)pppiVar2;
      __vbaHresultCheckObj();
    }
    pppiStack_ec = local_38;
    pcVar7 = __vbaObjSet_exref;
    local_38 = (int ***)0x0;
    pppiStack_f0 = &local_24;
    ppiStack_f4 = (int **)0x5c9683;
    __vbaObjSet();
    pppiStack_ec = (int ***)0x0;
    pppiStack_f0 = (int ***)local_24;
    ppiStack_f4 = (int **)0x5c968e;
    sVar1 = __vbaObjIs();
    if (sVar1 == 0) {
      if (*param_4 != 0) {
        pppiStack_ec = (int ***)local_bc;
        pppiStack_f0 = (int ***)local_24;
        ppiStack_f4 = (int **)0x5c96ab;
        pppiVar2 = (int ***)(*(code *)(*local_24)[0xc])();
        if ((int)pppiVar2 < 0) {
          ppiStack_f4 = (int **)0x30;
          ppiStack_f8 = (int **)&DAT_00447c00;
          ppiStack_fc = local_24;
          ppiStack_104 = (int **)0x5c96c3;
          ppiStack_100 = (int **)pppiVar2;
          __vbaHresultCheckObj();
        }
        ppiStack_f4 = (int **)(local_bc[0] + 1);
        if (SCARRY4(local_bc[0],1)) {
          ppiStack_f4 = (int **)0x5c9a88;
          __vbaErrorOverflow();
          ppiStack_10c = (int **)&DAT_0040fb26;
          puStack_110 = ExceptionList;
          pcStack_114 = (code *)0x5c9ab3;
          ExceptionList = &puStack_110;
          pppiStack_f0 = (int ***)&stack0xfffffffc;
          __vbaChkstk();
          pcStack_114 = pcVar7;
          ppiStack_118 = param_1;
          pppiStack_108 = (int ***)&pppiStack_11c;
          pppiStack_11c = (int ***)0x0;
          ppiStack_104 = (int **)&DAT_00407110;
          ppiStack_100 = (int **)0x0;
          ppiStack_fc = (int **)0x0;
          (*(code *)(*ppiStack_e8)[1])();
          *unaff_ESI = 0;
          ppiStack_f4 = (int **)0x2;
          __vbaOnError();
          ppiStack_f4 = (int **)0x3;
          piStack_12c = ppiStack_e8[0xd];
          iVar5 = (**(code **)(*ppiStack_e8[0xd] + 0x1c))();
          if (iVar5 < 0) {
            __vbaHresultCheckObj(0x1c,ppiStack_e8[0xd],&DAT_0043ea20,0x1c);
          }
          uVar6 = __vbaCastObjVar(&stack0xfffffed8,&DAT_00447c00);
          __vbaObjSet(&pcStack_114,uVar6);
          __vbaFreeVar();
          ppiStack_f4 = (int **)0x4;
          uVar6 = rtcErrObj();
          __vbaObjSet(&ppiStack_118,uVar6);
          ppiVar9 = &piStack_12c;
          iVar5 = (*(code *)piStack_12c[7])(ppiVar9);
          if (iVar5 < 0) {
            __vbaHresultCheckObj(iVar5,ppiVar9,&DAT_00439f3c,0x1c);
          }
          sVar1 = -0x6425;
          __vbaFreeObj();
          if (sVar1 != 0) {
            ppiStack_f4 = (int **)0x5;
            uVar6 = __vbaCastObj(0,&DAT_00447c00);
            __vbaObjSet(&pcStack_114,uVar6);
          }
          return;
        }
        ppiStack_f8 = local_24;
        ppiStack_fc = (int **)0x5c96dc;
        pppiVar2 = (int ***)(*(code *)(*local_24)[0xb])();
        if ((int)pppiVar2 < 0) {
          pppiStack_ec = (int ***)0x2c;
          pppiStack_f0 = (int ***)&DAT_00447c00;
          ppiStack_f4 = local_24;
          ppiStack_fc = (int **)0x5c96f4;
          ppiStack_f8 = (int **)pppiVar2;
          __vbaHresultCheckObj();
        }
      }
      pppiStack_ec = (int ***)local_24;
      pppiStack_f0 = &local_28;
      ppiStack_f4 = (int **)0x5c9702;
      __vbaObjSetAddref();
    }
    else {
      pppiStack_ec = (int ***)&DAT_00411138;
      pppiStack_f0 = (int ***)0x5c9712;
      pppiStack_ec = (int ***)__vbaNew();
      pppiStack_f0 = &local_30;
      ppiStack_f4 = (int **)0x5c9719;
      __vbaObjSet();
      ppiVar9 = (int **)*local_30;
      pppiStack_ec = (int ***)local_2c;
      pppiStack_f0 = (int ***)&local_38;
      ppiStack_f4 = (int **)0x5c972c;
      pppiStack_ec = (int ***)__vbaObjSetAddref();
      pppiStack_f0 = (int ***)local_30;
      ppiStack_f4 = (int **)0x5c9734;
      pppiVar2 = (int ***)(*(code *)ppiVar9[9])();
      if ((int)pppiVar2 < 0) {
        ppiStack_f4 = (int **)0x24;
        ppiStack_f8 = (int **)&DAT_00447c00;
        ppiStack_fc = local_30;
        ppiStack_104 = (int **)0x5c974e;
        ppiStack_100 = (int **)pppiVar2;
        __vbaHresultCheckObj();
      }
      ppiStack_f4 = (int **)0x5c975f;
      __vbaFreeObj();
      if (*param_4 == 0) {
        ppiStack_f4 = (int **)0x0;
        ppiStack_f8 = local_30;
        ppiStack_fc = (int **)0x5c977f;
        pppiVar3 = (int ***)(*(code *)(*local_30)[0xb])();
        pppiVar2 = pppiStack_108;
        ppiStack_104 = local_30;
      }
      else {
        ppiStack_f4 = (int **)0x1;
        ppiStack_f8 = local_30;
        ppiStack_fc = (int **)0x5c9772;
        pppiVar3 = (int ***)(*(code *)(*local_30)[0xb])();
        pppiVar2 = pppiStack_108;
        ppiStack_104 = local_30;
      }
      pppiStack_108 = pppiVar3;
      local_30 = ppiStack_104;
      if ((int)pppiStack_108 < 0) {
        ppiStack_fc = (int **)0x2c;
        ppiStack_100 = (int **)&DAT_00447c00;
        ppiStack_10c = (int **)0x5c9793;
        __vbaHresultCheckObj();
        pppiVar2 = pppiStack_108;
      }
      pppiStack_108 = pppiVar2;
      ppiStack_fc = (int **)*param_3;
      ppiStack_100 = local_30;
      ppiStack_104 = (int **)0x5c97a2;
      puVar4 = (undefined4 *)(*(code *)(*local_30)[7])();
      if ((int)puVar4 < 0) {
        ppiStack_104 = (int **)0x1c;
        pppiStack_108 = (int ***)&DAT_00447c00;
        ppiStack_10c = local_30;
        pcStack_114 = (code *)0x5c97ba;
        puStack_110 = puVar4;
        __vbaHresultCheckObj();
      }
      ppiStack_104 = (int **)*param_3;
      pppiStack_108 = (int ***)0x5c97c3;
      iVar5 = __vbaLenBstr();
      if (iVar5 == 0) {
        local_60 = 0x80020004;
        local_68[0] = (int *)0xa;
        local_50 = 0x80020004;
        local_58[0] = (int **)0xa;
        local_40 = 0x80020004;
        local_48[0] = (int **)0xa;
        ppiStack_104 = local_30;
        pppiStack_108 = (int ***)&local_38;
        ppiStack_10c = (int **)0x5c97f5;
        __vbaObjSetAddref();
        local_80 = (int ***)&local_38;
        local_88[0] = 0x4009;
        pcStack_114 = (code *)param_1[0xd];
        ppiStack_104 = local_68;
        pppiStack_108 = local_58;
        ppiStack_10c = (int **)local_48;
        puStack_110 = local_88;
        ppiStack_118 = (int **)0x5c9821;
        iVar5 = (**(code **)(*(int *)pcStack_114 + 0x20))();
        if (iVar5 < 0) {
          ppiStack_118 = (int **)0x20;
          pppiStack_11c = (int ***)&DAT_0043ea20;
          __vbaHresultCheckObj();
        }
        pcVar8 = __vbaCastObj_exref;
        ppiStack_118 = (int **)&DAT_00447c00;
        pppiStack_11c = local_38;
        ppiStack_118 = (int **)__vbaCastObj();
        pcVar7 = __vbaObjSet_exref;
        pppiStack_11c = &local_30;
        __vbaObjSet();
        ppiStack_118 = (int **)0x5c9860;
        __vbaFreeObj();
        ppiStack_118 = local_68;
        pppiStack_11c = local_58;
        __vbaFreeVarList();
      }
      else {
        local_50 = 0x80020004;
        local_58[0] = (int **)0xa;
        local_40 = 0x80020004;
        local_48[0] = (int **)0xa;
        local_90 = (int ***)param_3;
        local_98[0] = (int *)0x4008;
        ppiStack_104 = local_30;
        pppiStack_108 = (int ***)&local_38;
        ppiStack_10c = (int **)0x5c98ab;
        __vbaObjSetAddref();
        local_80 = (int ***)&local_38;
        local_88[0] = 0x4009;
        pcStack_114 = (code *)param_1[0xd];
        ppiStack_104 = (int **)local_58;
        pppiStack_108 = local_48;
        ppiStack_10c = local_98;
        puStack_110 = local_88;
        ppiStack_118 = (int **)0x5c98da;
        iVar5 = (**(code **)(*(int *)pcStack_114 + 0x20))();
        if (iVar5 < 0) {
          ppiStack_118 = (int **)0x20;
          pppiStack_11c = (int ***)&DAT_0043ea20;
          __vbaHresultCheckObj();
        }
        pcVar8 = __vbaCastObj_exref;
        ppiStack_118 = (int **)&DAT_00447c00;
        pppiStack_11c = local_38;
        ppiStack_118 = (int **)__vbaCastObj();
        pcVar7 = __vbaObjSet_exref;
        pppiStack_11c = &local_30;
        __vbaObjSet();
        ppiStack_118 = (int **)0x5c9919;
        __vbaFreeObj();
        ppiStack_118 = (int **)local_58;
        pppiStack_11c = local_48;
        __vbaFreeVarList();
      }
      ppiStack_118 = local_30;
      pppiStack_11c = &local_28;
      __vbaObjSetAddref();
      ppiStack_118 = (int **)&DAT_00447c00;
      pppiStack_11c = (int ***)0x0;
      (*pcVar8)();
      (*pcVar7)();
    }
  }
  pppiStack_ec = (int ***)0x5c9a01;
  __vbaExitProc();
  pppiStack_ec = (int ***)&LAB_005c9a5b;
  pppiStack_f0 = (int ***)0x5c9a50;
  __vbaFreeObj();
  pppiStack_f0 = (int ***)0x5c9a55;
  __vbaFreeObj();
  pppiStack_f0 = (int ***)0x5c9a5a;
  __vbaFreeObj();
  return;
}


// ---- Public_1 @ 005c9a90

/* WARNING: Restarted to delay deadcode elimination for space: stack */

void BBIMContacts::Public_1(int *param_1,undefined4 param_2,undefined4 *param_3)

{
  int iVar1;
  undefined4 uVar2;
  short sVar3;
  int *piVar4;
  int local_40;
  undefined4 local_3c;
  undefined4 *puStack_38;
  int *piStack_34;
  void *pvStack_24;
  undefined *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &DAT_0040fb26;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00407110;
  local_14 = 0;
  local_10 = 0;
  piStack_34 = param_1;
  puStack_38 = (undefined4 *)0x5c9ada;
  (**(code **)(*param_1 + 4))();
  *param_3 = 0;
  local_8 = 2;
  puStack_38 = (undefined4 *)0xffffffff;
  local_3c = 0x5c9af9;
  __vbaOnError();
  local_8 = 3;
  puStack_38 = &local_3c;
  local_3c = param_2;
  local_40 = param_1[0xd];
  iVar1 = (**(code **)(*(int *)param_1[0xd] + 0x1c))();
  if (iVar1 < 0) {
    __vbaHresultCheckObj(0x1c,param_1[0xd],&DAT_0043ea20,0x1c);
  }
  uVar2 = __vbaCastObjVar(&local_3c,&DAT_00447c00);
  __vbaObjSet(&stack0xffffffd8,uVar2);
  __vbaFreeVar();
  local_8 = 4;
  uVar2 = rtcErrObj();
  __vbaObjSet(&stack0xffffffd4,uVar2);
  piVar4 = &local_40;
  iVar1 = (**(code **)(local_40 + 0x1c))(piVar4);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar4,&DAT_00439f3c,0x1c);
  }
  sVar3 = -0x6425;
  __vbaFreeObj();
  if (sVar3 != 0) {
    local_8 = 5;
    uVar2 = __vbaCastObj(0,&DAT_00447c00);
    __vbaObjSet(&stack0xffffffd8,uVar2);
  }
  return;
}


// ---- Public_2 @ 005c9c60

undefined4 BBIMContacts::Public_2(int *param_1,undefined4 *param_2)

{
  int iVar1;
  undefined4 local_20;
  undefined4 local_1c;
  void *local_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &DAT_0040fb26;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00407150;
  local_8 = 0;
  ExceptionList = &local_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_20 = 0;
  local_1c = 0;
  iVar1 = (**(code **)(*(int *)param_1[0xd] + 0x24))((int *)param_1[0xd],&local_20);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xd],&DAT_0043ea20,0x24);
  }
  local_1c = local_20;
  (**(code **)(*param_1 + 8))(param_1);
  *param_2 = local_1c;
  ExceptionList = local_18;
  return local_8;
}


// ---- Public_3 @ 005c9cf0

void BBIMContacts::Public_3(int *param_1,int *param_2)

{
  code *pcVar1;
  int **ppiVar2;
  int iVar3;
  int *piVar4;
  undefined *puVar5;
  undefined4 uVar6;
  undefined4 uStack_11c;
  int *piStack_118;
  code *pcStack_114;
  undefined4 uStack_104;
  int iStack_100;
  int *piStack_fc;
  undefined *puStack_f8;
  int *piStack_f4;
  int *piStack_f0;
  int *piStack_ec;
  int *piStack_e8;
  int *piStack_e4;
  int **ppiStack_e0;
  int *piStack_dc;
  int *piStack_d8;
  undefined4 *puStack_d4;
  undefined4 *puStack_d0;
  int *piStack_cc;
  int local_a0 [9];
  undefined4 local_7c;
  undefined4 local_6c;
  undefined4 local_5c;
  undefined4 local_4c;
  undefined4 local_3c [2];
  undefined4 local_34;
  undefined4 local_2c;
  undefined4 local_28;
  int *local_24;
  void *pvStack_20;
  undefined *puStack_1c;
  undefined1 *local_18;
  undefined *local_14;
  undefined4 local_10;
  undefined4 local_c;
  
  puStack_1c = &DAT_0040fb26;
  pvStack_20 = ExceptionList;
  local_18 = &stack0xffffff38;
  local_14 = &DAT_00407158;
  local_10 = 0;
  local_c = 0;
  piStack_cc = param_1;
  puStack_d0 = (undefined4 *)0x5c9d2d;
  ExceptionList = &pvStack_20;
  (**(code **)(*param_1 + 4))();
  local_24 = (int *)0x0;
  local_28 = 0;
  local_2c = 0;
  local_3c[0] = 0;
  local_4c = 0;
  local_5c = 0;
  local_6c = 0;
  local_7c = 0;
  local_a0[0] = 0;
  puStack_d0 = (undefined4 *)0x1;
  puStack_d4 = (undefined4 *)0x5c9d53;
  __vbaOnError();
  puStack_d0 = (undefined4 *)0x5c9d5f;
  puStack_d0 = (undefined4 *)__vbaVarVargNofree();
  puStack_d4 = (undefined4 *)0x5c9d66;
  local_34 = __vbaStrErrVarCopy();
  local_3c[0] = 8;
  puStack_d0 = &local_2c;
  puStack_d4 = local_3c;
  piStack_d8 = param_1;
  piStack_dc = (int *)0x5c9d7e;
  iVar3 = (**(code **)(*param_1 + 0x20))();
  pcVar1 = __vbaHresultCheckObj_exref;
  if (iVar3 < 0) {
    piStack_dc = (int *)0x20;
    ppiStack_e0 = (int **)&LAB_00447be0;
    piStack_e4 = param_1;
    piStack_ec = (int *)0x5c9d93;
    piStack_e8 = (int *)iVar3;
    __vbaHresultCheckObj();
  }
  piStack_dc = (int *)local_2c;
  local_2c = 0;
  ppiStack_e0 = &local_24;
  piStack_e4 = (int *)0x5c9dac;
  __vbaObjSet();
  piStack_dc = (int *)0x5c9db5;
  __vbaFreeVar();
  piStack_dc = local_a0;
  ppiStack_e0 = (int **)local_24;
  piStack_e4 = (int *)0x5c9dc5;
  piVar4 = (int *)(**(code **)(*local_24 + 0x30))();
  if ((int)piVar4 < 0) {
    piStack_e4 = (int *)0x30;
    piStack_e8 = (int *)&DAT_00447c00;
    piStack_ec = local_24;
    piStack_f4 = (int *)0x5c9dd9;
    piStack_f0 = piVar4;
    __vbaHresultCheckObj();
  }
  if (local_a0[0] < 2) {
    piStack_e8 = (int *)param_1[0xd];
    piStack_e4 = param_2;
    piStack_ec = (int *)0x5c9e49;
    iVar3 = (**(code **)(*piStack_e8 + 0x28))();
    if (iVar3 < 0) {
      piStack_f4 = (int *)0x28;
      puStack_f8 = &DAT_0043ea20;
      piStack_fc = (int *)param_1[0xd];
      uStack_104 = 0x5c9e61;
      iStack_100 = iVar3;
      __vbaHresultCheckObj();
    }
  }
  else {
    piStack_e4 = local_a0;
    piStack_e8 = local_24;
    piStack_ec = (int *)0x5c9df2;
    puVar5 = (undefined *)(**(code **)(*local_24 + 0x30))();
    if ((int)puVar5 < 0) {
      piStack_ec = (int *)0x30;
      piStack_f0 = (int *)&DAT_00447c00;
      piStack_f4 = local_24;
      piStack_fc = (int *)0x5c9e06;
      puStack_f8 = puVar5;
      __vbaHresultCheckObj();
    }
    piStack_ec = (int *)(local_a0[0] + -1);
    if (SBORROW4(local_a0[0],1)) {
      piStack_ec = (int *)0x5c9f7d;
      __vbaErrorOverflow();
      ppiVar2 = ppiStack_e0;
      puStack_f8 = &DAT_0040fb26;
      piStack_fc = ExceptionList;
      pcStack_114 = pcVar1;
      piStack_118 = param_1;
      piStack_f4 = &uStack_11c;
      uStack_11c = 0;
      piStack_f0 = (int *)&DAT_00407180;
      piStack_ec = (int *)0x0;
      ExceptionList = &piStack_fc;
      piStack_e8 = (int *)&stack0xfffffffc;
      (**(code **)((int)*ppiStack_e0 + 4))(ppiStack_e0);
      iStack_100 = 0;
      uStack_104 = 0;
      *piStack_dc = 0;
      piVar4 = ppiVar2[0xd];
      iVar3 = (**(code **)(*piVar4 + 0x2c))(piVar4,&uStack_104);
      if (iVar3 < 0) {
        __vbaHresultCheckObj(iVar3,ppiVar2[0xd],&DAT_0043ea20,0x2c);
      }
      uVar6 = __vbaCastObj(uStack_104,&DAT_0043e250);
      __vbaObjSet(&iStack_100,uVar6);
      __vbaFreeObj();
      return;
    }
    piStack_f0 = local_24;
    piStack_f4 = (int *)0x5c9e1f;
    iVar3 = (**(code **)(*local_24 + 0x2c))();
    if (iVar3 < 0) {
      piStack_f4 = (int *)0x2c;
      puStack_f8 = &DAT_00447c00;
      piStack_fc = local_24;
      uStack_104 = 0x5c9e37;
      iStack_100 = iVar3;
      __vbaHresultCheckObj();
    }
  }
  piStack_f4 = (int *)0x5c9f19;
  __vbaExitProc();
  piStack_f4 = (int *)&LAB_005c9f58;
  puStack_f8 = (undefined *)0x5c9f57;
  __vbaFreeObj();
  return;
}


// ---- Public_4 @ 005c9f80

void BBIMContacts::Public_4(int *param_1,undefined4 *param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00407180;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  local_20 = 0;
  *param_2 = 0;
  iVar1 = (**(code **)(*(int *)param_1[0xd] + 0x2c))((int *)param_1[0xd],&local_20);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xd],&DAT_0043ea20,0x2c);
  }
  uVar2 = __vbaCastObj(local_20,&DAT_0043e250);
  __vbaObjSet(&local_1c,uVar2);
  __vbaFreeObj();
  return;
}


// ---- Public_5 @ 005ca060

void BBIMContacts::Public_5(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00407190;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  uVar1 = __vbaNew(&DAT_0043ea30);
  uVar1 = __vbaObjSet(&local_1c,uVar1);
  __vbaObjSetAddref(piVar2 + 0xd,uVar1);
  __vbaFreeObj();
  return;
}


// ---- Public_6 @ 005ca110

void BBIMContacts::Public_6(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004071a0;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  uVar1 = __vbaCastObj(0,&DAT_0043ea20);
  uVar1 = __vbaObjSet(&local_1c,uVar1);
  __vbaObjSetAddref(piVar2 + 0xd,uVar1);
  __vbaFreeObj();
  return;
}


