// BonziBDY_35.EXE :: BBIMSession
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 7

// ---- Public_0 @ 005ca1c0

void BBIMSession::Public_0(int *param_1)

{
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004071b0;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  __vbaStrCopy();
  __vbaStrCopy();
  __vbaFreeStr(&LAB_005ca21f);
  return;
}


// ---- Public_1 @ 005ca240

void BBIMSession::Public_1(int *param_1,undefined4 *param_2)

{
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004071c0;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  *param_2 = 0;
  __vbaStrCopy();
  return;
}


// ---- Public_2 @ 005ca2d0

void BBIMSession::Public_2(int *param_1,undefined4 param_2)

{
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004071d0;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  __vbaObjSetAddref(&local_1c,param_2);
  __vbaObjSetAddref(param_1 + 0xe,local_1c);
  __vbaFreeObj(&LAB_005ca333);
  return;
}


// ---- Public_3 @ 005ca360

void BBIMSession::Public_3(int *param_1,undefined4 *param_2)

{
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004071e0;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  *param_2 = 0;
  __vbaObjSetAddref(&local_1c,param_1[0xe]);
  return;
}


// ---- Public_6 @ 005ca3f0

undefined4 BBIMSession::Public_6(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004071f0;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Public_4 @ 005ca460

void BBIMSession::Public_4(int *param_1,undefined4 param_2)

{
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004071f8;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  __vbaObjSetAddref(&local_1c,param_2);
  __vbaObjSetAddref(param_1 + 0xd,local_1c);
  __vbaFreeObj(&LAB_005ca4c3);
  return;
}


// ---- Public_5 @ 005ca4f0

void BBIMSession::Public_5(int *param_1,undefined4 *param_2)

{
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00407208;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  *param_2 = 0;
  __vbaObjSetAddref(&local_1c,param_1[0xd]);
  return;
}


