// BonziBDY_35.EXE :: frmBBIMReverseList
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 7

// ---- Form_Load @ 005c77f0

undefined4 frmBBIMReverseList::Form_Load(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00406ef8;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  Public_1(piVar1);
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Public_1 @ 005c7860

/* WARNING: Restarted to delay deadcode elimination for space: ram */

void frmBBIMReverseList::Public_1(int *******param_1)

{
  undefined1 *puVar1;
  short sVar2;
  int iVar3;
  int *******pppppppiVar4;
  int local_9c;
  int *****local_80;
  int *****local_7c;
  int ******local_78;
  int ******local_74;
  int ******local_70;
  int ******local_6c;
  int ******local_68;
  int ******local_64;
  int ******local_60;
  int *******local_5c;
  int ******local_58;
  int ******ppppppiStack_54;
  int *******local_50;
  int ******ppppppiStack_4c;
  int ******local_48;
  int *******local_44;
  int *******local_40;
  int *******local_3c;
  int ******local_38;
  int ******local_34;
  void *pvStack_24;
  undefined *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &DAT_0040fb26;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00406f00;
  local_14 = 0;
  local_10 = 0;
  local_8 = 1;
  puVar1 = &stack0xffffffd0;
  if (*param_1 != (int ******)&DAT_0067bd44) {
    local_34 = (int ******)0x5c78c2;
    __vbaFailedFriend();
    puVar1 = local_1c;
  }
  local_1c = puVar1;
  local_8 = 3;
  local_34 = (int ******)0x5c78de;
  __vbaOnError();
  local_8 = 4;
  local_34 = (int ******)0x3;
  local_38 = (int ******)DAT_00673564;
  local_3c = (int *******)0x5c78fd;
  local_70 = (int ******)(*(code *)(*DAT_00673564)[0x15])();
  if ((int)local_70 < 0) {
    local_3c = (int *******)0x54;
    local_40 = (int *******)&DAT_0044777c;
    local_44 = (int *******)DAT_00673564;
    ppppppiStack_4c = (int ******)0x5c7920;
    local_48 = local_70;
    __vbaHresultCheckObj();
  }
  local_3c = local_44;
  local_40 = (int *******)&stack0xffffffd8;
  local_44 = (int *******)0x5c7953;
  __vbaObjSet();
  local_8 = 5;
  local_40 = &local_38;
  local_44 = (int *******)&local_80;
  local_48 = (int ******)&DAT_0044778c;
  ppppppiStack_4c = (int ******)0x5c7971;
  local_9c = __vbaForEachCollObj();
  while (local_9c != 0) {
    local_8 = 6;
    local_3c = (int *******)&local_3c;
    local_40 = (int *******)local_38;
    local_44 = (int *******)0x5c7993;
    local_78 = (int ******)(*(code *)(*local_38)[0xb])();
    if ((int)local_78 < 0) {
      local_44 = (int *******)0x2c;
      local_48 = (int ******)&DAT_0044778c;
      ppppppiStack_4c = local_38;
      ppppppiStack_54 = (int ******)0x5c79b3;
      local_50 = (int *******)local_78;
      __vbaHresultCheckObj();
    }
    if (DAT_00673584 == (int ****)0x0) {
      local_44 = (int *******)&DAT_00673584;
      local_48 = (int ******)&DAT_00420b84;
      ppppppiStack_4c = (int ******)0x5c79de;
      __vbaNew2();
    }
    local_70 = (int ******)DAT_00673584;
    local_44 = (int *******)&local_40;
    ppppppiStack_4c = (int ******)0x5c7a12;
    local_48 = local_70;
    local_74 = (int ******)(*(code *)(*DAT_00673584)[0x1cd])();
    if ((int)local_74 < 0) {
      local_3c = (int *******)0x734;
      local_40 = (int *******)&LAB_004477cc;
      local_44 = (int *******)local_70;
      ppppppiStack_4c = (int ******)0x5c7a35;
      local_48 = local_74;
      __vbaHresultCheckObj();
    }
    local_3c = (int *******)0x1;
    local_40 = (int *******)0x1;
    local_44 = (int *******)0x1;
    local_48 = (int ******)0x1;
    ppppppiStack_4c = (int ******)0x5c7a59;
    iVar3 = __vbaInStr();
    local_7c = (int *****)CONCAT22(local_7c._2_2_,-(ushort)(iVar3 == 0));
    local_3c = (int *******)&local_3c;
    local_40 = (int *******)&local_40;
    local_44 = (int *******)0x2;
    local_48 = (int ******)0x5c7a74;
    __vbaFreeStrList();
    if ((short)local_7c != 0) {
      local_8 = 7;
      local_3c = (int *******)&local_3c;
      local_40 = (int *******)local_38;
      local_44 = (int *******)0x5c7a9a;
      local_70 = (int ******)(*(code *)(*local_38)[0xb])();
      if ((int)local_70 < 0) {
        local_44 = (int *******)0x2c;
        local_48 = (int ******)&DAT_0044778c;
        ppppppiStack_4c = local_38;
        ppppppiStack_54 = (int ******)0x5c7aba;
        local_50 = (int *******)local_70;
        __vbaHresultCheckObj();
      }
      local_44 = local_3c;
      local_48 = (int ******)0x5c7ad6;
      rtcTrimBstr();
      local_58 = (int ******)0x8;
      local_44 = (int *******)&local_44;
      local_48 = (int ******)&local_58;
      ppppppiStack_4c = (int ******)DAT_00673568;
      local_50 = (int *******)0x5c7afa;
      local_74 = (int ******)(*(code *)(*DAT_00673568)[8])();
      if ((int)local_74 < 0) {
        local_3c = (int *******)0x20;
        local_40 = (int *******)&LAB_00447be0;
        local_44 = (int *******)DAT_00673568;
        ppppppiStack_4c = (int ******)0x5c7b1d;
        local_48 = local_74;
        __vbaHresultCheckObj();
      }
      local_3c = local_44;
      local_40 = &local_34;
      local_44 = (int *******)0x5c7b50;
      __vbaObjSet();
      local_3c = (int *******)0x5c7b59;
      __vbaFreeStr();
      local_3c = (int *******)0x5c7b62;
      __vbaFreeVar();
      local_8 = 8;
      local_3c = (int *******)0x0;
      local_40 = (int *******)local_34;
      local_44 = (int *******)0x5c7b75;
      sVar2 = __vbaObjIs();
      if (sVar2 != 0) {
        local_8 = 9;
        local_3c = param_1;
        local_40 = (int *******)0x5c7b96;
        local_40 = (int *******)(*(code *)(*param_1)[0xc0])();
        local_44 = (int *******)&local_44;
        local_48 = (int ******)0x5c7ba1;
        local_74 = (int ******)__vbaObjSet();
        local_60 = (int ******)0x80020004;
        local_68 = (int ******)0xa;
        local_40 = (int *******)&local_3c;
        local_44 = (int *******)local_38;
        local_48 = (int ******)0x5c7bc2;
        local_70 = (int ******)(*(code *)(*local_38)[0xb])();
        if ((int)local_70 < 0) {
          local_48 = (int ******)0x2c;
          ppppppiStack_4c = (int ******)&DAT_0044778c;
          local_50 = (int *******)local_38;
          local_58 = (int ******)0x5c7be2;
          ppppppiStack_54 = local_70;
          __vbaHresultCheckObj();
        }
        local_48 = (int ******)0x5c7bfe;
        __vbaChkstk();
        local_44 = (int *******)local_68;
        local_40 = (int *******)local_64;
        local_3c = (int *******)local_60;
        local_38 = (int ******)local_5c;
        local_48 = local_60;
        ppppppiStack_4c = local_74;
        local_50 = (int *******)0x5c7c2a;
        local_78 = (int ******)(*(code *)(*local_74)[0x7b])();
        if ((int)local_78 < 0) {
          local_50 = (int *******)0x1ec;
          ppppppiStack_54 = (int ******)&DAT_004408d8;
          local_58 = local_74;
          local_60 = (int ******)0x5c7c4d;
          local_5c = (int *******)local_78;
          __vbaHresultCheckObj();
        }
        local_50 = (int *******)0x5c7c68;
        __vbaFreeStr();
        local_50 = (int *******)0x5c7c71;
        __vbaFreeObj();
        local_8 = 10;
        local_50 = param_1;
        ppppppiStack_54 = (int ******)0x5c7c87;
        ppppppiStack_54 = (int ******)(*(code *)(*param_1)[0xc0])();
        local_58 = (int ******)&local_48;
        local_5c = (int *******)0x5c7c92;
        local_78 = (int ******)__vbaObjSet();
        ppppppiStack_54 = (int ******)param_1;
        local_58 = (int ******)0x5c7ca4;
        local_58 = (int ******)(*(code *)(*param_1)[0xc0])();
        local_5c = (int *******)&local_44;
        local_60 = (int ******)0x5c7caf;
        local_70 = (int ******)__vbaObjSet();
        local_58 = (int ******)&local_6c;
        local_60 = (int ******)0x5c7cc5;
        local_5c = (int *******)local_70;
        pppppppiVar4 = (int *******)(*(code *)(*local_70)[0x56])();
        local_74 = (int ******)pppppppiVar4;
        if ((int)pppppppiVar4 < 0) {
          local_60 = (int ******)0x158;
          local_64 = (int ******)&DAT_004408d8;
          local_68 = local_70;
          local_70 = (int ******)0x5c7ce8;
          local_6c = (int ******)pppppppiVar4;
          pppppppiVar4 = (int *******)__vbaHresultCheckObj();
        }
        local_60 = (int ******)0x7;
        local_64 = (int ******)CONCAT22((short)((uint)pppppppiVar4 >> 0x10),(short)local_6c);
        local_68 = local_78;
        local_6c = (int ******)0x5c7d10;
        local_7c = (int *****)(*(code *)(*local_78)[0x55])();
        if ((int)local_7c < 0) {
          local_3c = (int *******)0x154;
          local_40 = (int *******)&DAT_004408d8;
          local_44 = (int *******)local_78;
          ppppppiStack_4c = (int ******)0x5c7d33;
          local_48 = (int ******)local_7c;
          __vbaHresultCheckObj();
        }
        local_3c = &local_48;
        local_40 = (int *******)&local_44;
        local_44 = (int *******)0x2;
        local_48 = (int ******)0x5c7d55;
        __vbaFreeObjList();
      }
    }
    local_8 = 0xd;
    local_3c = &local_38;
    local_40 = (int *******)&local_80;
    local_44 = (int *******)&DAT_0044778c;
    local_48 = (int ******)0x5c7d72;
    local_9c = __vbaNextEachCollObj();
  }
  local_8 = 0xe;
  local_3c = (int *******)&DAT_00447bf0;
  local_40 = (int *******)0x0;
  local_44 = (int *******)0x5c7d99;
  local_3c = (int *******)__vbaCastObj();
  local_40 = (int *******)&stack0xffffffd8;
  local_44 = (int *******)0x5c7da4;
  __vbaObjSet();
  local_8 = 0xf;
  local_3c = (int *******)&DAT_00447c00;
  local_40 = (int *******)0x0;
  local_44 = (int *******)0x5c7db8;
  local_3c = (int *******)__vbaCastObj();
  local_40 = &local_34;
  local_44 = (int *******)0x5c7dc3;
  __vbaObjSet();
  local_8 = 0x10;
  local_3c = param_1;
  local_40 = (int *******)0x5c7dd9;
  local_40 = (int *******)(*(code *)(*param_1)[0xc0])();
  local_44 = (int *******)&local_44;
  local_48 = (int ******)0x5c7de4;
  local_70 = (int ******)__vbaObjSet();
  local_40 = &local_6c;
  local_48 = (int ******)0x5c7dfa;
  local_44 = (int *******)local_70;
  local_74 = (int ******)(*(code *)(*local_70)[0x36])();
  if ((int)local_74 < 0) {
    local_48 = (int ******)0xd8;
    ppppppiStack_4c = (int ******)&DAT_004408d8;
    local_50 = (int *******)local_70;
    local_58 = (int ******)0x5c7e1d;
    ppppppiStack_54 = local_74;
    __vbaHresultCheckObj();
  }
  local_78 = (int ******)CONCAT22(local_78._2_2_,-(ushort)((short)local_6c < 1));
  local_48 = (int ******)0x5c7e48;
  __vbaFreeObj();
  if ((short)local_78 != 0) {
    local_8 = 0x11;
    local_48 = (int ******)param_1;
    ppppppiStack_4c = (int ******)0x5c7e6a;
    ppppppiStack_4c = (int ******)(*(code *)(*param_1)[0xc3])();
    local_50 = (int *******)&local_44;
    ppppppiStack_54 = (int ******)0x5c7e75;
    local_70 = (int ******)__vbaObjSet();
    ppppppiStack_4c = (int ******)0x0;
    ppppppiStack_54 = (int ******)0x5c7e86;
    local_50 = (int *******)local_70;
    local_74 = (int ******)(*(code *)(*local_70)[0x1d])();
    if ((int)local_74 < 0) {
      ppppppiStack_54 = (int ******)0x74;
      local_58 = (int ******)&DAT_0043a898;
      local_5c = (int *******)local_70;
      local_64 = (int ******)0x5c7ea6;
      local_60 = local_74;
      __vbaHresultCheckObj();
    }
    ppppppiStack_54 = (int ******)0x5c7ec1;
    __vbaFreeObj();
    local_8 = 0x12;
    ppppppiStack_54 = (int ******)param_1;
    local_58 = (int ******)0x5c7ed7;
    local_58 = (int ******)(*(code *)(*param_1)[0xc5])();
    local_5c = (int *******)&local_44;
    local_60 = (int ******)0x5c7ee2;
    local_70 = (int ******)__vbaObjSet();
    local_58 = (int ******)0x0;
    local_60 = (int ******)0x5c7ef3;
    local_5c = (int *******)local_70;
    local_74 = (int ******)(*(code *)(*local_70)[0x1d])();
    if ((int)local_74 < 0) {
      local_48 = (int ******)0x74;
      ppppppiStack_4c = (int ******)&DAT_0043a898;
      local_50 = (int *******)local_70;
      local_58 = (int ******)0x5c7f13;
      ppppppiStack_54 = local_74;
      __vbaHresultCheckObj();
    }
    local_48 = (int ******)0x5c7f2e;
    __vbaFreeObj();
  }
  local_48 = (int ******)&LAB_005c7f9c;
  ppppppiStack_4c = (int ******)0x5c7f6e;
  __vbaFreeObj();
  ppppppiStack_4c = (int ******)0x5c7f77;
  __vbaFreeObj();
  ppppppiStack_4c = (int ******)0x5c7f80;
  __vbaFreeObj();
  ppppppiStack_4c = (int ******)0x5c7f89;
  __vbaFreeObj();
  ppppppiStack_4c = (int ******)0x5c7f92;
  __vbaFreeObj();
  ppppppiStack_4c = (int ******)0x5c7f9b;
  __vbaFreeObj();
  return;
}


// ---- lstReverse_MouseUp @ 005c7fc0

void frmBBIMReverseList::lstReverse_MouseUp(uint param_1,short *param_2)

{
  int *piVar1;
  int iVar2;
  int *piVar3;
  int *piVar4;
  short local_78 [2];
  int *local_74;
  undefined4 local_6c;
  int *local_64;
  undefined4 local_5c;
  int *local_54;
  int local_50;
  int **local_4c;
  undefined1 *local_48;
  int *local_44;
  int *local_40;
  short *local_3c;
  int **local_38;
  int *local_34;
  void *pvStack_24;
  undefined *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &DAT_0040fb26;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00406f70;
  local_14 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  local_10 = 0;
  local_38 = (int **)0x5c8015;
  local_34 = piVar4;
  (**(code **)(*piVar4 + 4))();
  local_8 = 2;
  local_38 = (int **)0xffffffff;
  local_3c = (short *)0x5c802b;
  __vbaOnError();
  if (*param_2 == 2) {
    local_8 = 4;
    local_3c = (short *)0x5c8057;
    local_38 = (int **)piVar4;
    local_3c = (short *)(**(code **)(*piVar4 + 0x300))();
    local_40 = (int *)&stack0xffffffd0;
    local_44 = (int *)0x5c8062;
    piVar1 = (int *)__vbaObjSet();
    local_3c = local_78;
    local_44 = (int *)0x5c8078;
    local_40 = piVar1;
    iVar2 = (**(code **)(*piVar1 + 0xd8))();
    if (iVar2 < 0) {
      local_44 = (int *)0xd8;
      local_48 = &DAT_004408d8;
      local_54 = (int *)0x5c809b;
      local_50 = iVar2;
      local_4c = (int **)piVar1;
      __vbaHresultCheckObj();
    }
    local_48 = (undefined1 *)0x5c80bc;
    local_44 = piVar4;
    local_48 = (undefined1 *)(**(code **)(*piVar4 + 0x300))();
    local_4c = &local_34;
    local_50 = 0x5c80c7;
    piVar1 = (int *)__vbaObjSet();
    local_48 = &stack0xffffffd8;
    local_50 = 0x5c80dd;
    local_4c = (int **)piVar1;
    piVar3 = (int *)(**(code **)(*piVar1 + 0xf8))();
    if ((int)piVar3 < 0) {
      local_38 = (int **)0xf8;
      local_3c = (short *)&DAT_004408d8;
      local_48 = (undefined1 *)0x5c8109;
      local_44 = piVar3;
      local_40 = piVar1;
      __vbaHresultCheckObj();
    }
    local_3c = (short *)0x5c8131;
    rtcTrimBstr();
    local_38 = (int **)0x5c813c;
    local_38 = (int **)__vbaStrMove();
    local_3c = (short *)&DAT_00433680;
    local_40 = (int *)0x5c8148;
    iVar2 = __vbaStrCmp();
    local_38 = (int **)&stack0xffffffd4;
    local_3c = (short *)&stack0xffffffd8;
    local_40 = (int *)0x2;
    local_44 = (int *)0x5c816a;
    __vbaFreeStrList();
    local_38 = &local_34;
    local_3c = (short *)&stack0xffffffd0;
    local_40 = (int *)0x2;
    local_44 = (int *)0x5c817d;
    __vbaFreeObjList();
    if (0 < local_78[0] && iVar2 != 0) {
      local_8 = 5;
      local_6c = 0x80020004;
      local_74 = (int *)0xa;
      local_5c = 0x80020004;
      local_64 = (int *)0xa;
      local_4c = (int **)0x80020004;
      local_54 = (int *)0xa;
      local_3c = (short *)0x80020004;
      local_44 = (int *)0xa;
      local_38 = (int **)0x5c81d8;
      __vbaChkstk();
      local_34 = local_74;
      local_38 = (int **)0x5c81fb;
      __vbaChkstk();
      local_34 = local_64;
      local_38 = (int **)0x5c821e;
      __vbaChkstk();
      local_34 = local_54;
      local_38 = (int **)0x5c8241;
      __vbaChkstk();
      local_34 = local_44;
      local_3c = (short *)0x5c8269;
      local_38 = (int **)piVar4;
      local_3c = (short *)(**(code **)(*piVar4 + 0x308))();
      local_40 = (int *)&stack0xffffffd0;
      local_44 = (int *)0x5c8274;
      local_3c = (short *)__vbaObjSet();
      local_44 = (int *)0x5c8284;
      local_40 = piVar4;
      iVar2 = (**(code **)(*piVar4 + 700))();
      if (iVar2 < 0) {
        local_38 = (int **)0x2bc;
        local_3c = (short *)&DAT_0044752c;
        local_48 = (undefined1 *)0x5c82a7;
        local_44 = (int *)iVar2;
        local_40 = piVar4;
        __vbaHresultCheckObj();
      }
      local_38 = (int **)0x5c82c2;
      __vbaFreeObj();
    }
  }
  return;
}


// ---- mnuAddFriend_Click @ 005c8320

/* WARNING: Restarted to delay deadcode elimination for space: ram */

void frmBBIMReverseList::mnuAddFriend_Click(uint param_1)

{
  int *piVar1;
  int **ppiVar2;
  int iVar3;
  undefined1 *puVar4;
  int *piVar5;
  undefined4 local_70 [2];
  undefined4 local_68;
  undefined4 local_60 [2];
  undefined4 local_58;
  int **ppiStack_54;
  int **local_50;
  int ***pppiStack_4c;
  undefined4 *local_48;
  int *piStack_44;
  int *local_40;
  int **ppiStack_3c;
  int *piStack_38;
  int *piStack_34;
  void *pvStack_24;
  undefined *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &DAT_0040fb26;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00406fb0;
  local_14 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  local_10 = 0;
  piStack_38 = (int *)0x5c8375;
  piStack_34 = piVar5;
  (**(code **)(*piVar5 + 4))();
  local_8 = 2;
  piStack_38 = (int *)0xffffffff;
  ppiStack_3c = (int **)0x5c838b;
  __vbaOnError();
  local_8 = 3;
  ppiStack_3c = (int **)0x5c83a1;
  piStack_38 = piVar5;
  ppiStack_3c = (int **)(**(code **)(*piVar5 + 0x300))();
  local_40 = (int *)&stack0xffffffd0;
  piStack_44 = (int *)0x5c83ac;
  piVar1 = (int *)__vbaObjSet();
  ppiStack_3c = (int **)&stack0xffffffd8;
  piStack_44 = (int *)0x5c83cb;
  local_40 = piVar1;
  ppiVar2 = (int **)(**(code **)(*piVar1 + 0xf8))();
  if ((int)ppiVar2 < 0) {
    piStack_44 = (int *)0xf8;
    local_48 = (undefined4 *)&DAT_004408d8;
    ppiStack_54 = (int **)0x5c83fa;
    local_50 = ppiVar2;
    pppiStack_4c = (int ***)piVar1;
    __vbaHresultCheckObj();
  }
  local_48 = (undefined4 *)0x5c8416;
  rtcTrimBstr();
  piStack_44 = (int *)0x5c8421;
  piStack_44 = (int *)__vbaStrMove();
  local_48 = (undefined4 *)&DAT_00433680;
  pppiStack_4c = (int ***)0x5c842d;
  iVar3 = __vbaStrCmp();
  piStack_44 = (int *)&stack0xffffffd4;
  local_48 = (undefined4 *)&stack0xffffffd8;
  pppiStack_4c = (int ***)0x2;
  local_50 = (int **)0x5c844c;
  __vbaFreeStrList();
  piStack_44 = (int *)0x5c8458;
  __vbaFreeObj();
  if (iVar3 == 0) {
    local_8 = 6;
    local_68 = 0x80020004;
    local_70[0] = 10;
    local_58 = 0x80020004;
    local_60[0] = 10;
    local_48 = (undefined4 *)0x80020004;
    local_50 = (int **)0xa;
    piStack_44 = (int *)0x5c85a4;
    __vbaVarDup();
    piStack_44 = local_70;
    local_48 = local_60;
    pppiStack_4c = &local_50;
    local_50 = (int **)0x40;
    ppiStack_54 = &local_40;
    local_58 = 0x5c85bc;
    rtcMsgBox();
    piStack_44 = local_70;
    local_48 = local_60;
    pppiStack_4c = &local_50;
    local_50 = &local_40;
    ppiStack_54 = (int **)0x4;
    local_58 = 0x5c85d4;
    __vbaFreeVarList();
  }
  else {
    local_8 = 4;
    local_48 = (undefined4 *)0x5c847d;
    piStack_44 = piVar5;
    local_48 = (undefined4 *)(**(code **)(*piVar5 + 0x300))();
    pppiStack_4c = (int ***)&stack0xffffffd0;
    local_50 = (int **)0x5c8488;
    piVar1 = (int *)__vbaObjSet();
    local_48 = (undefined4 *)&stack0xffffffd8;
    local_50 = (int **)0x5c84a7;
    pppiStack_4c = (int ***)piVar1;
    puVar4 = (undefined1 *)(**(code **)(*piVar1 + 0xf8))();
    if ((int)puVar4 < 0) {
      ppiStack_3c = (int **)0xf8;
      local_40 = (int *)&DAT_004408d8;
      pppiStack_4c = (int ***)0x5c84d6;
      local_48 = (undefined4 *)puVar4;
      piStack_44 = piVar1;
      __vbaHresultCheckObj();
    }
    if (DAT_00673584 == (int *)0x0) {
      ppiStack_3c = &DAT_00673584;
      local_40 = (int *)&DAT_00420b84;
      piStack_44 = (int *)0x5c8501;
      __vbaNew2();
    }
    local_40 = (int *)0x5c8521;
    rtcTrimBstr();
    ppiStack_3c = (int **)0x5c852c;
    ppiStack_3c = (int **)__vbaStrMove();
    local_40 = DAT_00673584;
    piStack_44 = (int *)0x5c853b;
    frmAgent::Public_84();
    piStack_44 = (int *)&stack0xffffffd4;
    local_48 = (undefined4 *)&stack0xffffffd8;
    pppiStack_4c = (int ***)0x2;
    local_50 = (int **)0x5c854b;
    __vbaFreeStrList();
    piStack_44 = (int *)0x5c8557;
    __vbaFreeObj();
  }
  return;
}


// ---- mnuProperties_Click @ 005c8640

void frmBBIMReverseList::mnuProperties_Click(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  int *piVar4;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffb8;
  local_c = &DAT_00406ff0;
  local_8 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar4 + 4))(piVar4);
  local_1c = 0;
  local_20 = 0;
  local_24 = 0;
  local_28 = 0;
  uVar1 = (**(code **)(*piVar4 + 0x300))(piVar4);
  piVar2 = (int *)__vbaObjSet(&local_28,uVar1);
  iVar3 = (**(code **)(*piVar2 + 0xf8))(piVar2,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_004408d8,0xf8);
  }
  rtcTrimBstr(local_1c);
  __vbaStrMove();
  iVar3 = *piVar4;
  local_24 = 0;
  uVar1 = __vbaI2I4();
  uVar1 = __vbaStrMove(uVar1);
  (**(code **)(iVar3 + 0x710))(piVar4,uVar1);
  __vbaFreeStrList(3,&local_1c,&local_20,&local_24);
  __vbaFreeObj();
  return;
}


// ---- OKButton_Click @ 005c8780

void frmBBIMReverseList::OKButton_Click(uint param_1)

{
  int *piVar1;
  undefined4 uVar2;
  int iVar3;
  int *piVar4;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc4;
  local_c = &DAT_00407000;
  local_8 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar4 + 4))(piVar4);
  local_1c = 0;
  if (DAT_00674f5c == (int *)0x0) {
    __vbaNew2(&DAT_0043752c,&DAT_00674f5c);
  }
  piVar1 = DAT_00674f5c;
  iVar3 = *DAT_00674f5c;
  uVar2 = __vbaObjSetAddref(&local_1c,piVar4);
  iVar3 = (**(code **)(iVar3 + 0x10))(piVar1,uVar2);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar1,&DAT_0043751c,0x10);
  }
  __vbaFreeObj();
  return;
}


// ---- Public_6 @ 005c8850

/* WARNING: Restarted to delay deadcode elimination for space: ram */

void frmBBIMReverseList::Public_6(int ********param_1,undefined4 param_2,short param_3)

{
  int *******pppppppiVar1;
  short sVar2;
  int iVar3;
  undefined4 uVar4;
  int local_a0;
  int *******local_84;
  int ******local_80;
  int *******local_7c;
  int *******local_78;
  int *******local_74;
  undefined *local_70;
  int *******local_6c;
  undefined **local_68;
  int *******local_64;
  int *local_60;
  int *******local_5c;
  int *******local_58;
  int *******local_54;
  int *******local_50;
  int *******local_4c;
  int *******local_48;
  int *******local_44;
  int *******local_40;
  int *******local_3c;
  int *******local_38;
  int *******local_34;
  void *pvStack_24;
  undefined *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &DAT_0040fb26;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00407010;
  local_14 = 0;
  local_10 = 0;
  local_8 = 1;
  local_34 = (int *******)0x5c88a1;
  __vbaStrCopy();
  local_8 = 2;
  local_34 = (int *******)0xffffffff;
  local_38 = (int *******)0x5c88b0;
  __vbaOnError();
  local_8 = 3;
  local_38 = (int *******)0x5c88c1;
  iVar3 = __vbaLenBstr();
  if (0 < iVar3) {
    local_8 = 4;
    if (DAT_00673584 == (int ****)0x0) {
      local_34 = (int *******)&DAT_00673584;
      local_38 = (int *******)&DAT_00420b84;
      local_3c = (int *******)0x5c88e9;
      __vbaNew2();
    }
    local_74 = (int *******)DAT_00673584;
    local_34 = (int *******)&local_48;
    local_3c = (int *******)0x5c891d;
    local_38 = local_74;
    local_78 = (int *******)(*(code *)(*DAT_00673584)[0x1c8])();
    if ((int)local_78 < 0) {
      local_3c = (int *******)0x720;
      local_40 = (int *******)&LAB_004477cc;
      local_44 = local_74;
      local_4c = (int *******)0x5c8940;
      local_48 = local_78;
      __vbaHresultCheckObj();
    }
    local_7c = local_48;
    local_3c = (int *******)&local_4c;
    local_40 = (int *******)(int)param_3;
    pppppppiVar1 = (int *******)*local_48;
    local_44 = local_48;
    local_48 = (int *******)0x5c896d;
    local_80 = (int ******)(*(code *)pppppppiVar1[0x15])();
    if ((int)local_80 < 0) {
      local_34 = (int *******)0x54;
      local_38 = (int *******)&DAT_0044777c;
      local_3c = local_7c;
      local_44 = (int *******)0x5c898d;
      local_40 = (int *******)local_80;
      __vbaHresultCheckObj();
    }
    local_34 = local_4c;
    local_4c = (int *******)0x0;
    local_38 = (int *******)&stack0xffffffd4;
    local_3c = (int *******)0x5c89c0;
    __vbaObjSet();
    local_34 = (int *******)0x5c89c9;
    __vbaFreeObj();
    local_8 = 5;
    local_38 = (int *******)&local_38;
    local_3c = (int *******)&local_84;
    local_40 = (int *******)&DAT_0044778c;
    local_44 = (int *******)0x5c89e7;
    local_a0 = __vbaForEachCollObj();
    while (local_a0 != 0) {
      local_8 = 6;
      local_34 = (int *******)&local_3c;
      local_3c = (int *******)0x5c8a09;
      local_74 = (int *******)(*(code *)(*local_38)[0xb])();
      if ((int)local_74 < 0) {
        local_3c = (int *******)0x2c;
        local_40 = (int *******)&DAT_0044778c;
        local_44 = local_38;
        local_4c = (int *******)0x5c8a29;
        local_48 = local_74;
        __vbaHresultCheckObj();
      }
      local_3c = (int *******)param_1;
      local_40 = (int *******)0x5c8a4a;
      local_40 = (int *******)(*(code *)(*param_1)[0xc0])();
      local_44 = (int *******)&local_48;
      local_48 = (int *******)0x5c8a55;
      local_78 = (int *******)__vbaObjSet();
      local_40 = (int *******)&local_40;
      local_48 = (int *******)0x5c8a6b;
      local_44 = local_78;
      local_7c = (int *******)(*(code *)(*local_78)[0x3e])();
      if ((int)local_7c < 0) {
        local_34 = (int *******)0xf8;
        local_38 = (int *******)&DAT_004408d8;
        local_3c = local_78;
        local_44 = (int *******)0x5c8a8e;
        local_40 = local_7c;
        __vbaHresultCheckObj();
      }
      local_34 = local_3c;
      local_38 = local_40;
      local_3c = (int *******)0x5c8aae;
      rtcTrimBstr();
      local_38 = (int *******)0x5c8ab9;
      local_38 = (int *******)__vbaStrMove();
      local_3c = (int *******)0x5c8ac0;
      iVar3 = __vbaStrCmp();
      local_80 = (int ******)CONCAT22(local_80._2_2_,-(ushort)(iVar3 == 0));
      local_34 = (int *******)&local_44;
      local_38 = (int *******)&local_3c;
      local_3c = (int *******)&local_40;
      local_40 = (int *******)0x3;
      local_44 = (int *******)0x5c8adf;
      __vbaFreeStrList();
      local_34 = (int *******)0x5c8aeb;
      __vbaFreeObj();
      if ((short)local_80 != 0) {
        local_34 = (int *******)&local_84;
        local_38 = (int *******)0x5c8afd;
        __vbaExitEachColl();
        break;
      }
      local_8 = 9;
      local_34 = (int *******)&local_38;
      local_38 = (int *******)&local_84;
      local_3c = (int *******)&DAT_0044778c;
      local_40 = (int *******)0x5c8b19;
      local_a0 = __vbaNextEachCollObj();
    }
    local_8 = 10;
    local_34 = (int *******)0x0;
    local_3c = (int *******)0x5c8b3f;
    sVar2 = __vbaObjIs();
    if (sVar2 == 0) {
      local_8 = 0xb;
      if (DAT_00674f5c == (int ****)0x0) {
        local_34 = (int *******)&DAT_00674f5c;
        local_38 = (int *******)&DAT_0043752c;
        local_3c = (int *******)0x5c8b6a;
        __vbaNew2();
      }
      local_74 = (int *******)DAT_00674f5c;
      if (DAT_00673598 == (int ****)0x0) {
        local_34 = (int *******)&DAT_00673598;
        local_38 = (int *******)&DAT_00416014;
        local_3c = (int *******)0x5c8ba4;
        __vbaNew2();
      }
      local_34 = (int *******)DAT_00673598;
      local_38 = (int *******)&local_48;
      local_3c = (int *******)0x5c8bcd;
      local_34 = (int *******)__vbaObjSetAddref();
      local_38 = local_74;
      local_3c = (int *******)0x5c8bda;
      local_78 = (int *******)(*(code *)(*local_74)[3])();
      if ((int)local_78 < 0) {
        local_3c = (int *******)0xc;
        local_40 = (int *******)&DAT_0043751c;
        local_44 = local_74;
        local_4c = (int *******)0x5c8bfa;
        local_48 = local_78;
        __vbaHresultCheckObj();
      }
      local_3c = (int *******)0x5c8c15;
      __vbaFreeObj();
      local_8 = 0xc;
      if (DAT_00673598 == (int ****)0x0) {
        local_3c = (int *******)&DAT_00673598;
        local_40 = (int *******)&DAT_00416014;
        local_44 = (int *******)0x5c8c35;
        __vbaNew2();
      }
      local_3c = (int *******)DAT_00673598;
      local_40 = (int *******)0x5c8c64;
      local_40 = (int *******)(*(code *)(*DAT_00673598)[0xc1])();
      local_44 = (int *******)&local_48;
      local_48 = (int *******)0x5c8c6f;
      local_78 = (int *******)__vbaObjSet();
      local_40 = (int *******)&local_3c;
      local_44 = local_38;
      local_48 = (int *******)0x5c8c82;
      local_74 = (int *******)(*(code *)(*local_38)[8])();
      if ((int)local_74 < 0) {
        local_48 = (int *******)0x20;
        local_4c = (int *******)&DAT_0044778c;
        local_50 = local_38;
        local_58 = (int *******)0x5c8ca2;
        local_54 = local_74;
        __vbaHresultCheckObj();
      }
      local_48 = local_3c;
      local_4c = local_78;
      local_50 = (int *******)0x5c8cc4;
      local_7c = (int *******)(*(code *)(*local_78)[0x15])();
      if ((int)local_7c < 0) {
        local_50 = (int *******)0x54;
        local_54 = (int *******)&DAT_0043873c;
        local_58 = local_78;
        local_60 = (int *)0x5c8ce4;
        local_5c = local_7c;
        __vbaHresultCheckObj();
      }
      local_50 = (int *******)0x5c8cff;
      __vbaFreeStr();
      local_50 = (int *******)0x5c8d08;
      __vbaFreeObj();
      local_8 = 0xd;
      if (DAT_00673598 == (int ****)0x0) {
        local_50 = (int *******)&DAT_00673598;
        local_54 = (int *******)&DAT_00416014;
        local_58 = (int *******)0x5c8d28;
        __vbaNew2();
      }
      local_50 = (int *******)DAT_00673598;
      local_54 = (int *******)0x5c8d57;
      local_54 = (int *******)(*(code *)(*DAT_00673598)[0xc2])();
      local_58 = (int *******)&local_48;
      local_5c = (int *******)0x5c8d62;
      local_78 = (int *******)__vbaObjSet();
      local_54 = (int *******)&local_3c;
      local_58 = local_38;
      local_5c = (int *******)0x5c8d75;
      local_74 = (int *******)(*(code *)(*local_38)[9])();
      if ((int)local_74 < 0) {
        local_5c = (int *******)0x24;
        local_60 = (int *)&DAT_0044778c;
        local_64 = local_38;
        local_6c = (int *******)0x5c8d95;
        local_68 = (undefined **)local_74;
        __vbaHresultCheckObj();
      }
      local_5c = local_3c;
      local_60 = (int *)local_78;
      local_64 = (int *******)0x5c8db7;
      local_7c = (int *******)(**(code **)((int)*local_78 + 0x54))();
      if ((int)local_7c < 0) {
        local_64 = (int *******)0x54;
        local_68 = (undefined **)&DAT_0043873c;
        local_6c = local_78;
        local_74 = (int *******)0x5c8dd7;
        local_70 = (undefined *)local_7c;
        __vbaHresultCheckObj();
      }
      local_64 = (int *******)0x5c8df2;
      __vbaFreeStr();
      local_64 = (int *******)0x5c8dfb;
      __vbaFreeObj();
      local_8 = 0xe;
      if (DAT_00673598 == (int ****)0x0) {
        local_64 = (int *******)&DAT_00673598;
        local_68 = (undefined **)&DAT_00416014;
        local_6c = (int *******)0x5c8e1b;
        __vbaNew2();
      }
      local_64 = (int *******)DAT_00673598;
      local_68 = (undefined **)0x5c8e4a;
      local_68 = (undefined **)(*(code *)(*DAT_00673598)[0xc3])();
      local_6c = (int *******)&local_48;
      local_70 = (undefined *)0x5c8e55;
      local_78 = (int *******)__vbaObjSet();
      local_68 = &local_70;
      local_6c = local_38;
      local_70 = (undefined *)0x5c8e68;
      iVar3 = (*(code *)(*local_38)[10])();
      if (iVar3 < 0) {
        local_70 = (undefined *)0x28;
        local_74 = (int *******)&DAT_0044778c;
        local_78 = local_38;
        local_7c = (int *******)&DAT_0044778c;
        local_80 = (int ******)0x5c8e88;
        __vbaHresultCheckObj();
      }
      local_74 = (int *******)0x5c8ea3;
      frmAgent::Proc_60de70();
      local_74 = (int *******)0x5c8eae;
      local_74 = (int *******)__vbaStrMove();
      local_7c = (int *******)0x5c8ebb;
      iVar3 = (*(code *)(*local_78)[0x15])();
      if (iVar3 < 0) {
        local_7c = (int *******)0x54;
        local_80 = (int ******)&DAT_0043873c;
        local_84 = local_78;
        __vbaHresultCheckObj(0x54);
      }
      local_7c = (int *******)0x5c8ef6;
      __vbaFreeStr();
      local_7c = (int *******)0x5c8eff;
      __vbaFreeObj();
      local_8 = 0xf;
      if (DAT_00673598 == (int ****)0x0) {
        local_7c = (int *******)&DAT_00673598;
        local_80 = (int ******)&DAT_00416014;
        local_84 = (int *******)0x5c8f1f;
        __vbaNew2();
      }
      local_80 = (int ******)DAT_00673598;
      local_7c = (int *******)0x447d4c;
      local_84 = (int *******)0x5c8f51;
      local_74 = (int *******)local_80;
      local_78 = (int *******)(*(code *)(*DAT_00673598)[0x15])();
      if ((int)local_78 < 0) {
        local_84 = (int *******)0x54;
        __vbaHresultCheckObj(local_78,local_74,&DAT_00447cac);
      }
      local_8 = 0x10;
      if (DAT_00673598 == (int ****)0x0) {
        local_84 = (int *******)&DAT_00673598;
        __vbaNew2(&DAT_00416014);
      }
      local_84 = (int *******)DAT_00673598;
      uVar4 = (*(code *)(*DAT_00673598)[0xc0])();
      local_74 = (int *******)__vbaObjSet(&local_48,uVar4);
      local_78 = (int *******)
                 (**(code **)((int)*local_74 + 0x54))(local_74,L"About the selected user");
      if ((int)local_78 < 0) {
        __vbaHresultCheckObj(local_78,local_74,&DAT_00439b90,0x54);
      }
      __vbaFreeObj();
      local_8 = 0x11;
      if (DAT_00673598 == (int ****)0x0) {
        __vbaNew2(&DAT_00416014,&DAT_00673598);
      }
      local_74 = (int *******)DAT_00673598;
      local_64 = (int *******)0x80020004;
      local_6c = (int *******)0xa;
      local_54 = (int *******)0x1;
      local_5c = (int *******)0x2;
      __vbaChkstk();
      local_84 = local_64;
      local_80 = (int ******)local_60;
      __vbaChkstk(local_6c,local_68);
      local_84 = local_54;
      local_80 = (int ******)local_50;
      local_78 = (int *******)(*(code *)(*local_74)[0xac])(local_74,local_5c,local_58);
      if ((int)local_78 < 0) {
        local_34 = (int *******)0x2b0;
        local_38 = (int *******)&DAT_00447cac;
        local_3c = local_74;
        local_44 = (int *******)0x5c9101;
        local_40 = local_78;
        __vbaHresultCheckObj();
      }
      local_8 = 0x12;
      local_34 = (int *******)&DAT_0044778c;
      local_38 = (int *******)0x0;
      local_3c = (int *******)0x5c9127;
      local_34 = (int *******)__vbaCastObj();
      local_38 = (int *******)&local_38;
      local_3c = (int *******)0x5c9132;
      __vbaObjSet();
    }
    local_8 = 0x14;
    local_34 = (int *******)&DAT_00447bf0;
    local_38 = (int *******)0x0;
    local_3c = (int *******)0x5c9146;
    local_34 = (int *******)__vbaCastObj();
    local_38 = (int *******)&stack0xffffffd4;
    local_3c = (int *******)0x5c9151;
    __vbaObjSet();
  }
  local_34 = (int *******)&LAB_005c91b1;
  local_38 = (int *******)0x5c918c;
  __vbaFreeObj();
  local_38 = (int *******)0x5c9195;
  __vbaFreeObj();
  local_38 = (int *******)0x5c919e;
  __vbaFreeStr();
  local_38 = (int *******)0x5c91a7;
  __vbaFreeObj();
  local_38 = (int *******)0x5c91b0;
  __vbaFreeObj();
  return;
}


