// BonziBDY_35.EXE :: frmConnectionType
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 3

// ---- cmdOK_Click @ 0055e110

/* WARNING: Restarted to delay deadcode elimination for space: ram */

void frmConnectionType::cmdOK_Click(uint param_1)

{
  short sVar1;
  int iVar2;
  int iVar3;
  undefined *****pppppuVar4;
  undefined4 unaff_EDI;
  int *piVar5;
  undefined4 uVar6;
  undefined4 uVar7;
  undefined4 uVar8;
  undefined4 uVar9;
  undefined *****local_3c;
  undefined ****local_38;
  undefined ****local_34;
  void *pvStack_24;
  undefined *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &DAT_0040fb26;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00402cd0;
  local_14 = param_1 & 1;
  pppppuVar4 = (undefined *****)(param_1 & 0xfffffffe);
  local_10 = 0;
  local_38 = (undefined ****)0x55e165;
  local_34 = (undefined ****)pppppuVar4;
  (*(code *)(*pppppuVar4)[1])();
  local_8 = 2;
  local_38 = (undefined ****)0xffffffff;
  local_3c = (undefined *****)0x55e17b;
  __vbaOnError();
  local_8 = 3;
  local_3c = (undefined *****)0x55e191;
  local_38 = (undefined ****)pppppuVar4;
  local_34 = (undefined ****)(*(code *)(*pppppuVar4)[0xc3])();
  local_3c = (undefined *****)&local_3c;
  sVar1 = __vbaBoolVarNull();
  local_3c = (undefined *****)0x55e1b2;
  __vbaFreeVar();
  if (sVar1 == 0) {
    local_8 = 5;
    local_3c = pppppuVar4;
    local_34 = (undefined ****)(*(code *)(*pppppuVar4)[0xc2])();
    local_3c = (undefined *****)&local_3c;
    sVar1 = __vbaBoolVarNull();
    local_3c = (undefined *****)0x55e217;
    __vbaFreeVar();
    if (sVar1 == 0) {
      local_8 = 7;
      local_3c = pppppuVar4;
      local_34 = (undefined ****)(*(code *)(*pppppuVar4)[0xc1])();
      local_3c = (undefined *****)&local_3c;
      sVar1 = __vbaBoolVarNull();
      local_3c = (undefined *****)0x55e279;
      __vbaFreeVar();
      if (sVar1 != 0) {
        local_8 = 8;
        local_3c = (undefined *****)&PTR_DAT_0043d380;
        rtcSaveSetting(L"BONZIBUDDY",L"UserInfo",L"ConnectionType");
      }
    }
    else {
      local_8 = 6;
      local_3c = (undefined *****)&DAT_0043d374;
      rtcSaveSetting(L"BONZIBUDDY",L"UserInfo",L"ConnectionType");
    }
  }
  else {
    local_8 = 4;
    local_3c = (undefined *****)0x43d364;
    rtcSaveSetting(L"BONZIBUDDY",L"UserInfo",L"ConnectionType");
  }
  local_8 = 10;
  local_3c = pppppuVar4;
  local_34 = (undefined ****)(*(code *)(*pppppuVar4)[0xc3])();
  local_3c = (undefined *****)0x9;
  sVar1 = __vbaBoolVarNull(&local_3c);
  __vbaFreeVar();
  if (sVar1 == 0) {
    local_8 = 0xd;
    if (DAT_00673208 == 0) {
      __vbaNew2(&DAT_00429ce4,&DAT_00673208);
    }
    uVar9 = 0;
    frmAgent::Public_146(DAT_00673208,0);
  }
  else {
    local_8 = 0xb;
    if (DAT_00673208 == 0) {
      __vbaNew2(&DAT_00429ce4,&DAT_00673208);
    }
    uVar9 = 0xffffffff;
    frmAgent::Public_146(DAT_00673208,0xffffffff);
  }
  local_8 = 0xf;
  if (DAT_00673208 == 0) {
    __vbaNew2(&DAT_00429ce4,&DAT_00673208);
  }
  iVar3 = DAT_00673208;
  frmAgent::Public_147(DAT_00673208);
  local_8 = 0x10;
  if (DAT_00673208 == 0) {
    __vbaNew2(&DAT_00429ce4,&DAT_00673208);
  }
  frmAgent::Public_148(DAT_00673208);
  local_8 = 0x11;
  uVar7 = 0x80020004;
  uVar6 = 10;
  __vbaChkstk(10,iVar3,0x80020004);
  iVar2 = (**(code **)(*DAT_0067307c + 0x6c))(DAT_0067307c,uVar6,iVar3,uVar7,uVar9);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,DAT_0067307c,&DAT_00437468,0x6c);
  }
  local_8 = 0x12;
  iVar2 = (**(code **)(*DAT_0067307c + 100))(DAT_0067307c,L"Acknowledge",&stack0xffffffd4);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,DAT_0067307c,&DAT_00437468,100);
  }
  __vbaFreeObj();
  local_8 = 0x13;
  uVar8 = 0x80020004;
  uVar7 = 10;
  __vbaStrCat(DAT_00673040,L"Thanks ");
  uVar6 = __vbaStrMove();
  local_34 = (undefined ****)__vbaStrCat(&DAT_004390b8,uVar6);
  local_3c = (undefined *****)0x8;
  __vbaChkstk(&stack0xffffffd4);
  __vbaChkstk(uVar7,iVar3,uVar8,uVar9);
  iVar3 = (**(code **)(*DAT_0067307c + 0x78))(DAT_0067307c,local_3c,local_38,local_34,unaff_EDI);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,DAT_0067307c,&DAT_00437468,0x78);
  }
  __vbaFreeStr();
  __vbaFreeObj();
  __vbaFreeVar();
  local_8 = 0x14;
  if (DAT_00674f5c == (int *)0x0) {
    __vbaNew2(&DAT_0043752c,&DAT_00674f5c);
  }
  piVar5 = DAT_00674f5c;
  uVar9 = __vbaObjSetAddref(&stack0xffffffd4,pppppuVar4);
  iVar3 = (**(code **)(*piVar5 + 0x10))(piVar5,uVar9);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar5,&DAT_0043751c,0x10);
  }
  __vbaFreeObj();
  return;
}


// ---- Form_Activate @ 0055e680

void frmConnectionType::Form_Activate(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00402d48;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  local_1c = 0;
  local_20 = 0;
  uVar1 = __vbaCastObj(piVar3,&DAT_004375cc);
  __vbaObjSet(&local_1c,uVar1);
  iVar2 = (**(code **)(*DAT_006731bc + 0x20))(DAT_006731bc,&local_1c,&local_20);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,DAT_006731bc,&DAT_004375dc,0x20);
  }
  __vbaFreeObj();
  return;
}


// ---- Form_Load @ 0055e750

void frmConnectionType::Form_Load(uint param_1)

{
  int iVar1;
  int iVar2;
  int *piVar3;
  int *piVar4;
  wchar_t *pwVar5;
  undefined4 uVar6;
  wchar_t *pwVar7;
  wchar_t *pwVar8;
  wchar_t *pwStack_24;
  wchar_t *pwStack_20;
  wchar_t *local_1c;
  undefined *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  pwStack_20 = 
  L"◿ሼ@◿ኄ@◿ᄤ@◿ი@◿ዴ@◿ၐ@◿ጤ@◿ᄬ@◿ጘ@◿ዸ@◿በ@◿ᇸ@◿ቜ@◿ၴ@◿ဘ@◿᎜@◿န@◿ᐄ@◿ዄ@◿ᅜ@◿ሤ@◿Ꮸ@◿Ꮠ@◿ᇘ@◿Ꮀ@◿ᄨ@◿ዬ@◿ጀ@◿Ⴌ@◿၀@◿၌@◿ቘ@◿ᇄ@◿Ⴜ@◿፠@◿Ꮜ@◿ၤ@◿ጐ@◿႔@◿ႀ@◿Ꭼ@◿ᐘ@◿ြ@◿ᄠ@◿ᐔ@◿჈@◿ာ@◿჌@◿ᄜ@◿ᆨ@◿ᄴ@◿ሜ@◿တ@◿ᇨ@◿ፀ@◿ᄐ@◿ሄ@◿Ⴘ@◿ጬ@◿ᄘ@◿ᅄ@◿ጴ@◿ጔ@◿የ@◿ጨ@◿ቐ@◿፜@◿ၔ@◿Ⴤ@◿፰@◿ဌ@◿ᅘ@◿ᆴ@◿ᇴ@◿ዤ@◿ဨ@◿ᇀ@◿ဠ@◿ᎈ@◿ገ@◿ፘ@◿ከ@◿᎘@◿႐@◿ሰ@◿ᅔ@◿း@◿ᅨ@◿ᅀ@◿ᇼ@◿᎔@◿ၼ@◿Ⴔ@◿ሔ@◿ዐ@◿ᆈ@◿አ@◿ᎄ@◿လ@◿Ꮴ@◿Ⴠ@◿ᆤ@◿ዀ@◿ቌ@◿ደ@◿ᆄ@◿Ⴈ@◿ዌ@◿ዠ@◿Ꮐ@◿ᆜ@◿ኘ@◿ᇔ@◿ቀ@◿რ@◿Ꭸ@◿ᅸ@◿ኌ@◿ጸ@◿ቈ@◿წ@◿ᏼ@◿ፐ@◿ᅤ@◿ዜ@◿ၸ@◿Ꮨ@◿ሐ@◿ᅠ@◿ወ@◿ᇰ@◿ᆘ@◿ኔ@◿ተ@◿ቬ@◿ጌ@◿ፌ@◿᎐@◿ᐐ@◿ე@◿ဈ@◿ᄰ@◿፴@◿၈@◿ፈ@◿Ꭴ@◿ጼ@◿ၜ@◿ᎀ@◿ሬ@◿Ꮌ@◿Ꮘ@◿ႈ@◿Ꮤ@◿ᇐ@◿ᅴ@◿ኼ@◿ᇤ@◿ᆀ@◿ረ@◿ᄸ@◿ፄ@◿ኀ@◿ၠ@◿Ⴐ@◿ኰ@◿Ⴄ@◿Ꮰ@◿ဤ@◿ᆼ@◿Ꮔ@◿ጠ@◿င@◿႘@◿ᆰ@◿፼@◿፸@◿ᅰ@◿Ⴀ@◿ဴ@◿ᆬ@◿ჸ@◿Ꮬ@◿ᇌ@◿ዘ@◿ჰ@◿ᇠ@◿ᇈ@◿ኤ@◿ႄ@◿ᄼ@◿ᆸ@◿Ꭰ@◿ႜ@◿ቴ@◿ኜ@◿ዔ@◿ᅬ@◿ᄌ@◿ა@◿ዼ@◿ၨ@◿ቔ@◿ሠ@◿ኸ@◿ሀ@◿ኬ@◿ᄈ@◿᐀@◿ሸ@◿ᐜ@◿ᏸ@◿ᆐ@◿ᄄ@◿ᄔ@◿Ᏸ@◿Ᏼ@◿ၰ@◿ኴ@◿ኈ@◿ᇜ@◿ူ@◿ቨ@◿ሌ@◿ᇬ@◿ቼ@◿ጜ@◿፨@◿ቤ@◿ᆠ@◿ၬ@◿ᐌ@◿Ꮈ@◿ቄ@◿ᄀ@◿ჼ@◿ᅐ@◿ᅌ@◿ᅈ@◿፬@◿ᐈ@◿ᎌ@◿ნ@◿၄@◿Ꮄ@◿ᆔ@◿შ@◿ቸ@◿ႌ@◿Ꮼ@◿ሴ@◿ᆌ@◿መ@◿ጄ@◿ჴ@◿ለ@◿ფ@◿က@◿ၘ@◿ነ@◿ፔ@◿፤@◿ጰ@桨䄇\xe800\xfff0\xffff"
  ;
  pwStack_24 = ExceptionList;
  ExceptionList = &pwStack_24;
  __vbaChkstk();
  local_1c = (wchar_t *)&stack0xffffffd0;
  local_18 = &DAT_00402d58;
  local_14 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  local_10 = 0;
  (**(code **)(*piVar4 + 4))(piVar4);
  local_8 = 2;
  __vbaOnError(0xffffffff);
  local_8 = 3;
  uVar6 = 8;
  __vbaChkstk(&DAT_00433680);
  pwVar7 = L"ConnectionType";
  pwVar5 = L"BONZIBUDDY";
  rtcGetSetting(L"BONZIBUDDY",L"UserInfo",L"ConnectionType",uVar6);
  __vbaStrMove();
  local_8 = 4;
  iVar1 = __vbaLenBstr();
  iVar2 = __vbaStrCmp();
  if (iVar1 == 0 || iVar2 == 0) {
    local_8 = 5;
    (**(code **)(*piVar4 + 0x30c))();
    piVar3 = (int *)__vbaObjSet();
    iVar1 = (**(code **)(*piVar3 + 0xe4))();
    if (iVar1 < 0) {
      pwVar7 = L"䖉\xeb98윇顅";
      __vbaHresultCheckObj(iVar1);
    }
    __vbaFreeObj();
  }
  else {
    local_8 = 6;
    iVar1 = __vbaStrCmp();
    if (iVar1 == 0) {
      local_8 = 7;
      (**(code **)(*piVar4 + 0x308))();
      piVar3 = (int *)__vbaObjSet();
      iVar1 = (**(code **)(*piVar3 + 0xe4))();
      if (iVar1 < 0) {
        pwVar7 = L"䖉\xeb94윇鑅";
        __vbaHresultCheckObj(iVar1);
      }
      __vbaFreeObj();
    }
    else {
      local_8 = 8;
      piVar3 = (int *)0x55e95b;
      iVar1 = __vbaStrCmp();
      if (iVar1 == 0) {
        local_8 = 9;
        (**(code **)(*piVar4 + 0x304))();
        piVar3 = (int *)__vbaObjSet();
        iVar1 = (**(code **)(*piVar3 + 0xe4))();
        if (iVar1 < 0) {
          pwVar7 = L"䖉\xeb90윇遅";
          __vbaHresultCheckObj(iVar1);
        }
        __vbaFreeObj();
      }
    }
  }
  local_8 = 0xb;
  pwVar8 = 
  L"Now let\'s select the option from my Internet Connection Screen which best describes how we will be connecting to the Internet!"
  ;
  __vbaChkstk();
  pwStack_20 = (wchar_t *)0x80020004;
  local_1c = pwVar5;
  __vbaChkstk();
  pwStack_24 = pwVar7;
  pwStack_20 = pwVar8;
  local_1c = (wchar_t *)piVar3;
  iVar1 = (**(code **)(*DAT_0067307c + 0x78))();
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,DAT_0067307c,&DAT_00437468);
  }
  __vbaFreeObj();
  local_14 = 0;
  __vbaFreeStr();
  return;
}


