// BonziBDY_35.EXE :: frmSpeak
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 6

// ---- cmdCancel_Click @ 0053f800

void frmSpeak::cmdCancel_Click(uint param_1)

{
  int *piVar1;
  undefined4 uVar2;
  int iVar3;
  int *piVar4;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffbc;
  local_c = &DAT_004016b8;
  local_8 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar4 + 4))(piVar4);
  local_1c = 0;
  local_24 = 0;
  local_20 = 0;
  uVar2 = __vbaCastObj(piVar4,&DAT_004375cc);
  __vbaObjSet(&local_1c,uVar2);
  iVar3 = (**(code **)(*DAT_006731bc + 0x1c))(DAT_006731bc,&local_1c,&local_20,&local_24);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,DAT_006731bc,&DAT_004375dc,0x1c);
  }
  __vbaFreeObj();
  if (DAT_00674f5c == (int *)0x0) {
    __vbaNew2(&DAT_0043752c,&DAT_00674f5c);
  }
  piVar1 = DAT_00674f5c;
  iVar3 = *DAT_00674f5c;
  uVar2 = __vbaObjSetAddref(&local_1c,piVar4);
  iVar3 = (**(code **)(iVar3 + 0x10))(piVar1,uVar2);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar1,&DAT_0043751c,0x10);
  }
  __vbaFreeObj();
  return;
}


// ---- cmdSpeak_Click @ 0053f930

void frmSpeak::cmdSpeak_Click(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  int *piVar4;
  undefined4 local_5c;
  undefined4 local_58;
  undefined4 local_54;
  undefined4 local_4c;
  undefined4 local_44;
  undefined4 local_40;
  undefined4 local_3c;
  undefined4 local_38;
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff80;
  local_c = &DAT_004016c8;
  local_8 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar4 + 4))(piVar4);
  local_1c = 0;
  local_20 = 0;
  local_24 = 0;
  local_28 = 0;
  local_38 = 0;
  local_58 = 0;
  local_5c = 0;
  uVar1 = (**(code **)(*piVar4 + 0x308))(piVar4);
  piVar2 = (int *)__vbaObjSet(&local_24,uVar1);
  iVar3 = (**(code **)(*piVar2 + 0xa0))(piVar2,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_00437318,0xa0);
  }
  rtcTrimBstr(local_1c);
  uVar1 = __vbaStrMove();
  iVar3 = __vbaLenBstr(uVar1);
  __vbaFreeStrList(2,&local_1c,&local_20);
  __vbaFreeObj();
  if (iVar3 == 0) {
    iVar3 = (**(code **)(*DAT_0067307c + 0x78))
                      (DAT_0067307c,8,local_44,L"You\'ll have to type something first.",local_3c,10,
                       local_54,0x80020004,local_4c,&local_24);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,DAT_0067307c,&DAT_00437468,0x78);
    }
    __vbaFreeObj();
  }
  else {
    iVar3 = (**(code **)(*DAT_0067307c + 0xd0))(DAT_0067307c,0,&local_5c);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,DAT_0067307c,&DAT_00438558,0xd0);
    }
    iVar3 = (**(code **)(*DAT_0067307c + 0x6c))(DAT_0067307c,10,local_44,0x80020004,local_3c);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,DAT_0067307c,&DAT_00437468,0x6c);
    }
    local_40 = 0x80020004;
    uVar1 = (**(code **)(*piVar4 + 0x308))(piVar4);
    piVar2 = (int *)__vbaObjSet(&local_24,uVar1);
    iVar3 = (**(code **)(*piVar2 + 0xa0))(piVar2,&local_1c);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar2,&DAT_00437318,0xa0);
    }
    local_30 = local_1c;
    local_38 = 8;
    local_1c = 0;
    iVar3 = (**(code **)(*DAT_0067307c + 0x78))
                      (DAT_0067307c,8,local_34,local_30,local_2c,10,local_44,local_40,local_3c,
                       &local_28);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,DAT_0067307c,&DAT_00437468,0x78);
    }
    __vbaFreeObjList(2,&local_24,&local_28);
    __vbaFreeVar();
  }
  return;
}


// ---- Form_Activate @ 0053fc30

void frmSpeak::Form_Activate(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_004016d8;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  local_1c = 0;
  local_20 = 0;
  uVar1 = __vbaCastObj(piVar3,&DAT_004375cc);
  __vbaObjSet(&local_1c,uVar1);
  iVar2 = (**(code **)(*DAT_006731bc + 0x20))(DAT_006731bc,&local_1c,&local_20);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,DAT_006731bc,&DAT_004375dc,0x20);
  }
  __vbaFreeObj();
  return;
}


// ---- Form_KeyUp @ 0053fd00

void frmSpeak::Form_KeyUp(uint param_1,short *param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 local_4c;
  undefined4 local_44;
  undefined4 local_3c;
  undefined4 local_34;
  undefined4 local_2c;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff94;
  local_c = &DAT_004016e8;
  local_8 = param_1 & 1;
  ExceptionList = &pvStack_18;
  (**(code **)(*(int *)(param_1 & 0xfffffffe) + 4))((int *)(param_1 & 0xfffffffe));
  local_1c = 0;
  local_20 = 0;
  if (*param_2 == 0x70) {
    iVar1 = (**(code **)(*DAT_0067307c + 0x6c))(DAT_0067307c,10,local_3c,0x80020004,local_34);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_0067307c,&DAT_00437468,0x6c);
    }
    if (DAT_00673208 == 0) {
      __vbaNew2(&DAT_00429ce4,&DAT_00673208);
    }
    frmAgent::Public_118(DAT_00673208);
    iVar1 = (**(code **)(*DAT_0067307c + 100))(DAT_0067307c,L"Suggest",&local_20);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_0067307c,&DAT_00437468,100);
    }
    __vbaFreeObj();
    iVar1 = (**(code **)(*DAT_0067307c + 0x78))
                      (DAT_0067307c,8,local_3c,
                       L"Having trouble?  Let me help you. From this screen, I can say anything you\'d like. Simply enter what you would like me to say and click on the \'Say It\' button."
                       ,local_34,10,local_4c,0x80020004,local_44,&local_20);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_0067307c,&DAT_00437468,0x78);
    }
    __vbaFreeObj();
    __vbaStrCat(DAT_00673040,L"And remember ");
    uVar2 = __vbaStrMove();
    uVar2 = __vbaStrCat(L", let\'s keep it clean!",uVar2);
    iVar1 = (**(code **)(*DAT_0067307c + 0x78))
                      (DAT_0067307c,8,local_2c,uVar2,local_24,10,local_3c,0x80020004,local_34,
                       &local_20);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_0067307c,&DAT_00437468,0x78);
    }
    __vbaFreeStr();
    __vbaFreeObj();
    __vbaFreeVar();
    iVar1 = (**(code **)(*DAT_0067307c + 100))(DAT_0067307c,L"Pleased",&local_20);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_0067307c,&DAT_00437468,100);
    }
    uVar2 = local_20;
    local_20 = 0;
    __vbaObjSet(&DAT_00673194,uVar2);
  }
  return;
}


// ---- Form_Load @ 0053ffc0

undefined4 frmSpeak::Form_Load(uint param_1)

{
  int iVar1;
  int *piVar2;
  void *local_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_004016f8;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  iVar1 = (**(code **)(*piVar2 + 0x1d4))(piVar2,0xffffffff);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar2,&DAT_00438924,0x1d4);
  }
  local_8 = 0;
  (**(code **)(*piVar2 + 8))(piVar2);
  ExceptionList = local_18;
  return local_8;
}


// ---- Form_Unload @ 00540050

void frmSpeak::Form_Unload(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_0040fb26;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc4;
  local_c = &DAT_00401700;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  local_1c = 0;
  local_24 = 0;
  local_20 = 0;
  uVar1 = __vbaCastObj(piVar3,&DAT_004375cc);
  __vbaObjSet(&local_1c,uVar1);
  iVar2 = (**(code **)(*DAT_006731bc + 0x1c))(DAT_006731bc,&local_1c,&local_20,&local_24);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,DAT_006731bc,&DAT_004375dc,0x1c);
  }
  __vbaFreeObj();
  return;
}


