// BonziBDY_4.EXE :: BBIMSessions
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 7

// ---- Add @ 007147b0

void BBIMSessions::Add(int *param_1,undefined4 *param_2,undefined4 *param_3,undefined4 *param_4,
                      undefined4 *param_5)

{
  short sVar1;
  short sVar2;
  undefined4 uVar3;
  int iVar4;
  code *pcVar5;
  undefined4 local_90 [2];
  undefined4 *local_88;
  undefined4 local_80 [2];
  undefined4 *local_78;
  undefined4 local_70;
  undefined4 local_60 [2];
  undefined4 local_58;
  undefined4 local_50 [2];
  undefined4 local_48;
  undefined4 local_40 [2];
  undefined4 local_38;
  undefined4 local_30;
  undefined4 local_2c;
  int *local_28;
  undefined4 local_24;
  void *pvStack_20;
  undefined1 *puStack_1c;
  undefined1 *local_18;
  undefined *local_14;
  undefined4 local_10;
  undefined4 local_c;
  
  puStack_1c = &LAB_00412856;
  pvStack_20 = ExceptionList;
  local_18 = &stack0xffffff24;
  local_14 = &DAT_00411350;
  local_10 = 0;
  local_c = 0;
  ExceptionList = &pvStack_20;
  (**(code **)(*param_1 + 4))(param_1);
  local_24 = 0;
  local_28 = (int *)0x0;
  local_2c = 0;
  local_30 = 0;
  local_40[0] = 0;
  local_50[0] = 0;
  local_60[0] = 0;
  local_70 = 0;
  local_80[0] = 0;
  local_90[0] = 0;
  *param_5 = 0;
  __vbaOnError(1);
  sVar1 = __vbaObjIs(*param_2,0);
  sVar2 = __vbaObjIs(*param_3,0);
  if (sVar2 == 0 && sVar1 == 0) {
    uVar3 = __vbaNew(&PTR_DAT_004140d4);
    __vbaObjSet(&local_28,uVar3);
    iVar4 = *local_28;
    uVar3 = __vbaObjSetAddref(&local_30,*param_2);
    iVar4 = (**(code **)(iVar4 + 0x2c))(local_28,uVar3);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,local_28,&DAT_0047276c,0x2c);
    }
    __vbaFreeObj();
    iVar4 = *local_28;
    uVar3 = __vbaObjSetAddref(&local_30,*param_3);
    iVar4 = (**(code **)(iVar4 + 0x24))(local_28,uVar3);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,local_28,&DAT_0047276c,0x24);
    }
    __vbaFreeObj();
    iVar4 = (**(code **)(*local_28 + 0x1c))(local_28,*param_4);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,local_28,&DAT_0047276c,0x1c);
    }
    iVar4 = __vbaLenBstr(*param_4);
    if (iVar4 == 0) {
      local_58 = 0x80020004;
      local_60[0] = 10;
      local_48 = 0x80020004;
      local_50[0] = 10;
      local_38 = 0x80020004;
      local_40[0] = 10;
      __vbaObjSetAddref(&local_30,local_28);
      local_78 = &local_30;
      local_80[0] = 0x4009;
      iVar4 = (**(code **)(*(int *)param_1[0xd] + 0x20))
                        ((int *)param_1[0xd],local_80,local_40,local_50,local_60);
      if (iVar4 < 0) {
        __vbaHresultCheckObj(iVar4,param_1[0xd],&DAT_00447b68,0x20);
      }
      pcVar5 = __vbaCastObj_exref;
      uVar3 = __vbaCastObj(local_30,&DAT_0047276c);
      __vbaObjSet(&local_28,uVar3);
      __vbaFreeObj();
      __vbaFreeVarList(3,local_40,local_50,local_60);
    }
    else {
      local_48 = 0x80020004;
      local_50[0] = 10;
      local_38 = 0x80020004;
      local_40[0] = 10;
      local_88 = param_4;
      local_90[0] = 0x4008;
      __vbaObjSetAddref(&local_30,local_28);
      local_78 = &local_30;
      local_80[0] = 0x4009;
      iVar4 = (**(code **)(*(int *)param_1[0xd] + 0x20))
                        ((int *)param_1[0xd],local_80,local_90,local_40,local_50);
      if (iVar4 < 0) {
        __vbaHresultCheckObj(iVar4,param_1[0xd],&DAT_00447b68,0x20);
      }
      pcVar5 = __vbaCastObj_exref;
      uVar3 = __vbaCastObj(local_30,&DAT_0047276c);
      __vbaObjSet(&local_28,uVar3);
      __vbaFreeObj();
      __vbaFreeVarList(2,local_40,local_50);
    }
    __vbaObjSetAddref(&local_24,local_28);
    uVar3 = (*pcVar5)(0,&DAT_0047276c);
    __vbaObjSet(&local_28,uVar3);
  }
  __vbaExitProc();
  __vbaFreeObj(&LAB_00714b95);
  return;
}


// ---- Item_Get @ 00714bc0

/* WARNING: Restarted to delay deadcode elimination for space: stack */

void BBIMSessions::Item_Get(int *param_1,undefined4 param_2,undefined4 *param_3)

{
  int iVar1;
  undefined4 uVar2;
  short sVar3;
  int *piVar4;
  int local_40;
  undefined4 local_3c;
  undefined4 *puStack_38;
  int *piStack_34;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00411378;
  local_14 = 0;
  local_10 = 0;
  piStack_34 = param_1;
  puStack_38 = (undefined4 *)0x714c0a;
  (**(code **)(*param_1 + 4))();
  *param_3 = 0;
  local_8 = 2;
  puStack_38 = (undefined4 *)0xffffffff;
  local_3c = 0x714c29;
  __vbaOnError();
  local_8 = 3;
  puStack_38 = &local_3c;
  local_3c = param_2;
  local_40 = param_1[0xd];
  iVar1 = (**(code **)(*(int *)param_1[0xd] + 0x1c))();
  if (iVar1 < 0) {
    __vbaHresultCheckObj(0x1c,param_1[0xd],&DAT_00447b68,0x1c);
  }
  uVar2 = __vbaCastObjVar(&local_3c,&DAT_0047276c);
  __vbaObjSet(&stack0xffffffd8,uVar2);
  __vbaFreeVar();
  local_8 = 4;
  uVar2 = rtcErrObj();
  __vbaObjSet(&stack0xffffffd4,uVar2);
  piVar4 = &local_40;
  iVar1 = (**(code **)(local_40 + 0x1c))(piVar4);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar4,&DAT_00443540,0x1c);
  }
  sVar3 = 0x4d0b;
  __vbaFreeObj();
  if (sVar3 != 0) {
    local_8 = 5;
    uVar2 = __vbaCastObj(0,&DAT_0047276c);
    __vbaObjSet(&stack0xffffffd8,uVar2);
  }
  return;
}


// ---- Count_Get @ 00714d90

undefined4 BBIMSessions::Count_Get(int *param_1,undefined4 *param_2)

{
  int iVar1;
  undefined4 local_20;
  undefined4 local_1c;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00412856;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_004113b8;
  local_8 = 0;
  ExceptionList = &local_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_20 = 0;
  local_1c = 0;
  iVar1 = (**(code **)(*(int *)param_1[0xd] + 0x24))((int *)param_1[0xd],&local_20);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xd],&DAT_00447b68,0x24);
  }
  local_1c = local_20;
  (**(code **)(*param_1 + 8))(param_1);
  *param_2 = local_1c;
  ExceptionList = local_18;
  return local_8;
}


// ---- Remove @ 00714e20

undefined4 BBIMSessions::Remove(int *param_1,undefined4 param_2)

{
  int iVar1;
  void *local_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined1 *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  local_24 = ExceptionList;
  ExceptionList = &local_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &LAB_004113c0;
  local_14 = 0;
  local_10 = 0;
  (**(code **)(*param_1 + 4))(param_1);
  local_8 = 2;
  __vbaOnError(0xffffffff);
  local_8 = 3;
  iVar1 = (**(code **)(*(int *)param_1[0xd] + 0x28))(param_1[0xd],param_2);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xd],&DAT_00447b68,0x28);
  }
  (**(code **)(*param_1 + 8))(param_1);
  ExceptionList = local_24;
  return local_14;
}


// ---- NewEnum_Get @ 00714ef0

void BBIMSessions::NewEnum_Get(int *param_1,undefined4 *param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_004113f0;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  local_20 = 0;
  *param_2 = 0;
  iVar1 = (**(code **)(*(int *)param_1[0xd] + 0x2c))((int *)param_1[0xd],&local_20);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xd],&DAT_00447b68,0x2c);
  }
  uVar2 = __vbaCastObj(local_20,&DAT_00447558);
  __vbaObjSet(&local_1c,uVar2);
  __vbaFreeObj();
  return;
}


// ---- Public_5 @ 00714fd0

void BBIMSessions::Public_5(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00411400;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  uVar1 = __vbaNew(&DAT_00447b78);
  uVar1 = __vbaObjSet(&local_1c,uVar1);
  __vbaObjSetAddref(piVar2 + 0xd,uVar1);
  __vbaFreeObj();
  return;
}


// ---- Public_6 @ 00715080

void BBIMSessions::Public_6(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00411410;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  uVar1 = __vbaCastObj(0,&DAT_00447b68);
  uVar1 = __vbaObjSet(&local_1c,uVar1);
  __vbaObjSetAddref(piVar2 + 0xd,uVar1);
  __vbaFreeObj();
  return;
}


