// BonziBDY_4.EXE :: clsBonziEventTap
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 8

// ---- Tap_Get @ 007283e0

void clsBonziEventTap::Tap_Get(int *param_1,undefined4 *param_2)

{
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00412168;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  *param_2 = 0;
  __vbaObjSetAddref(&local_1c,param_1[0xd]);
  return;
}


// ---- Tap_Set @ 00728470

undefined4 clsBonziEventTap::Tap_Set(int *param_1,undefined4 *param_2)

{
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00412856;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00412178;
  local_8 = 0;
  ExceptionList = &local_18;
  (**(code **)(*param_1 + 4))(param_1);
  __vbaObjSetAddref(param_1 + 0xd,*param_2);
  (**(code **)(*param_1 + 0x30))(param_1);
  (**(code **)(*param_1 + 0x34))(param_1);
  (**(code **)(*param_1 + 8))(param_1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Public_5 @ 007284f0

void clsBonziEventTap::Public_5(int *param_1)

{
  int *piVar1;
  int *piVar2;
  short sVar3;
  int iVar4;
  undefined4 uVar5;
  undefined4 local_68 [2];
  wchar_t *local_60;
  undefined4 local_58;
  undefined4 local_48 [4];
  undefined4 local_38 [2];
  undefined4 local_30;
  undefined4 local_28;
  int *local_24;
  int *local_20;
  undefined4 local_1c;
  int *local_18;
  void *pvStack_14;
  undefined1 *puStack_10;
  undefined1 *local_c;
  undefined *local_8;
  
  puStack_10 = &LAB_00412856;
  pvStack_14 = ExceptionList;
  local_c = &stack0xffffff70;
  local_8 = &DAT_00412180;
  local_18 = (int *)0x0;
  local_1c = 0;
  local_20 = (int *)0x0;
  local_24 = (int *)0x0;
  local_28 = 0;
  local_38[0] = 0;
  local_48[0] = 0;
  local_58 = 0;
  local_68[0] = 0;
  ExceptionList = &pvStack_14;
  iVar4 = (**(code **)(*param_1 + 0x1c))(param_1,&local_20);
  if (iVar4 < 0) {
    __vbaHresultCheckObj(iVar4,param_1,&DAT_0047639c,0x1c);
  }
  sVar3 = __vbaObjIs(local_20,0);
  __vbaFreeObj();
  if (sVar3 != -1) {
    iVar4 = (**(code **)(*param_1 + 0x1c))(param_1,&local_20);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,param_1,&DAT_0047639c,0x1c);
    }
    piVar1 = local_20;
    iVar4 = (**(code **)(*local_20 + 0x30))(local_20,&local_24);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,piVar1,&DAT_00475d6c,0x30);
    }
    sVar3 = __vbaObjIs(local_24,0);
    __vbaFreeObjList(2,&local_20,&local_24);
    if (sVar3 != 0) {
      iVar4 = (**(code **)(*param_1 + 0x1c))(param_1,&local_20);
      if (iVar4 < 0) {
        __vbaHresultCheckObj(iVar4,param_1,&DAT_0047639c,0x1c);
      }
      piVar1 = local_20;
      iVar4 = (**(code **)(*local_20 + 0x38))(local_20,&local_24);
      if (iVar4 < 0) {
        __vbaHresultCheckObj(iVar4,piVar1,&DAT_00475d6c,0x38);
      }
      uVar5 = __vbaCastObj(local_24,&DAT_0047599c);
      __vbaObjSet(&local_18,uVar5);
      __vbaFreeObjList(2,&local_20,&local_24);
      while (sVar3 = __vbaObjIs(local_18,0), sVar3 == 0) {
        iVar4 = (**(code **)(*local_18 + 0x20))(local_18,&local_1c);
        if (iVar4 < 0) {
          __vbaHresultCheckObj(iVar4,local_18,&DAT_0047599c,0x20);
        }
        local_30 = local_1c;
        local_1c = 0;
        local_38[0] = 8;
        rtcLowerCaseVar(local_48,local_38);
        local_60 = L"main";
        local_68[0] = 0x8008;
        sVar3 = __vbaVarTstEq(local_68,local_48);
        __vbaFreeVarList(2,local_38,local_48);
        if (sVar3 != 0) {
          iVar4 = (**(code **)(*param_1 + 0x1c))(param_1,&local_24);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,param_1,&DAT_0047639c,0x1c);
          }
          piVar1 = local_24;
          iVar4 = (**(code **)(*local_18 + 0x30))(local_18,&local_20);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,local_18,&DAT_0047599c,0x30);
          }
          piVar2 = local_20;
          local_20 = (int *)0x0;
          __vbaObjSet(&local_28,piVar2);
          iVar4 = (**(code **)(*piVar1 + 0x34))(piVar1,&local_28);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar1,&DAT_00475d6c,0x34);
          }
          __vbaFreeObjList(2,&local_28,&local_24);
        }
        iVar4 = (**(code **)(*local_18 + 0x28))(local_18,&local_20);
        if (iVar4 < 0) {
          __vbaHresultCheckObj(iVar4,local_18,&DAT_0047599c,0x28);
        }
        uVar5 = __vbaCastObj(local_20,&DAT_0047599c);
        __vbaObjSet(&local_18,uVar5);
        __vbaFreeObj();
      }
    }
  }
  __vbaFreeObj(&LAB_007287ee);
  return;
}


// ---- Public_6 @ 00728810

void clsBonziEventTap::Public_6(int *param_1)

{
  short *psVar1;
  int *piVar2;
  short sVar3;
  int iVar4;
  uint uVar5;
  int **ppiVar6;
  undefined4 local_1c;
  int *local_18;
  void *pvStack_14;
  undefined1 *puStack_10;
  undefined1 *local_c;
  undefined *local_8;
  
  puStack_10 = &LAB_00412856;
  pvStack_14 = ExceptionList;
  local_c = &stack0xffffffc4;
  local_8 = &DAT_00412190;
  local_18 = (int *)0x0;
  local_1c = 0;
  ExceptionList = &pvStack_14;
  iVar4 = (**(code **)(*param_1 + 0x1c))(param_1,&local_18);
  if (iVar4 < 0) {
    __vbaHresultCheckObj(iVar4,param_1,&DAT_0047639c,0x1c);
  }
  sVar3 = __vbaObjIs(local_18,0);
  __vbaFreeObj();
  if (sVar3 != -1) {
    __vbaRedim(0x440,4,param_1 + 0xe,&DAT_004757e8,1,1,1);
    ppiVar6 = &local_18;
    *(undefined2 *)(param_1 + 0xf) = 1;
    iVar4 = (**(code **)(*param_1 + 0x1c))(param_1,ppiVar6);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,param_1,&DAT_0047639c,0x1c);
    }
    piVar2 = local_18;
    iVar4 = (**(code **)(*local_18 + 0x30))(local_18,&local_1c);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,piVar2,&DAT_00475d6c,0x30);
    }
    psVar1 = (short *)param_1[0xe];
    if ((psVar1 == (short *)0x0) || (*psVar1 != 1)) {
      iVar4 = __vbaGenerateBoundsError(ppiVar6);
    }
    else {
      uVar5 = (int)(short)param_1[0xf] - *(int *)(psVar1 + 10);
      if (*(uint *)(psVar1 + 8) <= uVar5) {
        __vbaGenerateBoundsError(ppiVar6);
      }
      iVar4 = uVar5 * 4;
    }
    __vbaObjSetAddref(*(int *)(param_1[0xe] + 0xc) + iVar4,local_1c);
    __vbaFreeObjList(2,&local_18,&local_1c);
  }
  return;
}


// ---- RunEvent @ 00728a60

/* WARNING: Removing unreachable block (ram,0x0072bb00) */
/* WARNING: Removing unreachable block (ram,0x0072bb2a) */
/* WARNING: Removing unreachable block (ram,0x0072bb1e) */
/* WARNING: Removing unreachable block (ram,0x0072bb36) */
/* WARNING: Restarted to delay deadcode elimination for space: ram */
/* WARNING: Restarted to delay deadcode elimination for space: stack */

void clsBonziEventTap::RunEvent(int *********param_1)

{
  short sVar1;
  undefined2 uVar2;
  short sVar3;
  int iVar4;
  int ********ppppppppiVar5;
  int *unaff_EBX;
  int ********ppppppppiVar6;
  int local_3b8;
  int local_3a8;
  int local_394;
  int local_2c8;
  int local_2a4;
  int local_26c;
  int ******local_158 [5];
  int local_144;
  int *******local_140;
  int *******local_13c;
  int *******local_138;
  int *******local_134;
  int ********local_130;
  int *******local_12c;
  int ********local_128;
  int ********local_124;
  int ********local_120;
  int ********local_11c;
  int ********local_118;
  int ********local_114;
  undefined4 local_110;
  undefined2 local_10c;
  ushort local_108;
  int ******local_f4;
  int *******local_f0;
  wchar_t *local_ec;
  undefined4 local_e8;
  int ******local_e4 [2];
  undefined4 local_dc;
  undefined4 local_d4;
  undefined4 local_cc;
  int *******local_c4 [2];
  int *******local_bc;
  int *******local_b4;
  undefined4 local_b0;
  int *******local_ac;
  undefined *local_a8;
  int *******local_a4;
  int *******local_a0;
  int ********local_9c;
  int ********local_98 [2];
  int *******local_90;
  int *******local_8c;
  int ********local_88;
  int *******local_84;
  int ********local_80;
  int ********local_7c;
  int ********local_78;
  int ********local_74;
  int ********local_70;
  int ********local_6c;
  int ********local_68;
  int ********local_64;
  int *********in_stack_ffffffa0;
  int *********in_stack_ffffffa8;
  int ********ppppppppiStack_48;
  int *********in_stack_ffffffbc;
  int ********local_40;
  int ********local_3c;
  short sVar7;
  int ******ppppppiVar8;
  int *********pppppppppiVar9;
  int ********ppppppppiStack_24;
  int ********ppppppppiStack_20;
  int ********local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  ppppppppiStack_20 = (int ********)&LAB_00412856;
  ppppppppiStack_24 = ExceptionList;
  ExceptionList = &ppppppppiStack_24;
  __vbaChkstk();
  local_1c = (int ********)&stack0xffffffd0;
  local_18 = &DAT_004121a0;
  local_14 = 0;
  local_10 = 0;
  (*(code *)(*param_1)[1])();
  local_8 = 2;
  local_3c = (int ********)0x728ac0;
  __vbaOnError();
  local_8 = 3;
  if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
    __vbaGenerateBoundsError();
  }
  else {
    local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
    if (param_1[0xe][4] <= local_114) {
      __vbaGenerateBoundsError();
    }
  }
  local_3c = (int ********)0x728b53;
  sVar1 = __vbaObjIs();
  if (sVar1 == 0) {
    local_8 = 0x16;
    local_3c = (int ********)0x729beb;
    __vbaAryLock();
    if (((int *********)local_80 == (int *********)0x0) || (*(short *)local_80 != 1)) {
      local_26c = __vbaGenerateBoundsError();
    }
    else {
      local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)local_80[5]);
      if (local_80[4] <= local_114) {
        __vbaGenerateBoundsError();
      }
      local_26c = (int)local_114 << 2;
    }
    local_ec = (wchar_t *)((int)local_80[3] + local_26c);
    local_f4 = (int ******)0x4009;
    rtcTypeName();
    __vbaStrMove();
    __vbaAryUnlock();
    local_84 = (int *******)0x0;
    __vbaStrMove();
    local_8 = 0x17;
    iVar4 = __vbaStrCmp();
    if (iVar4 == 0) {
      local_8 = 0x18;
      if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
        __vbaGenerateBoundsError();
      }
      else {
        local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
        if (param_1[0xe][4] <= local_114) {
          __vbaGenerateBoundsError();
        }
      }
      __vbaCastObj();
      __vbaObjSet();
      local_8 = 0x19;
      local_114 = (int ********)(*(code *)(*local_3c)[0xc])();
      if ((int)local_114 < 0) {
        local_40 = local_114;
        __vbaHresultCheckObj();
      }
      local_ac = local_84;
      local_84 = (int *******)0x0;
      local_b4 = (int *******)0x8;
      local_3c = (int ********)0x729dfe;
      rtcTrimVar();
      local_3c = (int ********)0x729e12;
      __vbaStrVarVal();
      iVar4 = (int)*local_3c;
      local_3c = (int ********)0x729e1f;
      local_118 = (int ********)(**(code **)(iVar4 + 0x34))();
      if ((int)local_118 < 0) {
        local_3c = (int ********)0x34;
        local_40 = (int ********)&DAT_004764a0;
        ppppppppiStack_48 = local_118;
        __vbaHresultCheckObj();
      }
      local_3c = (int ********)0x729e66;
      __vbaFreeStr();
      local_3c = local_c4;
      local_40 = &local_b4;
      ppppppppiStack_48 = (int ********)0x729e7c;
      __vbaFreeVarList();
      local_8 = 0x1a;
      local_40 = &local_84;
      local_3c = local_40;
      local_114 = (int ********)(*(code *)local_84[0xc])();
      if ((int)local_114 < 0) {
        ppppppppiStack_48 = (int ********)&DAT_004764a0;
        __vbaHresultCheckObj();
      }
      local_ac = local_84;
      local_84 = (int *******)0x0;
      local_b4 = (int *******)0x8;
      ppppppppiStack_48 = local_c4;
      rtcLowerCaseVar();
      local_ec = L"true";
      local_f4 = (int ******)0x8008;
      ppppppppiStack_48 = (int ********)&local_f4;
      uVar2 = __vbaVarTstNe();
      local_118 = (int ********)CONCAT22(local_118._2_2_,uVar2);
      ppppppppiStack_48 = &local_b4;
      __vbaFreeVarList();
      if ((short)local_118 != 0) {
        local_8 = 0x1b;
        ppppppppiStack_48 = local_3c;
        local_114 = (int ********)(*(code *)(*local_3c)[0xd])();
        if ((int)local_114 < 0) {
          ppppppppiStack_48 = (int ********)&DAT_004764a0;
          __vbaHresultCheckObj();
        }
      }
      local_8 = 0x1d;
      ppppppppiStack_48 = local_3c;
      local_114 = (int ********)(*(code *)(*local_3c)[8])();
      if ((int)local_114 < 0) {
        __vbaHresultCheckObj();
      }
      local_84 = (int *******)0x0;
      __vbaStrMove();
      local_8 = 0x1e;
      __vbaStrI2();
      __vbaStrMove();
      local_8 = 0x1f;
      local_114 = (int ********)(*(code *)(*local_3c)[10])();
      if ((int)local_114 < 0) {
        local_64 = (int ********)0x72a080;
        __vbaHresultCheckObj();
      }
      local_118 = (int ********)(*(code *)(*local_3c)[0xc])();
      if ((int)local_118 < 0) {
        local_64 = local_3c;
        local_6c = (int ********)0x72a0ce;
        local_68 = local_118;
        __vbaHresultCheckObj();
      }
      if (DAT_0073a254 == (int ******)0x0) {
        local_64 = (int ********)0x72a0f9;
        __vbaNew2();
      }
      local_11c = (int ********)DAT_0073a254;
      local_10c = 0;
      local_108 = __vbaBoolStr();
      local_108 = ~local_108;
      local_84 = (int *******)0x0;
      __vbaStrMove();
      local_64 = &local_8c;
      local_68 = local_11c;
      local_6c = (int ********)0x72a189;
      local_120 = (int ********)(*(code *)(*local_11c)[0x1d0])();
      if ((int)local_120 < 0) {
        local_6c = (int ********)0x740;
        local_70 = (int ********)&DAT_004408d0;
        local_74 = local_11c;
        local_7c = (int ********)0x72a1b8;
        local_78 = local_120;
        __vbaHresultCheckObj();
      }
      local_6c = &local_8c;
      local_70 = (int ********)&local_88;
      local_74 = (int ********)0x2;
      local_78 = (int ********)0x72a1e0;
      __vbaFreeStrList();
      local_8 = 0x20;
      local_6c = (int ********)local_98;
      local_70 = local_3c;
      local_74 = (int ********)0x72a1fd;
      local_118 = (int ********)(*(code *)(*local_3c)[0xe])();
      if ((int)local_118 < 0) {
        local_74 = (int ********)0x38;
        local_78 = (int ********)&DAT_004764a0;
        local_7c = local_3c;
        local_84 = (int *******)0x72a226;
        local_80 = local_118;
        __vbaHresultCheckObj();
      }
      if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
        local_74 = (int ********)0x72a2a3;
        local_2a4 = __vbaGenerateBoundsError();
      }
      else {
        local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
        if (param_1[0xe][4] <= local_114) {
          local_74 = (int ********)0x72a286;
          __vbaGenerateBoundsError();
        }
        local_2a4 = (int)local_114 << 2;
      }
      local_70 = local_98[0];
      local_74 = (int ********)((int)param_1[0xe][3] + local_2a4);
      local_78 = (int ********)0x72a2c6;
      __vbaObjSetAddref();
      local_70 = (int ********)0x72a2d2;
      __vbaFreeObj();
      local_8 = 0x21;
      local_70 = (int ********)param_1;
      local_74 = (int ********)0x72a2e5;
      local_114 = (int ********)(*(code *)(*param_1)[9])();
      if ((int)local_114 < 0) {
        local_40 = (int ********)0x72a30c;
        local_3c = local_114;
        __vbaHresultCheckObj();
      }
    }
    else {
      local_8 = 0x22;
      iVar4 = __vbaStrCmp();
      if (iVar4 == 0) {
        local_8 = 0x23;
        if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
          __vbaGenerateBoundsError();
        }
        else {
          local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
          if (param_1[0xe][4] <= local_114) {
            __vbaGenerateBoundsError();
          }
        }
        __vbaCastObj();
        __vbaObjSet();
        local_8 = 0x24;
        local_ec = (wchar_t *)0x4;
        local_f4 = (int ******)0x3;
        if (DAT_0073a254 == (int ******)0x0) {
          __vbaNew2();
        }
        __vbaChkstk();
        ppppppppiStack_24 = (int ********)local_f0;
        ppppppppiStack_20 = (int ********)local_ec;
        local_1c = (int ********)local_e8;
        (*(code *)(*DAT_0073a254)[300])();
        local_3c = (int ********)0x72a487;
        __vbaObjSet();
        __vbaLateIdSt();
        ppppppppiStack_20 = (int ********)0x72a49a;
        __vbaFreeObj();
        local_8 = 0x25;
        ppppppppiStack_20 = &local_84;
        ppppppppiStack_24 = local_70;
        local_114 = (int ********)(*(code *)(*local_70)[8])();
        if ((int)local_114 < 0) {
          __vbaHresultCheckObj();
        }
        local_ac = local_84;
        local_84 = (int *******)0x0;
        local_b4 = (int *******)0x8;
        if (DAT_0073a254 == (int ******)0x0) {
          __vbaNew2();
        }
        __vbaChkstk();
        ppppppppiStack_24 = (int ********)local_b4;
        ppppppppiStack_20 = (int ********)local_b0;
        local_1c = (int ********)local_ac;
        local_18 = local_a8;
        (*(code *)(*DAT_0073a254)[300])();
        local_3c = (int ********)0x72a59b;
        __vbaObjSet();
        __vbaLateIdCall();
        local_1c = (int ********)0x72a5b1;
        __vbaFreeObj();
        local_1c = (int ********)0x72a5bd;
        __vbaFreeVar();
        local_8 = 0x26;
        local_1c = (int ********)local_98;
        ppppppppiStack_20 = local_70;
        ppppppppiStack_24 = (int ********)0x72a5d7;
        local_118 = (int ********)(*(code *)(*local_70)[10])();
        if ((int)local_118 < 0) {
          ppppppppiStack_24 = (int ********)0x28;
          __vbaHresultCheckObj();
        }
        if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
          ppppppppiStack_24 = (int ********)0x72a67d;
          local_2c8 = __vbaGenerateBoundsError();
        }
        else {
          local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
          if (param_1[0xe][4] <= local_114) {
            ppppppppiStack_24 = (int ********)0x72a660;
            __vbaGenerateBoundsError();
          }
          local_2c8 = (int)local_114 << 2;
        }
        ppppppppiStack_20 = local_98[0];
        ppppppppiStack_24 = (int ********)((int)param_1[0xe][3] + local_2c8);
        __vbaObjSetAddref();
        ppppppppiStack_20 = (int ********)0x72a6ac;
        __vbaFreeObj();
        local_8 = 0x27;
        ppppppppiStack_20 = (int ********)param_1;
        ppppppppiStack_24 = (int ********)0x72a6bf;
        local_114 = (int ********)(*(code *)(*param_1)[9])();
        if ((int)local_114 < 0) {
          local_40 = (int ********)0x72a6e6;
          local_3c = local_114;
          __vbaHresultCheckObj();
        }
      }
      else {
        local_8 = 0x28;
        iVar4 = __vbaStrCmp();
        if (iVar4 == 0) {
          local_8 = 0x29;
          if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
            __vbaGenerateBoundsError();
          }
          else {
            local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
            if (param_1[0xe][4] <= local_114) {
              __vbaGenerateBoundsError();
            }
          }
          __vbaCastObj();
          __vbaObjSet();
          local_8 = 0x2a;
          local_118 = (int ********)(*(code *)(*local_40)[0x14])();
          if ((int)local_118 < 0) {
            local_3c = local_40;
            local_40 = local_118;
            __vbaHresultCheckObj();
          }
          if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
            __vbaGenerateBoundsError();
          }
          else {
            local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
            if (param_1[0xe][4] <= local_114) {
              __vbaGenerateBoundsError();
            }
          }
          __vbaObjSetAddref();
          __vbaFreeObj();
          local_8 = 0x2b;
          local_114 = (int ********)(*(code *)(*local_40)[8])();
          if ((int)local_114 < 0) {
            local_3c = (int ********)&DAT_00476514;
            ppppppppiStack_48 = (int ********)0x72a8ee;
            __vbaHresultCheckObj();
          }
          local_3c = (int ********)0xffffffff;
          local_40 = (int ********)0x1;
          ppppppppiStack_48 = (int ********)0x443b44;
          rtcReplace();
          __vbaStrMove();
          ppppppppiVar6 = (int ********)*local_40;
          local_3c = local_40;
          local_40 = (int ********)0x72a93d;
          local_118 = (int ********)(*(code *)ppppppppiVar6[10])();
          if ((int)local_118 < 0) {
            local_40 = (int ********)0x28;
            ppppppppiStack_48 = (int ********)0x28;
            __vbaHresultCheckObj();
          }
          local_bc = (int *******)local_88;
          local_ac = local_8c;
          local_dc = 0x80020004;
          local_e4[0] = (int ******)0xa;
          local_cc = 0x80020004;
          local_d4 = 10;
          local_88 = (int ********)0x0;
          local_c4[0] = (int *******)0x8;
          local_8c = (int *******)0x0;
          local_b4 = (int *******)0x8;
          local_40 = (int ********)local_e4;
          ppppppppiStack_48 = local_c4;
          iVar4 = rtcMsgBox();
          local_11c = (int ********)CONCAT22(local_11c._2_2_,-(ushort)(iVar4 == 6));
          local_40 = &local_8c;
          ppppppppiStack_48 = (int ********)0x2;
          __vbaFreeStrList();
          local_40 = (int ********)local_e4;
          ppppppppiStack_48 = local_c4;
          __vbaFreeVarList();
          if ((short)local_11c == 0) {
            local_8 = 0x2e;
            local_40 = (int ********)local_98;
            ppppppppiStack_48 = (int ********)0x72ab39;
            local_114 = (int ********)(*(code *)local_98[0][0x12])();
            if ((int)local_114 < 0) {
              ppppppppiStack_48 = (int ********)0x48;
              __vbaHresultCheckObj();
            }
            ppppppppiStack_48 = local_98[0];
            local_98[0] = (int ********)0x0;
            __vbaObjSet();
            ppppppppiStack_48 = (int ********)&local_9c;
            (*(code *)(*param_1)[0xf])();
            __vbaFreeObj();
          }
          else {
            local_8 = 0x2c;
            local_40 = (int ********)local_98;
            ppppppppiStack_48 = (int ********)0x72aa96;
            local_114 = (int ********)(*(code *)local_98[0][0x10])();
            if ((int)local_114 < 0) {
              ppppppppiStack_48 = (int ********)0x40;
              __vbaHresultCheckObj();
            }
            ppppppppiStack_48 = local_98[0];
            local_98[0] = (int ********)0x0;
            __vbaObjSet();
            ppppppppiStack_48 = (int ********)&local_9c;
            (*(code *)(*param_1)[0xf])();
            __vbaFreeObj();
          }
          local_8 = 0x30;
          local_114 = (int ********)(*(code *)(*param_1)[9])();
          if ((int)local_114 < 0) {
            local_40 = (int ********)0x72abf7;
            local_3c = local_114;
            __vbaHresultCheckObj();
          }
        }
        else {
          local_8 = 0x31;
          iVar4 = __vbaStrCmp();
          if (iVar4 == 0) {
            local_8 = 0x32;
            if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
              __vbaGenerateBoundsError();
            }
            else {
              local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
              if (param_1[0xe][4] <= local_114) {
                __vbaGenerateBoundsError();
              }
            }
            __vbaCastObj();
            __vbaObjSet();
            local_8 = 0x33;
            local_118 = (int ********)(*(code *)(*local_7c)[8])();
            if ((int)local_118 < 0) {
              local_3c = local_7c;
              local_40 = local_118;
              __vbaHresultCheckObj();
            }
            if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
              __vbaGenerateBoundsError();
            }
            else {
              local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
              if (param_1[0xe][4] <= local_114) {
                __vbaGenerateBoundsError();
              }
            }
            __vbaObjSetAddref();
            __vbaFreeObj();
            local_8 = 0x34;
            local_114 = (int ********)(*(code *)(*param_1)[9])();
            if ((int)local_114 < 0) {
              local_40 = (int ********)0x72adf9;
              local_3c = local_114;
              __vbaHresultCheckObj();
            }
          }
          else {
            local_8 = 0x35;
            iVar4 = __vbaStrCmp();
            if (iVar4 == 0) {
              local_8 = 0x36;
              if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                __vbaGenerateBoundsError();
              }
              else {
                local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                if (param_1[0xe][4] <= local_114) {
                  __vbaGenerateBoundsError();
                }
              }
              __vbaCastObj();
              __vbaObjSet();
              local_8 = 0x37;
              local_118 = (int ********)(*(code *)(*in_stack_ffffffbc)[8])();
              if ((int)local_118 < 0) {
                local_40 = local_118;
                local_3c = (int ********)in_stack_ffffffbc;
                __vbaHresultCheckObj();
              }
              if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                __vbaGenerateBoundsError();
              }
              else {
                local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                if (param_1[0xe][4] <= local_114) {
                  __vbaGenerateBoundsError();
                }
              }
              __vbaObjSetAddref();
              __vbaFreeObj();
              local_8 = 0x38;
              local_114 = (int ********)(*(code *)(*param_1)[9])();
              if ((int)local_114 < 0) {
                local_40 = (int ********)0x72affb;
                local_3c = local_114;
                __vbaHresultCheckObj();
              }
            }
            else {
              local_8 = 0x39;
              iVar4 = __vbaStrCmp();
              if (iVar4 == 0) {
                local_8 = 0x3a;
                if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                  __vbaGenerateBoundsError();
                }
                else {
                  local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                  if (param_1[0xe][4] <= local_114) {
                    __vbaGenerateBoundsError();
                  }
                }
                __vbaCastObj();
                __vbaObjSet();
                local_8 = 0x3b;
                pppppppppiVar9 = local_98;
                local_114 = (int ********)(*(code *)(*param_1)[7])();
                if ((int)local_114 < 0) {
                  local_3c = (int ********)param_1;
                  local_40 = local_114;
                  __vbaHresultCheckObj();
                }
                local_118 = local_98[0];
                local_3c = (int ********)0x72b149;
                local_11c = (int ********)(*(code *)(*local_98[0])[0x10])();
                if ((int)local_11c < 0) {
                  local_3c = (int ********)0x40;
                  local_40 = (int ********)&DAT_00475d6c;
                  ppppppppiStack_48 = local_11c;
                  __vbaHresultCheckObj();
                }
                local_3c = (int ********)0x1;
                local_40 = (int ********)local_84;
                ppppppppiStack_48 = (int ********)0x1;
                iVar4 = __vbaInStr();
                local_120 = (int ********)CONCAT22(local_120._2_2_,-(ushort)(iVar4 != 0));
                local_3c = (int ********)0x72b1b2;
                __vbaFreeStr();
                local_3c = (int ********)0x72b1be;
                __vbaFreeObj();
                if ((short)local_120 == 0) {
                  local_8 = 0x3f;
                  local_108 = 0;
                  local_3c = &local_84;
                  local_40 = (int ********)pppppppppiVar9;
                  local_114 = (int ********)(*(code *)local_98[0][8])();
                  if ((int)local_114 < 0) {
                    local_40 = local_114;
                    local_3c = (int ********)pppppppppiVar9;
                    __vbaHresultCheckObj();
                  }
                  local_84 = (int *******)0x0;
                  __vbaStrMove();
                  if (DAT_0073a254 == (int ******)0x0) {
                    local_3c = (int ********)0x72b40d;
                    __vbaNew2();
                  }
                  local_3c = (int ********)0x0;
                  local_40 = (int ********)0x0;
                  ppppppppiStack_48 = (int ********)DAT_0073a254;
                  frmAgent::Public_67();
                  __vbaFreeStr();
                }
                else {
                  local_8 = 0x3c;
                  local_ec = L"";
                  local_f4 = (int ******)0x8;
                  local_3c = (int ********)0x72b1f2;
                  __vbaChkstk();
                  local_3c = (int ********)0x44a160;
                  local_40 = (int ********)0x44317c;
                  ppppppppiStack_48 = (int ********)0x72b22c;
                  local_ac = (int *******)rtcGetSetting();
                  local_b4 = (int *******)0x8;
                  __vbaVarMove();
                  local_8 = 0x3d;
                  local_108 = 0;
                  pppppppppiVar9 = (int *********)&local_84;
                  local_114 = (int ********)(*(code *)local_84[8])();
                  if ((int)local_114 < 0) {
                    local_40 = local_114;
                    local_3c = (int ********)pppppppppiVar9;
                    __vbaHresultCheckObj();
                  }
                  local_3c = (int ********)0x72b2b5;
                  local_ac = (int *******)__vbaStrCat();
                  local_b4 = (int *******)0x8;
                  local_3c = local_c4;
                  local_40 = (int ********)0x72b2dd;
                  __vbaVarCat();
                  __vbaStrVarMove();
                  __vbaStrMove();
                  if (DAT_0073a254 == (int ******)0x0) {
                    local_3c = (int ********)0x72b30b;
                    __vbaNew2();
                  }
                  local_3c = (int ********)0x0;
                  local_40 = (int ********)0x0;
                  ppppppppiStack_48 = (int ********)DAT_0073a254;
                  frmAgent::Public_67();
                  __vbaFreeStrList();
                  __vbaFreeVarList();
                }
                local_8 = 0x41;
                local_118 = (int ********)(*(code *)(*pppppppppiVar9)[10])();
                if ((int)local_118 < 0) {
                  local_64 = (int ********)0x72b494;
                  __vbaHresultCheckObj();
                }
                if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                  __vbaGenerateBoundsError();
                }
                else {
                  local_114 = (int ********)((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                  if (param_1[0xe][4] <= local_114) {
                    __vbaGenerateBoundsError();
                  }
                }
                __vbaObjSetAddref();
                __vbaFreeObj();
                local_8 = 0x42;
                local_114 = (int ********)(*(code *)(*param_1)[9])();
                if ((int)local_114 < 0) {
                  local_40 = (int ********)0x72b57a;
                  local_3c = local_114;
                  __vbaHresultCheckObj();
                }
              }
              else {
                local_8 = 0x43;
                iVar4 = __vbaStrCmp();
                if (iVar4 == 0) {
                  local_8 = 0x44;
                  if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                    __vbaGenerateBoundsError();
                  }
                  else {
                    local_114 = (int ********)
                                ((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                    if (param_1[0xe][4] <= local_114) {
                      __vbaGenerateBoundsError();
                    }
                  }
                  __vbaCastObj();
                  __vbaObjSet();
                  local_8 = 0x45;
                  if (DAT_0073a254 == (int ******)0x0) {
                    __vbaNew2();
                  }
                  local_118 = (int ********)DAT_0073a254;
                  local_114 = (int ********)(*(code *)(*in_stack_ffffffa8)[8])();
                  if ((int)local_114 < 0) {
                    local_40 = local_114;
                    local_3c = (int ********)in_stack_ffffffa8;
                    __vbaHresultCheckObj();
                  }
                  local_84 = (int *******)0x0;
                  __vbaStrMove();
                  local_3c = (int ********)0x72b720;
                  local_11c = (int ********)(*(code *)(*local_118)[0x1c6])();
                  if ((int)local_11c < 0) {
                    local_3c = (int ********)0x718;
                    local_40 = (int ********)&DAT_004408d0;
                    ppppppppiStack_48 = local_11c;
                    __vbaHresultCheckObj();
                  }
                  local_3c = (int ********)0x72b76d;
                  __vbaFreeStr();
                  local_8 = 0x46;
                  local_3c = (int ********)local_98;
                  local_118 = (int ********)(*(code *)(*in_stack_ffffffa8)[10])();
                  if ((int)local_118 < 0) {
                    ppppppppiStack_48 = (int ********)&DAT_00476614;
                    __vbaHresultCheckObj();
                  }
                  if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                    __vbaGenerateBoundsError();
                  }
                  else {
                    local_114 = (int ********)
                                ((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                    if (param_1[0xe][4] <= local_114) {
                      __vbaGenerateBoundsError();
                    }
                  }
                  local_40 = local_98[0];
                  ppppppppiStack_48 = (int ********)0x72b850;
                  __vbaObjSetAddref();
                  local_40 = (int ********)0x72b85c;
                  __vbaFreeObj();
                  local_8 = 0x47;
                  local_40 = (int ********)param_1;
                  local_114 = (int ********)(*(code *)(*param_1)[9])();
                  if ((int)local_114 < 0) {
                    local_40 = (int ********)0x72b896;
                    local_3c = local_114;
                    __vbaHresultCheckObj();
                  }
                }
                else {
                  local_8 = 0x48;
                  iVar4 = __vbaStrCmp();
                  if (iVar4 == 0) {
                    local_8 = 0x49;
                    modAgent::Proc_621930();
                    local_8 = 0x4a;
                    if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                      __vbaGenerateBoundsError();
                    }
                    else {
                      local_114 = (int ********)
                                  ((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                      if (param_1[0xe][4] <= local_114) {
                        __vbaGenerateBoundsError();
                      }
                    }
                    __vbaCastObj();
                    __vbaObjSet();
                    local_8 = 0x4b;
                    local_114 = (int ********)(**(code **)(*unaff_EBX + 0x28))();
                    if ((int)local_114 < 0) {
                      local_3c = (int ********)0x72b9bb;
                      __vbaHresultCheckObj();
                    }
                    local_ec = L"|";
                    local_f4 = (int ******)0x8;
                    __vbaVarDup();
                    local_3c = local_c4;
                    local_40 = (int ********)0x72ba0f;
                    rtcSplit();
                    local_110 = __vbaAryVar();
                    __vbaAryCopy();
                    __vbaFreeStr();
                    __vbaFreeVarList();
                    local_8 = 0x4c;
                    __vbaUbound();
                    local_10c = __vbaI2I4();
                    __vbaLbound();
                    local_108 = __vbaI2I4();
                    uVar2 = modRandom::Proc_737f40();
                    local_68 = (int ********)CONCAT22(local_68._2_2_,uVar2);
                    if (*(short *)((int)param_1 + 0x3e) == 0) {
                      local_8 = 0x4e;
                      local_ec = L",";
                      local_f4 = (int ******)0x8;
                      __vbaVarDup();
                      iVar4 = __vbaGenerateBoundsError();
                      local_3c = *(int *********)(local_a8 + iVar4);
                      local_40 = local_c4;
                      rtcSplit();
                      local_110 = __vbaAryVar();
                      __vbaAryCopy();
                      local_3c = (int ********)0x72bbba;
                      __vbaFreeVarList();
                      local_8 = 0x4f;
                      __vbaUbound();
                      sVar1 = __vbaI2I4();
                      __vbaLbound();
                      sVar3 = __vbaI2I4();
                      while (sVar3 <= sVar1) {
                        local_8 = 0x50;
                        iVar4 = __vbaUbound();
                        if (sVar3 < iVar4) {
                          local_8 = 0x51;
                          __vbaAryLock();
                          if (((int *********)local_80 == (int *********)0x0) ||
                             (*(short *)local_80 != 1)) {
                            local_394 = __vbaGenerateBoundsError();
                          }
                          else {
                            local_114 = (int ********)((int)(short)&local_80 - (int)local_80[5]);
                            if (local_80[4] <= local_114) {
                              __vbaGenerateBoundsError();
                            }
                            local_394 = (int)local_114 << 2;
                          }
                          local_ec = (wchar_t *)((int)local_80[3] + local_394);
                          local_f4 = (int ******)0x4008;
                          rtcTrimVar();
                          __vbaAryUnlock();
                          __vbaStrVarVal();
                          ppppppiVar8 = DAT_0073a08c;
                          local_118 = (int ********)(*(code *)(*DAT_0073a08c)[0x19])();
                          if ((int)local_118 < 0) {
                            ppppppiVar8 = (int ******)&DAT_004419ac;
                            local_40 = (int ********)0x72bd4e;
                            local_3c = local_118;
                            __vbaHresultCheckObj();
                          }
                          sVar7 = (short)ppppppiVar8;
                          __vbaFreeStr();
                          __vbaFreeObj();
                          __vbaFreeVar();
                        }
                        else {
                          *(short *)((int)param_1 + 0x3e) = -1;
                          local_8 = 0x54;
                          if (DAT_0073a254 == (int ******)0x0) {
                            __vbaNew2();
                          }
                          local_114 = (int ********)DAT_0073a254;
                          local_118 = (int ********)(*(code *)(*DAT_0073a254)[0x1d3])();
                          if ((int)local_118 < 0) {
                            local_3c = local_114;
                            local_40 = local_118;
                            __vbaHresultCheckObj();
                          }
                          local_8 = 0x55;
                          __vbaOnError();
                          ppppppppiVar6 = local_74;
                          local_8 = 0x56;
                          local_3c = (int ********)0x72be54;
                          __vbaAryLock();
                          if (((int *********)local_80 == (int *********)0x0) ||
                             (*(short *)local_80 != 1)) {
                            local_3a8 = __vbaGenerateBoundsError();
                          }
                          else {
                            local_114 = (int ********)((int)(short)ppppppppiVar6 - (int)local_80[5])
                            ;
                            if (local_80[4] <= local_114) {
                              __vbaGenerateBoundsError();
                            }
                            local_3a8 = (int)local_114 << 2;
                          }
                          local_ec = (wchar_t *)((int)local_80[3] + local_3a8);
                          local_f4 = (int ******)0x4008;
                          rtcTrimVar();
                          __vbaAryUnlock();
                          local_3c = (int ********)0x72bf08;
                          __vbaStrVarVal();
                          local_3c = (int ********)0x72bf1a;
                          local_118 = (int ********)(*(code *)(*DAT_0073a08c)[0x19])();
                          if ((int)local_118 < 0) {
                            local_40 = (int ********)0x72bf45;
                            local_3c = local_118;
                            __vbaHresultCheckObj();
                          }
                          local_98[0] = (int ********)0x0;
                          __vbaObjSet();
                          __vbaFreeStr();
                          __vbaFreeVar();
                          local_8 = 0x57;
                          sVar7 = -0x405d;
                          __vbaOnError();
                        }
                        local_8 = 0x59;
                        sVar3 = sVar7 + 1;
                        if (SCARRY2(sVar7,1)) {
                          __vbaErrorOverflow();
                          ppppppppiVar6 = ppppppppiStack_24;
                          local_3c = (int ********)&LAB_00412856;
                          local_40 = ExceptionList;
                          local_64 = ppppppppiStack_24;
                          local_68 = (int ********)0x72ce27;
                          ExceptionList = &local_40;
                          (*(code *)(*ppppppppiStack_24)[1])();
                          local_6c = (int ********)&stack0xffffffbc;
                          local_68 = ppppppppiStack_20;
                          ppppppppiStack_48 = (int ********)0x0;
                          local_70 = (int ********)0x72ce3d;
                          __vbaObjSetAddref();
                          ppppppppiVar6 = ppppppppiVar6 + 0x11;
                          local_68 = (int ********)0x0;
                          local_70 = (int ********)0x72ce47;
                          local_6c = ppppppppiVar6;
                          __vbaObjSetAddref();
                          local_6c = (int ********)*ppppppppiVar6;
                          local_68 = (int ********)0x0;
                          local_70 = (int ********)0x72ce51;
                          sVar1 = __vbaObjIs();
                          if (sVar1 == 0) {
                            local_6c = (int ********)*ppppppppiVar6;
                            local_68 = (int ********)&ppppppppiStack_48;
                            ppppppppiStack_48 = (int ********)0x0;
                            local_70 = (int ********)0x72ce65;
                            ppppppppiVar5 = (int ********)(*(code *)(*local_6c)[0xe])();
                            if ((int)ppppppppiVar5 < 0) {
                              local_70 = (int ********)*ppppppppiVar6;
                              local_68 = (int ********)0x38;
                              local_6c = (int ********)&DAT_004523f0;
                              local_78 = (int ********)0x72ce7c;
                              local_74 = ppppppppiVar5;
                              __vbaHresultCheckObj();
                            }
                          }
                          local_68 = (int ********)&LAB_0072ce8b;
                          local_6c = (int ********)0x72ce8a;
                          __vbaFreeObj();
                          return;
                        }
                      }
                    }
                    else {
                      local_8 = 0x5b;
                      local_3c = (int ********)0x72bfce;
                      local_118 = (int ********)(**(code **)(*unaff_EBX + 0x20))();
                      if ((int)local_118 < 0) {
                        local_3c = (int ********)0x20;
                        local_40 = (int ********)&DAT_00476648;
                        ppppppppiStack_48 = local_118;
                        __vbaHresultCheckObj();
                      }
                      if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                        local_3c = (int ********)0x72c074;
                        local_3b8 = __vbaGenerateBoundsError();
                      }
                      else {
                        local_114 = (int ********)
                                    ((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                        if (param_1[0xe][4] <= local_114) {
                          local_3c = (int ********)0x72c057;
                          __vbaGenerateBoundsError();
                        }
                        local_3b8 = (int)local_114 << 2;
                      }
                      local_3c = (int ********)((int)param_1[0xe][3] + local_3b8);
                      local_40 = (int ********)0x72c097;
                      __vbaObjSetAddref();
                      __vbaFreeObj();
                      *(short *)((int)param_1 + 0x3e) = 0;
                      local_8 = 0x5d;
                      local_3c = (int ********)0x72c0c6;
                      local_114 = (int ********)(*(code *)(*param_1)[9])();
                      if ((int)local_114 < 0) {
                        local_40 = (int ********)0x72c0ed;
                        local_3c = local_114;
                        __vbaHresultCheckObj();
                      }
                    }
                  }
                  else {
                    local_8 = 0x5f;
                    iVar4 = __vbaStrCmp();
                    if (iVar4 == 0) {
                      local_8 = 0x60;
                      if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                        __vbaGenerateBoundsError();
                      }
                      else {
                        local_114 = (int ********)
                                    ((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                        if (param_1[0xe][4] <= local_114) {
                          __vbaGenerateBoundsError();
                        }
                      }
                      __vbaCastObj();
                      __vbaObjSet();
                      local_8 = 0x61;
                      local_114 = (int ********)(*(code *)(*param_1)[7])();
                      if ((int)local_114 < 0) {
                        local_3c = (int ********)param_1;
                        local_40 = local_114;
                        __vbaHresultCheckObj();
                      }
                      local_118 = local_98[0];
                      local_3c = (int ********)0x72c23e;
                      local_11c = (int ********)(*(code *)(*local_98[0])[0xe])();
                      if ((int)local_11c < 0) {
                        local_3c = (int ********)0x38;
                        local_40 = (int ********)&DAT_00475d6c;
                        ppppppppiStack_48 = local_11c;
                        __vbaHresultCheckObj();
                      }
                      local_3c = (int ********)&DAT_0047599c;
                      local_40 = local_9c;
                      local_3c = (int ********)__vbaCastObj();
                      local_40 = (int ********)&local_78;
                      __vbaObjSet();
                      local_3c = (int ********)&local_9c;
                      local_40 = (int ********)local_98;
                      ppppppppiStack_48 = (int ********)0x72c2af;
                      __vbaFreeObjList();
                      while( true ) {
                        local_8 = 0x62;
                        local_3c = (int ********)0x0;
                        local_40 = local_78;
                        sVar1 = __vbaObjIs();
                        if (sVar1 != 0) break;
                        local_8 = 99;
                        local_3c = &local_84;
                        local_40 = local_64;
                        local_114 = (int ********)(*(code *)(*local_64)[8])();
                        if ((int)local_114 < 0) {
                          ppppppppiStack_48 = (int ********)&DAT_00476688;
                          __vbaHresultCheckObj();
                        }
                        ppppppppiStack_48 = local_78;
                        local_118 = (int ********)(*(code *)(*local_78)[8])();
                        if ((int)local_118 < 0) {
                          __vbaHresultCheckObj();
                        }
                        iVar4 = __vbaStrCmp();
                        local_11c = (int ********)CONCAT22(local_11c._2_2_,-(ushort)(iVar4 == 0));
                        __vbaFreeStrList();
                        if ((short)local_11c == 0) {
                          local_8 = 0x67;
                          local_114 = (int ********)(*(code *)(*local_78)[10])();
                          if ((int)local_114 < 0) {
                            local_3c = (int ********)0x28;
                            local_40 = (int ********)&DAT_0047599c;
                            ppppppppiStack_48 = local_114;
                            __vbaHresultCheckObj();
                          }
                          local_3c = (int ********)&DAT_0047599c;
                          local_40 = local_98[0];
                          local_3c = (int ********)__vbaCastObj();
                          local_40 = (int ********)&local_78;
                          __vbaObjSet();
                          local_3c = (int ********)0x72c52c;
                          __vbaFreeObj();
                        }
                        else {
                          local_8 = 100;
                          local_114 = (int ********)(*(code *)(*local_78)[0xc])();
                          if ((int)local_114 < 0) {
                            local_64 = (int ********)0x72c3f7;
                            __vbaHresultCheckObj();
                          }
                          local_98[0] = (int ********)0x0;
                          __vbaObjSet();
                          local_118 = (int ********)(*(code *)(*local_64)[0xb])();
                          if ((int)local_118 < 0) {
                            local_3c = (int ********)0x2c;
                            local_40 = (int ********)&DAT_00476688;
                            ppppppppiStack_48 = local_118;
                            __vbaHresultCheckObj();
                          }
                          local_3c = (int ********)0x72c48d;
                          __vbaFreeObj();
                          local_8 = 0x65;
                          local_3c = (int ********)&DAT_0047599c;
                          local_40 = (int ********)0x0;
                          local_3c = (int ********)__vbaCastObj();
                          local_40 = (int ********)&local_78;
                          __vbaObjSet();
                        }
                      }
                      local_8 = 0x6a;
                      local_3c = (int ********)local_98;
                      local_40 = local_64;
                      local_118 = (int ********)(*(code *)(*local_64)[0xc])();
                      if ((int)local_118 < 0) {
                        ppppppppiStack_48 = (int ********)&DAT_00476688;
                        __vbaHresultCheckObj();
                      }
                      if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                        __vbaGenerateBoundsError();
                      }
                      else {
                        local_114 = (int ********)
                                    ((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                        if (param_1[0xe][4] <= local_114) {
                          __vbaGenerateBoundsError();
                        }
                      }
                      local_40 = local_98[0];
                      ppppppppiStack_48 = (int ********)0x72c614;
                      __vbaObjSetAddref();
                      local_40 = (int ********)0x72c620;
                      __vbaFreeObj();
                      local_8 = 0x6b;
                      local_40 = (int ********)local_98;
                      ppppppppiStack_48 = (int ********)0x72c63a;
                      local_114 = (int ********)(*(code *)(*local_64)[10])();
                      if ((int)local_114 < 0) {
                        ppppppppiStack_48 = (int ********)0x28;
                        __vbaHresultCheckObj();
                      }
                      ppppppppiStack_48 = local_98[0];
                      local_98[0] = (int ********)0x0;
                      __vbaObjSet();
                      ppppppppiStack_48 = (int ********)&local_9c;
                      (*(code *)(*param_1)[0xf])();
                      __vbaFreeObj();
                      local_8 = 0x6c;
                      local_114 = (int ********)(*(code *)(*param_1)[9])();
                      if ((int)local_114 < 0) {
                        local_40 = (int ********)0x72c6f8;
                        local_3c = local_114;
                        __vbaHresultCheckObj();
                      }
                    }
                    else {
                      local_8 = 0x6d;
                      iVar4 = __vbaStrCmp();
                      if (iVar4 == 0) {
                        local_8 = 0x6e;
                        modAgent::Proc_621930();
                        local_8 = 0x6f;
                        if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1)) {
                          __vbaGenerateBoundsError();
                        }
                        else {
                          local_114 = (int ********)
                                      ((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                          if (param_1[0xe][4] <= local_114) {
                            __vbaGenerateBoundsError();
                          }
                        }
                        __vbaCastObj();
                        __vbaObjSet();
                        if (*(short *)((int)param_1 + 0x3e) == 0) {
                          *(short *)((int)param_1 + 0x3e) = -1;
                          local_8 = 0x72;
                          if (DAT_0073a254 == (int ******)0x0) {
                            __vbaNew2();
                          }
                          local_114 = (int ********)DAT_0073a254;
                          local_118 = (int ********)(*(code *)(*DAT_0073a254)[0x1d3])();
                          if ((int)local_118 < 0) {
                            local_40 = (int ********)0x72c88b;
                            local_3c = local_118;
                            __vbaHresultCheckObj();
                          }
                          local_8 = 0x73;
                          local_114 = (int ********)(*(code *)(*in_stack_ffffffa0)[10])();
                          if ((int)local_114 < 0) {
                            local_3c = (int ********)&DAT_004766bc;
                            ppppppppiStack_48 = (int ********)0x72c8dd;
                            __vbaHresultCheckObj();
                          }
                          local_3c = (int ********)0xffffffff;
                          local_40 = (int ********)0x1;
                          ppppppppiStack_48 = (int ********)0x443b44;
                          rtcReplace();
                          __vbaStrMove();
                          local_ac = (int *******)local_88;
                          local_ec = (wchar_t *)0x80020004;
                          local_f4 = (int ******)0xa;
                          local_88 = (int ********)0x0;
                          local_b4 = (int *******)0x8;
                          local_3c = (int ********)0x72c96a;
                          __vbaChkstk();
                          local_3c = (int ********)0x72c999;
                          __vbaChkstk();
                          local_3c = (int ********)DAT_0073a08c;
                          local_40 = (int ********)0x72c9cf;
                          local_118 = (int ********)(*(code *)(*DAT_0073a08c)[0x1e])();
                          if ((int)local_118 < 0) {
                            local_40 = (int ********)0x72c9fb;
                            local_3c = local_118;
                            __vbaHresultCheckObj();
                          }
                          local_98[0] = (int ********)0x0;
                          __vbaObjSet();
                          local_3c = (int ********)0x72ca48;
                          __vbaFreeStrList();
                          __vbaFreeVar();
                        }
                        else {
                          local_8 = 0x75;
                          local_118 = (int ********)(*(code *)(*in_stack_ffffffa0)[8])();
                          if ((int)local_118 < 0) {
                            local_40 = local_118;
                            local_3c = (int ********)in_stack_ffffffa0;
                            __vbaHresultCheckObj();
                          }
                          if ((param_1[0xe] == (int ********)0x0) || (*(short *)param_1[0xe] != 1))
                          {
                            __vbaGenerateBoundsError();
                          }
                          else {
                            local_114 = (int ********)
                                        ((int)*(short *)(param_1 + 0xf) - (int)param_1[0xe][5]);
                            if (param_1[0xe][4] <= local_114) {
                              __vbaGenerateBoundsError();
                            }
                          }
                          __vbaObjSetAddref();
                          __vbaFreeObj();
                          *(short *)((int)param_1 + 0x3e) = 0;
                          local_8 = 0x77;
                          local_114 = (int ********)(*(code *)(*param_1)[9])();
                          if ((int)local_114 < 0) {
                            local_40 = (int ********)0x72cb95;
                            local_3c = local_114;
                            __vbaHresultCheckObj();
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  else {
    local_8 = 4;
    (*(code *)(*param_1)[0xe])();
    if (*(short *)(param_1 + 0xf) < 1) {
      local_8 = 8;
      local_3c = (int ********)param_1;
      local_40 = (int ********)0x728bed;
      local_114 = (int ********)(*(code *)(*param_1)[7])();
      if ((int)local_114 < 0) {
        local_40 = (int ********)0x1c;
        ppppppppiStack_48 = (int ********)param_1;
        __vbaHresultCheckObj();
      }
      local_118 = local_98[0];
      local_40 = &local_84;
      ppppppppiStack_48 = (int ********)0x728c48;
      local_11c = (int ********)(*(code *)(*local_98[0])[0x10])();
      if ((int)local_11c < 0) {
        ppppppppiStack_48 = (int ********)0x40;
        __vbaHresultCheckObj();
      }
      local_ac = local_84;
      local_84 = (int *******)0x0;
      local_b4 = (int *******)0x8;
      ppppppppiStack_48 = &local_b4;
      rtcLowerCaseVar();
      ppppppppiStack_48 = (int ********)0x728cd2;
      __vbaVarMove();
      ppppppppiStack_48 = (int ********)0x728cde;
      __vbaFreeObj();
      ppppppppiStack_48 = (int ********)0x728cea;
      __vbaFreeVar();
      local_8 = 9;
      local_ec = L"product";
      local_f4 = (int ******)0x8008;
      ppppppppiStack_48 = (int ********)local_158;
      sVar1 = __vbaVarTstEq();
      if (sVar1 == 0) {
        local_8 = 0xb;
        local_ec = L"daily";
        local_f4 = (int ******)0x8008;
        ppppppppiStack_48 = (int ********)local_158;
        sVar1 = __vbaVarTstEq();
        if (sVar1 == 0) {
          local_8 = 0xd;
          local_ec = L"interest";
          local_f4 = (int ******)0x8008;
          ppppppppiStack_48 = (int ********)local_158;
          sVar1 = __vbaVarTstEq();
          if (sVar1 == 0) {
            local_8 = 0xf;
            local_ec = L"news";
            local_f4 = (int ******)0x8008;
            ppppppppiStack_48 = (int ********)local_158;
            sVar1 = __vbaVarTstEq();
            if (sVar1 != 0) {
              local_8 = 0x10;
              if (DAT_0073c818 == (int ******)0x0) {
                ppppppppiStack_48 = (int ********)&DAT_0073c818;
                __vbaNew2();
              }
              local_114 = (int ********)DAT_0073c818;
              ppppppppiStack_48 = (int ********)local_98;
              local_118 = (int ********)(*(code *)(*DAT_0073c818)[5])();
              if ((int)local_118 < 0) {
                __vbaHresultCheckObj();
              }
              local_11c = local_98[0];
              local_120 = (int ********)(*(code *)(*local_98[0])[0x18])();
              if ((int)local_120 < 0) {
                local_68 = (int ********)0x7297c3;
                local_64 = local_120;
                __vbaHresultCheckObj();
              }
              local_124 = (int ********)(*(code *)(*param_1)[7])();
              if ((int)local_124 < 0) {
                local_64 = (int ********)&DAT_0047639c;
                local_68 = (int ********)param_1;
                local_70 = (int ********)0x72980f;
                local_6c = local_124;
                __vbaHresultCheckObj();
              }
              local_128 = local_9c;
              local_64 = local_9c;
              local_68 = (int ********)0x729846;
              local_12c = (int *******)(*(code *)(*local_9c)[0x12])();
              if ((int)local_12c < 0) {
                local_68 = (int ********)0x48;
                local_6c = (int ********)&DAT_00475d6c;
                local_70 = local_128;
                local_78 = (int ********)0x729872;
                local_74 = (int ********)local_12c;
                __vbaHresultCheckObj();
              }
              local_68 = &local_a0;
              local_6c = (int ********)param_1;
              local_70 = (int ********)0x729897;
              local_130 = (int ********)(*(code *)(*param_1)[7])();
              if ((int)local_130 < 0) {
                local_70 = (int ********)0x1c;
                local_74 = (int ********)&DAT_0047639c;
                local_78 = (int ********)param_1;
                local_80 = (int ********)0x7298be;
                local_7c = local_130;
                __vbaHresultCheckObj();
              }
              local_134 = local_a0;
              local_70 = &local_8c;
              local_74 = (int ********)local_a0;
              local_78 = (int ********)0x7298f5;
              local_138 = (int *******)(*(code *)(*local_a0)[0x18])();
              if ((int)local_138 < 0) {
                local_78 = (int ********)0x60;
                local_7c = (int ********)&DAT_00475d6c;
                local_80 = (int ********)local_134;
                local_88 = (int ********)0x729921;
                local_84 = local_138;
                __vbaHresultCheckObj();
              }
              local_78 = &local_a4;
              local_7c = (int ********)param_1;
              local_80 = (int ********)0x729946;
              local_13c = (int *******)(*(code *)(*param_1)[7])();
              if ((int)local_13c < 0) {
                local_80 = (int ********)0x1c;
                local_84 = (int *******)&DAT_0047639c;
                local_88 = (int ********)param_1;
                local_90 = (int *******)0x72996d;
                local_8c = local_13c;
                __vbaHresultCheckObj();
              }
              local_140 = local_a4;
              local_80 = &local_90;
              local_84 = local_a4;
              local_88 = (int ********)0x7299a4;
              local_144 = (*(code *)(*local_a4)[0x1a])();
              if (local_144 < 0) {
                ppppppppiStack_48 = (int ********)0x68;
                __vbaHresultCheckObj();
              }
              ppppppppiStack_48 = (int ********)local_90;
              __vbaStrCat();
              __vbaStrMove();
              rtcSaveSetting();
              ppppppppiStack_48 = &local_90;
              __vbaFreeStrList();
              ppppppppiStack_48 = &local_a4;
              __vbaFreeObjList();
            }
          }
          else {
            local_8 = 0xe;
            if (DAT_0073c818 == (int ******)0x0) {
              ppppppppiStack_48 = (int ********)&DAT_0073c818;
              __vbaNew2();
            }
            local_114 = (int ********)DAT_0073c818;
            ppppppppiStack_48 = (int ********)local_98;
            local_118 = (int ********)(*(code *)(*DAT_0073c818)[5])();
            if ((int)local_118 < 0) {
              __vbaHresultCheckObj();
            }
            local_11c = local_98[0];
            local_120 = (int ********)(*(code *)(*local_98[0])[0x18])();
            if ((int)local_120 < 0) {
              local_68 = (int ********)0x7293f1;
              local_64 = local_120;
              __vbaHresultCheckObj();
            }
            local_124 = (int ********)(*(code *)(*param_1)[7])();
            if ((int)local_124 < 0) {
              local_64 = (int ********)&DAT_0047639c;
              local_68 = (int ********)param_1;
              local_70 = (int ********)0x72943d;
              local_6c = local_124;
              __vbaHresultCheckObj();
            }
            local_128 = local_9c;
            local_64 = local_9c;
            local_68 = (int ********)0x729474;
            local_12c = (int *******)(*(code *)(*local_9c)[0x12])();
            if ((int)local_12c < 0) {
              local_68 = (int ********)0x48;
              local_6c = (int ********)&DAT_00475d6c;
              local_70 = local_128;
              local_78 = (int ********)0x7294a0;
              local_74 = (int ********)local_12c;
              __vbaHresultCheckObj();
            }
            local_68 = &local_a0;
            local_6c = (int ********)param_1;
            local_70 = (int ********)0x7294c5;
            local_130 = (int ********)(*(code *)(*param_1)[7])();
            if ((int)local_130 < 0) {
              local_70 = (int ********)0x1c;
              local_74 = (int ********)&DAT_0047639c;
              local_78 = (int ********)param_1;
              local_80 = (int ********)0x7294ec;
              local_7c = local_130;
              __vbaHresultCheckObj();
            }
            local_134 = local_a0;
            local_70 = &local_8c;
            local_74 = (int ********)local_a0;
            local_78 = (int ********)0x729523;
            local_138 = (int *******)(*(code *)(*local_a0)[0x18])();
            if ((int)local_138 < 0) {
              local_78 = (int ********)0x60;
              local_7c = (int ********)&DAT_00475d6c;
              local_80 = (int ********)local_134;
              local_88 = (int ********)0x72954f;
              local_84 = local_138;
              __vbaHresultCheckObj();
            }
            local_78 = &local_a4;
            local_7c = (int ********)param_1;
            local_80 = (int ********)0x729574;
            local_13c = (int *******)(*(code *)(*param_1)[7])();
            if ((int)local_13c < 0) {
              local_80 = (int ********)0x1c;
              local_84 = (int *******)&DAT_0047639c;
              local_88 = (int ********)param_1;
              local_90 = (int *******)0x72959b;
              local_8c = local_13c;
              __vbaHresultCheckObj();
            }
            local_140 = local_a4;
            local_80 = &local_90;
            local_84 = local_a4;
            local_88 = (int ********)0x7295d2;
            local_144 = (*(code *)(*local_a4)[0x1a])();
            if (local_144 < 0) {
              ppppppppiStack_48 = (int ********)0x68;
              __vbaHresultCheckObj();
            }
            ppppppppiStack_48 = (int ********)local_90;
            __vbaStrCat();
            __vbaStrMove();
            rtcSaveSetting();
            ppppppppiStack_48 = &local_90;
            __vbaFreeStrList();
            ppppppppiStack_48 = &local_a4;
            __vbaFreeObjList();
          }
        }
        else {
          local_8 = 0xc;
          if (DAT_0073c818 == (int ******)0x0) {
            ppppppppiStack_48 = (int ********)&DAT_0073c818;
            __vbaNew2();
          }
          local_114 = (int ********)DAT_0073c818;
          ppppppppiStack_48 = (int ********)local_98;
          local_118 = (int ********)(*(code *)(*DAT_0073c818)[5])();
          if ((int)local_118 < 0) {
            __vbaHresultCheckObj();
          }
          local_11c = local_98[0];
          local_120 = (int ********)(*(code *)(*local_98[0])[0x18])();
          if ((int)local_120 < 0) {
            local_68 = (int ********)0x7290ff;
            local_64 = local_120;
            __vbaHresultCheckObj();
          }
          local_124 = (int ********)(*(code *)(*param_1)[7])();
          if ((int)local_124 < 0) {
            local_64 = (int ********)&DAT_0047639c;
            local_68 = (int ********)param_1;
            local_70 = (int ********)0x72914b;
            local_6c = local_124;
            __vbaHresultCheckObj();
          }
          local_128 = local_9c;
          local_64 = local_9c;
          local_68 = (int ********)0x729182;
          local_12c = (int *******)(*(code *)(*local_9c)[0x18])();
          if ((int)local_12c < 0) {
            local_68 = (int ********)0x60;
            local_6c = (int ********)&DAT_00475d6c;
            local_70 = local_128;
            local_78 = (int ********)0x7291ae;
            local_74 = (int ********)local_12c;
            __vbaHresultCheckObj();
          }
          local_68 = &local_a0;
          local_6c = (int ********)param_1;
          local_70 = (int ********)0x7291d3;
          local_130 = (int ********)(*(code *)(*param_1)[7])();
          if ((int)local_130 < 0) {
            local_70 = (int ********)0x1c;
            local_74 = (int ********)&DAT_0047639c;
            local_78 = (int ********)param_1;
            local_80 = (int ********)0x7291fa;
            local_7c = local_130;
            __vbaHresultCheckObj();
          }
          local_134 = local_a0;
          local_70 = &local_8c;
          local_74 = (int ********)local_a0;
          local_78 = (int ********)0x729231;
          local_138 = (int *******)(*(code *)(*local_a0)[0x1a])();
          if ((int)local_138 < 0) {
            ppppppppiStack_48 = (int ********)0x68;
            __vbaHresultCheckObj();
          }
          ppppppppiStack_48 = (int ********)local_8c;
          rtcSaveSetting();
          ppppppppiStack_48 = &local_8c;
          __vbaFreeStrList();
          ppppppppiStack_48 = &local_a0;
          __vbaFreeObjList();
        }
      }
      else {
        local_8 = 10;
        if (DAT_0073c818 == (int ******)0x0) {
          ppppppppiStack_48 = (int ********)&DAT_0073c818;
          __vbaNew2();
        }
        local_114 = (int ********)DAT_0073c818;
        ppppppppiStack_48 = (int ********)local_98;
        local_118 = (int ********)(*(code *)(*DAT_0073c818)[5])();
        if ((int)local_118 < 0) {
          __vbaHresultCheckObj();
        }
        local_11c = local_98[0];
        local_120 = (int ********)(*(code *)(*local_98[0])[0x18])();
        if ((int)local_120 < 0) {
          local_68 = (int ********)0x728e0d;
          local_64 = local_120;
          __vbaHresultCheckObj();
        }
        local_124 = (int ********)(*(code *)(*param_1)[7])();
        if ((int)local_124 < 0) {
          local_64 = (int ********)&DAT_0047639c;
          local_68 = (int ********)param_1;
          local_70 = (int ********)0x728e59;
          local_6c = local_124;
          __vbaHresultCheckObj();
        }
        local_128 = local_9c;
        local_64 = local_9c;
        local_68 = (int ********)0x728e90;
        local_12c = (int *******)(*(code *)(*local_9c)[0x18])();
        if ((int)local_12c < 0) {
          local_68 = (int ********)0x60;
          local_6c = (int ********)&DAT_00475d6c;
          local_70 = local_128;
          local_78 = (int ********)0x728ebc;
          local_74 = (int ********)local_12c;
          __vbaHresultCheckObj();
        }
        local_68 = &local_a0;
        local_6c = (int ********)param_1;
        local_70 = (int ********)0x728ee1;
        local_130 = (int ********)(*(code *)(*param_1)[7])();
        if ((int)local_130 < 0) {
          local_70 = (int ********)0x1c;
          local_74 = (int ********)&DAT_0047639c;
          local_78 = (int ********)param_1;
          local_80 = (int ********)0x728f08;
          local_7c = local_130;
          __vbaHresultCheckObj();
        }
        local_134 = local_a0;
        local_70 = &local_8c;
        local_74 = (int ********)local_a0;
        local_78 = (int ********)0x728f3f;
        local_138 = (int *******)(*(code *)(*local_a0)[0x1a])();
        if ((int)local_138 < 0) {
          ppppppppiStack_48 = (int ********)0x68;
          __vbaHresultCheckObj();
        }
        ppppppppiStack_48 = (int ********)local_8c;
        rtcSaveSetting();
        ppppppppiStack_48 = &local_8c;
        __vbaFreeStrList();
        ppppppppiStack_48 = &local_a0;
        __vbaFreeObjList();
      }
      local_8 = 0x12;
      ppppppppiStack_48 = (int ********)local_98;
      local_114 = (int ********)(*(code *)(*param_1)[7])();
      if ((int)local_114 < 0) {
        __vbaHresultCheckObj();
      }
      local_118 = local_98[0];
      local_11c = (int ********)(*(code *)(*local_98[0])[0x1c])();
      if ((int)local_11c < 0) {
        local_68 = (int ********)0x729b0e;
        local_64 = local_11c;
        __vbaHresultCheckObj();
      }
      local_84 = (int *******)0x0;
      __vbaStrMove();
      modTaps::Proc_72f310();
      __vbaFreeStr();
      __vbaFreeObj();
      local_8 = 0x13;
      local_110 = 3;
      local_64 = (int ********)0x729b90;
      local_114 = (int ********)(*(code *)(*param_1[0x11])[0xc])();
      if ((int)local_114 < 0) {
        local_40 = (int ********)0x729bbc;
        local_3c = local_114;
        __vbaHresultCheckObj();
      }
    }
    else {
      local_8 = 6;
      local_3c = (int ********)0x728b95;
      local_114 = (int ********)(*(code *)(*param_1)[9])();
      if ((int)local_114 < 0) {
        local_40 = (int ********)0x728bbc;
        local_3c = local_114;
        __vbaHresultCheckObj();
      }
    }
  }
  __vbaExitProc();
  __vbaFreeStr();
  __vbaFreeVar();
  __vbaFreeObj();
  __vbaFreeObj();
  local_3c = (int ********)0x72cd4f;
  __vbaAryDestruct();
  __vbaFreeObj();
  __vbaFreeObj();
  __vbaFreeObj();
  __vbaFreeVar();
  __vbaFreeObj();
  __vbaFreeStr();
  __vbaFreeObj();
  __vbaFreeObj();
  __vbaFreeStr();
  __vbaFreeObj();
  local_3c = (int ********)0x72cdb5;
  __vbaAryDestruct();
  __vbaFreeObj();
  __vbaFreeObj();
  return;
}


// ---- ShouldBeHeard @ 0072ceb0

undefined4 clsBonziEventTap::ShouldBeHeard(int *param_1,undefined4 param_2,undefined2 *param_3)

{
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined1 *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00412856;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &LAB_004123e0;
  local_8 = 0;
  ExceptionList = &local_18;
  (**(code **)(*param_1 + 4))(param_1);
  (**(code **)(*param_1 + 8))(param_1);
  *param_3 = 0xffff;
  ExceptionList = local_18;
  return local_8;
}


// ---- Public_9 @ 0072cf20

undefined4 clsBonziEventTap::Public_9(uint param_1)

{
  int *piVar1;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_004123e8;
  local_8 = param_1 & 1;
  piVar1 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar1 + 4))(piVar1);
  *(undefined2 *)(piVar1 + 0x10) = 1;
  local_8 = 0;
  (**(code **)(*piVar1 + 8))(piVar1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Public_10 @ 0072cf90

void clsBonziEventTap::Public_10(uint param_1)

{
  int *piVar1;
  short sVar2;
  int iVar3;
  undefined4 uVar4;
  int *piVar5;
  int *local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc4;
  local_c = &DAT_004123f0;
  local_8 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar5 + 4))(piVar5);
  local_1c = (int *)0x0;
  iVar3 = (**(code **)(*piVar5 + 0x1c))(piVar5,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar5,&DAT_0047639c,0x1c);
  }
  sVar2 = __vbaObjIs(local_1c,0);
  __vbaFreeObj();
  if (sVar2 != -1) {
    iVar3 = (**(code **)(*piVar5 + 0x1c))(piVar5,&local_1c);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar5,&DAT_0047639c,0x1c);
    }
    piVar1 = local_1c;
    iVar3 = (**(code **)(*local_1c + 0x24))(local_1c);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar1,&DAT_00475d6c,0x24);
    }
    __vbaFreeObj();
    uVar4 = __vbaCastObj(0,&DAT_00475d6c);
    __vbaObjSet(&local_1c,uVar4);
    iVar3 = (**(code **)(*piVar5 + 0x20))(piVar5,&local_1c);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar5,&DAT_0047639c,0x20);
    }
    __vbaFreeObj();
  }
  return;
}


