// BonziBDY_4.EXE :: CPeriods
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 7

// ---- Public_6 @ 005facc0

void CPeriods::Public_6(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00403d68;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  uVar1 = __vbaNew(&DAT_00447b78);
  uVar1 = __vbaObjSet(&local_1c,uVar1);
  __vbaObjSetAddref(piVar2 + 0xe,uVar1);
  __vbaFreeObj();
  return;
}


// ---- Add @ 005fad70
// decompilation failed: 
Low-level Error: Symbol $$undef00000167 extends beyond the end of the address space

// ---- NewEnum @ 005fb510

void CPeriods::NewEnum(int *param_1,undefined4 *param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00403de0;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  local_20 = 0;
  *param_2 = 0;
  iVar1 = (**(code **)(*(int *)param_1[0xe] + 0x2c))((int *)param_1[0xe],&local_20);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xe],&DAT_00447b68,0x2c);
  }
  uVar2 = __vbaCastObj(local_20,&DAT_00447558);
  __vbaObjSet(&local_1c,uVar2);
  __vbaFreeObj();
  return;
}


// ---- Remove @ 005fb5f0

undefined4 CPeriods::Remove(int *param_1,undefined4 param_2)

{
  int iVar1;
  void *local_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  local_24 = ExceptionList;
  ExceptionList = &local_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00403df0;
  local_14 = 0;
  local_10 = 0;
  (**(code **)(*param_1 + 4))(param_1);
  local_8 = 2;
  __vbaOnError(0xffffffff);
  local_8 = 3;
  iVar1 = (**(code **)(*(int *)param_1[0xe] + 0x28))(param_1[0xe],param_2);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xe],&DAT_00447b68,0x28);
  }
  (**(code **)(*param_1 + 8))(param_1);
  ExceptionList = local_24;
  return local_14;
}


// ---- Item @ 005fb6c0

void CPeriods::Item(int *param_1,undefined4 param_2,undefined4 *param_3)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 ***local_38;
  int *piStack_34;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00403e20;
  local_14 = 0;
  local_10 = 0;
  piStack_34 = param_1;
  local_38 = (undefined4 ***)0x5fb70a;
  (**(code **)(*param_1 + 4))();
  *param_3 = 0;
  local_8 = 2;
  local_38 = (undefined4 ***)0xffffffff;
  __vbaOnError();
  local_8 = 3;
  local_38 = &local_38;
  iVar1 = (**(code **)(*(int *)param_1[0xe] + 0x1c))(param_1[0xe],param_2);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xe],&DAT_00447b68,0x1c);
  }
  uVar2 = __vbaCastObjVar(&local_38,&DAT_00447b04);
  __vbaObjSet(&stack0xffffffd8,uVar2);
  __vbaFreeVar();
  return;
}


// ---- Count_Get @ 005fb7f0

undefined4 CPeriods::Count_Get(int *param_1,undefined4 *param_2)

{
  int iVar1;
  undefined4 local_20;
  undefined4 local_1c;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00412856;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00403e50;
  local_8 = 0;
  ExceptionList = &local_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_20 = 0;
  local_1c = 0;
  iVar1 = (**(code **)(*(int *)param_1[0xe] + 0x24))((int *)param_1[0xe],&local_20);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xe],&DAT_00447b68,0x24);
  }
  local_1c = local_20;
  (**(code **)(*param_1 + 8))(param_1);
  *param_2 = local_1c;
  ExceptionList = local_18;
  return local_8;
}


// ---- WeeksFromFirstOfYear @ 005fb880

void CPeriods::WeeksFromFirstOfYear(int *param_1,short param_2,undefined4 *param_3)

{
  short *psVar1;
  int *piVar2;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffb0;
  local_c = &DAT_00403e58;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  piVar2 = param_1;
  (**(code **)(*param_1 + 4))(param_1);
  *param_3 = 0;
  psVar1 = (short *)param_1[0xd];
  if ((psVar1 == (short *)0x0) || (*psVar1 != 1)) {
    __vbaGenerateBoundsError(piVar2);
  }
  else if (*(uint *)(psVar1 + 8) <= (uint)((int)param_2 - *(int *)(psVar1 + 10))) {
    __vbaGenerateBoundsError(piVar2);
  }
  __vbaVarMove();
  return;
}


