// BonziBDY_4.EXE :: frmAppointment
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 5

// ---- cmdAdd_Click @ 006bf380

/* WARNING: Restarted to delay deadcode elimination for space: ram */

void frmAppointment::cmdAdd_Click(uint param_1)

{
  ushort uVar1;
  wchar_t ******ppppppwVar2;
  wchar_t ****ppppwVar3;
  wchar_t *****pppppwVar4;
  int iVar5;
  int *piVar6;
  undefined4 uVar7;
  short sVar8;
  wchar_t ******ppppppwVar9;
  undefined1 *unaff_EBX;
  undefined4 unaff_ESI;
  float10 fVar10;
  float10 fVar11;
  wchar_t *****local_98;
  wchar_t *****local_94;
  wchar_t ******local_90;
  wchar_t ******local_8c;
  undefined8 local_88;
  wchar_t ******local_80;
  wchar_t ****local_7c;
  wchar_t ******local_78;
  wchar_t *****local_74;
  wchar_t *****pppppwStack_70;
  wchar_t ******ppppppwStack_6c;
  wchar_t ******ppppppwStack_68;
  wchar_t ****local_64;
  wchar_t ******ppppppwStack_60;
  wchar_t *****pppppwStack_5c;
  wchar_t *****pppppwStack_58;
  wchar_t ******local_54;
  wchar_t ******ppppppwStack_50;
  wchar_t ****local_4c;
  wchar_t ******ppppppwStack_48;
  wchar_t *****local_44;
  wchar_t *****local_40;
  wchar_t ******local_3c;
  wchar_t ******local_38;
  wchar_t ******local_34;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined1 *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &LAB_0040cca8;
  local_14 = param_1 & 1;
  ppppppwVar9 = (wchar_t ******)(param_1 & 0xfffffffe);
  local_10 = 0;
  local_38 = (wchar_t ******)0x6bf3d5;
  local_34 = ppppppwVar9;
  (*(code *)(*ppppppwVar9)[1])();
  local_8 = 2;
  local_38 = (wchar_t ******)0xffffffff;
  local_3c = (wchar_t ******)0x6bf3eb;
  __vbaOnError();
  local_8 = 3;
  local_3c = (wchar_t ******)0x6bf401;
  local_38 = ppppppwVar9;
  local_4c = (wchar_t ****)(*(code *)(*ppppppwVar9)[0xc2])();
  local_54 = (wchar_t ******)0x9;
  local_3c = (wchar_t ******)&local_54;
  local_40 = (wchar_t *****)0x6bf415;
  uVar1 = rtcIsDate();
  uVar1 = ~uVar1;
  local_3c = (wchar_t ******)0x6bf428;
  __vbaFreeVar();
  if (uVar1 == 0) {
    local_8 = 9;
    local_40 = (wchar_t *****)0x6bf619;
    local_3c = ppppppwVar9;
    local_40 = (wchar_t *****)(*(code *)(*ppppppwVar9)[0xc6])();
    local_44 = (wchar_t *****)&local_40;
    ppppppwStack_48 = (wchar_t ******)0x6bf624;
    pppppwVar4 = (wchar_t *****)__vbaObjSet();
    local_40 = (wchar_t *****)&stack0xffffffd8;
    ppppppwStack_48 = (wchar_t ******)0x6bf643;
    local_44 = pppppwVar4;
    ppppppwVar2 = (wchar_t ******)(*(code *)(*pppppwVar4)[0x28])();
    if ((int)ppppppwVar2 < 0) {
      ppppppwStack_48 = (wchar_t ******)0xa0;
      local_4c = (wchar_t ****)&DAT_0043f42c;
      pppppwStack_58 = (wchar_t *****)0x6bf672;
      local_54 = ppppppwVar2;
      ppppppwStack_50 = (wchar_t ******)pppppwVar4;
      __vbaHresultCheckObj();
    }
    local_4c = (wchar_t ****)0x6bf68e;
    iVar5 = __vbaLenBstr();
    sVar8 = -(ushort)(iVar5 != 0);
    ppppppwStack_48 = (wchar_t ******)0x6bf6a6;
    __vbaFreeStr();
    ppppppwStack_48 = (wchar_t ******)0x6bf6af;
    __vbaFreeObj();
    if (sVar8 == 0) {
      local_8 = 0x1b;
      ppppppwStack_48 = &local_40;
      local_4c = (wchar_t ****)0x442914;
      ppppppwStack_50 = (wchar_t ******)DAT_0073a08c;
      local_54 = (wchar_t ******)0x6c007e;
      ppppppwVar9 = (wchar_t ******)(*(code *)(*DAT_0073a08c)[0x19])();
      if ((int)ppppppwVar9 < 0) {
        local_54 = (wchar_t ******)0x64;
        pppppwStack_58 = (wchar_t *****)&DAT_004419ac;
        pppppwStack_5c = (wchar_t *****)DAT_0073a08c;
        local_64 = (wchar_t ****)0x6c00aa;
        ppppppwStack_60 = ppppppwVar9;
        __vbaHresultCheckObj();
      }
      local_54 = (wchar_t ******)0x6c00c5;
      __vbaFreeObj();
      local_8 = 0x1c;
      local_8c = (wchar_t ******)0x80020004;
      local_94 = (wchar_t *****)0xa;
      local_7c = (wchar_t ****)0x46d158;
      local_88._4_4_ = (wchar_t ******)0x8;
      local_54 = &local_40;
      pppppwStack_58 = (wchar_t *****)0x6c00fc;
      __vbaChkstk();
      local_54 = (wchar_t ******)local_94;
      ppppppwStack_50 = local_90;
      local_4c = (wchar_t ****)local_8c;
      ppppppwStack_48 = (wchar_t ******)local_88;
      pppppwStack_58 = (wchar_t *****)0x6c012b;
      __vbaChkstk();
      local_54 = local_88._4_4_;
      ppppppwStack_50 = local_80;
      local_4c = local_7c;
      ppppppwStack_48 = local_78;
      pppppwStack_58 = (wchar_t *****)DAT_0073a08c;
      pppppwStack_5c = (wchar_t *****)0x6c0155;
      ppppwVar3 = (wchar_t ****)(*(code *)(*DAT_0073a08c)[0x1e])();
      if ((int)ppppwVar3 < 0) {
        pppppwStack_58 = (wchar_t *****)0x78;
        pppppwStack_5c = (wchar_t *****)&DAT_004419ac;
        ppppppwStack_60 = (wchar_t ******)DAT_0073a08c;
        ppppppwStack_68 = (wchar_t ******)0x6c0181;
        local_64 = ppppwVar3;
        __vbaHresultCheckObj();
      }
      pppppwStack_58 = (wchar_t *****)0x6c019c;
      __vbaFreeObj();
    }
    else {
      local_8 = 10;
      local_4c = (wchar_t ****)0x6bf6d4;
      ppppppwStack_48 = ppppppwVar9;
      local_4c = (wchar_t ****)(*(code *)(*ppppppwVar9)[0xc6])();
      ppppppwStack_50 = &local_40;
      local_54 = (wchar_t ******)0x6bf6df;
      ppppwVar3 = (wchar_t ****)__vbaObjSet();
      local_4c = (wchar_t ****)&stack0xffffffd8;
      local_54 = (wchar_t ******)0x6bf6fe;
      ppppppwStack_50 = (wchar_t ******)ppppwVar3;
      ppppppwVar2 = (wchar_t ******)(*(code *)(*ppppwVar3)[0x28])();
      if ((int)ppppppwVar2 < 0) {
        local_54 = (wchar_t ******)0xa0;
        pppppwStack_58 = (wchar_t *****)&DAT_0043f42c;
        local_64 = (wchar_t ****)0x6bf72d;
        ppppppwStack_60 = ppppppwVar2;
        pppppwStack_5c = (wchar_t *****)ppppwVar3;
        __vbaHresultCheckObj();
      }
      pppppwStack_58 = (wchar_t *****)0x6bf749;
      rtcTrimBstr();
      local_54 = (wchar_t ******)0x6bf756;
      __vbaStrMove();
      local_54 = (wchar_t ******)0x6bf75f;
      __vbaFreeStr();
      local_54 = (wchar_t ******)0x6bf768;
      __vbaFreeObj();
      local_8 = 0xb;
      pppppwStack_58 = (wchar_t *****)0x6bf77e;
      local_54 = ppppppwVar9;
      pppppwStack_58 = (wchar_t *****)(*(code *)(*ppppppwVar9)[0xc4])();
      pppppwStack_5c = (wchar_t *****)&local_40;
      ppppppwStack_60 = (wchar_t ******)0x6bf789;
      piVar6 = (int *)__vbaObjSet();
      pppppwStack_58 = (wchar_t *****)&stack0xffffffd8;
      ppppppwStack_60 = (wchar_t ******)0x6bf7a8;
      pppppwStack_5c = (wchar_t *****)piVar6;
      iVar5 = (**(code **)(*piVar6 + 0xa8))();
      if (iVar5 < 0) {
        ppppppwStack_60 = (wchar_t ******)0xa8;
        local_64 = (wchar_t ****)&DAT_00446e04;
        pppppwStack_70 = (wchar_t *****)0x6bf7d7;
        ppppppwStack_6c = (wchar_t ******)iVar5;
        ppppppwStack_68 = (wchar_t ******)piVar6;
        __vbaHresultCheckObj();
      }
      local_64 = (wchar_t ****)0x6bf7f8;
      ppppppwStack_60 = ppppppwVar9;
      local_64 = (wchar_t ****)(*(code *)(*ppppppwVar9)[0xc5])();
      ppppppwStack_68 = &local_44;
      ppppppwStack_6c = (wchar_t ******)0x6bf803;
      pppppwVar4 = (wchar_t *****)__vbaObjSet();
      local_64 = (wchar_t ****)&stack0xffffffd4;
      ppppppwStack_6c = (wchar_t ******)0x6bf822;
      ppppppwStack_68 = (wchar_t ******)pppppwVar4;
      ppppppwVar2 = (wchar_t ******)(*(code *)(*pppppwVar4)[0x2a])();
      if ((int)ppppppwVar2 < 0) {
        ppppppwStack_6c = (wchar_t ******)0xa8;
        pppppwStack_70 = (wchar_t *****)&DAT_00446e04;
        local_7c = (wchar_t ****)0x6bf851;
        local_78 = ppppppwVar2;
        local_74 = pppppwVar4;
        __vbaHresultCheckObj();
      }
      pppppwStack_70 = (wchar_t *****)&DAT_0043ff54;
      local_74 = (wchar_t *****)0x6bf872;
      __vbaStrCat();
      ppppppwStack_6c = (wchar_t ******)0x6bf87d;
      ppppppwStack_6c = (wchar_t ******)__vbaStrMove();
      local_74 = (wchar_t *****)0x6bf888;
      __vbaStrCat();
      ppppppwStack_6c = (wchar_t ******)0x6bf893;
      ppppppwStack_6c = (wchar_t ******)__vbaStrMove();
      pppppwStack_70 = (wchar_t *****)0x6bf89a;
      rtcTrimBstr();
      ppppppwStack_6c = (wchar_t ******)0x6bf8a7;
      __vbaStrMove();
      ppppppwStack_6c = (wchar_t ******)&local_34;
      pppppwStack_70 = (wchar_t *****)&stack0xffffffd4;
      local_74 = (wchar_t *****)&stack0xffffffd0;
      local_78 = (wchar_t ******)&stack0xffffffd8;
      local_7c = (wchar_t ****)0x4;
      local_80 = (wchar_t ******)0x6bf8bf;
      __vbaFreeStrList();
      ppppppwStack_6c = &local_44;
      pppppwStack_70 = (wchar_t *****)&local_40;
      local_74 = (wchar_t *****)0x2;
      local_78 = (wchar_t ******)0x6bf8d2;
      __vbaFreeObjList();
      local_8 = 0xc;
      local_8c = (wchar_t ******)&DAT_00452b18;
      local_94 = (wchar_t *****)0x8;
      ppppppwStack_6c = (wchar_t ******)0x6bf8ff;
      __vbaVarDup();
      local_7c = (wchar_t ****)0x46d134;
      local_88 = (double)CONCAT44(8,(wchar_t ******)local_88);
      ppppppwStack_6c = (wchar_t ******)0x6bf919;
      __vbaVarDup();
      ppppppwStack_6c = (wchar_t ******)0x1;
      pppppwStack_70 = (wchar_t *****)0x1;
      local_74 = &local_64;
      local_78 = (wchar_t ******)&local_54;
      local_7c = (wchar_t ****)0x6bf92b;
      rtcBstrFromFormatVar();
      ppppppwStack_6c = (wchar_t ******)0x6bf936;
      __vbaStrMove();
      pppppwStack_70 = (wchar_t *****)0x6bf945;
      ppppppwStack_6c = ppppppwVar9;
      pppppwStack_70 = (wchar_t *****)(*(code *)(*ppppppwVar9)[0xc4])();
      local_74 = (wchar_t *****)&local_40;
      local_78 = (wchar_t ******)0x6bf950;
      pppppwVar4 = (wchar_t *****)__vbaObjSet();
      pppppwStack_70 = (wchar_t *****)&stack0xffffffd8;
      local_78 = (wchar_t ******)0x6bf96f;
      local_74 = pppppwVar4;
      iVar5 = (*(code *)(*pppppwVar4)[0x2a])();
      if (iVar5 < 0) {
        local_78 = (wchar_t ******)0xa8;
        local_7c = (wchar_t ****)&DAT_00446e04;
        local_88 = (double)CONCAT44(iVar5,0x6bf99e);
        local_80 = (wchar_t ******)pppppwVar4;
        __vbaHresultCheckObj();
      }
      local_7c = (wchar_t ****)0x6bf9bf;
      local_78 = ppppppwVar9;
      local_7c = (wchar_t ****)(*(code *)(*ppppppwVar9)[0xc5])();
      local_80 = &local_44;
      local_88 = (double)CONCAT44(0x6bf9ca,(wchar_t ******)local_88);
      piVar6 = (int *)__vbaObjSet();
      local_7c = (wchar_t ****)&stack0xffffffd4;
      local_88 = (double)CONCAT44(0x6bf9e9,(wchar_t ******)local_88);
      local_80 = (wchar_t ******)piVar6;
      pppppwVar4 = (wchar_t *****)(**(code **)(*piVar6 + 0xa8))();
      uVar1 = 0;
      if ((int)pppppwVar4 < 0) {
        local_88 = 3.5649750857489e-312;
        local_94 = (wchar_t *****)0x6bfa18;
        local_90 = (wchar_t ******)pppppwVar4;
        local_8c = (wchar_t ******)piVar6;
        __vbaHresultCheckObj();
      }
      local_3c = (wchar_t ******)0x0;
      local_88 = (double)CONCAT44(unaff_EBX,&DAT_0043ff54);
      local_8c = (wchar_t ******)0x6bfa49;
      __vbaStrCat();
      local_88 = (double)CONCAT44(0x6bfa54,(wchar_t ******)local_88);
      uVar7 = __vbaStrMove();
      local_88 = (double)CONCAT44(uVar7,unaff_ESI);
      local_8c = (wchar_t ******)0x6bfa5f;
      __vbaStrCat();
      local_88 = (double)CONCAT44(0x6bfa6a,(wchar_t ******)local_88);
      uVar7 = __vbaStrMove();
      local_88 = (double)CONCAT44(uVar7,0x6bfa71);
      fVar10 = (float10)__vbaDateStr();
      local_88 = (double)CONCAT44(0x6bfa86,(wchar_t ******)local_88);
      uVar7 = __vbaStrMove();
      local_88 = (double)CONCAT44(uVar7,0x6bfa8d);
      fVar11 = (float10)__vbaDateStr();
      if ((uVar1 & 0xd) != 0) {
        __vbaFPException();
        return;
      }
      local_88 = (double)(fVar11 + (float10)(double)fVar10);
      local_8c = (wchar_t ******)0x6bfaa9;
      fVar10 = (float10)__vbaDateR8();
      local_88 = (double)fVar10;
      local_8c = (wchar_t ******)0x6bfab5;
      __vbaStrDate();
      local_88 = (double)CONCAT44(0x6bfac2,(wchar_t ******)local_88);
      __vbaStrMove();
      local_88 = (double)CONCAT44(&local_3c,&local_38);
      local_8c = (wchar_t ******)&local_34;
      local_90 = (wchar_t ******)&stack0xffffffd4;
      local_94 = (wchar_t *****)&stack0xffffffd0;
      local_98 = (wchar_t *****)&stack0xffffffd8;
      __vbaFreeStrList(6);
      local_88 = (double)CONCAT44(&local_44,&local_40);
      local_8c = (wchar_t ******)0x2;
      local_90 = (wchar_t ******)0x6bfaf5;
      __vbaFreeObjList();
      local_88 = (double)CONCAT44(&local_64,&local_54);
      local_8c = (wchar_t ******)0x2;
      local_90 = (wchar_t ******)0x6bfb08;
      __vbaFreeVarList();
      local_8 = 0xd;
      local_88._0_4_ = (wchar_t ******)0x6bfb21;
      local_88._4_4_ = ppppppwVar9;
      local_88._0_4_ = (wchar_t ******)(*(code *)(*ppppppwVar9)[0xc9])();
      local_8c = &local_40;
      local_90 = (wchar_t ******)0x6bfb2c;
      pppppwVar4 = (wchar_t *****)__vbaObjSet();
      local_88 = (double)CONCAT44(local_88._4_4_,&local_98);
      local_90 = (wchar_t ******)0x6bfb4e;
      local_8c = (wchar_t ******)pppppwVar4;
      iVar5 = (*(code *)(*pppppwVar4)[0x38])();
      if (iVar5 < 0) {
        local_90 = (wchar_t ******)0xe0;
        local_94 = (wchar_t *****)&DAT_00446678;
        local_98 = pppppwVar4;
        __vbaHresultCheckObj(iVar5);
      }
      sVar8 = -(ushort)((short)local_98 == 1);
      local_90 = (wchar_t ******)0x6bfbae;
      __vbaFreeObj();
      if (sVar8 == 0) {
        local_8 = 0x11;
        local_90 = (wchar_t ******)0x6bfe4b;
        __vbaStrCopy();
        local_8 = 0x12;
        local_90 = (wchar_t ******)0x6bfe62;
        __vbaStrCopy();
      }
      else {
        local_8 = 0xe;
        local_94 = (wchar_t *****)0x6bfbd3;
        local_90 = ppppppwVar9;
        local_94 = (wchar_t *****)(*(code *)(*ppppppwVar9)[0xc2])();
        local_98 = (wchar_t *****)&local_40;
        local_98 = (wchar_t *****)__vbaObjSet();
        local_94 = (wchar_t *****)&stack0xffffffd8;
        iVar5 = (*(code *)(*local_98)[0x28])();
        if (iVar5 < 0) {
          __vbaHresultCheckObj(&DAT_0043f42c,0xa0,&DAT_0043f42c,0xa0);
        }
        local_7c = (wchar_t ****)0x46d144;
        local_88 = (double)CONCAT44(8,(wchar_t ******)local_88);
        __vbaVarDup();
        local_54 = (wchar_t ******)0x8;
        local_4c = (wchar_t ****)unaff_EBX;
        rtcVarFromFormatVar(&local_74,&local_54,&local_64,1,1);
        __vbaStrVarMove(&local_74);
        __vbaStrMove();
        __vbaFreeObj();
        __vbaFreeVarList(3,&local_54,&local_64,&local_74);
        local_8 = 0xf;
        uVar7 = (*(code *)(*ppppppwVar9)[200])(ppppppwVar9);
        piVar6 = (int *)__vbaObjSet(&local_40,uVar7);
        iVar5 = (**(code **)(*piVar6 + 0xa8))(piVar6,&stack0xffffffd8);
        if (iVar5 < 0) {
          __vbaHresultCheckObj(iVar5,piVar6,&DAT_00446e04,0xa8);
        }
        uVar7 = (*(code *)(*ppppppwVar9)[199])(ppppppwVar9);
        pppppwVar4 = (wchar_t *****)__vbaObjSet(&local_44,uVar7);
        iVar5 = (*(code *)(*pppppwVar4)[0x2a])(pppppwVar4,&stack0xffffffd4);
        if (iVar5 < 0) {
          local_90 = (wchar_t ******)0xa8;
          local_94 = (wchar_t *****)&DAT_00446e04;
          local_98 = pppppwVar4;
          __vbaHresultCheckObj(iVar5);
        }
        local_94 = (wchar_t *****)&DAT_0043ff54;
        local_98 = (wchar_t *****)0x6bfdcf;
        local_90 = (wchar_t ******)(wchar_t ****)0x0;
        __vbaStrCat();
        local_90 = (wchar_t ******)0x6bfdda;
        local_90 = (wchar_t ******)__vbaStrMove();
        local_98 = (wchar_t *****)0x6bfde5;
        __vbaStrCat();
        local_90 = (wchar_t ******)0x6bfdf0;
        local_90 = (wchar_t ******)__vbaStrMove();
        local_94 = (wchar_t *****)0x6bfdf7;
        rtcTrimBstr();
        local_90 = (wchar_t ******)0x6bfe04;
        __vbaStrMove();
        local_90 = (wchar_t ******)&local_34;
        local_94 = (wchar_t *****)&stack0xffffffd4;
        local_98 = (wchar_t *****)&stack0xffffffd0;
        __vbaFreeStrList(4,&stack0xffffffd8);
        local_90 = &local_44;
        local_94 = (wchar_t *****)&local_40;
        local_98 = (wchar_t *****)0x2;
        __vbaFreeObjList();
      }
      if (DAT_0073a0aa != 0) {
        local_8 = 0x15;
        local_90 = &local_40;
        local_94 = (wchar_t *****)0x454318;
        local_98 = (wchar_t *****)DAT_0073a08c;
        iVar5 = (*(code *)(*DAT_0073a08c)[0x19])();
        if (iVar5 < 0) {
          local_90 = (wchar_t ******)0x64;
          local_94 = (wchar_t *****)&DAT_004419ac;
          local_98 = (wchar_t *****)DAT_0073a08c;
          __vbaHresultCheckObj(iVar5);
        }
        local_90 = (wchar_t ******)0x6bfedc;
        __vbaFreeObj();
      }
      local_8 = 0x17;
      local_90 = &local_40;
      local_94 = (wchar_t *****)0x45a554;
      local_98 = (wchar_t *****)DAT_0073a08c;
      iVar5 = (*(code *)(*DAT_0073a08c)[0x19])();
      if (iVar5 < 0) {
        __vbaHresultCheckObj(100,DAT_0073a08c,&DAT_004419ac,100);
      }
      __vbaFreeObj();
      local_8 = 0x18;
      iVar5 = (*(code *)(*DAT_0073a08c)[0x19])(DAT_0073a08c,L"WriteReturn",&local_40);
      if (iVar5 < 0) {
        __vbaHresultCheckObj(iVar5,DAT_0073a08c,&DAT_004419ac,100);
      }
      __vbaFreeObj();
      local_8 = 0x19;
      if (DAT_0073c818 == (wchar_t ****)0x0) {
        __vbaNew2(&DAT_00441f00,&DAT_0073c818);
      }
      ppppppwVar2 = (wchar_t ******)DAT_0073c818;
      uVar7 = __vbaObjSetAddref(&local_40,ppppppwVar9);
      ppppwVar3 = (wchar_t ****)(*(code *)(*ppppppwVar2)[4])(ppppppwVar2,uVar7);
      if ((int)ppppwVar3 < 0) {
        pppppwStack_58 = (wchar_t *****)0x10;
        pppppwStack_5c = (wchar_t *****)&DAT_00441ef0;
        ppppppwStack_68 = (wchar_t ******)0x6c003d;
        local_64 = ppppwVar3;
        ppppppwStack_60 = ppppppwVar2;
        __vbaHresultCheckObj();
      }
      pppppwStack_58 = (wchar_t *****)0x6c0058;
      __vbaFreeObj();
    }
  }
  else {
    local_8 = 4;
    local_3c = &local_40;
    local_40 = (wchar_t *****)0x442914;
    local_44 = (wchar_t *****)DAT_0073a08c;
    ppppppwStack_48 = (wchar_t ******)0x6bf459;
    ppppppwVar2 = (wchar_t ******)(*(code *)(*DAT_0073a08c)[0x19])();
    if ((int)ppppppwVar2 < 0) {
      ppppppwStack_48 = (wchar_t ******)0x64;
      local_4c = (wchar_t ****)&DAT_004419ac;
      ppppppwStack_50 = (wchar_t ******)DAT_0073a08c;
      pppppwStack_58 = (wchar_t *****)0x6bf485;
      local_54 = ppppppwVar2;
      __vbaHresultCheckObj();
    }
    ppppppwStack_48 = (wchar_t ******)0x6bf4a0;
    __vbaFreeObj();
    local_8 = 5;
    local_8c = (wchar_t ******)0x80020004;
    local_94 = (wchar_t *****)0xa;
    local_7c = (wchar_t ****)0x46d09c;
    local_88._4_4_ = (wchar_t ******)0x8;
    ppppppwStack_48 = &local_40;
    local_4c = (wchar_t ****)0x6bf4d7;
    __vbaChkstk();
    ppppppwStack_48 = (wchar_t ******)local_94;
    local_44 = (wchar_t *****)local_90;
    local_40 = (wchar_t *****)local_8c;
    local_3c = (wchar_t ******)local_88;
    local_4c = (wchar_t ****)0x6bf506;
    __vbaChkstk();
    ppppppwStack_48 = local_88._4_4_;
    local_44 = (wchar_t *****)local_80;
    local_40 = (wchar_t *****)local_7c;
    local_3c = local_78;
    local_4c = DAT_0073a08c;
    ppppppwStack_50 = (wchar_t ******)0x6bf531;
    ppppwVar3 = (wchar_t ****)(*(code *)(*DAT_0073a08c)[0x1e])();
    if ((int)ppppwVar3 < 0) {
      ppppppwStack_50 = (wchar_t ******)0x78;
      local_54 = (wchar_t ******)&DAT_004419ac;
      pppppwStack_58 = (wchar_t *****)DAT_0073a08c;
      ppppppwStack_60 = (wchar_t ******)0x6bf55d;
      pppppwStack_5c = (wchar_t *****)ppppwVar3;
      __vbaHresultCheckObj();
    }
    ppppppwStack_50 = (wchar_t ******)0x6bf578;
    __vbaFreeObj();
    local_8 = 6;
    local_54 = (wchar_t ******)0x6bf58e;
    ppppppwStack_50 = ppppppwVar9;
    local_54 = (wchar_t ******)(*(code *)(*ppppppwVar9)[0xc2])();
    pppppwStack_58 = (wchar_t *****)&local_40;
    pppppwStack_5c = (wchar_t *****)0x6bf599;
    ppppppwVar9 = (wchar_t ******)__vbaObjSet();
    pppppwStack_58 = (wchar_t *****)0x6bf5b4;
    local_54 = ppppppwVar9;
    ppppwVar3 = (wchar_t ****)(*(code *)(*ppppppwVar9)[0x81])();
    if ((int)ppppwVar3 < 0) {
      pppppwStack_58 = (wchar_t *****)0x204;
      pppppwStack_5c = (wchar_t *****)&DAT_0043f42c;
      ppppppwStack_68 = (wchar_t ******)0x6bf5e3;
      local_64 = ppppwVar3;
      ppppppwStack_60 = ppppppwVar9;
      __vbaHresultCheckObj();
    }
    pppppwStack_58 = (wchar_t *****)0x6bf5fe;
    __vbaFreeObj();
  }
  return;
}


// ---- cmdDelete_Click @ 006c0230

/* WARNING: Restarted to delay deadcode elimination for space: ram */

void frmAppointment::cmdDelete_Click(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  ushort in_FPUStatusWord;
  float10 fVar4;
  float10 fVar5;
  undefined4 local_50;
  int iStack_4c;
  int *piStack_48;
  undefined4 **ppuStack_44;
  undefined4 *local_40;
  undefined8 uStack_3c;
  int *piStack_34;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_0040cd40;
  local_14 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  local_10 = 0;
  uStack_3c = (double)CONCAT44(0x6c0285,(undefined4)uStack_3c);
  piStack_34 = piVar3;
  (**(code **)(*piVar3 + 4))();
  local_8 = 2;
  uStack_3c = -NAN;
  __vbaOnError();
  local_8 = 3;
  uStack_3c = (double)CONCAT44(0x6c02b3,(undefined4)uStack_3c);
  __vbaStrCopy();
  local_8 = 4;
  uStack_3c = (double)CONCAT44(0x6c02cb,(undefined4)uStack_3c);
  __vbaStrCopy();
  local_8 = 5;
  uStack_3c = (double)CONCAT44(0x6c02ec,(undefined4)uStack_3c);
  __vbaVarDup();
  uStack_3c = (double)CONCAT44(0x6c0306,(undefined4)uStack_3c);
  __vbaVarDup();
  uStack_3c = 2.12199579145934e-314;
  local_40 = &local_50;
  ppuStack_44 = &local_40;
  piStack_48 = (int *)0x6c0318;
  rtcBstrFromFormatVar();
  uStack_3c = (double)CONCAT44(0x6c0323,(undefined4)uStack_3c);
  __vbaStrMove();
  uStack_3c = (double)CONCAT44(piVar3[0xe],0x6c0340);
  fVar4 = (float10)__vbaDateStr();
  uStack_3c = (double)CONCAT44(0x6c0355,(undefined4)uStack_3c);
  uVar1 = __vbaStrMove();
  uStack_3c = (double)CONCAT44(uVar1,0x6c035c);
  fVar5 = (float10)__vbaDateStr();
  if ((in_FPUStatusWord & 0xd) != 0) {
    __vbaFPException();
    return;
  }
  uStack_3c = (double)(fVar5 + (float10)(double)fVar4);
  local_40 = (undefined4 *)0x6c0378;
  fVar4 = (float10)__vbaDateR8();
  uStack_3c = (double)fVar4;
  local_40 = (undefined4 *)0x6c0384;
  __vbaStrDate();
  uStack_3c = (double)CONCAT44(0x6c0391,(undefined4)uStack_3c);
  __vbaStrMove();
  uStack_3c = (double)CONCAT44(&stack0xffffffd4,&stack0xffffffd8);
  local_40 = (undefined4 *)0x2;
  ppuStack_44 = (undefined4 **)0x6c03a1;
  __vbaFreeStrList();
  uStack_3c = (double)CONCAT44(&local_50,&local_40);
  local_40 = (undefined4 *)0x2;
  ppuStack_44 = (undefined4 **)0x6c03b4;
  __vbaFreeVarList();
  local_8 = 6;
  uStack_3c = (double)CONCAT44(0x6c03cf,(undefined4)uStack_3c);
  __vbaStrCopy();
  local_8 = 7;
  uStack_3c = (double)CONCAT44(0x6c03e7,(undefined4)uStack_3c);
  __vbaStrCopy();
  local_8 = 8;
  if (DAT_0073c818 == (int *)0x0) {
    uStack_3c = 1.7606222858108195e-306;
    local_40 = (undefined4 *)0x6c0407;
    __vbaNew2();
  }
  piVar3 = DAT_0073c818;
  uStack_3c = (double)(CONCAT44(param_1,&stack0xffffffd0) & 0xfffffffeffffffff);
  local_40 = (undefined4 *)0x6c0436;
  uVar1 = __vbaObjSetAddref();
  uStack_3c = (double)CONCAT44(uVar1,piVar3);
  local_40 = (undefined4 *)0x6c0443;
  iVar2 = (**(code **)(*piVar3 + 0x10))();
  if (iVar2 < 0) {
    local_40 = (undefined4 *)0x10;
    ppuStack_44 = (undefined4 **)&DAT_00441ef0;
    local_50 = 0x6c0463;
    iStack_4c = iVar2;
    piStack_48 = piVar3;
    __vbaHresultCheckObj();
  }
  local_40 = (undefined4 *)0x6c047e;
  __vbaFreeObj();
  return;
}


// ---- Form_Activate @ 006c04f0

void frmAppointment::Form_Activate(uint param_1)

{
  int iVar1;
  undefined4 uVar2;
  int *piVar3;
  int *piVar4;
  undefined4 unaff_EBX;
  undefined4 unaff_ESI;
  int **local_40;
  undefined1 *local_3c;
  int *local_38;
  int *local_34;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_0040cd88;
  local_14 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  local_10 = 0;
  local_38 = (int *)0x6c0545;
  local_34 = piVar4;
  (**(code **)(*piVar4 + 4))();
  local_8 = 2;
  local_38 = (int *)0xffffffff;
  local_3c = (undefined1 *)0x6c055b;
  __vbaOnError();
  local_8 = 3;
  local_3c = (undefined1 *)0x6c0571;
  local_38 = piVar4;
  local_3c = (undefined1 *)(**(code **)(*piVar4 + 0x318))();
  local_40 = &local_38;
  local_40 = (int **)__vbaObjSet();
  local_3c = &stack0xffffffd8;
  iVar1 = (*(code *)(*local_40)[0x28])();
  if (iVar1 < 0) {
    __vbaHresultCheckObj(&DAT_0043f42c,0xa0,&DAT_0043f42c,0xa0);
  }
  rtcTrimBstr(unaff_EBX);
  __vbaStrMove();
  __vbaStrCopy();
  __vbaFreeStrList(2,&stack0xffffffd8,&stack0xffffffd4);
  __vbaFreeObj();
  local_8 = 4;
  uVar2 = (**(code **)(*piVar4 + 0x310))(piVar4);
  piVar3 = (int *)__vbaObjSet(&local_38,uVar2);
  iVar1 = (**(code **)(*piVar3 + 0xa8))(piVar3,&stack0xffffffd8);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0xa8);
  }
  uVar2 = (**(code **)(*piVar4 + 0x314))(piVar4);
  piVar3 = (int *)__vbaObjSet(&local_3c,uVar2);
  iVar1 = (**(code **)(*piVar3 + 0xa8))(piVar3,&stack0xffffffd4);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0xa8);
  }
  __vbaStrCat(&DAT_0043ff54,unaff_EBX);
  uVar2 = __vbaStrMove();
  __vbaStrCat(unaff_ESI,uVar2);
  __vbaStrMove();
  __vbaStrCopy();
  __vbaFreeStrList(4,&stack0xffffffd8,&stack0xffffffd0,&stack0xffffffd4,&local_34);
  __vbaFreeObjList(2,&local_38,&local_3c);
  local_8 = 5;
  uVar2 = (**(code **)(*piVar4 + 0x308))(piVar4);
  piVar3 = (int *)__vbaObjSet(&local_38,uVar2);
  iVar1 = (**(code **)(*piVar3 + 0xa0))(piVar3,&stack0xffffffd8);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_0043f42c,0xa0);
  }
  __vbaStrCopy();
  __vbaFreeStr();
  __vbaFreeObj();
  local_8 = 6;
  uVar2 = (**(code **)(*piVar4 + 800))(piVar4);
  piVar3 = (int *)__vbaObjSet(&local_38,uVar2);
  iVar1 = (**(code **)(*piVar3 + 0xa8))(piVar3,&stack0xffffffd8);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0xa8);
  }
  uVar2 = (**(code **)(*piVar4 + 0x31c))(piVar4);
  piVar3 = (int *)__vbaObjSet(&local_3c,uVar2);
  iVar1 = (**(code **)(*piVar3 + 0xa8))(piVar3,&stack0xffffffd4);
  if (iVar1 < 0) {
    uVar2 = __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0xa8);
  }
  else {
    uVar2 = 0;
  }
  __vbaStrCat(&DAT_0043ff54,unaff_EBX);
  uVar2 = __vbaStrMove(uVar2);
  __vbaStrCat(unaff_ESI,uVar2);
  __vbaStrMove();
  __vbaStrCopy();
  __vbaFreeStrList(4,&stack0xffffffd8,&stack0xffffffd0,&stack0xffffffd4,&local_34);
  __vbaFreeObjList(2,&local_38,&local_3c);
  if (DAT_0073a0aa != 0) {
    local_8 = 8;
    local_40 = (int **)((uint)local_40 & 0xffff0000);
    uVar2 = __vbaCastObj(piVar4,&DAT_00440b00);
    __vbaObjSet(&local_38,uVar2);
    iVar1 = (**(code **)(*DAT_0073a218 + 0x20))(DAT_0073a218,&local_38,&local_40);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_0073a218,&DAT_00440b10,0x20);
    }
    __vbaFreeObj();
  }
  return;
}


// ---- Form_Load @ 006c09e0

void frmAppointment::Form_Load(uint param_1)

{
  int iVar1;
  undefined4 uVar2;
  int *piVar3;
  int *piVar4;
  int *piVar5;
  undefined4 unaff_ESI;
  undefined4 uVar6;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_0040cdd0;
  local_14 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  local_10 = 0;
  piVar3 = piVar5;
  (**(code **)(*piVar5 + 4))();
  local_8 = 2;
  __vbaOnError(0xffffffff);
  local_8 = 3;
  iVar1 = (**(code **)(*piVar5 + 0x1d4))(piVar5,0xffffffff);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar5,&DAT_00456008,0x1d4);
  }
  local_8 = 4;
  piVar4 = piVar5;
  uVar2 = (**(code **)(*piVar5 + 0x310))(piVar5);
  uVar2 = __vbaObjSet(&stack0xffffffd8,uVar2);
  uVar6 = 10;
  __vbaChkstk(piVar4,uVar2,10);
  uVar2 = unaff_ESI;
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"12:00",uVar6,piVar3,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 5;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"12:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 6;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"1:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 7;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar4 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  piVar3 = piVar4;
  iVar1 = (**(code **)(*piVar4 + 0x1ec))(piVar4,L"1:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    uVar6 = __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  else {
    uVar6 = 0;
  }
  __vbaFreeObj(piVar4,uVar6);
  local_8 = 8;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"2:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 9;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"2:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 10;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"3:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0xb;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"3:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0xc;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"4:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0xd;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"4:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0xe;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"5:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0xf;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"5:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x10;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"6:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x11;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"6:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x12;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"7:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x13;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"7:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x14;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"8:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x15;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"8:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x16;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"9:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x17;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"9:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x18;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"10:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x19;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"10:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x1a;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"11:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x1b;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"11:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x1c;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"12:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x1d;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"12:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x1e;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"1:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x1f;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"1:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x20;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"2:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x21;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"2:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x22;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"3:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x23;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"3:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x24;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"4:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x25;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"4:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x26;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"5:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x27;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"5:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x28;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"6:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x29;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"6:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x2a;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"7:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x2b;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"7:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x2c;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"8:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x2d;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"8:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x2e;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"9:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x2f;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"9:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x30;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"10:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x31;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"10:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x32;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"11:00",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x33;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,L"11:30",uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x34;
  uVar6 = (**(code **)(*piVar5 + 800))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  iVar1 = (**(code **)(*piVar3 + 0xac))(piVar3,L"12:00");
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0xac);
  }
  __vbaFreeObj();
  local_8 = 0x35;
  uVar6 = (**(code **)(*piVar5 + 0x310))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  iVar1 = (**(code **)(*piVar3 + 0xac))(piVar3,L"12:00");
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0xac);
  }
  __vbaFreeObj();
  local_8 = 0x36;
  uVar6 = (**(code **)(*piVar5 + 0x31c))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,&PTR_DAT_0046b2c8,uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x37;
  uVar6 = (**(code **)(*piVar5 + 0x31c))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,&PTR_DAT_0046c924,uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x38;
  uVar6 = (**(code **)(*piVar5 + 0x31c))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  iVar1 = (**(code **)(*piVar3 + 0xac))(piVar3,&PTR_DAT_0046b2c8);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0xac);
  }
  __vbaFreeObj();
  local_8 = 0x39;
  uVar6 = (**(code **)(*piVar5 + 0x314))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,&PTR_DAT_0046b2c8,uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x3a;
  uVar6 = (**(code **)(*piVar5 + 0x314))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar6);
  uVar6 = 10;
  __vbaChkstk();
  iVar1 = (**(code **)(*piVar3 + 0x1ec))(piVar3,&PTR_DAT_0046c924,uVar6,uVar2,0x80020004,unaff_ESI);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0x1ec);
  }
  __vbaFreeObj();
  local_8 = 0x3b;
  uVar2 = (**(code **)(*piVar5 + 0x314))(piVar5);
  piVar3 = (int *)__vbaObjSet(&stack0xffffffd8,uVar2);
  iVar1 = (**(code **)(*piVar3 + 0xac))(piVar3,&PTR_DAT_0046b2c8);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar3,&DAT_00446e04,0xac);
  }
  __vbaFreeObj();
  return;
}


// ---- Form_Unload @ 006c2e50

void frmAppointment::Form_Unload(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_0040cee0;
  local_8 = param_1 & 1;
  ExceptionList = &pvStack_18;
  (**(code **)(*(int *)(param_1 & 0xfffffffe) + 4))((int *)(param_1 & 0xfffffffe));
  local_1c = 0;
  DAT_0073a0aa = 0;
  local_20 = 0;
  if (DAT_0073a310 == 0) {
    __vbaNew2(&DAT_0041ed48,&DAT_0073a310);
  }
  uVar1 = __vbaCastObj(DAT_0073a310,&DAT_00440b00);
  __vbaObjSet(&local_1c,uVar1);
  iVar2 = (**(code **)(*DAT_0073a218 + 0x20))(DAT_0073a218,&local_1c,&local_20);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,DAT_0073a218,&DAT_00440b10,0x20);
  }
  uVar1 = __vbaCastObj(local_1c,&DAT_00446d6c);
  __vbaObjSet(&DAT_0073a310,uVar1);
  __vbaFreeObj();
  return;
}


