// BonziBDY_4.EXE :: frmBBIMDialog
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 3

// ---- CancelButton_Click @ 006e52e0

void frmBBIMDialog::CancelButton_Click(uint param_1)

{
  int *piVar1;
  int iVar2;
  undefined4 uVar3;
  int *piVar4;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc4;
  local_c = &DAT_0040e750;
  local_8 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar4 + 4))(piVar4);
  local_1c = 0;
  if (DAT_0073a614 == (int *)0x0) {
    __vbaNew2(&DAT_004283e0,&DAT_0073a614);
  }
  piVar1 = DAT_0073a614;
  iVar2 = (**(code **)(*DAT_0073a614 + 0x728))
                    (DAT_0073a614,L"This is what is returned when the user clicks cancel!");
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar1,&DAT_00455054,0x728);
  }
  if (DAT_0073c818 == (int *)0x0) {
    __vbaNew2(&DAT_00441f00,&DAT_0073c818);
  }
  piVar1 = DAT_0073c818;
  iVar2 = *DAT_0073c818;
  uVar3 = __vbaObjSetAddref(&local_1c,piVar4);
  iVar2 = (**(code **)(iVar2 + 0x10))(piVar1,uVar3);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar1,&DAT_00441ef0,0x10);
  }
  __vbaFreeObj();
  return;
}


// ---- Form_Load @ 006e5400

undefined4 frmBBIMDialog::Form_Load(uint param_1)

{
  int *piVar1;
  int *piVar2;
  int iVar3;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffcc;
  local_c = &DAT_0040e760;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  if (DAT_0073a614 == (int *)0x0) {
    __vbaNew2(&DAT_004283e0,&DAT_0073a614);
  }
  piVar1 = DAT_0073a614;
  iVar3 = (**(code **)(*DAT_0073a614 + 0x728))(DAT_0073a614,&DAT_0043c9f4);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar1,&DAT_00455054,0x728);
  }
  local_8 = 0;
  (**(code **)(*piVar2 + 8))(piVar2);
  ExceptionList = local_18;
  return local_8;
}


// ---- OKButton_Click @ 006e54b0

void frmBBIMDialog::OKButton_Click(uint param_1)

{
  int *piVar1;
  undefined4 uVar2;
  int *piVar3;
  int iVar4;
  int *piVar5;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffb8;
  local_c = &DAT_0040e768;
  local_8 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar5 + 4))(piVar5);
  local_1c = 0;
  local_20 = 0;
  if (DAT_0073a614 == (int *)0x0) {
    __vbaNew2(&DAT_004283e0,&DAT_0073a614);
  }
  piVar1 = DAT_0073a614;
  uVar2 = (**(code **)(*piVar5 + 0x2fc))(piVar5);
  piVar3 = (int *)__vbaObjSet(&local_20,uVar2);
  iVar4 = (**(code **)(*piVar3 + 0xa0))(piVar3,&local_1c);
  if (iVar4 < 0) {
    __vbaHresultCheckObj(iVar4,piVar3,&DAT_0043f42c,0xa0);
  }
  iVar4 = (**(code **)(*piVar1 + 0x728))(piVar1,local_1c);
  if (iVar4 < 0) {
    __vbaHresultCheckObj(iVar4,piVar1,&DAT_00455054,0x728);
  }
  __vbaFreeStr();
  __vbaFreeObj();
  if (DAT_0073c818 == (int *)0x0) {
    __vbaNew2(&DAT_00441f00,&DAT_0073c818);
  }
  piVar1 = DAT_0073c818;
  iVar4 = *DAT_0073c818;
  uVar2 = __vbaObjSetAddref(&local_20,piVar5);
  iVar4 = (**(code **)(iVar4 + 0x10))(piVar1,uVar2);
  if (iVar4 < 0) {
    __vbaHresultCheckObj(iVar4,piVar1,&DAT_00441ef0,0x10);
  }
  __vbaFreeObj();
  return;
}


