// BonziBDY_4.EXE :: frmGoldPasswordEntry
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 2

// ---- cmdCancel_Click @ 007280b0

undefined4 frmGoldPasswordEntry::cmdCancel_Click(uint param_1)

{
  int iVar1;
  int *piVar2;
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00412150;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  *(undefined2 *)(piVar2 + 0xd) = 0;
  iVar1 = (**(code **)(*piVar2 + 0x2b4))(piVar2);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar2,&DAT_004762d4,0x2b4);
  }
  local_8 = 0;
  (**(code **)(*piVar2 + 8))(piVar2);
  ExceptionList = local_18;
  return local_8;
}


// ---- cmdOK_Click @ 00728140

void frmGoldPasswordEntry::cmdOK_Click(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  undefined4 uVar4;
  int *piVar5;
  undefined4 local_50;
  undefined4 local_48;
  undefined4 local_40;
  undefined4 local_38;
  undefined4 local_34 [2];
  undefined4 local_2c;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff8c;
  local_c = &DAT_00412158;
  local_8 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar5 + 4))(piVar5);
  local_1c = 0;
  local_20 = 0;
  local_24 = 0;
  local_34[0] = 0;
  uVar1 = (**(code **)(*piVar5 + 0x304))(piVar5);
  piVar2 = (int *)__vbaObjSet(&local_24,uVar1);
  iVar3 = (**(code **)(*piVar2 + 0xa0))(piVar2,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_0043f42c,0xa0);
  }
  uVar1 = local_1c;
  rtcGetSetting(L"BonziBUDDY",L"UserInfo",L"GoldPass",8,local_40,&DAT_0043c9f4,local_38);
  uVar4 = __vbaStrMove(uVar1);
  iVar3 = __vbaStrCmp(uVar4,uVar1);
  __vbaFreeStrList(2,&local_1c,&local_20);
  __vbaFreeObj();
  if (iVar3 == 0) {
    *(undefined2 *)(piVar5 + 0xd) = 0xffff;
    iVar3 = (**(code **)(*piVar5 + 0x2b4))(piVar5);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar5,&DAT_004762d4,0x2b4);
    }
  }
  else {
    iVar3 = (**(code **)(*DAT_0073a08c + 100))(DAT_0073a08c,&DAT_004522e4,&local_24);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,DAT_0073a08c,&DAT_004419ac,100);
    }
    __vbaFreeObj();
    iVar3 = (**(code **)(*DAT_0073a08c + 0x78))
                      (DAT_0073a08c,8,local_40,L"Invalid password, please try again!",local_38,10,
                       local_50,0x80020004,local_48,&local_24);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,DAT_0073a08c,&DAT_004419ac,0x78);
    }
    __vbaFreeObj();
    uVar1 = (**(code **)(*piVar5 + 0x304))(piVar5);
    piVar2 = (int *)__vbaObjSet(&local_24,uVar1);
    iVar3 = (**(code **)(*piVar2 + 0x204))(piVar2);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar2,&DAT_0043f42c,0x204);
    }
    __vbaFreeObj();
    local_2c = 0x80020004;
    local_34[0] = 10;
    rtcSendKeys(L"{Home}+{End}",local_34);
    __vbaFreeVar();
  }
  return;
}


