// BonziBDY_4.EXE :: frmNBProgress
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 3

// ---- Form_Load @ 006ceef0

void frmNBProgress::Form_Load(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_0040d648;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  local_1c = 0;
  uVar1 = (**(code **)(*piVar3 + 0x2fc))(piVar3);
  piVar3 = (int *)__vbaObjSet(&local_1c,uVar1);
  iVar2 = (**(code **)(*piVar3 + 100))(piVar3,1000);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar3,&DAT_00441ed0,100);
  }
  __vbaFreeObj();
  return;
}


// ---- Form_Unload @ 006cefb0

void frmNBProgress::Form_Unload(uint param_1)

{
  int iVar1;
  int ****ppppiVar2;
  undefined4 local_64 [2];
  undefined4 local_5c;
  undefined4 local_54;
  undefined4 uStack_50;
  int ***local_4c;
  int ***pppiStack_48;
  int ****local_44;
  undefined4 *puStack_40;
  undefined4 *puStack_3c;
  int ***pppiStack_38;
  int ***local_34;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined1 *local_18;
  uint local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &LAB_0040d658;
  local_14 = param_1 & 1;
  ppppiVar2 = (int ****)(param_1 & 0xfffffffe);
  local_10 = 0;
  pppiStack_38 = (int ***)0x6cf005;
  local_34 = (int ***)ppppiVar2;
  (*(code *)(*ppppiVar2)[1])();
  local_8 = 2;
  pppiStack_38 = (int ***)0xffffffff;
  puStack_3c = (undefined4 *)0x6cf01b;
  __vbaOnError();
  local_8 = 3;
  puStack_3c = (undefined4 *)0x6cf031;
  pppiStack_38 = (int ***)ppppiVar2;
  iVar1 = (*(code *)(*ppppiVar2)[0xad])();
  if (iVar1 < 0) {
    puStack_3c = (undefined4 *)0x2b4;
    puStack_40 = (undefined4 *)&DAT_00456818;
    local_4c = (int ***)0x6cf05d;
    pppiStack_48 = (int ***)iVar1;
    local_44 = ppppiVar2;
    __vbaHresultCheckObj();
  }
  local_8 = 4;
  local_5c = 0x80020004;
  local_64[0] = 10;
  local_4c = (int ***)0x80020004;
  local_54 = 10;
  puStack_3c = (undefined4 *)0x6cf0ac;
  __vbaVarDup();
  puStack_3c = (undefined4 *)0x6cf0c6;
  __vbaVarDup();
  puStack_3c = local_64;
  puStack_40 = &local_54;
  local_44 = (int ****)&local_44;
  pppiStack_48 = (int ***)0x40;
  local_4c = (int ***)&local_34;
  uStack_50 = 0x6cf0de;
  rtcMsgBox();
  puStack_3c = local_64;
  puStack_40 = &local_54;
  local_44 = (int ****)&local_44;
  pppiStack_48 = (int ***)&local_34;
  local_4c = (int ***)0x4;
  uStack_50 = 0x6cf0f6;
  __vbaFreeVarList();
  return;
}


// ---- Timer1_Timer @ 006cf150

/* WARNING: Restarted to delay deadcode elimination for space: ram */
/* WARNING: Restarted to delay deadcode elimination for space: stack */

void frmNBProgress::Timer1_Timer(uint param_1)

{
  undefined *puVar1;
  int *piVar2;
  int ******ppppppiVar3;
  int iVar4;
  undefined4 uVar5;
  wchar_t *****pppppwVar6;
  short sVar7;
  wchar_t *****unaff_ESI;
  int *piVar8;
  wchar_t *pwVar9;
  wchar_t **ppwVar10;
  short sVar11;
  wchar_t *****in_stack_fffffee4;
  int ******ppppppiStack_118;
  int ******ppppppiStack_114;
  wchar_t ******ppppppwStack_108;
  int ******ppppppiStack_e8;
  int ******ppppppiStack_e4;
  wchar_t *pwStack_d8;
  int ******ppppppiStack_c4;
  wchar_t *pwStack_c0;
  int ******ppppppiStack_b8;
  wchar_t *pwStack_b4;
  int *piStack_9c;
  int *piStack_98;
  undefined4 *puStack_94;
  void *pvStack_90;
  undefined1 *puStack_8c;
  int *piStack_88;
  int *piStack_84;
  undefined *puStack_80;
  int *piStack_7c;
  int *piStack_78;
  int **ppiStack_74;
  int *piStack_70;
  undefined4 local_28;
  undefined4 local_24;
  void *pvStack_20;
  undefined1 *puStack_1c;
  undefined1 *local_18;
  undefined *local_14;
  uint local_10;
  undefined4 local_c;
  
  puStack_1c = &LAB_00412856;
  pvStack_20 = ExceptionList;
  local_18 = &stack0xffffff94;
  local_14 = &DAT_0040d690;
  local_10 = param_1 & 1;
  piVar8 = (int *)(param_1 & 0xfffffffe);
  local_c = 0;
  ppiStack_74 = (int **)0x6cf195;
  ExceptionList = &pvStack_20;
  piStack_70 = piVar8;
  (**(code **)(*piVar8 + 4))();
  local_24 = 0;
  ppiStack_74 = (int **)0x1;
  piStack_78 = (int *)0x6cf1a3;
  __vbaOnError();
  sVar7 = (short)piVar8[0xd];
  if (sVar7 == 0) {
    sVar7 = 0x1e;
    *(undefined2 *)((int)piVar8 + 0x36) = 0x1e;
  }
  else {
    ppiStack_74 = (int **)piVar8;
    if (sVar7 == 0x1e) {
      piStack_78 = (int *)0x6cf1c9;
      piStack_78 = (int *)(**(code **)(*piVar8 + 0x2fc))();
      piStack_7c = &local_24;
      puStack_80 = (undefined *)0x6cf1d4;
      piVar2 = (int *)__vbaObjSet();
      piStack_78 = (int *)0x1f4;
      puStack_80 = (undefined *)0x6cf1e1;
      piStack_7c = piVar2;
      puVar1 = (undefined *)(**(code **)(*piVar2 + 100))();
      if ((int)puVar1 < 0) {
        ppiStack_74 = (int **)0x64;
        piStack_78 = (int *)&DAT_00441ed0;
        piStack_84 = (int *)0x6cf1f6;
        puStack_80 = puVar1;
        piStack_7c = piVar2;
        __vbaHresultCheckObj();
      }
      ppiStack_74 = (int **)0x6cf1ff;
      __vbaFreeObj();
      *(undefined2 *)((int)piVar8 + 0x36) = 0x14;
      if (SCARRY2((short)piVar8[0xd],0x14)) {
LAB_006cf43b:
        ppiStack_74 = (int **)0x6cf441;
        __vbaErrorOverflow();
        puStack_8c = &LAB_00412856;
        pvStack_90 = ExceptionList;
        puStack_94 = (undefined4 *)0x6cf473;
        ExceptionList = &pvStack_90;
        piStack_70 = (int *)&stack0xfffffffc;
        __vbaChkstk();
        puStack_94 = (undefined4 *)0x0;
        piStack_88 = (int *)&piStack_9c;
        piStack_84 = (int *)&LAB_0040d6b8;
        puStack_80 = (undefined *)0x0;
        piStack_7c = (int *)0x0;
        piStack_9c = piVar2;
        piStack_98 = piVar8;
        (*(code *)(*unaff_ESI)[1])();
        ppiStack_74 = (int **)0x2;
        __vbaOnError();
        ppiStack_74 = (int **)0x3;
        (*(code *)(*unaff_ESI)[0xcd])();
        ppppppiVar3 = (int ******)__vbaObjSet();
        iVar4 = (*(code *)(*ppppppiVar3)[0x38])();
        if (iVar4 < 0) {
          pwStack_b4 = L"企㎭暙ᇏಷꨀ怀鏓\b";
          pwStack_c0 = L"薉Ｌ\xffff૫藇Ｌ\xffff";
          ppppppiStack_b8 = ppppppiVar3;
          __vbaHresultCheckObj();
        }
        sVar11 = (short)in_stack_fffffee4;
        sVar7 = -(ushort)(sVar11 == -1);
        __vbaFreeObj();
        if (sVar7 != 0) {
          ppiStack_74 = (int **)0x4;
          pwStack_b4 = 
          L"赐걅ｐ⠕䀑褀傅\xffff棿\xe870F趋ｐ\xffffᆋ薋ｐ\xffffｐ呒\xe2db薉ｌ\xffff붃ｌ\xffff紀樣桔ㅨD趋ｐ\xffff譑䲕\xffff勿ᗿ჌@薉Ｈ\xffff૫藇Ｈ\xffff"
          ;
          pwStack_b4 = (wchar_t *)(*(code *)(*unaff_ESI)[0xcb])();
          ppppppiStack_b8 = (int ******)&ppppppiStack_c4;
          ppppppiVar3 = (int ******)__vbaObjSet();
          pwStack_b4 = L"Time to Live (TTL=32)";
          ppppppiStack_b8 = ppppppiVar3;
          iVar4 = (*(code *)(*ppppppiVar3)[0x15])();
          if (iVar4 < 0) {
            pwStack_c0 = L"仩㎭暙ᇏಷꨀ怀鏓\x10";
            ppppppiStack_c4 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x5;
          pwStack_c0 = L"赐걅ｐ⠕䀑褀傅\xffff櫿诿傍\xffff诿謑傅\xffff僿鋿ä";
          pwStack_c0 = (wchar_t *)(*(code *)(*unaff_ESI)[0xcd])();
          ppppppiStack_c4 = (int ******)&ppppppiStack_c4;
          ppppppiStack_c4 = (int ******)__vbaObjSet();
          pwStack_c0 = (wchar_t *)0xffffffff;
          iVar4 = (*(code *)(*ppppppiStack_c4)[0x39])();
          if (iVar4 < 0) {
            pwStack_d8 = L"薉Ｄ\xffff૫藇Ｄ\xffff";
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x6;
          (*(code *)(*unaff_ESI)[0xcf])();
          ppppppiVar3 = (int ******)__vbaObjSet();
          iVar4 = (*(code *)(*ppppppiVar3)[0x23])();
          if (iVar4 < 0) {
            pwStack_b4 = L"仡㎭暙ᇏಷꨀ怀鏓湭䵵楡n";
            pwStack_c0 = L"薉＠\xffff૫藇＠\xffff";
            ppppppiStack_b8 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
        }
        ppiStack_74 = (int **)0x8;
        pwStack_b4 = 
        L"赐걅ｐ⠕䀑褀傅\xffff跿咍\xffff凿開ｐ\xffffʋ趋ｐ\xffffｑ\xe090";
        pwStack_b4 = (wchar_t *)(*(code *)(*unaff_ESI)[0xce])();
        ppppppiStack_b8 = (int ******)&ppppppiStack_c4;
        ppppppiVar3 = (int ******)__vbaObjSet();
        pwStack_b4 = (wchar_t *)&stack0xfffffee4;
        ppppppiStack_b8 = ppppppiVar3;
        iVar4 = (*(code *)(*ppppppiVar3)[0x38])();
        if (iVar4 < 0) {
          pwStack_c0 = L"企㎭暙ᇏಷꨀ怀鏓\b";
          ppppppiStack_c4 = ppppppiVar3;
          __vbaHresultCheckObj();
        }
        sVar7 = -(ushort)(sVar11 == -1);
        __vbaFreeObj();
        if (sVar7 != 0) {
          ppiStack_74 = (int **)0x9;
          pwStack_c0 = 
          L"赐걅ｐ⠕䀑褀傅\xffff棿\xe8a0F趋ｐ\xffffᆋ薋ｐ\xffffｐ呒\xe2db薉ｌ\xffff붃ｌ\xffff紀樣桔ㅨD趋ｐ\xffff譑䲕\xffff勿ᗿ჌@薉８\xffff૫藇８\xffff"
          ;
          pwStack_c0 = (wchar_t *)(*(code *)(*unaff_ESI)[0xcb])();
          ppppppiStack_c4 = (int ******)&ppppppiStack_c4;
          ppppppiStack_c4 = (int ******)__vbaObjSet();
          pwStack_c0 = L"Time to Live (TTL=64)";
          iVar4 = (*(code *)(*ppppppiStack_c4)[0x15])();
          if (iVar4 < 0) {
            pwStack_d8 = L"薉８\xffff૫藇８\xffff";
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0xa;
          (*(code *)(*unaff_ESI)[0xce])();
          piVar8 = (int *)__vbaObjSet();
          iVar4 = (**(code **)(*piVar8 + 0xe4))();
          if (iVar4 < 0) {
            pwStack_d8 = L"企㎭暙ᇏಷꨀ怀鏓\b";
            ppppppiStack_e4 = (int ******)0x6cf89b;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0xb;
          pwStack_d8 = L"赐걅ｐ⠕䀑褀傅\xffff櫿謀傍\xffff诿謑傅\xffff僿鋿\x8c";
          pwStack_d8 = (wchar_t *)(*(code *)(*unaff_ESI)[0xcf])();
          ppppppiVar3 = (int ******)__vbaObjSet();
          pwStack_d8 = (wchar_t *)0x0;
          iVar4 = (*(code *)(*ppppppiVar3)[0x23])();
          if (iVar4 < 0) {
            pwStack_c0 = L"仡㎭暙ᇏಷꨀ怀鏓湭䵵楡n";
            ppppppiStack_c4 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
        }
        ppiStack_74 = (int **)0xd;
        pwStack_c0 = 
        L"赐걅ｐ⠕䀑褀傅\xffff跿咍\xffff凿開ｐ\xffffʋ趋ｐ\xffffｑ\xe090";
        pwStack_c0 = (wchar_t *)(*(code *)(*unaff_ESI)[0xcc])();
        ppppppiStack_c4 = (int ******)&ppppppiStack_c4;
        ppppppiStack_c4 = (int ******)__vbaObjSet();
        pwStack_c0 = (wchar_t *)&stack0xfffffee4;
        iVar4 = (*(code *)(*ppppppiStack_c4)[0x38])();
        if (iVar4 < 0) {
          pwStack_d8 = L"薉，\xffff૫藇，\xffff";
          __vbaHresultCheckObj();
        }
        sVar7 = -(ushort)(sVar11 == -1);
        __vbaFreeObj();
        if (sVar7 != 0) {
          ppiStack_74 = (int **)0xe;
          (*(code *)(*unaff_ESI)[0xcb])();
          ppppppiVar3 = (int ******)__vbaObjSet();
          (*(code *)(*unaff_ESI)[0xcf])();
          pwStack_d8 = L"薉ｐ\xffff喍劼薋ｐ\xffffࢋ開ｐ\xffffｒꂑ";
          piVar8 = (int *)__vbaObjSet();
          pwStack_d8 = L"\xe2db薉ｌ\xffff붃ｌ\xffff紀栦\xa0";
          puVar1 = (undefined *)(**(code **)(*piVar8 + 0xa0))();
          if ((int)puVar1 < 0) {
            pwStack_d8 = (wchar_t *)0xa0;
            ppppppiStack_e8 = (int ******)0x6cfa7f;
            ppppppiStack_e4 = (int ******)puVar1;
            __vbaHresultCheckObj();
          }
          pwStack_d8 = L"Time to Live (TTL=";
          rtcTrimBstr();
          __vbaStrMove();
          __vbaStrCat();
          pwStack_d8 = 
          L"桐炐Fᗿ႘@킋䶍ﾰ쀕䀓倀薋ｈ\xffffࢋ開ｈ\xffffｒ呑\xe2db薉ｄ\xffff붃ｄ\xffff紀樣桔ㅨD薋ｈ\xffff譐䒍\xffff凿ᗿ჌@薉＄\xffff૫藇＄\xffff"
          ;
          pwStack_d8 = (wchar_t *)__vbaStrMove();
          __vbaStrCat();
          pwStack_d8 = (wchar_t *)0x6cfad4;
          pwStack_d8 = (wchar_t *)__vbaStrMove();
          iVar4 = (*(code *)(*ppppppiVar3)[0x15])();
          if (iVar4 < 0) {
            ppppppiStack_e4 = (int ******)&DAT_00443168;
            ppppppiStack_e8 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          ppppppiStack_e4 = (int ******)&stack0xffffff44;
          ppppppiStack_e8 = (int ******)&ppppppiStack_b8;
          __vbaFreeStrList();
          ppppppiStack_e4 = (int ******)&ppppppiStack_c4;
          ppppppiStack_e8 = (int ******)0x2;
          __vbaFreeObjList();
          ppiStack_74 = (int **)0xf;
          ppppppiStack_e4 = (int ******)0x6cfb69;
          ppppppiStack_e4 = (int ******)(*(code *)(*unaff_ESI)[0xcf])();
          ppppppiStack_e8 = (int ******)&ppppppiStack_c4;
          ppppppiStack_e8 = (int ******)__vbaObjSet();
          ppppppiStack_e4 = (int ******)0xffffffff;
          iVar4 = (*(code *)(*ppppppiStack_e8)[0x23])();
          if (iVar4 < 0) {
            pwStack_d8 = L"薉＀\xffff૫藇＀\xffff";
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
        }
        ppiStack_74 = (int **)0x11;
        (*(code *)(*unaff_ESI)[0xd9])();
        piVar8 = (int *)__vbaObjSet();
        iVar4 = (**(code **)(*piVar8 + 0xe0))();
        if (iVar4 < 0) {
          pwStack_d8 = L"企㎭暙ᇏಷꨀ怀鏓\b";
          ppppppiStack_e4 = (int ******)0x6cfc4d;
          __vbaHresultCheckObj();
        }
        sVar7 = -(ushort)(sVar11 == -1);
        __vbaFreeObj();
        if (sVar7 != 0) {
          ppiStack_74 = (int **)0x12;
          ppppppwStack_108 = (wchar_t ******)0x2;
          __vbaVarMove();
          ppiStack_74 = (int **)0x13;
          pwStack_d8 = 
          L"赐걕ｒ⠕䀑褀傅\xffff棿\xe62cF薋ｐ\xffffࢋ開ｐ\xffffｒ呑\xe2db薉ｌ\xffff붃ｌ\xffff紀樣桔ㅨD薋ｐ\xffff譐䲍\xffff凿ᗿ჌@薉ﻸ\xffff૫藇ﻸ\xffff"
          ;
          pwStack_d8 = (wchar_t *)(*(code *)(*unaff_ESI)[0xd6])();
          ppppppiVar3 = (int ******)__vbaObjSet();
          pwStack_d8 = L"Maximum Transfer Unit (MTU=576)";
          iVar4 = (*(code *)(*ppppppiVar3)[0x15])();
          if (iVar4 < 0) {
            ppppppiStack_e4 = (int ******)&DAT_00443168;
            ppppppiStack_e8 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x14;
          ppppppiStack_e4 = (int ******)0x6cfd52;
          ppppppiStack_e4 = (int ******)(*(code *)(*unaff_ESI)[0xd7])();
          ppppppiStack_e8 = (int ******)&ppppppiStack_c4;
          ppppppiStack_e8 = (int ******)__vbaObjSet();
          ppppppiStack_e4 = (int ******)0x0;
          iVar4 = (*(code *)(*ppppppiStack_e8)[0x23])();
          if (iVar4 < 0) {
            pwStack_d8 = L"仡㎭暙ᇏಷꨀ怀鏓湭䵵楡n";
            ppppppiStack_e4 = (int ******)0x6cfda9;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
        }
        ppiStack_74 = (int **)0x16;
        pwStack_d8 = 
        L"赐걕ｒ⠕䀑褀傅\xffff跿咅\xffff僿趋ｐ\xffffᆋ薋ｐ\xffffｐ\xe092";
        pwStack_d8 = (wchar_t *)(*(code *)(*unaff_ESI)[0xda])();
        ppppppiVar3 = (int ******)__vbaObjSet();
        pwStack_d8 = (wchar_t *)&stack0xfffffee4;
        iVar4 = (*(code *)(*ppppppiVar3)[0x38])();
        if (iVar4 < 0) {
          ppppppiStack_e4 = (int ******)&DAT_00451a20;
          ppppppiStack_e8 = ppppppiVar3;
          __vbaHresultCheckObj();
        }
        sVar7 = -(ushort)(sVar11 == -1);
        __vbaFreeObj();
        if (sVar7 != 0) {
          ppiStack_74 = (int **)0x17;
          ppppppwStack_108 = (wchar_t ******)0x2;
          __vbaVarMove();
          ppiStack_74 = (int **)0x18;
          ppppppiStack_e4 = (int ******)0x6cfeb6;
          ppppppiStack_e4 = (int ******)(*(code *)(*unaff_ESI)[0xd6])();
          ppppppiStack_e8 = (int ******)&ppppppiStack_c4;
          ppppppiStack_e8 = (int ******)__vbaObjSet();
          ppppppiStack_e4 = (int ******)0x46e670;
          iVar4 = (*(code *)(*ppppppiStack_e8)[0x15])();
          if (iVar4 < 0) {
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x19;
          (*(code *)(*unaff_ESI)[0xd7])();
          ppppppiVar3 = (int ******)__vbaObjSet();
          iVar4 = (*(code *)(*ppppppiVar3)[0x23])();
          if (iVar4 < 0) {
            ppppppiStack_e4 = (int ******)&DAT_0043f42c;
            ppppppiStack_e8 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
        }
        ppiStack_74 = (int **)0x1b;
        ppppppiStack_e4 = (int ******)0x6cffc3;
        ppppppiStack_e4 = (int ******)(*(code *)(*unaff_ESI)[0xd8])();
        ppppppiStack_e8 = (int ******)&ppppppiStack_c4;
        ppppppiStack_e8 = (int ******)__vbaObjSet();
        ppppppiStack_e4 = (int ******)&stack0xfffffee4;
        iVar4 = (*(code *)(*ppppppiStack_e8)[0x38])();
        if (iVar4 < 0) {
          __vbaHresultCheckObj();
        }
        sVar7 = -(ushort)(sVar11 == -1);
        __vbaFreeObj();
        if (sVar7 != 0) {
          ppiStack_74 = (int **)0x1c;
          (*(code *)(*unaff_ESI)[0xd7])();
          piVar8 = (int *)__vbaObjSet();
          iVar4 = (**(code **)(*piVar8 + 0xa0))();
          if (iVar4 < 0) {
            ppppppwStack_108 = (wchar_t ******)0x6d00ce;
            __vbaHresultCheckObj();
          }
          rtcR8ValFromBstr();
          __vbaFPInt();
          ppppppwStack_108 = (wchar_t ******)0x5;
          __vbaVarMove();
          __vbaFreeStr();
          __vbaFreeObj();
          ppiStack_74 = (int **)0x1d;
          (*(code *)(*unaff_ESI)[0xd6])();
          ppppppiVar3 = (int ******)__vbaObjSet();
          (*(code *)(*unaff_ESI)[0xd7])();
          ppppppwStack_108 = (wchar_t ******)0x6d0162;
          piVar8 = (int *)__vbaObjSet();
          ppppppwStack_108 = (wchar_t ******)0x6d0181;
          puVar1 = (undefined *)(**(code **)(*piVar8 + 0xa0))();
          if ((int)puVar1 < 0) {
            ppppppwStack_108 = (wchar_t ******)0xa0;
            ppppppiStack_118 = (int ******)0x6d01b0;
            ppppppiStack_114 = (int ******)puVar1;
            __vbaHresultCheckObj();
          }
          ppppppwStack_108 = (wchar_t ******)0x46e6b8;
          rtcTrimBstr();
          __vbaStrMove();
          __vbaStrCat();
          ppppppwStack_108 = (wchar_t ******)0x6d01ee;
          ppppppwStack_108 = (wchar_t ******)__vbaStrMove();
          __vbaStrCat();
          ppppppwStack_108 = (wchar_t ******)0x6d0205;
          ppppppwStack_108 = (wchar_t ******)__vbaStrMove();
          iVar4 = (*(code *)(*ppppppiVar3)[0x15])();
          if (iVar4 < 0) {
            ppppppiStack_114 = (int ******)&DAT_00443168;
            ppppppiStack_118 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          ppppppiStack_114 = (int ******)&stack0xffffff44;
          ppppppiStack_118 = (int ******)&ppppppiStack_b8;
          __vbaFreeStrList(4);
          ppppppiStack_114 = (int ******)&ppppppiStack_c4;
          ppppppiStack_118 = (int ******)0x2;
          __vbaFreeObjList();
          ppiStack_74 = (int **)0x1e;
          ppppppiStack_114 = (int ******)0x6d029a;
          ppppppiStack_114 = (int ******)(*(code *)(*unaff_ESI)[0xd7])();
          ppppppiStack_118 = (int ******)&ppppppiStack_c4;
          ppppppiStack_118 = (int ******)__vbaObjSet();
          ppppppiStack_114 = (int ******)0xffffffff;
          in_stack_fffffee4 = (wchar_t *****)0x6d02c2;
          iVar4 = (*(code *)(*ppppppiStack_118)[0x23])();
          if (iVar4 < 0) {
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
        }
        ppiStack_74 = (int **)0x20;
        (*(code *)(*unaff_ESI)[0xd4])();
        piVar8 = (int *)__vbaObjSet();
        iVar4 = (**(code **)(*piVar8 + 0xe0))();
        if (iVar4 < 0) {
          ppppppwStack_108 = (wchar_t ******)0x6d037e;
          __vbaHresultCheckObj();
        }
        sVar7 = -(ushort)((short)in_stack_fffffee4 == -1);
        __vbaFreeObj();
        if (sVar7 != 0) {
          ppiStack_74 = (int **)0x21;
          ppppppwStack_108 = (wchar_t ******)0x2;
          __vbaVarMove();
          ppiStack_74 = (int **)0x22;
          (*(code *)(*unaff_ESI)[0xd0])();
          piVar8 = (int *)__vbaObjSet();
          iVar4 = (**(code **)(*piVar8 + 0x54))();
          if (iVar4 < 0) {
            ppppppwStack_108 = (wchar_t ******)&DAT_00443168;
            ppppppiStack_114 = (int ******)0x6d0452;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x23;
          ppppppwStack_108 = (wchar_t ******)0x6d0483;
          ppppppwStack_108 = (wchar_t ******)(*(code *)(*unaff_ESI)[0xd2])();
          ppppppiVar3 = (int ******)__vbaObjSet();
          ppppppwStack_108 = (wchar_t ******)0x0;
          iVar4 = (*(code *)(*ppppppiVar3)[0x23])();
          if (iVar4 < 0) {
            ppppppiStack_114 = (int ******)&DAT_0043f42c;
            ppppppiStack_118 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x24;
          ppppppiStack_114 = (int ******)0x6d050b;
          ppppppiStack_114 = (int ******)(*(code *)(*unaff_ESI)[0xd1])();
          ppppppiStack_118 = (int ******)&ppppppiStack_c4;
          ppppppiStack_118 = (int ******)__vbaObjSet();
          ppppppiStack_114 = (int ******)0x0;
          in_stack_fffffee4 = (wchar_t *****)0x6d0533;
          iVar4 = (*(code *)(*ppppppiStack_118)[0x25])();
          if (iVar4 < 0) {
            ppppppwStack_108 = (wchar_t ******)0x6d0562;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
        }
        ppiStack_74 = (int **)0x26;
        (*(code *)(*unaff_ESI)[0xd3])();
        piVar8 = (int *)__vbaObjSet();
        iVar4 = (**(code **)(*piVar8 + 0xe0))();
        if (iVar4 < 0) {
          ppppppwStack_108 = (wchar_t ******)&DAT_00451a20;
          ppppppiStack_114 = (int ******)0x6d05ef;
          __vbaHresultCheckObj();
        }
        sVar7 = -(ushort)((short)in_stack_fffffee4 == -1);
        __vbaFreeObj();
        if (sVar7 != 0) {
          ppiStack_74 = (int **)0x27;
          ppppppwStack_108 = (wchar_t ******)0x6d0645;
          ppppppwStack_108 = (wchar_t ******)(*(code *)(*unaff_ESI)[0xd2])();
          ppppppiVar3 = (int ******)__vbaObjSet();
          ppppppwStack_108 = (wchar_t ******)0x0;
          iVar4 = (*(code *)(*ppppppiVar3)[0x23])();
          if (iVar4 < 0) {
            ppppppiStack_114 = (int ******)&DAT_0043f42c;
            ppppppiStack_118 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x28;
          ppppppiStack_114 = (int ******)0x6d06cd;
          ppppppiStack_114 = (int ******)(*(code *)(*unaff_ESI)[0xd1])();
          ppppppiStack_118 = (int ******)&ppppppiStack_c4;
          ppppppiStack_118 = (int ******)__vbaObjSet();
          ppppppiStack_114 = (int ******)0xffffffff;
          iVar4 = (*(code *)(*ppppppiStack_118)[0x25])();
          if (iVar4 < 0) {
            __vbaHresultCheckObj(&DAT_00446e04,&DAT_00446e04,&DAT_00446e04);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x29;
          uVar5 = (*(code *)(*unaff_ESI)[0xd1])();
          __vbaObjSet(&ppppppiStack_c4,uVar5);
          ppwVar10 = &pwStack_b4;
          iVar4 = (**(code **)(pwStack_b4 + 0x54))(ppwVar10);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,ppwVar10,&DAT_00446e04,0xa8);
          }
          __vbaStrCmp(&DAT_0046e6f4,pwStack_b4);
          __vbaFreeStr();
          sVar7 = 0x7ef;
          __vbaFreeObj();
          if (sVar7 != 0) {
            ppiStack_74 = (int **)0x2a;
            ppppppwStack_108 = (wchar_t ******)0x2;
            ppppppiStack_118 = (int ******)0x2;
            uVar5 = __vbaVarSub(&pwStack_d8,&ppppppwStack_108,&stack0xffffff60);
            __vbaVarMul(&ppppppiStack_e8,&ppppppiStack_118,uVar5);
            __vbaVarMove();
            ppiStack_74 = (int **)0x2b;
            uVar5 = (*(code *)(*unaff_ESI)[0xd0])(unaff_ESI);
            piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
            ppppppwStack_108 = (wchar_t ******)0x2;
            ppppppiStack_118 = (int ******)0x2;
            uVar5 = __vbaVarSub(&pwStack_d8,&ppppppwStack_108,&stack0xffffff60);
            __vbaVarMul(&ppppppiStack_e8,&ppppppiStack_118,uVar5);
            __vbaVarMove();
            pwVar9 = L"Receive Window (RWIN=";
            rtcStrFromVar(&stack0xffffff08);
            uVar5 = __vbaStrMove(pwVar9);
            rtcTrimBstr(uVar5);
            uVar5 = __vbaStrMove();
            __vbaStrCat(uVar5,pwVar9);
            uVar5 = __vbaStrMove();
            __vbaStrCat(&DAT_00467090,uVar5);
            uVar5 = __vbaStrMove();
            iVar4 = (**(code **)(*piVar8 + 0x54))(piVar8,uVar5);
            if (iVar4 < 0) {
              __vbaHresultCheckObj(iVar4,piVar8,&DAT_00443168,0x54);
            }
            __vbaFreeStrList(4,&pwStack_b4,&ppppppiStack_b8,&stack0xffffff44,&pwStack_c0);
            __vbaFreeObj();
            __vbaFreeVar();
          }
          ppiStack_74 = (int **)0x2d;
          uVar5 = (*(code *)(*unaff_ESI)[0xd1])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0xa8))(piVar8,&pwStack_b4);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00446e04,0xa8);
          }
          iVar4 = __vbaStrCmp(&DAT_0046e8d0,pwStack_b4);
          sVar7 = -(ushort)(iVar4 == 0);
          __vbaFreeStr();
          __vbaFreeObj();
          if (sVar7 != 0) {
            ppiStack_74 = (int **)0x2e;
            ppppppwStack_108 = (wchar_t ******)0x2;
            ppppppiStack_118 = (int ******)0x2;
            uVar5 = __vbaVarSub(&pwStack_d8,&ppppppwStack_108,&stack0xffffff60);
            __vbaVarMul(&ppppppiStack_e8,&ppppppiStack_118,uVar5);
            __vbaVarMove();
            ppiStack_74 = (int **)0x2f;
            uVar5 = (*(code *)(*unaff_ESI)[0xd0])(unaff_ESI);
            piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
            ppppppwStack_108 = (wchar_t ******)0x2;
            ppppppiStack_118 = (int ******)0x2;
            uVar5 = __vbaVarSub(&pwStack_d8,&ppppppwStack_108,&stack0xffffff60);
            __vbaVarMul(&ppppppiStack_e8,&ppppppiStack_118,uVar5);
            __vbaVarMove();
            pwVar9 = L"Receive Window (RWIN=";
            rtcStrFromVar(&stack0xffffff08);
            uVar5 = __vbaStrMove(pwVar9);
            rtcTrimBstr(uVar5);
            uVar5 = __vbaStrMove();
            __vbaStrCat(uVar5,pwVar9);
            uVar5 = __vbaStrMove();
            __vbaStrCat(&DAT_00467090,uVar5);
            uVar5 = __vbaStrMove();
            iVar4 = (**(code **)(*piVar8 + 0x54))(piVar8,uVar5);
            if (iVar4 < 0) {
              __vbaHresultCheckObj(iVar4,piVar8,&DAT_00443168,0x54);
            }
            __vbaFreeStrList(4,&pwStack_b4,&ppppppiStack_b8,&stack0xffffff44,&pwStack_c0);
            __vbaFreeObj();
            __vbaFreeVar();
          }
          ppiStack_74 = (int **)0x31;
          uVar5 = (*(code *)(*unaff_ESI)[0xd1])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0xa8))(piVar8,&pwStack_b4);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00446e04,0xa8);
          }
          iVar4 = __vbaStrCmp(&DAT_0046e8dc,pwStack_b4);
          sVar7 = -(ushort)(iVar4 == 0);
          __vbaFreeStr();
          __vbaFreeObj();
          if (sVar7 != 0) {
            ppiStack_74 = (int **)0x32;
            ppppppwStack_108 = (wchar_t ******)0x2;
            ppppppiStack_118 = (int ******)0x2;
            uVar5 = __vbaVarSub(&pwStack_d8,&ppppppwStack_108,&stack0xffffff60);
            __vbaVarMul(&ppppppiStack_e8,&ppppppiStack_118,uVar5);
            __vbaVarMove();
            ppiStack_74 = (int **)0x33;
            uVar5 = (*(code *)(*unaff_ESI)[0xd0])(unaff_ESI);
            piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
            ppppppwStack_108 = (wchar_t ******)0x2;
            ppppppiStack_118 = (int ******)0x2;
            uVar5 = __vbaVarSub(&pwStack_d8,&ppppppwStack_108,&stack0xffffff60);
            __vbaVarMul(&ppppppiStack_e8,&ppppppiStack_118,uVar5);
            __vbaVarMove();
            pwVar9 = L"Receive Window (RWIN=";
            rtcStrFromVar(&stack0xffffff08);
            uVar5 = __vbaStrMove(pwVar9);
            rtcTrimBstr(uVar5);
            uVar5 = __vbaStrMove();
            __vbaStrCat(uVar5,pwVar9);
            uVar5 = __vbaStrMove();
            __vbaStrCat(&DAT_00467090,uVar5);
            uVar5 = __vbaStrMove();
            iVar4 = (**(code **)(*piVar8 + 0x54))(piVar8,uVar5);
            if (iVar4 < 0) {
              __vbaHresultCheckObj(iVar4,piVar8,&DAT_00443168,0x54);
            }
            __vbaFreeStrList(4,&pwStack_b4,&ppppppiStack_b8,&stack0xffffff44,&pwStack_c0);
            __vbaFreeObj();
            __vbaFreeVar();
          }
          ppiStack_74 = (int **)0x35;
          uVar5 = (*(code *)(*unaff_ESI)[0xd1])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0xa8))(piVar8,&pwStack_b4);
          if (iVar4 < 0) {
            ppppppwStack_108 = (wchar_t ******)&DAT_00446e04;
            ppppppiStack_114 = (int ******)0x6d0f25;
            __vbaHresultCheckObj();
          }
          ppppppwStack_108 = (wchar_t ******)&DAT_0046ddc4;
          iVar4 = __vbaStrCmp();
          sVar7 = -(ushort)(iVar4 == 0);
          __vbaFreeStr();
          __vbaFreeObj();
          in_stack_fffffee4 = unaff_ESI;
          if (sVar7 != 0) {
            ppiStack_74 = (int **)0x36;
            ppppppiStack_118 = (int ******)0x2;
            ppppppwStack_108 = (wchar_t ******)&ppppppwStack_108;
            __vbaVarSub();
            ppppppwStack_108 = (wchar_t ******)&ppppppiStack_118;
            __vbaVarMul();
            __vbaVarMove();
            ppiStack_74 = (int **)0x37;
            ppppppwStack_108 = (wchar_t ******)0x6d0fec;
            ppppppwStack_108 = (wchar_t ******)(*(code *)(*unaff_ESI)[0xd0])();
            piVar8 = (int *)__vbaObjSet();
            ppppppiStack_118 = (int ******)0x2;
            ppppppwStack_108 = (wchar_t ******)&stack0xffffff60;
            ppppppiStack_114 = (int ******)0x6d103a;
            ppppppwStack_108 = (wchar_t ******)__vbaVarSub();
            ppppppiStack_114 = (int ******)0x6d104c;
            __vbaVarMul();
            ppppppwStack_108 = (wchar_t ******)0x6d105a;
            __vbaVarMove();
            ppppppwStack_108 = (wchar_t ******)0x46e560;
            rtcStrFromVar();
            __vbaStrMove();
            rtcTrimBstr();
            __vbaStrMove();
            __vbaStrCat();
            ppppppwStack_108 = (wchar_t ******)0x6d109b;
            ppppppwStack_108 = (wchar_t ******)__vbaStrMove();
            __vbaStrCat();
            ppppppwStack_108 = (wchar_t ******)0x6d10b2;
            ppppppwStack_108 = (wchar_t ******)__vbaStrMove();
            iVar4 = (**(code **)(*piVar8 + 0x54))();
            if (iVar4 < 0) {
              ppppppwStack_108 = (wchar_t ******)&DAT_00443168;
              ppppppiStack_114 = (int ******)0x6d10f1;
              __vbaHresultCheckObj();
            }
            ppppppwStack_108 = (wchar_t ******)&stack0xffffff44;
            ppppppiStack_114 = (int ******)0x4;
            ppppppiStack_118 = (int ******)0x6d111b;
            __vbaFreeStrList();
            __vbaFreeObj();
            __vbaFreeVar();
          }
        }
        ppiStack_74 = (int **)0x3a;
        ppppppwStack_108 = (wchar_t ******)0x6d1149;
        ppppppwStack_108 = (wchar_t ******)(*(code *)(*unaff_ESI)[0xd5])();
        ppppppiVar3 = (int ******)__vbaObjSet();
        ppppppwStack_108 = (wchar_t ******)&stack0xfffffee4;
        pppppwVar6 = (wchar_t *****)(*(code *)(*ppppppiVar3)[0x38])();
        if ((int)pppppwVar6 < 0) {
          ppppppiStack_114 = (int ******)&DAT_00451a20;
          ppppppiStack_118 = ppppppiVar3;
          __vbaHresultCheckObj();
          in_stack_fffffee4 = pppppwVar6;
        }
        sVar7 = -(ushort)((short)in_stack_fffffee4 == -1);
        __vbaFreeObj();
        if (sVar7 != 0) {
          ppiStack_74 = (int **)0x3b;
          ppppppiStack_114 = (int ******)0x6d11fb;
          ppppppiStack_114 = (int ******)(*(code *)(*unaff_ESI)[0xd2])();
          ppppppiStack_118 = (int ******)&ppppppiStack_c4;
          ppppppiStack_118 = (int ******)__vbaObjSet();
          ppppppiStack_114 = (int ******)&pwStack_b4;
          iVar4 = (*(code *)(*ppppppiStack_118)[0x28])();
          if (iVar4 < 0) {
            __vbaHresultCheckObj(&DAT_0043f42c,&DAT_0043f42c,&DAT_0043f42c);
          }
          rtcR8ValFromBstr();
          __vbaFPInt();
          ppppppwStack_108 = (wchar_t ******)&DAT_00000005;
          __vbaVarMove();
          __vbaFreeStr();
          __vbaFreeObj();
          ppiStack_74 = (int **)0x3c;
          uVar5 = (*(code *)(*unaff_ESI)[0xd0])();
          __vbaObjSet(&ppppppiStack_c4,uVar5);
          pwVar9 = L"Receive Window (RWIN=";
          rtcStrFromVar(&stack0xffffff50);
          uVar5 = __vbaStrMove(pwVar9);
          rtcTrimBstr(uVar5);
          uVar5 = __vbaStrMove();
          __vbaStrCat(uVar5,pwVar9);
          uVar5 = __vbaStrMove();
          __vbaStrCat(&DAT_00467090,uVar5);
          piVar8 = (int *)__vbaStrMove();
          iVar4 = (**(code **)(*piVar8 + 0x54))(piVar8);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00443168,0x54);
          }
          __vbaFreeStrList(4,&pwStack_b4,&ppppppiStack_b8,&stack0xffffff44,&pwStack_c0);
          __vbaFreeObj();
          ppiStack_74 = (int **)0x3d;
          uVar5 = (*(code *)(*unaff_ESI)[0xd2])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x8c))(piVar8,0xffffffff);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_0043f42c,0x8c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x3e;
          uVar5 = (*(code *)(*unaff_ESI)[0xd1])(unaff_ESI);
          ppppppiVar3 = (int ******)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (*(code *)(*ppppppiVar3)[0x25])(ppppppiVar3,0);
          if (iVar4 < 0) {
            ppppppiStack_114 = (int ******)&DAT_00446e04;
            ppppppiStack_118 = ppppppiVar3;
            __vbaHresultCheckObj();
          }
          __vbaFreeObj();
        }
        ppiStack_74 = (int **)0x40;
        ppppppiStack_114 = (int ******)0x6d14be;
        ppppppiStack_114 = (int ******)(*(code *)(*unaff_ESI)[0xc4])();
        ppppppiStack_118 = (int ******)&ppppppiStack_c4;
        ppppppiStack_118 = (int ******)__vbaObjSet();
        ppppppiStack_114 = (int ******)&stack0xfffffee4;
        sVar7 = 0x14eb;
        iVar4 = (*(code *)(*ppppppiStack_118)[0x38])();
        if (iVar4 < 0) {
          sVar7 = 0xe0;
          __vbaHresultCheckObj(&DAT_00451a20,&DAT_00451a20,&DAT_00451a20);
        }
        sVar7 = -(ushort)(sVar7 == -1);
        __vbaFreeObj();
        if (sVar7 == 0) {
          ppiStack_74 = (int **)0x4d;
          if (DAT_0073a6a0 == (int *)0x0) {
            __vbaNew2(&DAT_004271e0);
          }
          piVar8 = DAT_0073a6a0;
          iVar4 = (**(code **)(*DAT_0073a6a0 + 0x54))(DAT_0073a6a0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(0x54,piVar8,&DAT_0045689c,0x54);
          }
          ppiStack_74 = (int **)0x4e;
          uVar5 = (*(code *)(*unaff_ESI)[0xca])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00446678,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x4f;
          uVar5 = (*(code *)(*unaff_ESI)[0xcd])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x50;
          uVar5 = (*(code *)(*unaff_ESI)[0xce])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x51;
          uVar5 = (*(code *)(*unaff_ESI)[0xda])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x52;
          uVar5 = (*(code *)(*unaff_ESI)[0xd9])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x53;
          uVar5 = (*(code *)(*unaff_ESI)[0xd1])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00446e04,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x54;
          uVar5 = (*(code *)(*unaff_ESI)[0xd4])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x55;
          uVar5 = (*(code *)(*unaff_ESI)[0xd3])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x56;
          uVar5 = (*(code *)(*unaff_ESI)[0xc4])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x57;
          uVar5 = (*(code *)(*unaff_ESI)[0xc3])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
        }
        else {
          ppiStack_74 = (int **)0x41;
          if (DAT_0073a6a0 == (int *)0x0) {
            __vbaNew2(&DAT_004271e0);
          }
          piVar8 = DAT_0073a6a0;
          iVar4 = (**(code **)(*DAT_0073a6a0 + 0x54))(DAT_0073a6a0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(0x54,piVar8,&DAT_0045689c,0x54);
          }
          ppiStack_74 = (int **)0x42;
          uVar5 = (*(code *)(*unaff_ESI)[0xca])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00446678,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x43;
          uVar5 = (*(code *)(*unaff_ESI)[0xce])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x44;
          uVar5 = (*(code *)(*unaff_ESI)[0xcd])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x45;
          uVar5 = (*(code *)(*unaff_ESI)[0xd9])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x46;
          uVar5 = (*(code *)(*unaff_ESI)[0xda])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x47;
          uVar5 = (*(code *)(*unaff_ESI)[0xd1])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00446e04,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x48;
          uVar5 = (*(code *)(*unaff_ESI)[0xd3])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x49;
          uVar5 = (*(code *)(*unaff_ESI)[0xd4])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x4a;
          uVar5 = (*(code *)(*unaff_ESI)[0xc4])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0xff0000);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
          ppiStack_74 = (int **)0x4b;
          uVar5 = (*(code *)(*unaff_ESI)[0xc3])(unaff_ESI);
          piVar8 = (int *)__vbaObjSet(&ppppppiStack_c4,uVar5);
          iVar4 = (**(code **)(*piVar8 + 0x6c))(piVar8,0);
          if (iVar4 < 0) {
            __vbaHresultCheckObj(iVar4,piVar8,&DAT_00451a20,0x6c);
          }
          __vbaFreeObj();
        }
        __vbaFreeVar(&LAB_006d213e);
        __vbaFreeVar();
        return;
      }
      *(short *)(piVar8 + 0xd) = (short)piVar8[0xd] + 0x14;
      goto LAB_006cf276;
    }
    if (sVar7 < 0x32) goto LAB_006cf276;
    piStack_78 = (int *)0x6cf228;
    piStack_78 = (int *)(**(code **)(*piVar8 + 0x2fc))();
    piStack_7c = &local_24;
    puStack_80 = (undefined *)0x6cf233;
    piVar2 = (int *)__vbaObjSet();
    piStack_78 = (int *)0xfa;
    puStack_80 = (undefined *)0x6cf240;
    piStack_7c = piVar2;
    puVar1 = (undefined *)(**(code **)(*piVar2 + 100))();
    if ((int)puVar1 < 0) {
      ppiStack_74 = (int **)0x64;
      piStack_78 = (int *)&DAT_00441ed0;
      piStack_84 = (int *)0x6cf255;
      puStack_80 = puVar1;
      piStack_7c = piVar2;
      __vbaHresultCheckObj();
    }
    ppiStack_74 = (int **)0x6cf25e;
    __vbaFreeObj();
    *(undefined2 *)((int)piVar8 + 0x36) = 10;
    sVar7 = (short)piVar8[0xd] + 10;
    if (SCARRY2((short)piVar8[0xd],10)) goto LAB_006cf43b;
  }
  *(short *)(piVar8 + 0xd) = sVar7;
LAB_006cf276:
  if ((short)piVar8[0xd] < 0x65) {
    piStack_78 = (int *)(float)(int)(short)piVar8[0xd];
    puStack_80 = (undefined *)0x4;
    ppiStack_74 = (int **)local_28;
    piStack_84 = (int *)&DAT_00000005;
    puStack_8c = (undefined1 *)0x6cf329;
    piStack_88 = piVar8;
    pvStack_90 = (void *)(**(code **)(*piVar8 + 0x30c))();
    puStack_94 = &local_24;
    piStack_98 = (int *)0x6cf334;
    pvStack_90 = (void *)__vbaObjSet();
    puStack_94 = (undefined4 *)0x6cf33b;
    __vbaLateIdSt();
    piStack_7c = (int *)0x6cf344;
    __vbaFreeObj();
  }
  else {
    if (DAT_0073c818 == (int *)0x0) {
      ppiStack_74 = &DAT_0073c818;
      piStack_78 = (int *)&DAT_00441f00;
      piStack_7c = (int *)0x6cf298;
      __vbaNew2();
    }
    piVar8 = DAT_0073c818;
    if (DAT_0073a68c == 0) {
      ppiStack_74 = (int **)&DAT_0073a68c;
      piStack_78 = (int *)&DAT_004174cc;
      piStack_7c = (int *)0x6cf2b6;
      __vbaNew2();
    }
    iVar4 = *piVar8;
    ppiStack_74 = (int **)DAT_0073a68c;
    piStack_78 = &local_24;
    piStack_7c = (int *)0x6cf2c9;
    ppiStack_74 = (int **)__vbaObjSetAddref();
    piStack_78 = piVar8;
    piStack_7c = (int *)0x6cf2ce;
    piVar2 = (int *)(**(code **)(iVar4 + 0x10))();
    if ((int)piVar2 < 0) {
      piStack_7c = (int *)0x10;
      puStack_80 = &DAT_00441ef0;
      piStack_84 = piVar8;
      puStack_8c = (undefined1 *)0x6cf2e3;
      piStack_88 = piVar2;
      __vbaHresultCheckObj();
    }
    piStack_7c = (int *)0x6cf2ec;
    __vbaFreeObj();
  }
  piStack_7c = (int *)0x6cf409;
  __vbaExitProc();
  return;
}


