// BonziBDY_4.EXE :: frmTellAFriend
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 6

// ---- cmdSend_Click @ 0060fbc0

void frmTellAFriend::cmdSend_Click(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  int *piVar4;
  undefined4 uVar5;
  int *piVar6;
  undefined4 uVar7;
  undefined4 uVar8;
  undefined4 local_60 [5];
  undefined4 local_4c;
  undefined4 local_48;
  undefined4 local_44;
  undefined4 local_40;
  undefined4 local_3c;
  int *local_38;
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined1 *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff70;
  local_c = &LAB_00404b88;
  local_8 = param_1 & 1;
  piVar6 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar6 + 4))(piVar6);
  local_1c = 0;
  local_20 = 0;
  local_24 = 0;
  local_28 = 0;
  local_2c = 0;
  local_30 = 0;
  local_34 = 0;
  local_38 = (int *)0x0;
  local_3c = 0;
  local_4c = 0;
  local_60[0] = 0;
  if (DAT_0073a43c == (int *)0x0) {
    __vbaNew2(&DAT_00423fc0,&DAT_0073a43c);
  }
  uVar1 = (**(code **)(*DAT_0073a43c + 0x314))(DAT_0073a43c);
  piVar2 = (int *)__vbaObjSet(&local_34,uVar1);
  iVar3 = (**(code **)(*piVar2 + 0x40))(piVar2,0,&local_38);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_004480b4,0x40);
  }
  piVar2 = local_38;
  uVar1 = (**(code **)(*piVar6 + 0x2fc))(piVar6);
  piVar4 = (int *)__vbaObjSet(&local_3c,uVar1);
  iVar3 = (**(code **)(*piVar4 + 0xa0))(piVar4,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_0043f42c,0xa0);
  }
  iVar3 = (**(code **)(*piVar2 + 0xa4))(piVar2,local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_0043f42c,0xa4);
  }
  __vbaFreeStr();
  __vbaFreeObjList(3,&local_34,&local_3c,&local_38);
  if (DAT_0073a43c == (int *)0x0) {
    __vbaNew2(&DAT_00423fc0,&DAT_0073a43c);
  }
  uVar1 = (**(code **)(*DAT_0073a43c + 0x310))(DAT_0073a43c);
  piVar2 = (int *)__vbaObjSet(&local_3c,uVar1);
  uVar1 = (**(code **)(*piVar6 + 0x30c))(piVar6);
  piVar4 = (int *)__vbaObjSet(&local_38,uVar1);
  iVar3 = (**(code **)(*piVar4 + 0x50))(piVar4,&local_20);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_00441988,0x50);
  }
  uVar1 = (**(code **)(*piVar6 + 0x304))(piVar6);
  piVar4 = (int *)__vbaObjSet(&local_34,uVar1);
  iVar3 = (**(code **)(*piVar4 + 0xa0))(piVar4,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_0043f42c,0xa0);
  }
  iVar3 = *piVar2;
  __vbaStrCat(local_1c,local_20);
  uVar1 = __vbaStrMove();
  iVar3 = (**(code **)(iVar3 + 0xa4))(piVar2,uVar1);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_0043f42c,0xa4);
  }
  __vbaFreeStrList(3,&local_20,&local_1c,&local_24);
  __vbaFreeObjList(3,&local_34,&local_38,&local_3c);
  uVar1 = (**(code **)(*piVar6 + 0x308))(piVar6);
  piVar2 = (int *)__vbaObjSet(&local_34,uVar1);
  iVar3 = (**(code **)(*piVar2 + 0x50))(piVar2,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_00441988,0x50);
  }
  __vbaStrCat(&DAT_0043fbcc,local_1c);
  uVar1 = __vbaStrMove();
  __vbaStrCat(&DAT_0043fbcc,uVar1);
  uVar1 = __vbaStrMove();
  __vbaStrCat(L"http://www.bonzi.com/bonzibuddy/bonzibuddyfriend.asp",uVar1);
  uVar1 = __vbaStrMove();
  __vbaStrCat(&DAT_0043fbcc,uVar1);
  uVar1 = __vbaStrMove();
  __vbaStrCat(&DAT_0043fbcc,uVar1);
  uVar1 = __vbaStrMove();
  local_44 = __vbaStrCat(&PTR_DAT_0044aaa0,uVar1);
  local_4c = 8;
  if (DAT_0073a43c == (int *)0x0) {
    __vbaNew2(&DAT_00423fc0,&DAT_0073a43c);
  }
  uVar7 = 0;
  piVar2 = DAT_0073a43c;
  uVar1 = local_4c;
  uVar8 = local_44;
  uVar5 = (**(code **)(*DAT_0073a43c + 0x334))(DAT_0073a43c,0,local_4c,local_48,local_44,local_40);
  uVar5 = __vbaObjSet(&local_38,uVar5);
  __vbaLateIdSt(uVar5,piVar2,uVar7,uVar1,local_48,uVar8);
  __vbaFreeStrList(6,&local_1c,&local_20,&local_24,&local_28,&local_2c,&local_30);
  __vbaFreeObjList(2,&local_34,&local_38);
  __vbaFreeVar();
  iVar3 = (**(code **)(*piVar6 + 0x2b4))(piVar6);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar6,&DAT_0044a998,0x2b4);
  }
  if (DAT_0073a43c == (int *)0x0) {
    __vbaNew2(&DAT_00423fc0,&DAT_0073a43c);
  }
  piVar6 = DAT_0073a43c;
  local_60[0] = 0xffffffff;
  iVar3 = (**(code **)(*DAT_0073a43c + 0x704))(DAT_0073a43c,local_60,&local_4c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar6,&DAT_004480f4,0x704);
  }
  __vbaFreeVar();
  return;
}


// ---- cmdTo_Click @ 00610020

void frmTellAFriend::cmdTo_Click(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  int *piVar4;
  int *piVar5;
  undefined4 local_2c;
  undefined4 local_28;
  int *local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined1 *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffa8;
  local_c = &LAB_00404b98;
  local_8 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar5 + 4))(piVar5);
  local_1c = 0;
  local_20 = 0;
  local_24 = (int *)0x0;
  local_28 = 0;
  local_2c = 0;
  if (DAT_0073a43c == (int *)0x0) {
    __vbaNew2(&DAT_00423fc0,&DAT_0073a43c);
  }
  uVar1 = (**(code **)(*DAT_0073a43c + 0x314))(DAT_0073a43c);
  piVar2 = (int *)__vbaObjSet(&local_20,uVar1);
  iVar3 = (**(code **)(*piVar2 + 0x40))(piVar2,0,&local_24);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_004480b4,0x40);
  }
  piVar2 = local_24;
  uVar1 = (**(code **)(*piVar5 + 0x2fc))(piVar5);
  piVar4 = (int *)__vbaObjSet(&local_28,uVar1);
  iVar3 = (**(code **)(*piVar4 + 0xa0))(piVar4,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_0043f42c,0xa0);
  }
  iVar3 = (**(code **)(*piVar2 + 0xa4))(piVar2,local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_0043f42c,0xa4);
  }
  __vbaFreeStr();
  __vbaFreeObjList(3,&local_20,&local_28,&local_24);
  if (DAT_0073a43c == (int *)0x0) {
    __vbaNew2(&DAT_00423fc0,&DAT_0073a43c);
  }
  piVar2 = DAT_0073a43c;
  local_2c = 0;
  iVar3 = (**(code **)(*DAT_0073a43c + 0x6f8))(DAT_0073a43c,&local_2c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_004480f4,0x6f8);
  }
  while( true ) {
    if (DAT_0073a400 == (int *)0x0) {
      __vbaNew2(&DAT_0041ff20,&DAT_0073a400);
    }
    piVar2 = DAT_0073a400;
    iVar3 = (**(code **)(*DAT_0073a400 + 0x1b8))(DAT_0073a400,&local_2c);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,piVar2,&DAT_00447e30,0x1b8);
    }
    if (((short)local_2c == 0) || ((short)piVar5[0xd] != 0)) break;
    rtcDoEvents();
  }
  uVar1 = (**(code **)(*piVar5 + 0x2fc))(piVar5);
  piVar5 = (int *)__vbaObjSet(&local_28,uVar1);
  if (DAT_0073a43c == (int *)0x0) {
    __vbaNew2(&DAT_00423fc0,&DAT_0073a43c);
  }
  uVar1 = (**(code **)(*DAT_0073a43c + 0x314))(DAT_0073a43c);
  piVar2 = (int *)__vbaObjSet(&local_20,uVar1);
  iVar3 = (**(code **)(*piVar2 + 0x40))(piVar2,0,&local_24);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_004480b4,0x40);
  }
  piVar2 = local_24;
  iVar3 = (**(code **)(*local_24 + 0xa0))(local_24,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar2,&DAT_0043f42c,0xa0);
  }
  iVar3 = (**(code **)(*piVar5 + 0xa4))(piVar5,local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar5,&DAT_0043f42c,0xa4);
  }
  __vbaFreeStr();
  __vbaFreeObjList(3,&local_20,&local_24,&local_28);
  return;
}


// ---- Form_Activate @ 00610310

void frmTellAFriend::Form_Activate(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_50;
  undefined4 local_4c;
  undefined4 local_48;
  undefined4 local_40;
  undefined4 local_3c;
  undefined4 local_38;
  undefined4 local_30;
  undefined4 local_2c;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff94;
  local_c = &DAT_00404ba8;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  local_1c = 0;
  local_2c = 0;
  local_3c = 0;
  local_4c = 0;
  if (*(short *)((int)piVar3 + 0x36) == 0) {
    local_50 = 0xffffffff;
    uVar1 = __vbaCastObj(piVar3,&DAT_00440b00);
    __vbaObjSet(&local_1c,uVar1);
    iVar2 = (**(code **)(*DAT_0073a218 + 0x20))(DAT_0073a218,&local_1c,&local_50);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,DAT_0073a218,&DAT_00440b10,0x20);
    }
    __vbaFreeObj();
    iVar2 = (**(code **)(*DAT_0073a08c + 100))(DAT_0073a08c,L"GestureDown",&local_1c);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,DAT_0073a08c,&DAT_004419ac,100);
    }
    __vbaFreeObj();
    iVar2 = (**(code **)(*DAT_0073a08c + 0x78))
                      (DAT_0073a08c,8,local_38,
                       L"You can enter as many friends\' and loved ones\' e-mail addresses as you would like!"
                       ,local_30,10,local_48,0x80020004,local_40,&local_1c);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,DAT_0073a08c,&DAT_004419ac,0x78);
    }
    __vbaFreeObj();
    iVar2 = (**(code **)(*DAT_0073a08c + 100))(DAT_0073a08c,L"Explain",&local_1c);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,DAT_0073a08c,&DAT_004419ac,100);
    }
    __vbaFreeObj();
    local_24 = __vbaStrCat(L"will allow your friends and loved ones to download little old me for Free!"
                           ,
                           L"\\pau=1000\\I will be happy to send them an automated e-mail message on your behalf! \\pau=1000\\This "
                          );
    local_2c = 8;
    iVar2 = (**(code **)(*DAT_0073a08c + 0x78))
                      (DAT_0073a08c,8,local_28,local_24,local_20,10,local_38,0x80020004,local_30,
                       &local_1c);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,DAT_0073a08c,&DAT_004419ac,0x78);
    }
    __vbaFreeObj();
    __vbaFreeVar();
    iVar2 = (**(code **)(*DAT_0073a08c + 100))(DAT_0073a08c,L"Greet",&local_1c);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,DAT_0073a08c,&DAT_004419ac,100);
    }
    __vbaFreeObj();
    local_24 = __vbaStrCat(L", if your friends are anything like you, I can\'t wait to meet them!",
                           DAT_0073a040);
    local_2c = 8;
    iVar2 = (**(code **)(*DAT_0073a08c + 0x78))
                      (DAT_0073a08c,8,local_28,local_24,local_20,10,local_38,0x80020004,local_30,
                       &local_1c);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,DAT_0073a08c,&DAT_004419ac,0x78);
    }
    __vbaFreeObj();
    __vbaFreeVar();
    iVar2 = (**(code **)(*DAT_0073a08c + 100))(DAT_0073a08c,L"Pleased",&local_1c);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,DAT_0073a08c,&DAT_004419ac,100);
    }
    __vbaFreeObj();
    rtcSaveSetting(&PTR_DAT_0043b010,L"BonziMAIL",L"TellAFriend",L"TRUE");
    DAT_0073a0ae = 0;
    iVar2 = (**(code **)(*DAT_0073a08c + 100))(DAT_0073a08c,L"Blink",&local_1c);
    if (iVar2 < 0) {
      __vbaHresultCheckObj(iVar2,DAT_0073a08c,&DAT_004419ac,100);
    }
    uVar1 = local_1c;
    local_1c = 0;
    __vbaObjSet(&DAT_0073a204,uVar1);
    *(undefined2 *)((int)piVar3 + 0x36) = 0xffff;
  }
  return;
}


// ---- Form_Load @ 006106e0

void frmTellAFriend::Form_Load(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00404bb8;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  local_1c = 0;
  *(undefined2 *)(piVar3 + 0xd) = 0;
  *(undefined2 *)((int)piVar3 + 0x36) = 0;
  uVar1 = (**(code **)(*piVar3 + 0x304))(piVar3);
  piVar3 = (int *)__vbaObjSet(&local_1c,uVar1);
  iVar2 = (**(code **)(*piVar3 + 0xa4))(piVar3,DAT_0073a040);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar3,&DAT_0043f42c,0xa4);
  }
  __vbaFreeObj();
  return;
}


// ---- Form_Unload @ 006107b0

void frmTellAFriend::Form_Unload(uint param_1)

{
  undefined4 uVar1;
  int iVar2;
  int *piVar3;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc4;
  local_c = &DAT_00404bc8;
  local_8 = param_1 & 1;
  piVar3 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar3 + 4))(piVar3);
  local_1c = 0;
  *(undefined2 *)(piVar3 + 0xd) = 0xffff;
  local_24 = 0;
  local_20 = 0;
  uVar1 = __vbaCastObj(piVar3,&DAT_00440b00);
  __vbaObjSet(&local_1c,uVar1);
  iVar2 = (**(code **)(*DAT_0073a218 + 0x1c))(DAT_0073a218,&local_1c,&local_20,&local_24);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,DAT_0073a218,&DAT_00440b10,0x1c);
  }
  __vbaFreeObj();
  return;
}


// ---- Import @ 00610890

void frmTellAFriend::Import(int *param_1)

{
  int *piVar1;
  undefined4 uVar2;
  int iVar3;
  int *piVar4;
  int *local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffb4;
  local_c = &DAT_00404bd8;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  local_20 = 0;
  local_24 = (int *)0x0;
  if (DAT_0073c818 == (int *)0x0) {
    __vbaNew2(&DAT_00441f00,&DAT_0073c818);
  }
  piVar4 = DAT_0073c818;
  if (DAT_0073a400 == (int *)0x0) {
    __vbaNew2(&DAT_0041ff20,&DAT_0073a400);
  }
  iVar3 = *piVar4;
  uVar2 = __vbaObjSetAddref(&local_20,DAT_0073a400);
  iVar3 = (**(code **)(iVar3 + 0xc))(piVar4,uVar2);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_00441ef0,0xc);
  }
  __vbaFreeObj();
  uVar2 = (**(code **)(*param_1 + 0x2fc))(param_1);
  piVar4 = (int *)__vbaObjSet(&local_20,uVar2);
  if (DAT_0073a400 == (int *)0x0) {
    __vbaNew2(&DAT_0041ff20,&DAT_0073a400);
  }
  piVar1 = DAT_0073a400;
  iVar3 = (**(code **)(*DAT_0073a400 + 0x6f8))(DAT_0073a400,&local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar1,&DAT_00447e60,0x6f8);
  }
  iVar3 = (**(code **)(*piVar4 + 0xa4))(piVar4,local_1c);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_0043f42c,0xa4);
  }
  __vbaFreeStr();
  __vbaFreeObj();
  uVar2 = (**(code **)(*param_1 + 0x2fc))(param_1);
  piVar4 = (int *)__vbaObjSet(&local_20,uVar2);
  iVar3 = (**(code **)(*piVar4 + 0x8c))(piVar4,0xffffffff);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_0043f42c,0x8c);
  }
  __vbaFreeObj();
  uVar2 = (**(code **)(*param_1 + 0x304))(param_1);
  piVar4 = (int *)__vbaObjSet(&local_20,uVar2);
  iVar3 = (**(code **)(*piVar4 + 0x8c))(piVar4,0xffffffff);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_0043f42c,0x8c);
  }
  __vbaFreeObj();
  uVar2 = (**(code **)(*param_1 + 0x314))(param_1);
  piVar4 = (int *)__vbaObjSet(&local_20,uVar2);
  iVar3 = (**(code **)(*piVar4 + 0x40))(piVar4,0,&local_24);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_004480b4,0x40);
  }
  piVar4 = local_24;
  iVar3 = (**(code **)(*local_24 + 0x8c))(local_24,0xffffffff);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_004431b8,0x8c);
  }
  __vbaFreeObjList(2,&local_20,&local_24);
  uVar2 = (**(code **)(*param_1 + 0x310))(param_1);
  piVar4 = (int *)__vbaObjSet(&local_20,uVar2);
  iVar3 = (**(code **)(*piVar4 + 0x8c))(piVar4,0xffffffff);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_004431b8,0x8c);
  }
  __vbaFreeObj();
  if (DAT_0073a488 == (int *)0x0) {
    __vbaNew2(&DAT_00419e7c,&DAT_0073a488);
  }
  piVar4 = DAT_0073a488;
  iVar3 = (**(code **)(*DAT_0073a488 + 0x94))(DAT_0073a488,0xffffffff);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar4,&DAT_0044a998,0x94);
  }
  iVar3 = (**(code **)(*DAT_0073a08c + 100))(DAT_0073a08c,L"Blink",&local_20);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,DAT_0073a08c,&DAT_004419ac,100);
  }
  uVar2 = local_20;
  local_20 = 0;
  __vbaObjSet(&DAT_0073a1d8,uVar2);
  return;
}


