// BonziBDY_4.EXE :: modBBIM
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 3

// ---- Proc_71cfc0 @ 0071cfc0

/* WARNING: Restarted to delay deadcode elimination for space: ram */

void modBBIM::Proc_71cfc0(void)

{
  int *piVar1;
  code *pcVar2;
  undefined2 uVar3;
  short sVar4;
  int iVar5;
  undefined *puVar6;
  undefined4 *puVar7;
  undefined2 extraout_var;
  undefined2 extraout_var_00;
  undefined2 extraout_var_01;
  undefined2 uVar8;
  bool bVar9;
  int local_150;
  undefined1 local_14c [4];
  undefined4 local_148 [2];
  undefined4 *local_140;
  undefined1 local_128 [16];
  undefined4 local_118 [2];
  undefined4 local_110;
  int *local_108;
  undefined1 local_104 [4];
  undefined4 local_100;
  undefined4 local_fc;
  int local_f8 [25];
  undefined1 local_94 [8];
  undefined4 uStack_8c;
  int iStack_88;
  int *piStack_84;
  int *piStack_80;
  undefined1 *puStack_7c;
  int *piStack_78;
  undefined4 *puStack_74;
  int **ppiStack_70;
  int *piStack_6c;
  undefined4 *puStack_68;
  int *piStack_64;
  undefined4 *puStack_60;
  int **ppiStack_5c;
  wchar_t *pwStack_58;
  int *piStack_54;
  int *piStack_50;
  int *piStack_4c;
  int *piStack_48;
  int **ppiStack_44;
  int *piStack_40;
  undefined4 *puStack_3c;
  int *piStack_38;
  int **ppiStack_34;
  int iVar10;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00411820;
  local_14 = 0;
  local_10 = 0;
  local_8 = 2;
  ppiStack_34 = (int **)0xffffffff;
  piStack_38 = (int *)0x71d014;
  __vbaOnError();
  local_8 = 3;
  local_110 = 0x80020004;
  local_118[0] = 10;
  ppiStack_34 = (int **)local_118;
  piStack_38 = (int *)0x71d03c;
  uVar3 = rtcFreeFile();
  ppiStack_34 = (int **)0x71d04c;
  __vbaFreeVar();
  local_8 = 4;
  if (DAT_0073c818 == (int *)0x0) {
    ppiStack_34 = &DAT_0073c818;
    piStack_38 = (int *)&DAT_00441f00;
    puStack_3c = (undefined4 *)0x71d06c;
    __vbaNew2();
  }
  piVar1 = DAT_0073c818;
  ppiStack_34 = &local_108;
  puStack_3c = (undefined4 *)0x71d0a9;
  piStack_38 = piVar1;
  iVar5 = (**(code **)(*DAT_0073c818 + 0x14))();
  if (iVar5 < 0) {
    puStack_3c = (undefined4 *)0x14;
    piStack_40 = (int *)&DAT_00441ef0;
    piStack_4c = (int *)0x71d0d5;
    piStack_48 = (int *)iVar5;
    ppiStack_44 = (int **)piVar1;
    __vbaHresultCheckObj();
  }
  piVar1 = local_108;
  puStack_3c = &local_100;
  piStack_40 = local_108;
  ppiStack_44 = (int **)0x71d10c;
  piStack_50 = (int *)(**(code **)(*local_108 + 0x50))();
  if ((int)piStack_50 < 0) {
    ppiStack_44 = (int **)0x50;
    piStack_48 = (int *)&DAT_004437b4;
    piStack_4c = piVar1;
    piStack_54 = (int *)0x71d138;
    __vbaHresultCheckObj();
  }
  local_110 = local_100;
  local_100 = 0;
  local_118[0] = 8;
  ppiStack_44 = (int **)0x1;
  piStack_48 = local_118;
  piStack_4c = (int *)local_128;
  piStack_50 = (int *)0x71d18c;
  rtcRightCharVar();
  local_140 = (undefined4 *)&DAT_00441f24;
  local_148[0] = 0x8008;
  ppiStack_44 = (int **)local_128;
  piStack_48 = local_148;
  piStack_4c = (int *)0x71d1b4;
  sVar4 = __vbaVarTstEq();
  ppiStack_44 = (int **)0x71d1c7;
  __vbaFreeObj();
  ppiStack_44 = (int **)local_128;
  piStack_48 = local_118;
  piStack_4c = (int *)0x2;
  piStack_50 = (int *)0x71d1dd;
  __vbaFreeVarList();
  if (sVar4 == 0) {
    local_8 = 7;
    if (DAT_0073c818 == (int *)0x0) {
      ppiStack_44 = &DAT_0073c818;
      piStack_48 = (int *)&DAT_00441f00;
      piStack_4c = (int *)0x71d34a;
      __vbaNew2();
    }
    piVar1 = DAT_0073c818;
    ppiStack_44 = &local_108;
    piStack_4c = (int *)0x71d387;
    piStack_48 = piVar1;
    iVar5 = (**(code **)(*DAT_0073c818 + 0x14))();
    if (iVar5 < 0) {
      piStack_4c = (int *)0x14;
      piStack_50 = (int *)&DAT_00441ef0;
      ppiStack_5c = (int **)0x71d3b3;
      pwStack_58 = (wchar_t *)iVar5;
      piStack_54 = piVar1;
      __vbaHresultCheckObj();
    }
    piVar1 = local_108;
    piStack_4c = &local_100;
    piStack_50 = local_108;
    piStack_54 = (int *)0x71d3ea;
    iVar5 = (**(code **)(*local_108 + 0x50))();
    if (iVar5 < 0) {
      piStack_54 = (int *)0x50;
      pwStack_58 = L"佹㎭暙ᇏಷꨀ怀鏓Ô";
      ppiStack_5c = (int **)piVar1;
      piStack_64 = (int *)0x71d416;
      puStack_60 = (undefined4 *)iVar5;
      __vbaHresultCheckObj();
    }
    piStack_54 = (int *)local_100;
    pwStack_58 = L"\\";
    ppiStack_5c = (int **)0x71d43a;
    __vbaStrCat();
    piStack_54 = (int *)0x71d448;
    piStack_54 = (int *)__vbaStrMove();
    pwStack_58 = L"contacts.nbd";
    ppiStack_5c = (int **)0x71d454;
    __vbaStrCat();
    piStack_54 = (int *)0x71d462;
    __vbaStrMove();
    piStack_54 = (int *)local_104;
    pwStack_58 = (wchar_t *)&local_100;
    ppiStack_5c = (int **)0x2;
    puStack_60 = (undefined4 *)0x71d478;
    __vbaFreeStrList();
    piStack_54 = (int *)0x71d487;
    __vbaFreeObj();
  }
  else {
    local_8 = 5;
    if (DAT_0073c818 == (int *)0x0) {
      ppiStack_44 = &DAT_0073c818;
      piStack_48 = (int *)&DAT_00441f00;
      piStack_4c = (int *)0x71d20f;
      __vbaNew2();
    }
    piVar1 = DAT_0073c818;
    ppiStack_44 = &local_108;
    piStack_4c = (int *)0x71d24c;
    piStack_48 = piVar1;
    iVar5 = (**(code **)(*DAT_0073c818 + 0x14))();
    if (iVar5 < 0) {
      piStack_4c = (int *)0x14;
      piStack_50 = (int *)&DAT_00441ef0;
      ppiStack_5c = (int **)0x71d278;
      pwStack_58 = (wchar_t *)iVar5;
      piStack_54 = piVar1;
      __vbaHresultCheckObj();
    }
    piVar1 = local_108;
    piStack_4c = &local_100;
    piStack_50 = local_108;
    piStack_54 = (int *)0x71d2af;
    iVar5 = (**(code **)(*local_108 + 0x50))();
    if (iVar5 < 0) {
      piStack_54 = (int *)0x50;
      pwStack_58 = L"佹㎭暙ᇏಷꨀ怀鏓Ô";
      ppiStack_5c = (int **)piVar1;
      piStack_64 = (int *)0x71d2db;
      puStack_60 = (undefined4 *)iVar5;
      __vbaHresultCheckObj();
    }
    piStack_54 = (int *)local_100;
    pwStack_58 = L"contacts.nbd";
    ppiStack_5c = (int **)0x71d2ff;
    __vbaStrCat();
    piStack_54 = (int *)0x71d30d;
    __vbaStrMove();
    piStack_54 = (int *)0x71d319;
    __vbaFreeStr();
    piStack_54 = (int *)0x71d325;
    __vbaFreeObj();
  }
  local_8 = 9;
  local_140 = &local_fc;
  local_148[0] = 0x4008;
  piStack_54 = (int *)0x0;
  pwStack_58 = (wchar_t *)local_148;
  ppiStack_5c = (int **)0x71d4b3;
  rtcDir();
  piStack_54 = (int *)0x71d4c1;
  piStack_54 = (int *)__vbaStrMove();
  pwStack_58 = L"";
  ppiStack_5c = (int **)0x71d4cd;
  iVar5 = __vbaStrCmp();
  piStack_54 = (int *)0x71d4e8;
  __vbaFreeStr();
  uVar8 = extraout_var_00;
  if (iVar5 != 0) {
    local_8 = 10;
    local_140 = &local_fc;
    local_148[0] = 0x4008;
    piStack_54 = local_148;
    pwStack_58 = L"䗇೼";
    rtcKillFiles();
    uVar8 = extraout_var_01;
  }
  local_8 = 0xc;
  piStack_54 = (int *)local_fc;
  pwStack_58 = (wchar_t *)CONCAT22(uVar8,uVar3);
  ppiStack_5c = (int **)0x66;
  puStack_60 = (undefined4 *)0x4004;
  piStack_64 = (int *)0x71d53d;
  __vbaFileOpen();
  local_8 = 0xd;
  piStack_54 = &local_150;
  pwStack_58 = (wchar_t *)DAT_0073a708;
  ppiStack_5c = (int **)0x71d55c;
  puVar6 = (undefined *)(**(code **)(*DAT_0073a708 + 0x24))();
  if ((int)puVar6 < 0) {
    ppiStack_5c = (int **)0x24;
    puStack_60 = (undefined4 *)&DAT_00471c84;
    piStack_64 = DAT_0073a708;
    piStack_6c = (int *)0x71d588;
    puStack_68 = (undefined4 *)puVar6;
    __vbaHresultCheckObj();
  }
  iVar10 = 1;
  iVar5 = local_150;
  do {
    if (local_150 < iVar10) {
      local_8 = 0x12;
      ppiStack_5c = (int **)CONCAT22((short)((uint)iVar5 >> 0x10),uVar3);
      puStack_60 = (undefined4 *)0x71d813;
      __vbaFileClose();
      ppiStack_5c = (int **)&LAB_0071d86d;
      puStack_60 = (undefined4 *)0x71d86c;
      __vbaFreeStr();
      return;
    }
    local_8 = 0xe;
    local_140 = (undefined4 *)&stack0xffffffd8;
    local_148[0] = 0x4003;
    ppiStack_5c = &local_108;
    puStack_60 = local_148;
    piStack_64 = DAT_0073a708;
    puStack_68 = (undefined4 *)0x71d613;
    puVar7 = (undefined4 *)(**(code **)(*DAT_0073a708 + 0x20))();
    if ((int)puVar7 < 0) {
      puStack_68 = (undefined4 *)0x20;
      piStack_6c = (int *)&DAT_00471c84;
      ppiStack_70 = (int **)DAT_0073a708;
      piStack_78 = (int *)0x71d63e;
      puStack_74 = puVar7;
      __vbaHresultCheckObj();
    }
    piVar1 = local_108;
    puStack_68 = &local_100;
    piStack_6c = local_108;
    ppiStack_70 = (int **)0x71d675;
    puStack_7c = (undefined1 *)(**(code **)(*local_108 + 0x20))();
    if ((int)puStack_7c < 0) {
      ppiStack_70 = (int **)0x20;
      puStack_74 = (undefined4 *)&DAT_00471a58;
      piStack_78 = piVar1;
      piStack_80 = (int *)0x71d6a1;
      __vbaHresultCheckObj();
    }
    ppiStack_70 = (int **)local_100;
    puStack_74 = (undefined4 *)local_94;
    piStack_78 = (int *)0x32;
    puStack_7c = (undefined1 *)0x71d6c9;
    __vbaLsetFixstr();
    ppiStack_70 = (int **)0x71d6d5;
    __vbaFreeStr();
    ppiStack_70 = (int **)0x71d6e1;
    __vbaFreeObj();
    local_8 = 0xf;
    local_140 = (undefined4 *)&stack0xffffffd8;
    local_148[0] = 0x4003;
    ppiStack_70 = &local_108;
    puStack_74 = local_148;
    piStack_78 = DAT_0073a708;
    puStack_7c = (undefined1 *)0x71d71b;
    iVar5 = (**(code **)(*DAT_0073a708 + 0x20))();
    if (iVar5 < 0) {
      puStack_7c = (undefined1 *)0x20;
      piStack_80 = (int *)&DAT_00471c84;
      piStack_84 = DAT_0073a708;
      uStack_8c = 0x71d747;
      iStack_88 = iVar5;
      __vbaHresultCheckObj();
    }
    piVar1 = local_108;
    puStack_7c = local_14c;
    piStack_80 = local_108;
    piStack_84 = (int *)0x71d77e;
    puVar7 = (undefined4 *)(**(code **)(*local_108 + 0x34))();
    if ((int)puVar7 < 0) {
      ppiStack_5c = (int **)0x34;
      puStack_60 = (undefined4 *)&DAT_00471a58;
      piStack_64 = piVar1;
      piStack_6c = (int *)0x71d7aa;
      puStack_68 = puVar7;
      __vbaHresultCheckObj();
    }
    ppiStack_5c = (int **)0x71d7d3;
    __vbaFreeObj();
    local_8 = 0x10;
    ppiStack_5c = (int **)CONCAT22(extraout_var,uVar3);
    piStack_64 = local_f8;
    puStack_68 = (undefined4 *)&DAT_00475578;
    piStack_6c = (int *)0x71d7f5;
    puStack_60 = (undefined4 *)iVar10;
    iVar5 = __vbaPutOwner4();
    local_8 = 0x11;
    bVar9 = SCARRY4(iVar10,1);
    iVar10 = iVar10 + 1;
  } while (!bVar9);
  ppiStack_5c = (int **)0x71d884;
  __vbaErrorOverflow();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}


// ---- Proc_71d890 @ 0071d890

void modBBIM::Proc_71d890(int param_1)

{
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00411890;
  local_14 = 0;
  local_10 = 0;
  local_8 = 2;
  __vbaOnError(0xffffffff);
  if (param_1 < 0x23) {
    if (param_1 == 0x22) {
      local_8 = 0x13;
      __vbaStrCopy();
    }
    else {
      switch(param_1) {
      case 0:
        local_8 = 5;
        __vbaStrCopy();
        break;
      case 1:
        local_8 = 7;
        __vbaStrCopy();
        break;
      case 2:
        local_8 = 9;
        __vbaStrCopy();
        break;
      case 6:
        local_8 = 0xb;
        __vbaStrCopy();
        break;
      case 10:
        local_8 = 0xd;
        __vbaStrCopy();
        break;
      case 0xe:
        local_8 = 0xf;
        __vbaStrCopy();
        break;
      case 0x12:
        local_8 = 0x11;
        __vbaStrCopy();
      }
    }
  }
  else if (param_1 < 0x201) {
    if (param_1 == 0x200) {
      local_8 = 0x1b;
      __vbaStrCopy();
    }
    else if (param_1 == 0x32) {
      local_8 = 0x15;
      __vbaStrCopy();
    }
    else if (param_1 == 0x42) {
      local_8 = 0x17;
      __vbaStrCopy();
    }
    else if (param_1 == 0x100) {
      local_8 = 0x19;
      __vbaStrCopy();
    }
  }
  else if (param_1 == 0x300) {
    local_8 = 0x1d;
    __vbaStrCopy();
  }
  else if (param_1 == 0x400) {
    local_8 = 0x1f;
    __vbaStrCopy();
  }
  return;
}


// ---- Proc_71db40 @ 0071db40

void modBBIM::Proc_71db40(undefined2 param_1)

{
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00411938;
  local_14 = 0;
  local_10 = 0;
  local_8 = 2;
  __vbaOnError(0xffffffff);
  switch(param_1) {
  case 0:
    local_8 = 5;
    __vbaStrCopy();
    break;
  case 1:
    local_8 = 7;
    __vbaStrCopy();
    break;
  case 2:
    local_8 = 9;
    __vbaStrCopy();
    break;
  case 3:
    local_8 = 0xb;
    __vbaStrCopy();
    break;
  default:
    local_8 = 0xd;
    __vbaStrCopy();
  }
  return;
}


