// BonziBDY_4.EXE :: modMail
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 5

// ---- Proc_711c40 @ 00711c40

void modMail::Proc_711c40(undefined4 param_1)

{
  int *piVar1;
  int iVar2;
  undefined4 local_24;
  int *local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  
  puStack_14 = &LAB_00412856;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffbc;
  local_c = &DAT_00411018;
  local_1c = 0;
  local_20 = (int *)0x0;
  local_24 = 0;
  ExceptionList = &pvStack_18;
  __vbaNew2(&DAT_004145e4,&local_20);
  piVar1 = local_20;
  iVar2 = (**(code **)(*local_20 + 0x2c))(local_20);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar1,&DAT_00447f48,0x2c);
  }
  if (local_20 == (int *)0x0) {
    __vbaNew2(&DAT_004145e4,&local_20);
  }
  piVar1 = local_20;
  iVar2 = (**(code **)(*local_20 + 0x38))(local_20,param_1,&local_24);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,piVar1,&DAT_00447f48,0x38);
  }
  local_24 = 0;
  __vbaStrMove();
  __vbaFreeObj(&LAB_00711d18);
  return;
}


// ---- Proc_711d30 @ 00711d30

/* WARNING: Heritage AFTER dead removal. Example location: r0x00000000 : 0x00712002 */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Restarted to delay deadcode elimination for space: ram */
/* WARNING: Restarted to delay deadcode elimination for space: stack */
/* WARNING: Exceeded maximum restarts with more pending */

void modMail::Proc_711d30(undefined4 *param_1)

{
  int ***pppiVar1;
  code *pcVar2;
  short sVar3;
  short sVar4;
  short sVar5;
  short sVar6;
  int iVar7;
  int **ppiVar8;
  short sVar9;
  bool bVar10;
  ushort uVar11;
  undefined4 *local_c0;
  int *local_a0;
  undefined local_6c [16];
  int *local_5c [4];
  undefined4 local_4c;
  undefined4 local_48;
  int **local_44;
  int ***local_40;
  int ****local_3c;
  int ***local_38;
  int ***local_34;
  undefined1 *puStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  int **local_10;
  int **ppiStack_c;
  int **local_8;
  
  puStack_20 = &LAB_00412856;
  puStack_24 = ExceptionList;
  ExceptionList = &puStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00411028;
  local_14 = 0;
  local_10 = (int **)0x0;
  local_8 = (int **)0x2;
  local_34 = (int ***)0xffffffff;
  local_38 = (int ***)0x711d84;
  __vbaOnError();
  local_8 = (int **)0x3;
  if (local_38 == (int ***)0x0) {
    local_34 = (int ***)&local_38;
    local_38 = (int ***)&DAT_004145e4;
    local_3c = (int ****)0x711da0;
    __vbaNew2();
  }
  pppiVar1 = local_38;
  ppiVar8 = *local_38;
  local_38 = (int ***)0x711dd4;
  local_34 = pppiVar1;
  local_44 = (int **)(*(code *)ppiVar8[0xb])();
  uVar11 = 0;
  if ((int)local_44 < 0) {
    local_38 = (int ***)0x2c;
    local_3c = (int ****)&DAT_00447f48;
    local_48 = 0x711e00;
    local_40 = pppiVar1;
    __vbaHresultCheckObj();
  }
  local_8 = (int **)0x4;
  local_38 = (int ***)0x0;
  local_3c = (int ****)0x474df0;
  local_40 = (int ***)local_5c;
  local_44 = (int **)0x711e2a;
  rtcCreateObject2();
  local_38 = (int ***)local_5c;
  local_3c = (int ****)0x711e34;
  local_38 = (int ***)__vbaObjVar();
  local_3c = &local_34;
  local_40 = (int ***)0x711e3f;
  __vbaObjSetAddref();
  local_38 = (int ***)0x711e48;
  __vbaFreeVar();
  local_8 = (int **)0x5;
  local_38 = (int ***)0x0;
  local_3c = (int ****)local_34;
  local_40 = (int ***)0x711e5b;
  sVar3 = __vbaObjIs();
  if (sVar3 == 0) {
    local_8 = (int **)0x8;
    local_38 = (int ***)0x711e8c;
    __vbaChkstk();
    local_34 = (int ***)0x8;
    local_38 = (int ***)0x1;
    local_3c = (int ****)0x474e28;
    local_40 = (int ***)0x8;
    local_44 = local_5c;
    local_48 = 0x711ec6;
    __vbaLateMemCallLd();
    __vbaObjVar();
    __vbaObjSetAddref();
    __vbaFreeVar();
    local_8 = (int **)0x9;
    sVar3 = __vbaObjIs();
    if (sVar3 == 0) {
      local_8 = (int **)0xc;
      __vbaChkstk();
      puStack_24 = &DAT_00000004;
      local_1c = (undefined1 *)0x0;
      __vbaLateIdSt();
      local_8 = (int **)0xd;
      local_18 = (undefined *)0x711f80;
      __vbaChkstk();
      local_14 = 4;
      ppiStack_c = (int **)0x0;
      local_18 = (undefined *)0x2;
      local_1c = (undefined1 *)*param_1;
      puStack_20 = (undefined1 *)0x711fb3;
      __vbaLateIdSt();
      local_8 = (int **)0x711fd8;
      __vbaChkstk();
      local_8 = (int **)0x1;
      ppiStack_c = (int **)_DAT_00000000;
      local_10 = (int **)0x71200b;
      __vbaLateIdSt();
      local_8 = (int **)0x5;
      ppiStack_c = local_5c;
      local_10 = (int **)0x712042;
      __vbaLateMemCallLd();
      local_8 = (int **)0x712050;
      __vbaVarLateMemCallLd();
      sVar3 = __vbaVarTstEq();
      __vbaFreeVarList();
      if (sVar3 == 0) {
        local_8 = (int **)0x5;
        ppiStack_c = local_5c;
        local_10 = (int **)0x7120ae;
        __vbaLateMemCallLd();
        local_8 = (int **)0x7120bc;
        __vbaVarLateMemCallLd();
        sVar3 = __vbaI2Var();
        sVar9 = 1;
        local_8 = (int **)0x7120ec;
        __vbaFreeVarList();
        do {
          if (sVar3 < sVar9) {
            local_8 = (int **)0x15;
            rtcDoEvents();
            local_8 = (int **)0x472ebc;
            local_10 = local_5c;
            local_14 = 0x71227e;
            ppiStack_c = (int **)5;
            __vbaLateMemCallLd();
            local_8 = (int **)local_6c;
            ppiStack_c = (int **)0x71228c;
            __vbaVarLateMemCallLd();
            sVar3 = __vbaI2Var();
            sVar9 = 1;
            local_8 = (int **)0x7122bc;
            __vbaFreeVarList();
            goto LAB_007122d6;
          }
          local_8 = local_5c;
          ppiStack_c = (int **)0x712132;
          __vbaLateIdCallLd();
          __vbaR4Var();
          local_8 = (int **)0x453660;
          ppiStack_c = (int **)0x712177;
          __vbaChkstk();
          local_8 = (int **)0x4002;
          ppiStack_c = (int **)0x1;
          local_10 = (int **)0x472ebc;
          local_18 = local_6c;
          local_1c = (undefined1 *)0x7121b1;
          local_14 = 5;
          __vbaLateMemCallLd();
          __vbaVarLateMemCallLd();
          __vbaVarAdd();
          __vbaR4Var();
          ppiStack_c = (int **)0x7121f1;
          __vbaChkstk();
          local_8 = (int **)0x4;
          ppiStack_c = (int **)0x1;
          local_10 = (int **)*local_c0;
          local_14 = 0x712224;
          __vbaLateIdSt();
          local_8 = local_5c;
          ppiStack_c = (int **)&DAT_00000004;
          local_10 = (int **)0x71223f;
          __vbaFreeVarList();
          local_8 = (int **)0x14;
          bVar10 = SCARRY2(sVar9,1);
          sVar9 = sVar9 + 1;
        } while (!bVar10);
        goto LAB_00712974;
      }
    }
  }
code_r0x007128ef:
  local_38 = (int ***)&LAB_0071295c;
  local_3c = (int ****)0x712940;
  __vbaFreeObj();
  local_3c = (int ****)0x712949;
  __vbaFreeObj();
  local_3c = (int ****)0x712952;
  __vbaFreeObj();
  local_3c = (int ****)0x71295b;
  __vbaFreeObj();
  return;
  while( true ) {
    local_8 = (int **)0x17;
    __vbaChkstk();
    local_8 = local_5c;
    ppiStack_c = (int **)0x712345;
    __vbaLateMemCallLd();
    __vbaObjVar();
    __vbaObjSetAddref();
    __vbaFreeVar();
    local_8 = (int **)0x18;
    __vbaLateMemCallLd();
    __vbaVarLateMemCallLd();
    sVar4 = __vbaVarTstGt();
    __vbaFreeVarList();
    if (sVar4 != 0) {
      local_8 = (int **)0x19;
      __vbaLateMemCallLd();
      __vbaVarLateMemCallLd();
      sVar4 = __vbaI2Var();
      sVar5 = 1;
      local_8 = (int **)0x712443;
      __vbaFreeVarList();
      while (sVar5 <= sVar4) {
        local_8 = (int **)0x1a;
        __vbaChkstk();
        local_8 = (int **)0x4743a4;
        ppiStack_c = (int **)local_3c;
        local_10 = local_5c;
        local_14 = 0x7124d3;
        __vbaLateMemCallLd();
        __vbaVarLateMemCallLdRf();
        rtcTrimVar();
        rtcUpperCaseVar();
        sVar6 = __vbaVarTstEq();
        __vbaFreeVarList();
        if (sVar6 != 0) {
          local_8 = (int **)0x1b;
          __vbaChkstk();
          __vbaLateMemCallLd();
          __vbaVarLateMemCallLd();
          __vbaStrVarVal();
          rtcReplace();
          __vbaStrMove();
          __vbaChkstk();
          __vbaLateMemCallLd();
          __vbaVarLateMemCallLd();
          if (local_38 == (int ***)0x0) {
            __vbaNew2();
          }
          pppiVar1 = local_38;
          __vbaStrVarMove();
          __vbaStrMove();
          local_4c = 0;
          __vbaStrMove();
          iVar7 = (*(code *)(*pppiVar1)[9])();
          uVar11 = 0;
          if (iVar7 < 0) {
            __vbaHresultCheckObj();
          }
          __vbaFreeStrList();
          __vbaFreeVarList();
        }
        local_8 = (int **)0x1d;
        __vbaLateIdCallLd();
        __vbaR4Var();
        if ((uVar11 & 0xd) != 0) {
          __vbaFPException();
          return;
        }
        ppiStack_c = (int **)0x7127d9;
        __vbaChkstk();
        local_8 = (int **)0x4;
        ppiStack_c = (int **)&DAT_00000005;
        local_10 = (int **)*local_a0;
        local_14 = 0x71280c;
        __vbaLateIdSt();
        __vbaFreeVar();
        local_8 = (int **)0x1e;
        rtcDoEvents();
        local_8 = (int **)0x1f;
        bVar10 = SCARRY2(sVar5,1);
        sVar5 = sVar5 + 1;
        if (bVar10) goto LAB_00712974;
      }
    }
    local_8 = (int **)0x21;
    bVar10 = SCARRY2(sVar9,1);
    sVar9 = sVar9 + 1;
    if (bVar10) break;
LAB_007122d6:
    if (sVar3 < sVar9) {
      local_8 = (int **)0x22;
      __vbaObjSetAddref();
      local_8 = (int **)0x23;
      __vbaObjSetAddref();
      local_8 = (int **)0x24;
      if (local_38 == (int ***)0x0) {
        __vbaNew2();
      }
      pppiVar1 = local_38;
      ppiVar8 = (int **)(*(code *)(*local_38)[0xc])();
      if ((int)ppiVar8 < 0) {
        local_38 = (int ***)0x30;
        local_3c = (int ****)&DAT_00447f48;
        local_48 = 0x7128dc;
        local_44 = ppiVar8;
        local_40 = pppiVar1;
        __vbaHresultCheckObj();
      }
      goto code_r0x007128ef;
    }
  }
LAB_00712974:
  __vbaErrorOverflow();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}


// ---- Proc_712980 @ 00712980

void modMail::Proc_712980(void)

{
  short sVar1;
  undefined *local_68;
  undefined4 local_64;
  undefined **local_60;
  undefined4 *local_5c;
  undefined **local_58;
  undefined4 local_54;
  undefined4 local_50;
  undefined4 local_4c;
  undefined4 local_48;
  undefined4 uStack_40;
  undefined **ppuStack_3c;
  wchar_t *pwStack_38;
  undefined **ppuStack_34;
  undefined **local_24;
  wchar_t *local_20;
  undefined **local_1c;
  undefined4 *local_18;
  undefined **local_14;
  undefined4 local_10;
  undefined4 local_c;
  undefined4 local_8;
  
  local_20 = 
  L"◿ቌ@◿ኔ@◿ᄬ@◿ნ@◿ጄ@◿ၔ@◿ጸ@◿ᄴ@◿ጬ@◿ገ@◿ተ@◿ለ@◿ቬ@◿ၼ@◿လ@◿Ꮀ@◿ဘ@◿ᐘ@◿ዔ@◿ᅬ@◿ሴ@◿᐀@◿Ꮸ@◿ᇨ@◿ᆸ@◿ዼ@◿ᐰ@◿Ꮔ@◿ᐬ@◿჌@◿ᄨ@◿႘@◿ူ@◿ၨ@◿ၐ@◿ᅔ@◿ፈ@◿ጤ@◿ႈ@◿Ꮐ@◿၄@◿ᄰ@◿Ᏸ@◿ᄤ@◿တ@◿ᄼ@◿ሬ@◿ᇸ@◿ፔ@◿ᄔ@◿ሔ@◿Ⴠ@◿ፀ@◿፴@◿ᄠ@◿၀@◿ጐ@◿ጼ@◿ዸ@◿ၘ@◿჈@◿በ@◿፰@◿ᎄ@◿ဌ@◿ጨ@◿ᅨ@◿ᇄ@◿ሄ@◿ዴ@◿ာ@◿ᇔ@◿Ⴐ@◿ဤ@◿᎜@◿ጜ@◿፬@◿ኸ@◿Ꭼ@◿႔@◿ቀ@◿ᅤ@◿ြ@◿ᅸ@◿ᅐ@◿ሌ@◿Ꭸ@◿ႄ@◿Ⴜ@◿ሤ@◿ዠ@◿ᆘ@◿ኰ@◿᎘@◿ဠ@◿ᏼ@◿Ⴤ@◿ᆴ@◿ዐ@◿ቜ@◿ጀ@◿ᆔ@◿Ⴌ@◿ዜ@◿ደ@◿Ꮨ@◿ᆬ@◿ከ@◿ᇤ@◿ቐ@◿ფ@◿Ꮌ@◿ᆈ@◿ኜ@◿ፌ@◿ቘ@◿ჰ@◿ᐐ@◿፤@◿ᅴ@◿ዬ@◿ႀ@◿ሠ@◿ᅰ@◿ዘ@◿ሀ@◿ᆨ@◿ኤ@◿ኀ@◿ቼ@◿ጠ@◿፠@◿Ꭴ@◿ᐨ@◿ი@◿ဈ@◿ᄸ@◿ᎈ@◿၌@◿፜@◿Ꮈ@◿ፐ@◿ၠ@◿᎔@◿ሼ@◿Ꮤ@◿Ꮰ@◿႐@◿Ꮼ@◿ᇠ@◿ᆄ@◿ዌ@◿ა@◿ᇴ@◿ᆐ@◿ሸ@◿ᅄ@◿ቨ@◿ፘ@◿Ꮴ@◿ነ@◿Ⴘ@◿ၤ@◿Ⴔ@◿ዀ@◿Ⴈ@◿ᏸ@◿Ᏼ@◿ᇜ@◿᎐@◿ᆀ@◿ᇘ@◿ኴ@◿ဨ@◿ႌ@◿ე@◿င@◿း@◿ቸ@◿ሜ@◿ᐄ@◿ၬ@◿ኄ@◿ᄐ@◿ᇼ@◿ᇐ@◿ᇀ@◿ጴ@◿፼@◿ቴ@◿Ꮄ@◿Ꮠ@◿ᐌ@◿Ꮜ@◿ᆠ@◿ၸ@◿ᅠ@◿ᐴ@◿ኼ@◿ᅘ@◿ወ@◿ᎀ@◿ᐤ@◿Ꭰ@◿რ@◿ᅜ@◿ᅼ@◿ᆰ@◿ᄌ@◿ᇌ@◿ᅌ@◿ኬ@◿የ@◿Ⴄ@◿ᆼ@◿၈@◿ቔ@◿ᄈ@◿န@◿ᄜ@◿ᐈ@◿ᄄ@◿ჴ@◿ၴ@◿ጘ@◿ሐ@◿ኘ@◿Ⴀ@◿ᎌ@◿ሰ@◿ኌ@◿წ@◿ᇰ@◿ᆤ@◿ၰ@◿ጌ@◿ቤ@◿ቈ@◿ᄀ@◿ᐔ@◿ᇈ@◿Ꮬ@◿ጰ@◿ႜ@◿ဴ@◿ჼ@◿ዤ@◿ᇬ@◿ዄ@◿ኈ@◿ᐠ@◿Ꮘ@◿ᐜ@◿ᅀ@◿ቄ@◿ᆜ@◿ረ@◿ᄘ@◿ᅈ@◿ጔ@◿ჸ@◿መ@◿შ@◿က@◿ၜ@◿አ@◿፨@◿፸@◿ፄ@表䄶\xe800\xfff0\xffff"
  ;
  local_24 = ExceptionList;
  ExceptionList = &local_24;
  __vbaChkstk();
  local_1c = (undefined **)&stack0xffffffd0;
  local_18 = (undefined4 *)&DAT_004110e0;
  local_14 = (undefined **)0x0;
  local_10 = 0;
  local_8 = 2;
  ppuStack_34 = (undefined **)0x1;
  pwStack_38 = L"䗇ϼ";
  __vbaOnError();
  local_8 = 4;
  local_5c = &DAT_0043c9f4;
  local_64 = 8;
  ppuStack_34 = (undefined **)0x712a04;
  __vbaChkstk();
  local_24 = local_58;
  ppuStack_34 = &PTR_DAT_004749a4;
  pwStack_38 = L"BonziMAIL";
  ppuStack_3c = &PTR_DAT_0043b010;
  uStack_40 = 0x712a32;
  rtcGetSetting();
  local_24 = (undefined **)0x712a3d;
  __vbaStrMove();
  local_68._0_2_ = 0;
  local_24 = (undefined **)0x712a62;
  __vbaStrMove();
  local_24 = &local_68;
  modTextCrypt::Proc_71bd50();
  __vbaStrMove();
  __vbaStrCopy();
  ppuStack_34 = (undefined **)&stack0xffffffd8;
  pwStack_38 = (wchar_t *)0x3;
  ppuStack_3c = (undefined **)0x712a9c;
  __vbaFreeStrList();
  local_8 = 5;
  local_5c = &DAT_0043c9f4;
  local_64 = 8;
  __vbaChkstk();
  local_24 = local_60;
  local_20 = (wchar_t *)local_5c;
  local_1c = local_58;
  ppuStack_34 = &PTR_DAT_0043b010;
  pwStack_38 = L"킋䶍ￔ쀕䀓昀䗇\x9c謀푅薉｠\xffff䗇Ô";
  rtcGetSetting();
  local_1c = (undefined **)0x712af7;
  __vbaStrMove();
  local_68._0_2_ = 0;
  local_1c = (undefined **)0x712b1c;
  __vbaStrMove();
  local_1c = &local_68;
  local_20 = (wchar_t *)&stack0xffffffd8;
  local_24 = (undefined **)0x712b29;
  modTextCrypt::Proc_71bd50();
  local_24 = (undefined **)0x712b34;
  __vbaStrMove();
  local_24 = (undefined **)0x712b45;
  __vbaStrCopy();
  local_24 = (undefined **)&stack0xffffffd0;
  ppuStack_34 = (undefined **)0x712b59;
  __vbaFreeStrList();
  local_8 = 6;
  local_5c = &DAT_0043c9f4;
  local_64 = 8;
  local_24 = (undefined **)0x712b7b;
  __vbaChkstk();
  local_20 = (wchar_t *)local_64;
  local_1c = local_60;
  local_18 = local_5c;
  local_14 = local_58;
  local_24 = &PTR_DAT_0047387c;
  rtcGetSetting();
  local_14 = (undefined **)0x712bb4;
  __vbaStrMove();
  local_68._0_2_ = 0;
  local_14 = (undefined **)0x712bd9;
  __vbaStrMove();
  local_14 = &local_68;
  local_18 = (undefined4 *)&stack0xffffffd8;
  local_1c = (undefined **)0x712be6;
  modTextCrypt::Proc_71bd50();
  local_1c = (undefined **)0x712bf1;
  __vbaStrMove();
  local_1c = (undefined **)0x712c02;
  __vbaStrCopy();
  local_1c = (undefined **)&stack0xffffffd0;
  local_20 = (wchar_t *)&stack0xffffffd4;
  local_24 = (undefined **)&stack0xffffffd8;
  __vbaFreeStrList();
  local_8 = 7;
  local_1c = (undefined **)0x0;
  local_20 = L"䖉잸끅\b";
  local_4c = __vbaStrI4();
  local_54 = 8;
  local_1c = (undefined **)0x712c3c;
  __vbaChkstk();
  local_18 = (undefined4 *)local_54;
  local_14 = (undefined **)local_50;
  local_10 = local_4c;
  local_c = local_48;
  local_1c = &PTR_DAT_004732b8;
  local_20 = L"BonziMAIL";
  local_24 = &PTR_DAT_0043b010;
  rtcGetSetting();
  local_c = 0x712c75;
  local_c = __vbaStrMove();
  local_10 = 0x712c7c;
  sVar1 = __vbaI2Str();
  DAT_0073a2b0 = (int)sVar1;
  local_c = 0x712c91;
  __vbaFreeStr();
  local_c = 0x712c9a;
  __vbaFreeVar();
  local_8 = 8;
  local_c = 0x712ed4;
  __vbaExitProc();
  return;
}


// ---- SaveBonziMailSettings @ 00712f30

void modMail::SaveBonziMailSettings(void)

{
  undefined4 uVar1;
  void *pvStack_24;
  undefined1 *puStack_20;
  undefined1 *local_1c;
  undefined *local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_8;
  
  puStack_20 = &LAB_00412856;
  pvStack_24 = ExceptionList;
  ExceptionList = &pvStack_24;
  __vbaChkstk();
  local_1c = &stack0xffffffd0;
  local_18 = &DAT_00411148;
  local_14 = 0;
  local_10 = 0;
  local_8 = 2;
  __vbaOnError(1);
  local_8 = 4;
  modTextCrypt::EncryptText(&DAT_0073a2a4);
  uVar1 = __vbaStrMove();
  rtcSaveSetting(&PTR_DAT_0043b010,L"BonziMAIL",&PTR_DAT_004749a4,uVar1);
  __vbaFreeStr();
  local_8 = 5;
  modTextCrypt::EncryptText(&DAT_0073a2a8);
  uVar1 = __vbaStrMove();
  rtcSaveSetting(&PTR_DAT_0043b010,L"BonziMAIL",&PTR_DAT_00474030,uVar1);
  __vbaFreeStr();
  local_8 = 6;
  modTextCrypt::EncryptText(&DAT_0073a2ac);
  uVar1 = __vbaStrMove();
  rtcSaveSetting(&PTR_DAT_0043b010,L"BonziMAIL",&PTR_DAT_0047387c,uVar1);
  __vbaFreeStr();
  local_8 = 7;
  __vbaStrI4(DAT_0073a2b0);
  uVar1 = __vbaStrMove();
  rtcSaveSetting(&PTR_DAT_0043b010,L"BonziMAIL",&PTR_DAT_004732b8,uVar1);
  __vbaFreeStr();
  local_8 = 8;
  __vbaExitProc();
  return;
}


// ---- Proc_713300 @ 00713300

void modMail::Proc_713300(undefined4 *param_1)

{
  short sVar1;
  undefined4 uVar2;
  int iVar3;
  undefined4 local_68 [2];
  undefined4 local_60;
  undefined4 local_58 [2];
  undefined4 *local_50;
  undefined4 local_48;
  undefined4 local_38 [4];
  undefined4 local_28 [4];
  undefined4 local_18;
  void *pvStack_14;
  undefined1 *puStack_10;
  undefined1 *local_c;
  undefined *local_8;
  
  puStack_10 = &LAB_00412856;
  pvStack_14 = ExceptionList;
  local_c = &stack0xffffff84;
  local_8 = &DAT_004111b0;
  local_28[0] = 0;
  local_38[0] = 0;
  local_48 = 0;
  local_68[0] = 0;
  local_18 = 0xffffffff;
  local_50 = param_1;
  local_58[0] = 0x4008;
  ExceptionList = &pvStack_14;
  rtcTrimVar(local_28,local_58);
  local_60 = 0;
  local_68[0] = 0x8002;
  uVar2 = __vbaLenVar(local_38,local_28);
  sVar1 = __vbaVarTstEq(local_68,uVar2);
  __vbaFreeVar();
  if (sVar1 != 0) {
    local_18 = 0;
  }
  iVar3 = __vbaInStr(0,&DAT_00444d98,*param_1,1);
  if (iVar3 == 0) {
    local_18 = 0;
  }
  __vbaInStr(0,&DAT_00448378,*param_1,1);
  return;
}


