// BonziBDY_2.EXE :: frmSpeak
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 6

// ---- btnCancel_ev0 @ 0045c680

void __cdecl frmSpeak::btnCancel_ev0(uint param_1)

{
  int *piVar1;
  undefined4 uVar2;
  int iVar3;
  int *piVar4;
  undefined4 local_28;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_00406e06;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffb4;
  local_c = &DAT_00401dc0;
  local_8 = param_1 & 1;
  piVar4 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar4 + 4))(piVar4);
  local_1c = 0;
  iVar3 = *DAT_004c4064;
  uVar2 = __vbaI2I4(10,local_28,0x80020004,local_20,&local_1c);
  uVar2 = __vbaI2I4(uVar2);
  iVar3 = (**(code **)(iVar3 + 0x80))(DAT_004c4064,uVar2);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,DAT_004c4064,&DAT_00415a44,0x80);
  }
  __vbaFreeObj();
  if (DAT_004c4c40 == (int *)0x0) {
    __vbaNew2(&DAT_00415874,&DAT_004c4c40);
  }
  piVar1 = DAT_004c4c40;
  iVar3 = *DAT_004c4c40;
  uVar2 = __vbaObjSetAddref(&local_1c,piVar4);
  iVar3 = (**(code **)(iVar3 + 0x10))(piVar1,uVar2);
  if (iVar3 < 0) {
    __vbaHresultCheckObj(iVar3,piVar1,&DAT_00415864,0x10);
  }
  __vbaFreeObj();
  return;
}


// ---- btnSpeak_ev0 @ 0045c7d0

void __cdecl frmSpeak::btnSpeak_ev0(uint param_1)

{
  short sVar1;
  undefined4 uVar2;
  int *piVar3;
  int iVar4;
  int *piVar5;
  undefined4 local_78;
  undefined4 local_74;
  undefined4 local_70;
  undefined4 local_68;
  undefined4 local_64;
  undefined4 local_60;
  wchar_t *local_5c;
  undefined4 local_58;
  undefined4 local_54;
  undefined4 local_44 [4];
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined1 *local_c;
  uint local_8;
  
  puStack_14 = &DAT_00406e06;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff60;
  local_c = &LAB_00401dd0;
  local_8 = param_1 & 1;
  piVar5 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar5 + 4))(piVar5);
  local_1c = 0;
  local_20 = 0;
  local_24 = 0;
  local_34 = 0;
  local_44[0] = 0;
  local_54 = 0;
  local_64 = 0;
  local_74 = 0;
  local_78 = 0;
  uVar2 = (**(code **)(*piVar5 + 0x308))(piVar5);
  piVar3 = (int *)__vbaObjSet(&local_20,uVar2);
  iVar4 = (**(code **)(*piVar3 + 0xa0))(piVar3,&local_1c);
  if (iVar4 < 0) {
    __vbaHresultCheckObj(iVar4,piVar3,&DAT_004154c0,0xa0);
  }
  local_2c = local_1c;
  local_1c = 0;
  local_34 = 8;
  rtcTrimVar(local_44,&local_34);
  local_5c = L"";
  local_64 = 0x8008;
  sVar1 = __vbaVarTstNe(&local_64,local_44);
  __vbaFreeObj();
  __vbaFreeVarList(2,&local_34,local_44);
  if (sVar1 == 0) {
    local_64 = 8;
    local_5c = L"You\'ll have to type something first.";
    iVar4 = (**(code **)(*DAT_004c4064 + 0x78))
                      (DAT_004c4064,8,local_60,L"You\'ll have to type something first.",local_58,10,
                       local_70,0x80020004,local_68,&local_20);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,DAT_004c4064,&DAT_00415a44,0x78);
    }
    __vbaFreeObj();
  }
  else {
    iVar4 = (**(code **)(*DAT_004c4064 + 0xd0))(DAT_004c4064,0,&local_78);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,DAT_004c4064,&DAT_00418eb4,0xd0);
    }
    local_64 = 10;
    local_5c = (wchar_t *)0x80020004;
    iVar4 = (**(code **)(*DAT_004c4064 + 0x6c))(DAT_004c4064,10,local_60,0x80020004,local_58);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,DAT_004c4064,&DAT_00415a44,0x6c);
    }
    local_5c = (wchar_t *)0x80020004;
    local_64 = 10;
    uVar2 = (**(code **)(*piVar5 + 0x308))(piVar5);
    piVar3 = (int *)__vbaObjSet(&local_20,uVar2);
    iVar4 = (**(code **)(*piVar3 + 0xa0))(piVar3,&local_1c);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,piVar3,&DAT_004154c0,0xa0);
    }
    local_2c = local_1c;
    local_1c = 0;
    local_34 = 8;
    iVar4 = (**(code **)(*DAT_004c4064 + 0x78))
                      (DAT_004c4064,8,local_30,local_2c,local_28,local_64,local_60,local_5c,local_58
                       ,&local_24);
    if (iVar4 < 0) {
      __vbaHresultCheckObj(iVar4,DAT_004c4064,&DAT_00415a44,0x78);
    }
    __vbaFreeObjList(2,&local_20,&local_24);
    __vbaFreeVar();
  }
  return;
}


// ---- Form_Activate @ 0045cb10

void __cdecl frmSpeak::Form_Activate(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined1 *local_c;
  uint local_8;
  
  puStack_14 = &DAT_00406e06;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &LAB_00401de0;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  uVar1 = __vbaCastObj(piVar2,&DAT_00415b20);
  __vbaObjSet(&local_1c,uVar1);
  modAgent::Proc_47b6a0(&local_1c);
  __vbaFreeObj();
  return;
}


// ---- Form_KeyUp @ 0045cbc0

void __cdecl frmSpeak::Form_KeyUp(uint param_1,short *param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 local_4c;
  undefined4 local_44;
  undefined4 local_3c;
  undefined4 local_34;
  undefined4 local_2c;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_00406e06;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffff94;
  local_c = &DAT_00401df0;
  local_8 = param_1 & 1;
  ExceptionList = &pvStack_18;
  (**(code **)(*(int *)(param_1 & 0xfffffffe) + 4))((int *)(param_1 & 0xfffffffe));
  local_1c = 0;
  local_20 = 0;
  if (*param_2 == 0x70) {
    iVar1 = (**(code **)(*DAT_004c4064 + 0x6c))(DAT_004c4064,10,local_3c,0x80020004,local_34);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_004c4064,&DAT_00415a44,0x6c);
    }
    if (DAT_004c41b4 == (int *)0x0) {
      __vbaNew2(&DAT_0040ff40,&DAT_004c41b4);
    }
    frmAgent::Public_90(DAT_004c41b4);
    iVar1 = (**(code **)(*DAT_004c4064 + 100))(DAT_004c4064,L"Suggest",&local_20);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_004c4064,&DAT_00415a44,100);
    }
    __vbaFreeObj();
    iVar1 = (**(code **)(*DAT_004c4064 + 0x78))
                      (DAT_004c4064,8,local_3c,
                       L"Having trouble?  Let me help you. From this screen, I can say anything you\'d like. Simply enter what you would like me to say and click on the \'Say It\' button."
                       ,local_34,10,local_4c,0x80020004,local_44,&local_20);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_004c4064,&DAT_00415a44,0x78);
    }
    __vbaFreeObj();
    __vbaStrCat(DAT_004c4028,L"And remember ");
    uVar2 = __vbaStrMove();
    uVar2 = __vbaStrCat(L", let\'s keep it clean!",uVar2);
    iVar1 = (**(code **)(*DAT_004c4064 + 0x78))
                      (DAT_004c4064,8,local_2c,uVar2,local_24,10,local_3c,0x80020004,local_34,
                       &local_20);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_004c4064,&DAT_00415a44,0x78);
    }
    __vbaFreeStr();
    __vbaFreeObj();
    __vbaFreeVar();
    iVar1 = (**(code **)(*DAT_004c4064 + 100))(DAT_004c4064,L"Pleased",&local_20);
    if (iVar1 < 0) {
      __vbaHresultCheckObj(iVar1,DAT_004c4064,&DAT_00415a44,100);
    }
    uVar2 = local_20;
    local_20 = 0;
    __vbaObjSet(&DAT_004c4188,uVar2);
  }
  return;
}


// ---- Form_Load @ 0045ce80

undefined4 frmSpeak::Form_Load(uint param_1)

{
  int iVar1;
  int *piVar2;
  void *local_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &DAT_00406e06;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00401e00;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &local_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  iVar1 = (**(code **)(*piVar2 + 0x1d4))(piVar2,0xffffffff);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,piVar2,&DAT_00418e74,0x1d4);
  }
  local_8 = 0;
  (**(code **)(*piVar2 + 8))(piVar2);
  ExceptionList = local_18;
  return local_8;
}


// ---- Form_ev20 @ 0045cf10

void __cdecl frmSpeak::Form_ev20(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int local_1c;
  void *pvStack_18;
  undefined *puStack_14;
  undefined1 *local_10;
  undefined1 *local_c;
  uint local_8;
  
  puStack_14 = &DAT_00406e06;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &LAB_00401e08;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  uVar1 = __vbaCastObj(piVar2,&DAT_00415b20);
  __vbaObjSet(&local_1c,uVar1);
  modAgent::Proc_47b6a0(&local_1c);
  __vbaFreeObj();
  return;
}


