// Jigsaw.exe :: clsDLLIScore
// C pseudocode generated by Ghidra from native VB6 code. Not the original source.
// Functions: 10

// ---- Public_0 @ 007352d0

void clsDLLIScore::Public_0(int *param_1,undefined4 *param_2)

{
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00401c46;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00401bb0;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  *param_2 = 0;
  __vbaStrCopy();
  return;
}


// ---- Public_1 @ 00735360

undefined4 clsDLLIScore::Public_1(int *param_1)

{
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00401c46;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00401bc0;
  local_8 = 0;
  ExceptionList = &local_18;
  (**(code **)(*param_1 + 4))(param_1);
  __vbaStrCopy();
  (**(code **)(*param_1 + 8))(param_1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Public_2 @ 007353d0

void clsDLLIScore::Public_2(int *param_1)

{
  int iVar1;
  float10 fVar2;
  undefined4 local_30 [4];
  double local_20;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00401c46;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffb8;
  local_c = &DAT_00401bc8;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_30[0] = 0;
  local_20 = 0.0;
  iVar1 = (**(code **)(*(int *)param_1[0xd] + 0x1c))((int *)param_1[0xd],local_30);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xd],&DAT_00451a58,0x1c);
  }
  fVar2 = (float10)__vbaDateVar(local_30);
  local_20 = (double)fVar2;
  __vbaFreeVar();
  return;
}


// ---- Public_3 @ 00735490

void clsDLLIScore::Public_3(int *param_1,undefined4 *param_2)

{
  int iVar1;
  undefined4 local_28 [2];
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00401c46;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffb0;
  local_c = &DAT_00401bd8;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_28[0] = 7;
  local_1c = param_2[1];
  local_20 = *param_2;
  iVar1 = (**(code **)(*(int *)param_1[0xd] + 0x20))((int *)param_1[0xd],local_28);
  if (iVar1 < 0) {
    __vbaHresultCheckObj(iVar1,param_1[0xd],&DAT_00451a58,0x20);
  }
  __vbaFreeVar();
  return;
}


// ---- Public_4 @ 00735540

void clsDLLIScore::Public_4(int *param_1,undefined4 *param_2)

{
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00401c46;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00401be8;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  *param_2 = 0;
  __vbaObjSetAddref(&local_1c,param_1[0xd]);
  return;
}


// ---- Public_5 @ 007355d0

undefined4 clsDLLIScore::Public_5(int *param_1,undefined4 *param_2)

{
  void *local_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00401c46;
  local_18 = ExceptionList;
  local_10 = &stack0xffffffd4;
  local_c = &DAT_00401bf8;
  local_8 = 0;
  ExceptionList = &local_18;
  (**(code **)(*param_1 + 4))(param_1);
  __vbaObjSetAddref(param_1 + 0xd,*param_2);
  (**(code **)(*param_1 + 8))(param_1);
  ExceptionList = local_18;
  return local_8;
}


// ---- Public_6 @ 00735640

void clsDLLIScore::Public_6(int *param_1)

{
  undefined4 uVar1;
  undefined4 local_24 [2];
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00401c46;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffc8;
  local_c = &DAT_00401c00;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_24[0] = 0;
  local_1c = 0xffffffff;
  uVar1 = __vbaCastObj(0,&DAT_00451a58);
  uVar1 = __vbaObjSet(local_24,uVar1);
  __vbaObjSetAddref(param_1 + 0xd,uVar1);
  __vbaFreeObj();
  return;
}


// ---- Public_7 @ 007356f0

void clsDLLIScore::Public_7(int *param_1,undefined4 *param_2)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 local_30 [4];
  undefined4 local_20;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00401c46;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffa8;
  local_c = &DAT_00401c10;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = 0;
  local_20 = 0;
  local_30[0] = 0;
  *param_2 = 0;
  param_1 = param_1 + 0xd;
  uVar1 = __vbaNew(&DAT_0044c7c4);
  uVar1 = __vbaObjSet(&local_20,uVar1);
  __vbaObjSetAddref(param_1,uVar1);
  __vbaFreeObj();
  __vbaVarDup();
  iVar2 = (**(code **)(*(int *)*param_1 + 0x38))((int *)*param_1,local_30);
  if (iVar2 < 0) {
    __vbaHresultCheckObj(iVar2,*param_1,&DAT_00451a58,0x38);
  }
  __vbaFreeVar();
  return;
}


// ---- Public_9 @ 00735800

void clsDLLIScore::Public_9(uint param_1)

{
  undefined4 uVar1;
  int *piVar2;
  undefined4 local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  uint local_8;
  
  puStack_14 = &LAB_00401c46;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffd0;
  local_c = &DAT_00401c20;
  local_8 = param_1 & 1;
  piVar2 = (int *)(param_1 & 0xfffffffe);
  ExceptionList = &pvStack_18;
  (**(code **)(*piVar2 + 4))(piVar2);
  local_1c = 0;
  uVar1 = __vbaCastObj(0,&DAT_00451a58);
  uVar1 = __vbaObjSet(&local_1c,uVar1);
  __vbaObjSetAddref(piVar2 + 0xd,uVar1);
  __vbaFreeObj();
  return;
}


// ---- Public_8 @ 007358b0

/* WARNING: Control flow encountered bad instruction data */

void clsDLLIScore::Public_8(int *param_1)

{
  undefined4 uVar1;
  short sVar2;
  int iVar3;
  uint uVar4;
  undefined4 local_28 [2];
  uint local_20;
  int *local_1c;
  void *pvStack_18;
  undefined1 *puStack_14;
  undefined1 *local_10;
  undefined *local_c;
  undefined4 local_8;
  
  puStack_14 = &LAB_00401c46;
  pvStack_18 = ExceptionList;
  local_10 = &stack0xffffffb8;
  local_c = &DAT_00401c30;
  local_8 = 0;
  ExceptionList = &pvStack_18;
  (**(code **)(*param_1 + 4))(param_1);
  local_1c = (int *)0x0;
  local_20 = 0;
  local_28[0] = 0;
  uVar4 = 1;
  __vbaObjSetAddref(&local_1c,param_1[0xd]);
  while( true ) {
    iVar3 = (**(code **)(*local_1c + 0x2c))(local_1c,local_28);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,local_1c,&DAT_00451a58,0x2c);
    }
    sVar2 = __vbaObjIs(local_28[0],0);
    __vbaFreeObj();
    if (sVar2 == -1) break;
    sVar2 = (short)uVar4;
    uVar4 = (uint)(ushort)(sVar2 + 1);
    if (SCARRY2(sVar2,1)) {
      __vbaErrorOverflow(local_1c);
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
    iVar3 = (**(code **)(*local_1c + 0x2c))(local_1c,local_28);
    if (iVar3 < 0) {
      __vbaHresultCheckObj(iVar3,local_1c,&DAT_00451a58,0x2c);
    }
    uVar1 = local_28[0];
    local_28[0] = 0;
    __vbaObjSet(&local_1c,uVar1);
  }
  local_20 = uVar4;
  __vbaFreeObj(&LAB_007359a5);
  return;
}


